"use strict";

mappages["blackdragon"] = {};
mappages["blackdragon"].terrain = [];
 mappages["blackdragon"].terrain[0] = '.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. nn nn nn nn nn nn nn nn nn nn';
 mappages["blackdragon"].terrain[1] = '.. .. .. .. __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ nn nn nn nn nn nn';
 mappages["blackdragon"].terrain[2] = '.. .. .. ./ uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu';
 mappages["blackdragon"].terrain[3] = '.. .. .| uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu';
 mappages["blackdragon"].terrain[4] = '.. .. .| uu uu uu /. -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- nn nn nn';
 mappages["blackdragon"].terrain[5] = '.. .. .| uu uu /. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. nn';
 mappages["blackdragon"].terrain[6] = '.. .. .| uu uu |. .. .. .. .. .. .. #% #% #% #% #% #% #% #% #% .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..';
 mappages["blackdragon"].terrain[7] = '.. .. .| uu uu |. .. .. .. .. .. #% u, .. .. .. u, .. ., ., ., #% .. ## ## ## ## ## ## ## ## ## ## .. .. .. .. .. .. .. .. .. .. .. ..';
 mappages["blackdragon"].terrain[8] = '.. .. .| uu uu |. .. .. .. .. #% u, .. .. ,, .. .. ,, ., ., ., #% .. ## ## +* +* +* +* +* +* +* ## .. .. .. .. .. .. .. .. .. .. .. ..';
 mappages["blackdragon"].terrain[9] = '.. .. .| uu uu |. .. .. .. .. #% .. .. ,, u, .. .. .. .. .. .. #% .. ## ## +* +* +* +* +* +* +* ## ## ## ## ## ## ## ## ## ## ## .. ..';
mappages["blackdragon"].terrain[10] = '.. .. .| uu uu |. .. .. .. .. #% ,, .. __ .. .. .. ,, .. ,, .. #% .. ## ## +* +* +* +* +* +* +* ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. ..';
mappages["blackdragon"].terrain[11] = '.. .. .| uu uu |. .. .. .. .. #% .. ./ uu `. ,, .. .. .. .. ,, #% .. ## ## +* +* +* +* +* +* +* ## ++ ++ +o ++ ++ ++ +o ++ ++ ## .. ..';
mappages["blackdragon"].terrain[12] = '.. .. .| uu uu |. .. .. .. .. #% .. .` uu /. .. .. .. ,, .. .. #% .. ## ## +* +* +* +* +* +* +* ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. ..';
mappages["blackdragon"].terrain[13] = '.. .. .| uu uu |. .. .. .. .. #% ,; .. -, .. .. u, .. .. ,, u, #% .. ## ## ## ## ## ## ++ ## ## ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. ..';
mappages["blackdragon"].terrain[14] = '.. .. .| uu uu |. .. .. .. .. #% ,; ,; .. ,, .. .. .. .. .. .. #% .. ## ## b1 b2 b3 ++ ++ ++ ++ ## ++ ++ +o ++ ++ ++ +o ++ ++ ## .. ..';
mappages["blackdragon"].terrain[15] = '.. .. .| uu uu |. .. .. .. .. #% ,; ,; ,; .. .. .. .. .. .. ,, #% .. ## ++ b8 b0 b4 ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. ..';
mappages["blackdragon"].terrain[16] = '.. .. .| uu uu |. .. ## #+ ## ## ## ## ## ## #O ## ++ ## #O ## ## ## ## ## b7 b6 b5 ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. ..';
mappages["blackdragon"].terrain[17] = '.. .. .| uu uu |. .. ## ++ ## ## ++ ++ ++ ++ ++ ## ++ ## ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ +o ++ ++ ++ +o ++ ++ ## .. ..';
mappages["blackdragon"].terrain[18] = '.. .. .| uu uu |. .. ## ++ ## ## ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ## ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. ..';
mappages["blackdragon"].terrain[19] = '.. .. .| uu uu |. .. #+ ++ ## ## ## ++ ++ ++ ++ ## ++ ## ++ ++ ++ ++ ## ## ## ## ## ## ## ## ## ## ## ## ++ ++ ++ ++ ## ## ## ## .. ..';
mappages["blackdragon"].terrain[20] = '.. .. .| uu uu |. .. ## ++ ## ## ## ++ ++ ++ ++ ## ++ ## ## ## ## ## ## ## ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .. .. ..';
mappages["blackdragon"].terrain[21] = '.. .. .| uu uu |. .. ## ++ ## ## ## ## ## ## ## ## ++ ## ++ ++ ++ ++ ## ## ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .. .. ./';
mappages["blackdragon"].terrain[22] = '.. .. .| uu uu |. .. ## ++ ## ## ## ++ ++ ++ ++ ## ++ ## ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .. .| uu';
mappages["blackdragon"].terrain[23] = '.. .. .| uu uu |. .. #+ ++ ## ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ## ++ ++ ++ ++ ++ ++ ++ ++ ## ## ## ## ## ## ## .. .. .. ./ uu';
mappages["blackdragon"].terrain[24] = '.. .. .| uu uu |. .. ## ++ ## ## ## ++ ++ ++ ++ ## ++ ## ++ ++ ++ ++ ## ## ++ ++ ++ ++ ## ++ ++ ++ ## ++ ## ++ ## .. .. .. .. .| uu uu';
mappages["blackdragon"].terrain[25] = '.. .. .| uu uu |. .. ## ++ ## ## ## ## ## ## ## ## ++ ## ## ## ## ## ## ## ## ## ## ## ## ++ ++ ++ ## ++ ++ ++ ## .. .. .. .. .| uu uu';
mappages["blackdragon"].terrain[26] = '.. .. .| uu uu |. .. ## ++ ## ## ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ## .. .. .. .. .| uu uu';
mappages["blackdragon"].terrain[27] = '.. .. .| uu uu |. .. ## ++ ++ ## ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ## .. .. .. .. ./ uu uu';
mappages["blackdragon"].terrain[28] = '.. .. .| uu uu |. .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ## .. .. .. .| uu uu uu';
mappages["blackdragon"].terrain[29] = '.. .. .| uu uu |. .. #+ ++ ## #+ ## ++ ## #+ ## ## ## ## ## ## ## ++ ## ## ## ## ## ## ## ++ ## ## ## ## ## ++ ## ## .. .. .| uu uu uu';
mappages["blackdragon"].terrain[30] = '.. .. .| uu uu |. .. ## ++ ## uu +o ++ +o uu ## ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ## ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .| uu uu uu';
mappages["blackdragon"].terrain[31] = '.. .. .| uu uu |. .. ## ++ ## uu ++ ++ ++ uu ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .| uu uu uu';
mappages["blackdragon"].terrain[32] = '.. .. .| uu uu |. .. ## ++ ## uu +o ++ +o uu ## ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ## ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .. .` uu uu';
mappages["blackdragon"].terrain[33] = '.. .. .| uu uu |. .. #+ ++ ## uu ++ ++ ++ uu ## ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .. .| uu uu';
mappages["blackdragon"].terrain[34] = '.. .. .| uu uu |. .. ## ++ ## uu +o ++ +o uu ## ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ## ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .. .| uu uu';
mappages["blackdragon"].terrain[35] = '.. .. .| uu uu |. .. ## #+ ## uu ++ ++ ++ uu ## ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ## ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .. .| uu uu';
mappages["blackdragon"].terrain[36] = '.. .. .| uu uu |. .. .. .. ## uu +o ++ +o uu ## ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ## ## ## ## ## ## ## ## ## ## ## ## ## .. .. .. .| uu uu';
mappages["blackdragon"].terrain[37] = '.. .. .| uu uu |. .. .. .. ## uu ++ ++ ++ uu ## ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ## .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ./ uu uu';
mappages["blackdragon"].terrain[38] = '.. .. .| uu uu |. .. .. .. ## ## ## ++ ## ## ## ## #+ ## ## ## ## #+ ## ## ## ## .. .. .. .. .. .. .. .. .. .. .. .. .. .. .| uu uu uu';
mappages["blackdragon"].terrain[39] = '.. .. .| uu uu |. .. .. .. .. .. !! !! !! .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .| uu uu uu';
mappages["blackdragon"].terrain[40] = '.. .. .| uu uu `. __ __ __ __ __ !! !! !! __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ .. .. .. .. .. ./ uu uu uu';
mappages["blackdragon"].terrain[41] = '.. .. .| uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu `. __ .. .. .. uu uu uu uu';
mappages["blackdragon"].terrain[42] = '.. .. .. .` uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu `. __ ./ uu uu uu uu';
mappages["blackdragon"].terrain[43] = '.. .. .. .. -- -- -- -- -- -- -- !! !! !! -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- .` uu uu uu uu uu uu uu uu uu';
mappages["blackdragon"].terrain[44] = '.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. -- .` uu uu uu uu uu uu uu';

mappages["blackdragon"].features = [];
mappages["blackdragon"].features[0] = {name : 'Doorway', x : 12, y : 29};
mappages["blackdragon"].features[1] = {name : 'Door', x : 22, y : 29, desc : "locked door", locked : 1};
mappages["blackdragon"].features[2] = {name : 'Door', x : 19, y : 31, desc : "locked door", locked : 1};
mappages["blackdragon"].features[3] = {name : 'BDCLever', x : 11, y : 39};
mappages["blackdragon"].features[4] = {name : 'BedHead', x : 20, y : 32};
mappages["blackdragon"].features[5] = {name : 'BedHead', x : 20, y : 34};
mappages["blackdragon"].features[6] = {name : 'BedHead', x : 20, y : 36};
mappages["blackdragon"].features[7] = {name : 'BedFoot', x : 21, y : 32};
mappages["blackdragon"].features[8] = {name : 'BedFoot', x : 21, y : 34};
mappages["blackdragon"].features[9] = {name : 'BedFoot', x : 21, y : 36};
mappages["blackdragon"].features[10] = {name : 'BedHead', x : 24, y : 32};
mappages["blackdragon"].features[11] = {name : 'BedHead', x : 24, y : 34};
mappages["blackdragon"].features[12] = {name : 'BedHead', x : 24, y : 36};
mappages["blackdragon"].features[13] = {name : 'BedFoot', x : 25, y : 32};
mappages["blackdragon"].features[14] = {name : 'BedFoot', x : 25, y : 34};
mappages["blackdragon"].features[15] = {name : 'BedFoot', x : 25, y : 36};
mappages["blackdragon"].features[16] = {name : 'Door', x : 17, y : 25};
mappages["blackdragon"].features[17] = {name : 'Door', x : 18, y : 23, desc : "locked door", locked : 1};
mappages["blackdragon"].features[18] = {name : 'Door', x : 16, y : 23, desc : "locked door", locked : 1};
mappages["blackdragon"].features[19] = {name : 'Door', x : 16, y : 18, desc : "locked door", locked : 1};
mappages["blackdragon"].features[20] = {name : 'Door', x : 18, y : 18, desc : "locked door", locked : 1};
mappages["blackdragon"].features[21] = {name : 'BedHead', x : 21, y : 19};
mappages["blackdragon"].features[22] = {name : 'BedHead', x : 21, y : 24};
mappages["blackdragon"].features[23] = {name : 'BedHead', x : 12, y : 24};
mappages["blackdragon"].features[24] = {name : 'BedHead', x : 12, y : 20};
mappages["blackdragon"].features[25] = {name : 'BedFoot', x : 22, y : 19};
mappages["blackdragon"].features[26] = {name : 'BedFoot', x : 22, y : 24};
mappages["blackdragon"].features[27] = {name : 'BedFoot', x : 13, y : 24};
mappages["blackdragon"].features[28] = {name : 'BedFoot', x : 13, y : 20};
mappages["blackdragon"].features[29] = {name : 'Mirror', x : 22, y : 21};
mappages["blackdragon"].features[30] = {name : 'Mirror', x : 14, y : 22};
mappages["blackdragon"].features[31] = {name : 'Mirror', x : 13, y : 17};
mappages["blackdragon"].features[32] = {name : 'Mirror', x : 20, y : 17};
mappages["blackdragon"].features[33] = {name : 'BookshelfLeft', x : 19, y : 21};
mappages["blackdragon"].features[34] = {name : 'BookshelfRight', x : 20, y : 21};
mappages["blackdragon"].features[35] = {name : 'BookshelfOne', x : 19, y : 19};
mappages["blackdragon"].features[36] = {name : 'BookshelfOne', x : 15, y : 20};
mappages["blackdragon"].features[37] = {name : 'BookshelfOne', x : 12, y : 22};
mappages["blackdragon"].features[38] = {name : 'DoorWindow', x : 17, y : 16};
mappages["blackdragon"].features[39] = {name : 'DoorWindow', x : 30, y : 29};
mappages["blackdragon"].features[40] = {name : 'LeftTable', x : 28, y : 31};
mappages["blackdragon"].features[41] = {name : 'LeftTable', x : 32, y : 31};
mappages["blackdragon"].features[42] = {name : 'MiddleTable', x : 29, y : 31};
mappages["blackdragon"].features[43] = {name : 'MiddleTable', x : 33, y : 31};
mappages["blackdragon"].features[44] = {name : 'MiddleTable', x : 34, y : 31};
mappages["blackdragon"].features[45] = {name : 'RightTable', x : 30, y : 31};
mappages["blackdragon"].features[46] = {name : 'RightTable', x : 35, y : 31};
mappages["blackdragon"].features[47] = {name : 'LeftTable', x : 28, y : 34};
mappages["blackdragon"].features[48] = {name : 'LeftTable', x : 32, y : 34};
mappages["blackdragon"].features[49] = {name : 'MiddleTable', x : 29, y : 34};
mappages["blackdragon"].features[50] = {name : 'MiddleTable', x : 33, y : 34};
mappages["blackdragon"].features[51] = {name : 'MiddleTable', x : 34, y : 34};
mappages["blackdragon"].features[52] = {name : 'RightTable', x : 35, y : 34};
mappages["blackdragon"].features[53] = {name : 'RightTable', x : 30, y : 34};
mappages["blackdragon"].features[54] = {name : 'BottomChair', x : 28, y : 32};
mappages["blackdragon"].features[55] = {name : 'BottomChair', x : 30, y : 32};
mappages["blackdragon"].features[56] = {name : 'BottomChair', x : 28, y : 35};
mappages["blackdragon"].features[57] = {name : 'BottomChair', x : 30, y : 35};
mappages["blackdragon"].features[58] = {name : 'BottomChair', x : 32, y : 35};
mappages["blackdragon"].features[59] = {name : 'BottomChair', x : 34, y : 35};
mappages["blackdragon"].features[60] = {name : 'TopChair', x : 29, y : 30};
mappages["blackdragon"].features[61] = {name : 'TopChair', x : 33, y : 30};
mappages["blackdragon"].features[62] = {name : 'TopChair', x : 35, y : 30};
mappages["blackdragon"].features[63] = {name : 'TopChair', x : 33, y : 33};
mappages["blackdragon"].features[64] = {name : 'TopChair', x : 35, y : 33};
mappages["blackdragon"].features[65] = {name : 'BottomChair', x : 34, y : 32};
mappages["blackdragon"].features[66] = {name : 'BottomChair', x : 32, y : 32};
mappages["blackdragon"].features[67] = {name : 'TopChair', x : 29, y : 33};
mappages["blackdragon"].features[68] = {name : 'DoorWindow', x : 36, y : 29};
mappages["blackdragon"].features[69] = {name : 'LeftTable', x : 34, y : 26};
mappages["blackdragon"].features[70] = {name : 'RightTable', x : 35, y : 26};
mappages["blackdragon"].features[71] = {name : 'Door', x : 29, y : 23};
mappages["blackdragon"].features[72] = {name : 'Door', x : 11, y : 28, desc : "locked door", locked : 1};
mappages["blackdragon"].features[73] = {name : 'Throne', x : 37, y : 10};
mappages["blackdragon"].features[74] = {name : 'Door', x : 32, y : 17, desc : "magically locked door", locked : 2};
mappages["blackdragon"].features[75] = {name : 'PentagramSW', x : 25, y : 12};
mappages["blackdragon"].features[76] = {name : 'PentagramS', x : 26, y : 12};
mappages["blackdragon"].features[77] = {name : 'PentagramSE', x : 27, y : 12};
mappages["blackdragon"].features[78] = {name : 'PentagramE', x : 27, y : 11};
mappages["blackdragon"].features[79] = {name : 'PentagramC', x : 26, y : 11};
mappages["blackdragon"].features[80] = {name : 'PentagramW', x : 25, y : 11};
mappages["blackdragon"].features[81] = {name : 'PentagramN', x : 26, y : 10};
mappages["blackdragon"].features[82] = {name : 'PentagramNW', x : 25, y : 10};
mappages["blackdragon"].features[83] = {name : 'PentagramNE', x : 27, y : 10};
mappages["blackdragon"].features[84] = {name : 'BookshelfLeft', x : 25, y : 8};
mappages["blackdragon"].features[85] = {name : 'BookshelfLeft', x : 27, y : 8};
mappages["blackdragon"].features[86] = {name : 'BookshelfLeft', x : 29, y : 8};
mappages["blackdragon"].features[87] = {name : 'BookshelfRight', x : 26, y : 8};
mappages["blackdragon"].features[88] = {name : 'BookshelfRight', x : 28, y : 8};
mappages["blackdragon"].features[89] = {name : 'BookshelfRight', x : 30, y : 8};
mappages["blackdragon"].features[90] = {name : 'Mirror', x : 31, y : 8};
mappages["blackdragon"].features[91] = {name : 'Doorway', x : 29, y : 13};
mappages["blackdragon"].features[92] = {name : 'Mirror', x : 30, y : 14};
mappages["blackdragon"].features[93] = {name : 'RightChair', x : 31, y : 18};
mappages["blackdragon"].features[94] = {name : 'RightTable', x : 30, y : 18};
mappages["blackdragon"].features[95] = {name : 'LeftTable', x : 29, y : 18};
mappages["blackdragon"].features[96] = {name : 'LeftTable', x : 25, y : 21};
mappages["blackdragon"].features[97] = {name : 'MiddleTable', x : 26, y : 21};
mappages["blackdragon"].features[98] = {name : 'RightTable', x : 27, y : 21};
mappages["blackdragon"].features[99] = {name : 'MoatLeverOff', x : 9, y : 27};
mappages["blackdragon"].features[100] = {name : 'BookshelfLeft', x : 25, y : 24};
mappages["blackdragon"].features[101] = {name : 'BookshelfRight', x : 26, y : 24};
mappages["blackdragon"].features[102] = {name : 'BookshelfRight', x : 28, y : 24};
mappages["blackdragon"].features[103] = {name : 'BookshelfLeft', x : 27, y : 24};
mappages["blackdragon"].features[104] = {name : 'TopChair', x : 26, y : 20};
mappages["blackdragon"].features[105] = {name : 'SmallBox', x : 20, y : 37};
mappages["blackdragon"].features[106] = {name : 'SmallBox', x : 20, y : 35};
mappages["blackdragon"].features[107] = {name : 'SmallBox', x : 20, y : 33};
mappages["blackdragon"].features[108] = {name : 'SmallBox', x : 25, y : 33};
mappages["blackdragon"].features[109] = {name : 'SmallBox', x : 25, y : 35};
mappages["blackdragon"].features[110] = {name : 'SmallBox', x : 25, y : 37};
mappages["blackdragon"].features[111] = {name : 'Chest', x : 17, y : 30};
mappages["blackdragon"].features[112] = {name : 'Chest', x : 16, y : 30};
mappages["blackdragon"].features[113] = {name : 'Chest', x : 16, y : 31};
mappages["blackdragon"].features[114] = {name : 'Chest', x : 16, y : 36};
mappages["blackdragon"].features[115] = {name : 'Chest', x : 16, y : 37};
mappages["blackdragon"].features[116] = {name : 'Chest', x : 17, y : 37};
mappages["blackdragon"].features[117] = {name : 'BedHead', x : 25, y : 17};
mappages["blackdragon"].features[118] = {name : 'BedFoot', x : 26, y : 17};
mappages["blackdragon"].features[119] = {name : 'WallPortcullis', x : 12, y : 38, locked : 1};
mappages["blackdragon"].features[120] = {name : 'BedHead', x : 24, y : 30};
mappages["blackdragon"].features[121] = {name : 'BedFoot', x : 25, y : 30};
mappages["blackdragon"].features[122] = {name : 'SmallBox', x : 23, y : 30};
mappages["blackdragon"].features[123] = {name : 'StairUp', x : 25, y : 20, entermap : 'blackdragon2', enterx : 25, entery : 20};
mappages["blackdragon"].features[124] = {name : 'Brazier', x : 20, y : 30};
mappages["blackdragon"].features[125] = {name : 'Fireplace', x : 11, y : 17};
mappages["blackdragon"].features[126] = {name : 'Fireplace', x : 11, y : 23};
mappages["blackdragon"].features[127] = {name : 'Fireplace', x : 23, y : 17};
mappages["blackdragon"].features[128] = {name : 'Fireplace', x : 23, y : 22};
mappages["blackdragon"].features[129] = {name : 'Fireplace', x : 26, y : 31};
mappages["blackdragon"].features[130] = {name : 'Fireplace', x : 27, y : 33};
mappages["blackdragon"].features[131] = {name : 'Spit', x : 37, y : 30};
mappages["blackdragon"].features[132] = {name : 'Brazier', x : 37, y : 35};
mappages["blackdragon"].features[133] = {name : 'Fireplace', x : 36, y : 24};
mappages["blackdragon"].features[134] = {name : 'Fireplace', x : 34, y : 24};
mappages["blackdragon"].features[135] = {name : 'Spit', x : 34, y : 28};
mappages["blackdragon"].features[136] = {name : 'Brazier', x : 31, y : 12};
mappages["blackdragon"].features[137] = {name : 'Fireplace', x : 24, y : 15};
mappages["blackdragon"].features[138] = {name : 'TorchWest', x : 33, y : 12};
mappages["blackdragon"].features[139] = {name : 'TorchWest', x : 33, y : 15};
mappages["blackdragon"].features[140] = {name : 'TorchEast', x : 41, y : 12};
mappages["blackdragon"].features[141] = {name : 'TorchEast', x : 41, y : 15};


mappages["blackdragon"].npcs = [];
mappages["blackdragon"].npcs[0] = {name : 'TownGuardNPC', x : 10, y : 40, NPCName: 'Guard', Conversation: 'bdc_outer_guard', Gender: 'female', Bark: '0', NPCBand: '0'};
mappages["blackdragon"].npcs[1] = {name : 'TownGuardNPC', x : 13, y : 35, NPCName: 'Guard', Conversation: 'bdc_guard', Gender: 'male', Bark: '0', NPCBand: '0'};
mappages["blackdragon"].npcs[2] = {name : 'TownGuardNPC', x : 11, y : 35, NPCName: 'Guard', Conversation: 'bdc_guard', Gender: 'female', Bark: '0', NPCBand: '0'};
mappages["blackdragon"].npcs[3] = {name : 'PrinceNPC', x : 37, y : 12, NPCName: 'Prince Lance', Conversation: 'lance', ConversationFlag: 'lance', Gender: 'male', Bark: '0', NPCBand: '0'};
mappages["blackdragon"].npcs[4] = {name : 'BlackDragonNPC', x : 39, y : 15, NPCName: 'Black Dragon', Conversation: 'blackdragon', Gender: 'male', Leash: 2, Bark: '0', NPCBand: '0'};
mappages["blackdragon"].npcs[5] = {name : 'TownGuardNPC', x : 34, y : 20, NPCName: 'Guard', Conversation: 'bdc_throne_guard', Gender: 'male', Bark: '0', NPCBand: '0'};
mappages["blackdragon"].npcs[6] = {name : 'TownGuardNPC', x : 33, y : 16, NPCName: 'Guard', Conversation: 'bdc_throne_guard', Gender: 'female', Bark: '0', NPCBand: '0'};
mappages["blackdragon"].npcs[7] = {name : 'TownGuardNPC', x : 8, y : 34, NPCName: 'Guard', Conversation: 'bdc_guard', Gender: 'male', Bark: '0', NPCBand: '0'};
mappages["blackdragon"].npcs[8] = {name : 'TownGuardNPC', x : 8, y : 27, NPCName: 'Guard', Conversation: 'bdc_guard', Gender: 'monster', Bark: '0', NPCBand: '0'};
mappages["blackdragon"].npcs[9] = {name : 'TownsfolkVillagerNPC', x : 16, y : 9, NPCName: 'Taran', Conversation: 'taran', ConversationFlag: 'taran', Gender: 'male', Bark: '0', NPCBand: '0', OverrideGraphic: '310.gif'};
mappages["blackdragon"].npcs[10] = {name : 'MageVillagerNPC', x : 26, y : 20, NPCName: 'Justice', Conversation: 'justice', ConversationFlag: 'justice', Gender: 'female', Bark: '0', NPCBand: '0', OverrideGraphic: '303.gif'};

mappages["blackdragon"].desc = "Black Dragon Castle";
mappages["blackdragon"].music = 'Dark Towne';
mappages["blackdragon"].savename = 'B Drag Castle';
mappages["blackdragon"].exitmap = 'darkunknown';
mappages["blackdragon"].exitx = '49';
mappages["blackdragon"].exity = '90';
mappages["blackdragon"].wraps = 'None';
mappages["blackdragon"].enterx = '10';
mappages["blackdragon"].entery = '43';
mappages["blackdragon"].seeBelow = '';
mappages["blackdragon"].lightLevel = 'cycle';
mappages["blackdragon"].alwaysRemember = '0';
mappages["blackdragon"].scale = '1';
mappages["blackdragon"].underground = '0';
mappages["blackdragon"].undergroundDesc = '';
mappages["blackdragon"].enterscript = '';
mappages["blackdragon"].entertestscript = '';
mappages["blackdragon"].exitscript = 'maps_exit';
mappages["blackdragon"].exittestscript = '';
mappages["blackdragon"].returnmap = 'darkunknown';
mappages["blackdragon"].returnx = '69';
mappages["blackdragon"].returny = '74';
mappages["blackdragon"].returninfused = '0';
mappages["blackdragon"].linkedMaps = [""];
mappages["blackdragon"].editorLabels = '{}';

mappages["blackdragon"].onload = function(mapref) {
  // check for act 1 to be over, if so, gate is open
  if ((gamestate.getMode() !== "loadgame") && (!DU.gameflags.getFlag("editor"))) {
    if (DU.gameflags.getFlag("act2")) {
      Open_BDC_Gate(this);
    }
  }
}

mappages["blackdragon"].maps_exit = function() {
  this.Exit = function(who,tomap,fromx,fromy,tox,toy) {
    DU.gameflags.deleteFlag("bdc_gate_open");
  }
}

function Open_BDC_Gate(mapref) {
  // makes sense for this to be here. Called in onload if rebellion is over, and by the outer guard if you have the pin
  // working here
  if (mapref.getName() === "blackdragon") {
    mapref.getTile(11,39).getTopFeature().setGraphicArray(["moatLever-on.gif","moatLever-on.gif",0,0]);
    var gate = mapref.getTile(12,38).getTopFeature();
    gate.unlockMe();
    gate.use();
    var planks = localFactory.createTile("PlanksNS");
    mapref.setTerrain(11,41,planks);
    mapref.setTerrain(12,41,planks);
    mapref.setTerrain(13,41,planks);
    mapref.setTerrain(11,42,planks);
    mapref.setTerrain(12,42,planks);
    mapref.setTerrain(13,42,planks);
    DrawMainFrame("draw",PC.getHomeMap(),PC.getx(),PC.gety());
  }
}


mappages["blackdragon2"] = {};
mappages["blackdragon2"].terrain = [];
 mappages["blackdragon2"].terrain[0] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["blackdragon2"].terrain[1] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["blackdragon2"].terrain[2] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["blackdragon2"].terrain[3] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["blackdragon2"].terrain[4] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["blackdragon2"].terrain[5] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["blackdragon2"].terrain[6] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["blackdragon2"].terrain[7] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["blackdragon2"].terrain[8] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["blackdragon2"].terrain[9] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[10] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[11] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[12] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[13] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[14] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[15] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[16] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[17] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[18] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[19] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ## ## ## ## ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[20] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ++ ++ ++ ++ ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[21] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ++ ++ ++ ++ ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[22] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ++ ++ ++ ++ ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[23] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ++ ++ ++ ++ ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[24] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ++ ++ ++ ++ ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[25] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ## ## ## ## ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[26] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[27] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[28] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[29] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[30] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[31] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[32] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[33] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[34] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[35] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[36] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[37] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[38] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[39] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[40] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[41] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[42] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[43] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon2"].terrain[44] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';

mappages["blackdragon2"].features = [];
mappages["blackdragon2"].features[0] = {name : 'StairDown', x : 25, y : 20, entermap : 'blackdragon', enterx : 25, entery : 20};
mappages["blackdragon2"].features[1] = {name : 'PentagramNW', x : 26, y : 22};
mappages["blackdragon2"].features[2] = {name : 'PentagramN', x : 27, y : 22};
mappages["blackdragon2"].features[3] = {name : 'PentagramNE', x : 28, y : 22};
mappages["blackdragon2"].features[4] = {name : 'PentagramE', x : 28, y : 23};
mappages["blackdragon2"].features[5] = {name : 'PentagramC', x : 27, y : 23};
mappages["blackdragon2"].features[6] = {name : 'PentagramW', x : 26, y : 23};
mappages["blackdragon2"].features[7] = {name : 'PentagramSW', x : 26, y : 24};
mappages["blackdragon2"].features[8] = {name : 'PentagramS', x : 27, y : 24};
mappages["blackdragon2"].features[9] = {name : 'PentagramSE', x : 28, y : 24};
mappages["blackdragon2"].features[10] = {name : 'StairUp2', x : 25, y : 21, entermap : 'blackdragon3', enterx : 25, entery : 21};
mappages["blackdragon2"].features[11] = {name : 'FireField', x : 25, y : 24};
mappages["blackdragon2"].features[12] = {name : 'FireField', x : 28, y : 21};
mappages["blackdragon2"].features[13] = {name : 'BookshelfOne', x : 28, y : 20};
mappages["blackdragon2"].features[14] = {name : 'Chest', x : 27, y : 20};


mappages["blackdragon2"].npcs = [];

mappages["blackdragon2"].desc = "Black Dragon Castle";
mappages["blackdragon2"].music = 'Dark Towne';
mappages["blackdragon2"].savename = 'B Drag Castle';
mappages["blackdragon2"].exitmap = 'darkunknown';
mappages["blackdragon2"].exitx = '49';
mappages["blackdragon2"].exity = '90';
mappages["blackdragon2"].wraps = 'None';
mappages["blackdragon2"].enterx = '10';
mappages["blackdragon2"].entery = '43';
mappages["blackdragon2"].seeBelow = 'blackdragon';
mappages["blackdragon2"].lightLevel = 'cycle';
mappages["blackdragon2"].alwaysRemember = '0';
mappages["blackdragon2"].scale = '1';
mappages["blackdragon2"].underground = '0';
mappages["blackdragon2"].undergroundDesc = '';
mappages["blackdragon2"].enterscript = '';
mappages["blackdragon2"].entertestscript = '';
mappages["blackdragon2"].exitscript = 'maps_exit';
mappages["blackdragon2"].exittestscript = '';
mappages["blackdragon2"].returnmap = 'darkunknown';
mappages["blackdragon2"].returnx = '69';
mappages["blackdragon2"].returny = '74';
mappages["blackdragon2"].returninfused = '0';
mappages["blackdragon2"].linkedMaps = [""];
mappages["blackdragon2"].editorLabels = '{}';

mappages["blackdragon3"] = {};
mappages["blackdragon3"].terrain = [];
 mappages["blackdragon3"].terrain[0] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["blackdragon3"].terrain[1] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["blackdragon3"].terrain[2] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["blackdragon3"].terrain[3] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["blackdragon3"].terrain[4] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["blackdragon3"].terrain[5] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["blackdragon3"].terrain[6] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["blackdragon3"].terrain[7] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["blackdragon3"].terrain[8] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["blackdragon3"].terrain[9] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[10] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[11] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[12] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[13] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[14] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[15] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[16] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[17] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[18] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[19] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ## #O ## ## ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[20] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ++ ++ ++ ++ ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[21] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ++ ++ ++ ++ ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[22] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb #O ++ ++ ++ ++ #O sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[23] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ++ ++ ++ ++ ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[24] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ++ ++ ++ ++ ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[25] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ## ## #O ## ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[26] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[27] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[28] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[29] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[30] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[31] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[32] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[33] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[34] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[35] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[36] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[37] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[38] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[39] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[40] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[41] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[42] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[43] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon3"].terrain[44] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';

mappages["blackdragon3"].features = [];
mappages["blackdragon3"].features[0] = {name : 'StairDown2', x : 25, y : 21, entermap : 'blackdragon2', enterx : 25, entery : 21};
mappages["blackdragon3"].features[1] = {name : 'GrandfatherClock', x : 25, y : 20};
mappages["blackdragon3"].features[2] = {name : 'BedHead', x : 25, y : 24};
mappages["blackdragon3"].features[3] = {name : 'BedFoot', x : 26, y : 24};
mappages["blackdragon3"].features[4] = {name : 'Mirror', x : 28, y : 20};
mappages["blackdragon3"].features[5] = {name : 'Dresser', x : 28, y : 24};
mappages["blackdragon3"].features[6] = {name : 'LeftTable', x : 25, y : 22};
mappages["blackdragon3"].features[7] = {name : 'RightTable', x : 26, y : 22};
mappages["blackdragon3"].features[8] = {name : 'RightChair', x : 27, y : 22};
mappages["blackdragon3"].features[1] = {name : 'BlackDragonLadderWall', x : 24, y : 20};

mappages["blackdragon3"].npcs = [];

mappages["blackdragon3"].desc = "Black Dragon Castle";
mappages["blackdragon3"].music = 'Dark Towne';
mappages["blackdragon3"].savename = 'B Drag Castle';
mappages["blackdragon3"].exitmap = 'darkunknown';
mappages["blackdragon3"].exitx = '49';
mappages["blackdragon3"].exity = '90';
mappages["blackdragon3"].wraps = 'None';
mappages["blackdragon3"].enterx = '10';
mappages["blackdragon3"].entery = '43';
mappages["blackdragon3"].seeBelow = 'blackdragon2';
mappages["blackdragon3"].lightLevel = 'cycle';
mappages["blackdragon3"].alwaysRemember = '0';
mappages["blackdragon3"].scale = '1';
mappages["blackdragon3"].underground = '0';
mappages["blackdragon3"].undergroundDesc = '';
mappages["blackdragon3"].enterscript = '';
mappages["blackdragon3"].entertestscript = '';
mappages["blackdragon3"].exitscript = 'maps_exit';
mappages["blackdragon3"].exittestscript = '';
mappages["blackdragon3"].returnmap = 'darkunknown';
mappages["blackdragon3"].returnx = '69';
mappages["blackdragon3"].returny = '74';
mappages["blackdragon3"].returninfused = '0';
mappages["blackdragon3"].linkedMaps = [""];
mappages["blackdragon3"].editorLabels = '{}';


mappages["blackdragon4"] = {};
mappages["blackdragon4"].terrain = [];
 mappages["blackdragon4"].terrain[0] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["blackdragon4"].terrain[1] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["blackdragon4"].terrain[2] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["blackdragon4"].terrain[3] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["blackdragon4"].terrain[4] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["blackdragon4"].terrain[5] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["blackdragon4"].terrain[6] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["blackdragon4"].terrain[7] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["blackdragon4"].terrain[8] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["blackdragon4"].terrain[9] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[10] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[11] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[12] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[13] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[14] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[15] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[16] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[17] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[18] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[19] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ## #O ## ## ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[20] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ++ ++ ++ ++ ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[21] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ++ ++ ++ ++ ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[22] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb #O ++ ++ ++ ++ #O sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[23] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ++ ++ ++ ++ ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[24] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ++ ++ ++ ++ ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[25] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ## ## #O ## ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[26] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[27] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[28] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[29] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[30] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[31] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[32] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[33] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[34] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[35] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[36] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[37] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[38] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[39] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[40] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[41] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[42] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[43] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["blackdragon4"].terrain[44] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';

mappages["blackdragon4"].features = [];
mappages["blackdragon4"].features[0] = {name : 'LadderDown', x : 25, y : 20, entermap : 'blackdragon3', enterx : 25, entery : 20};
mappages["blackdragon4"].features[1] = {name : 'Chest', x : 25, y : 23};
mappages["blackdragon4"].features[2] = {name : 'Chest', x : 25, y : 24};
mappages["blackdragon4"].features[3] = {name : 'Chest', x : 26, y : 24};
mappages["blackdragon4"].features[4] = {name : 'BookshelfLeft', x : 27, y : 20};
mappages["blackdragon4"].features[5] = {name : 'BookshelfRight', x : 28, y : 20};
mappages["blackdragon4"].features[6] = {name : 'BookshelfRight', x : 28, y : 22};
mappages["blackdragon4"].features[7] = {name : 'BookshelfLeft', x : 27, y : 22};
mappages["blackdragon4"].features[8] = {name : 'UnlitBrazier', x : 28, y : 24};
mappages["blackdragon4"].npcs = [];

mappages["blackdragon4"].desc = "Black Dragon Castle";
mappages["blackdragon4"].music = 'Dark Towne';
mappages["blackdragon4"].savename = 'B Drag Castle';
mappages["blackdragon4"].exitmap = 'darkunknown';
mappages["blackdragon4"].exitx = '49';
mappages["blackdragon4"].exity = '90';
mappages["blackdragon4"].wraps = 'None';
mappages["blackdragon4"].enterx = '10';
mappages["blackdragon4"].entery = '43';
mappages["blackdragon4"].seeBelow = 'blackdragon3';
mappages["blackdragon4"].lightLevel = 'cycle';
mappages["blackdragon4"].alwaysRemember = '0';
mappages["blackdragon4"].scale = '1';
mappages["blackdragon4"].underground = '0';
mappages["blackdragon4"].undergroundDesc = '';
mappages["blackdragon4"].enterscript = '';
mappages["blackdragon4"].entertestscript = '';
mappages["blackdragon4"].exitscript = 'maps_exit';
mappages["blackdragon4"].exittestscript = '';
mappages["blackdragon4"].returnmap = 'darkunknown';
mappages["blackdragon4"].returnx = '69';
mappages["blackdragon4"].returny = '74';
mappages["blackdragon4"].returninfused = '0';
mappages["blackdragon4"].linkedMaps = [""];
mappages["blackdragon4"].editorLabels = '{}';

mappages["blackdragon4"].onload = function(mapref) {
  // check for act 1 to be over, if not, forcefields
  if ((gamestate.getMode() !== "loadgame") && (!DU.gameflags.getFlag("editor"))) {
    if (!DU.gameflags.getFlag("act2")) {
      let field1, field2, field3;
      field1 = localFactory.createTile("EnergyField");
      field2 = localFactory.createTile("EnergyField");
      field3 = localFactory.createTile("EnergyField");
      mapref.placeThing(26,20,field1);
      mapref.placeThing(25,21,field2);
      mapref.placeThing(26,21,field3);
    }
  }
}
