"use strict";

mappages["blackdragon"] = {};
mappages["blackdragon"].terrain = [];
 mappages["blackdragon"].terrain[0] = '.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. nn nn nn nn nn nn nn nn nn nn';
 mappages["blackdragon"].terrain[1] = '.. .. .. .. __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ nn nn nn nn nn nn';
 mappages["blackdragon"].terrain[2] = '.. .. .. ./ uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu';
 mappages["blackdragon"].terrain[3] = '.. .. .| uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu';
 mappages["blackdragon"].terrain[4] = '.. .. .| uu uu uu /. -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- nn nn nn';
 mappages["blackdragon"].terrain[5] = '.. .. .| uu uu /. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. nn';
 mappages["blackdragon"].terrain[6] = '.. .. .| uu uu |. .. .. .. .. .. .. #% #% #% #% #% #% #% #% #% .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..';
 mappages["blackdragon"].terrain[7] = '.. .. .| uu uu |. .. .. .. .. .. #% .. .. .. .. .. .. ., ., ., #% .. ## ## ## ## ## ## ## ## ## ## .. .. .. .. .. .. .. .. .. .. .. ..';
 mappages["blackdragon"].terrain[8] = '.. .. .| uu uu |. .. .. .. .. #% .. .. .. ,, .. .. ,, ., ., ., #% .. ## ## +* +* +* +* +* +* +* ## .. .. .. .. .. .. .. .. .. .. .. ..';
 mappages["blackdragon"].terrain[9] = '.. .. .| uu uu |. .. .. .. .. #% .. .. ,, .. .. .. .. .. .. .. #% .. ## ## +* +* +* +* +* +* +* ## ## ## ## ## ## ## ## ## ## ## .. ..';
mappages["blackdragon"].terrain[10] = '.. .. .| uu uu |. .. .. .. .. #% ,, .. __ .. .. .. ,, .. ,, .. #% .. ## ## +* +* +* +* +* +* +* ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. ..';
mappages["blackdragon"].terrain[11] = '.. .. .| uu uu |. .. .. .. .. #% .. ./ uu `. ,, .. .. .. .. ,, #% .. ## ## +* +* +* +* +* +* +* ## ++ ++ +o ++ ++ ++ +o ++ ++ ## .. ..';
mappages["blackdragon"].terrain[12] = '.. .. .| uu uu |. .. .. .. .. #% .. .` uu /. .. .. .. ,, .. .. #% .. ## ## +* +* +* +* +* +* +* ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. ..';
mappages["blackdragon"].terrain[13] = '.. .. .| uu uu |. .. .. .. .. #% ,; .. -, .. .. .. .. .. ,, .. #% .. ## ## ## ## ## ## ++ ## ## ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. ..';
mappages["blackdragon"].terrain[14] = '.. .. .| uu uu |. .. .. .. .. #% ,; ,; .. ,, .. .. .. .. .. .. #% .. ## ## b1 b2 b3 ++ ++ ++ ++ ## ++ ++ +o ++ ++ ++ +o ++ ++ ## .. ..';
mappages["blackdragon"].terrain[15] = '.. .. .| uu uu |. .. .. .. .. #% ,; ,; ,; .. .. .. .. .. .. ,, #% .. ## ++ b8 b0 b4 ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. ..';
mappages["blackdragon"].terrain[16] = '.. .. .| uu uu |. .. ## #+ ## ## ## ## ## ## #O ## ++ ## #O ## ## ## ## ## b7 b6 b5 ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. ..';
mappages["blackdragon"].terrain[17] = '.. .. .| uu uu |. .. ## ++ ## ## ++ ++ ++ ++ ++ ## ++ ## ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ +o ++ ++ ++ +o ++ ++ ## .. ..';
mappages["blackdragon"].terrain[18] = '.. .. .| uu uu |. .. ## ++ ## ## ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ## ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. ..';
mappages["blackdragon"].terrain[19] = '.. .. .| uu uu |. .. #+ ++ ## ## ## ++ ++ ++ ++ ## ++ ## ++ ++ ++ ++ ## ## ## ## ## ## ## ## ## ## ## ## ++ ++ ++ ++ ## ## ## ## .. ..';
mappages["blackdragon"].terrain[20] = '.. .. .| uu uu |. .. ## ++ ## ## ## ++ ++ ++ ++ ## ++ ## ## ## ## ## ## ## ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .. .. ..';
mappages["blackdragon"].terrain[21] = '.. .. .| uu uu |. .. ## ++ ## ## ## ## ## ## ## ## ++ ## ++ ++ ++ ++ ## ## ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .. .. ./';
mappages["blackdragon"].terrain[22] = '.. .. .| uu uu |. .. ## ++ ## ## ## ++ ++ ++ ++ ## ++ ## ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .. .| uu';
mappages["blackdragon"].terrain[23] = '.. .. .| uu uu |. .. #+ ++ ## ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ## ++ ++ ++ ++ ++ ++ ++ ++ ## ## ## ## ## ## ## .. .. .. ./ uu';
mappages["blackdragon"].terrain[24] = '.. .. .| uu uu |. .. ## ++ ## ## ## ++ ++ ++ ++ ## ++ ## ++ ++ ++ ++ ## ## ++ ++ ++ ++ ## ++ ++ ++ ## ++ ## ++ ## .. .. .. .. .| uu uu';
mappages["blackdragon"].terrain[25] = '.. .. .| uu uu |. .. ## ++ ## ## ## ## ## ## ## ## ++ ## ## ## ## ## ## ## ## ## ## ## ## ++ ++ ++ ## ++ ++ ++ ## .. .. .. .. .| uu uu';
mappages["blackdragon"].terrain[26] = '.. .. .| uu uu |. .. ## ++ ## ## ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ## .. .. .. .. .| uu uu';
mappages["blackdragon"].terrain[27] = '.. .. .| uu uu |. .. ## ++ ++ ## ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ## .. .. .. .. ./ uu uu';
mappages["blackdragon"].terrain[28] = '.. .. .| uu uu |. .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ## .. .. .. .| uu uu uu';
mappages["blackdragon"].terrain[29] = '.. .. .| uu uu |. .. #+ ++ ## #+ ## ++ ## #+ ## ## ## ## ## ## ## ++ ## ## ## ## ## ## ## ++ ## ## ## ## ## ++ ## ## .. .. .| uu uu uu';
mappages["blackdragon"].terrain[30] = '.. .. .| uu uu |. .. ## ++ ## uu +o ++ +o uu ## ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ## ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .| uu uu uu';
mappages["blackdragon"].terrain[31] = '.. .. .| uu uu |. .. ## ++ ## uu ++ ++ ++ uu ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .| uu uu uu';
mappages["blackdragon"].terrain[32] = '.. .. .| uu uu |. .. ## ++ ## uu +o ++ +o uu ## ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ## ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .. .` uu uu';
mappages["blackdragon"].terrain[33] = '.. .. .| uu uu |. .. #+ ++ ## uu ++ ++ ++ uu ## ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .. .| uu uu';
mappages["blackdragon"].terrain[34] = '.. .. .| uu uu |. .. ## ++ ## uu +o ++ +o uu ## ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ## ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .. .| uu uu';
mappages["blackdragon"].terrain[35] = '.. .. .| uu uu |. .. ## #+ ## uu ++ ++ ++ uu ## ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ## ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .. .| uu uu';
mappages["blackdragon"].terrain[36] = '.. .. .| uu uu |. .. .. .. ## uu +o ++ +o uu ## ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ## ## ## ## ## ## ## ## ## ## ## ## ## .. .. .. .| uu uu';
mappages["blackdragon"].terrain[37] = '.. .. .| uu uu |. .. .. .. ## uu ++ ++ ++ uu ## ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ## .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ./ uu uu';
mappages["blackdragon"].terrain[38] = '.. .. .| uu uu |. .. .. .. ## ## ## ++ ## ## ## ## #+ ## ## ## ## #+ ## ## ## ## .. .. .. .. .. .. .. .. .. .. .. .. .. .. .| uu uu uu';
mappages["blackdragon"].terrain[39] = '.. .. .| uu uu |. .. .. .. .. .. !! !! !! .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .| uu uu uu';
mappages["blackdragon"].terrain[40] = '.. .. .| uu uu `. __ __ __ __ __ !! !! !! __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ __ .. .. .. .. .. ./ uu uu uu';
mappages["blackdragon"].terrain[41] = '.. .. .| uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu `. __ .. .. .. uu uu uu uu';
mappages["blackdragon"].terrain[42] = '.. .. .. .` uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu uu `. __ ./ uu uu uu uu';
mappages["blackdragon"].terrain[43] = '.. .. .. .. -- -- -- -- -- -- -- !! !! !! -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- .` uu uu uu uu uu uu uu uu uu';
mappages["blackdragon"].terrain[44] = '.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. -- .` uu uu uu uu uu uu uu';

mappages["blackdragon"].features = [];
mappages["blackdragon"].features[0] = {name : 'Doorway', x : 12, y : 29};
mappages["blackdragon"].features[1] = {name : 'Door', x : 22, y : 29, desc : "locked door", locked : 1};
mappages["blackdragon"].features[2] = {name : 'Door', x : 19, y : 31, desc : "locked door", locked : 1};
mappages["blackdragon"].features[3] = {name : 'BDCLever', x : 11, y : 39};
mappages["blackdragon"].features[4] = {name : 'BedHead', x : 20, y : 32};
mappages["blackdragon"].features[5] = {name : 'BedHead', x : 20, y : 34};
mappages["blackdragon"].features[6] = {name : 'BedHead', x : 20, y : 36};
mappages["blackdragon"].features[7] = {name : 'BedFoot', x : 21, y : 32};
mappages["blackdragon"].features[8] = {name : 'BedFoot', x : 21, y : 34};
mappages["blackdragon"].features[9] = {name : 'BedFoot', x : 21, y : 36};
mappages["blackdragon"].features[10] = {name : 'BedHead', x : 24, y : 32};
mappages["blackdragon"].features[11] = {name : 'BedHead', x : 24, y : 34};
mappages["blackdragon"].features[12] = {name : 'BedHead', x : 24, y : 36};
mappages["blackdragon"].features[13] = {name : 'BedFoot', x : 25, y : 32};
mappages["blackdragon"].features[14] = {name : 'BedFoot', x : 25, y : 34};
mappages["blackdragon"].features[15] = {name : 'BedFoot', x : 25, y : 36};
mappages["blackdragon"].features[16] = {name : 'LeftTable', x : 23, y : 30};
mappages["blackdragon"].features[17] = {name : 'MiddleTable', x : 24, y : 30};
mappages["blackdragon"].features[18] = {name : 'RightTable', x : 25, y : 30};
mappages["blackdragon"].features[19] = {name : 'Brazier', x : 20, y : 30};
mappages["blackdragon"].features[20] = {name : 'Door', x : 17, y : 25};
mappages["blackdragon"].features[21] = {name : 'Door', x : 18, y : 23, desc : "locked door", locked : 1};
mappages["blackdragon"].features[22] = {name : 'Door', x : 16, y : 23, desc : "locked door", locked : 1};
mappages["blackdragon"].features[23] = {name : 'Door', x : 16, y : 18, desc : "locked door", locked : 1};
mappages["blackdragon"].features[24] = {name : 'Door', x : 18, y : 18, desc : "locked door", locked : 1};
mappages["blackdragon"].features[25] = {name : 'BedHead', x : 21, y : 19};
mappages["blackdragon"].features[26] = {name : 'BedHead', x : 21, y : 24};
mappages["blackdragon"].features[27] = {name : 'BedHead', x : 12, y : 24};
mappages["blackdragon"].features[28] = {name : 'BedHead', x : 12, y : 20};
mappages["blackdragon"].features[29] = {name : 'BedFoot', x : 22, y : 19};
mappages["blackdragon"].features[30] = {name : 'BedFoot', x : 22, y : 24};
mappages["blackdragon"].features[31] = {name : 'BedFoot', x : 13, y : 24};
mappages["blackdragon"].features[32] = {name : 'BedFoot', x : 13, y : 20};
mappages["blackdragon"].features[33] = {name : 'Mirror', x : 22, y : 21};
mappages["blackdragon"].features[34] = {name : 'Mirror', x : 14, y : 22};
mappages["blackdragon"].features[35] = {name : 'Mirror', x : 13, y : 17};
mappages["blackdragon"].features[36] = {name : 'Mirror', x : 20, y : 17};
mappages["blackdragon"].features[37] = {name : 'BookshelfLeft', x : 19, y : 21};
mappages["blackdragon"].features[38] = {name : 'BookshelfRight', x : 20, y : 21};
mappages["blackdragon"].features[39] = {name : 'BookshelfOne', x : 19, y : 19};
mappages["blackdragon"].features[40] = {name : 'BookshelfOne', x : 15, y : 20};
mappages["blackdragon"].features[41] = {name : 'BookshelfOne', x : 12, y : 22};
mappages["blackdragon"].features[42] = {name : 'DoorWindow', x : 17, y : 16};
mappages["blackdragon"].features[43] = {name : 'Fireplace', x : 11, y : 17};
mappages["blackdragon"].features[44] = {name : 'Fireplace', x : 11, y : 23};
mappages["blackdragon"].features[45] = {name : 'Fireplace', x : 23, y : 17};
mappages["blackdragon"].features[46] = {name : 'Fireplace', x : 23, y : 22};
mappages["blackdragon"].features[47] = {name : 'DoorWindow', x : 30, y : 29};
mappages["blackdragon"].features[48] = {name : 'Fireplace', x : 26, y : 31};
mappages["blackdragon"].features[49] = {name : 'LeftTable', x : 28, y : 31};
mappages["blackdragon"].features[50] = {name : 'LeftTable', x : 32, y : 31};
mappages["blackdragon"].features[51] = {name : 'MiddleTable', x : 29, y : 31};
mappages["blackdragon"].features[52] = {name : 'MiddleTable', x : 33, y : 31};
mappages["blackdragon"].features[53] = {name : 'MiddleTable', x : 34, y : 31};
mappages["blackdragon"].features[54] = {name : 'RightTable', x : 30, y : 31};
mappages["blackdragon"].features[55] = {name : 'RightTable', x : 35, y : 31};
mappages["blackdragon"].features[56] = {name : 'Fireplace', x : 27, y : 33};
mappages["blackdragon"].features[57] = {name : 'LeftTable', x : 28, y : 34};
mappages["blackdragon"].features[58] = {name : 'LeftTable', x : 32, y : 34};
mappages["blackdragon"].features[59] = {name : 'MiddleTable', x : 29, y : 34};
mappages["blackdragon"].features[60] = {name : 'MiddleTable', x : 33, y : 34};
mappages["blackdragon"].features[61] = {name : 'MiddleTable', x : 34, y : 34};
mappages["blackdragon"].features[62] = {name : 'RightTable', x : 35, y : 34};
mappages["blackdragon"].features[63] = {name : 'RightTable', x : 30, y : 34};
mappages["blackdragon"].features[64] = {name : 'BottomChair', x : 28, y : 32};
mappages["blackdragon"].features[65] = {name : 'BottomChair', x : 30, y : 32};
mappages["blackdragon"].features[66] = {name : 'BottomChair', x : 28, y : 35};
mappages["blackdragon"].features[67] = {name : 'BottomChair', x : 30, y : 35};
mappages["blackdragon"].features[68] = {name : 'BottomChair', x : 32, y : 35};
mappages["blackdragon"].features[69] = {name : 'BottomChair', x : 34, y : 35};
mappages["blackdragon"].features[70] = {name : 'TopChair', x : 29, y : 30};
mappages["blackdragon"].features[71] = {name : 'TopChair', x : 33, y : 30};
mappages["blackdragon"].features[72] = {name : 'TopChair', x : 35, y : 30};
mappages["blackdragon"].features[73] = {name : 'TopChair', x : 33, y : 33};
mappages["blackdragon"].features[74] = {name : 'TopChair', x : 35, y : 33};
mappages["blackdragon"].features[75] = {name : 'BottomChair', x : 34, y : 32};
mappages["blackdragon"].features[76] = {name : 'BottomChair', x : 32, y : 32};
mappages["blackdragon"].features[77] = {name : 'TopChair', x : 29, y : 33};
mappages["blackdragon"].features[78] = {name : 'Spit', x : 37, y : 30};
mappages["blackdragon"].features[79] = {name : 'Brazier', x : 37, y : 35};
mappages["blackdragon"].features[80] = {name : 'Fireplace', x : 36, y : 24};
mappages["blackdragon"].features[81] = {name : 'Fireplace', x : 34, y : 24};
mappages["blackdragon"].features[82] = {name : 'DoorWindow', x : 36, y : 29};
mappages["blackdragon"].features[83] = {name : 'Spit', x : 34, y : 28};
mappages["blackdragon"].features[84] = {name : 'LeftTable', x : 34, y : 26};
mappages["blackdragon"].features[85] = {name : 'RightTable', x : 35, y : 26};
mappages["blackdragon"].features[86] = {name : 'Door', x : 29, y : 23};
mappages["blackdragon"].features[87] = {name : 'Door', x : 11, y : 28, desc : "locked door", locked : 1};
mappages["blackdragon"].features[88] = {name : 'Throne', x : 37, y : 10};
mappages["blackdragon"].features[89] = {name : 'Door', x : 32, y : 17, desc : "magically locked door", locked : 2};
mappages["blackdragon"].features[90] = {name : 'PentagramSW', x : 25, y : 12};
mappages["blackdragon"].features[91] = {name : 'PentagramS', x : 26, y : 12};
mappages["blackdragon"].features[92] = {name : 'PentagramSE', x : 27, y : 12};
mappages["blackdragon"].features[93] = {name : 'PentagramE', x : 27, y : 11};
mappages["blackdragon"].features[94] = {name : 'PentagramC', x : 26, y : 11};
mappages["blackdragon"].features[95] = {name : 'PentagramW', x : 25, y : 11};
mappages["blackdragon"].features[96] = {name : 'PentagramN', x : 26, y : 10};
mappages["blackdragon"].features[97] = {name : 'PentagramNW', x : 25, y : 10};
mappages["blackdragon"].features[98] = {name : 'PentagramNE', x : 27, y : 10};
mappages["blackdragon"].features[99] = {name : 'BookshelfLeft', x : 25, y : 8};
mappages["blackdragon"].features[100] = {name : 'BookshelfLeft', x : 27, y : 8};
mappages["blackdragon"].features[101] = {name : 'BookshelfLeft', x : 29, y : 8};
mappages["blackdragon"].features[102] = {name : 'BookshelfRight', x : 26, y : 8};
mappages["blackdragon"].features[103] = {name : 'BookshelfRight', x : 28, y : 8};
mappages["blackdragon"].features[104] = {name : 'BookshelfRight', x : 30, y : 8};
mappages["blackdragon"].features[105] = {name : 'Mirror', x : 31, y : 8};
mappages["blackdragon"].features[106] = {name : 'Doorway', x : 29, y : 13};
mappages["blackdragon"].features[107] = {name : 'Brazier', x : 31, y : 12};
mappages["blackdragon"].features[108] = {name : 'Mirror', x : 30, y : 14};
mappages["blackdragon"].features[109] = {name : 'RightChair', x : 31, y : 18};
mappages["blackdragon"].features[110] = {name : 'RightTable', x : 30, y : 18};
mappages["blackdragon"].features[111] = {name : 'LeftTable', x : 29, y : 18};
mappages["blackdragon"].features[112] = {name : 'LeftTable', x : 25, y : 21};
mappages["blackdragon"].features[113] = {name : 'MiddleTable', x : 26, y : 21};
mappages["blackdragon"].features[114] = {name : 'RightTable', x : 27, y : 21};
mappages["blackdragon"].features[115] = {name : 'MoatLeverOff', x : 9, y : 27};
mappages["blackdragon"].features[116] = {name : 'BookshelfLeft', x : 25, y : 24};
mappages["blackdragon"].features[117] = {name : 'BookshelfRight', x : 26, y : 24};
mappages["blackdragon"].features[118] = {name : 'BookshelfRight', x : 28, y : 24};
mappages["blackdragon"].features[119] = {name : 'BookshelfLeft', x : 27, y : 24};
mappages["blackdragon"].features[120] = {name : 'TopChair', x : 26, y : 20};
mappages["blackdragon"].features[121] = {name : 'SmallBox', x : 20, y : 37, lootgroup : '', lootedid : ''};
mappages["blackdragon"].features[122] = {name : 'SmallBox', x : 20, y : 35, lootgroup : '', lootedid : ''};
mappages["blackdragon"].features[123] = {name : 'SmallBox', x : 20, y : 33, lootgroup : '', lootedid : ''};
mappages["blackdragon"].features[124] = {name : 'SmallBox', x : 25, y : 33, lootgroup : '', lootedid : ''};
mappages["blackdragon"].features[125] = {name : 'SmallBox', x : 25, y : 35, lootgroup : '', lootedid : ''};
mappages["blackdragon"].features[126] = {name : 'SmallBox', x : 25, y : 37, lootgroup : '', lootedid : ''};
mappages["blackdragon"].features[127] = {name : 'Chest', x : 17, y : 30, lootgroup : '', lootedid : ''};
mappages["blackdragon"].features[128] = {name : 'Chest', x : 16, y : 30, lootgroup : '', lootedid : ''};
mappages["blackdragon"].features[129] = {name : 'Chest', x : 16, y : 31, lootgroup : '', lootedid : ''};
mappages["blackdragon"].features[130] = {name : 'Chest', x : 16, y : 36, lootgroup : '', lootedid : ''};
mappages["blackdragon"].features[131] = {name : 'Chest', x : 16, y : 37, lootgroup : '', lootedid : ''};
mappages["blackdragon"].features[132] = {name : 'Chest', x : 17, y : 37, lootgroup : '', lootedid : ''};
mappages["blackdragon"].features[133] = {name : 'Fireplace', x : 24, y : 15};
mappages["blackdragon"].features[134] = {name : 'BedHead', x : 25, y : 17};
mappages["blackdragon"].features[135] = {name : 'BedFoot', x : 26, y : 17};
mappages["blackdragon"].features[136] = {name : 'WallPortcullis', x : 12, y : 38, locked : 1};

mappages["blackdragon"].npcs = [];
mappages["blackdragon"].npcs[0] = {name : 'TownGuardNPC', x : 10, y : 40, NPCName: 'Guard', Conversation: 'bdc_outer_guard', Gender: 'female', Bark: '0', NPCBand: '0'};
mappages["blackdragon"].npcs[1] = {name : 'TownGuardNPC', x : 13, y : 35, NPCName: 'Guard', Conversation: 'bdc_guard', Gender: 'male', Bark: '0', NPCBand: '0'};
mappages["blackdragon"].npcs[2] = {name : 'TownGuardNPC', x : 11, y : 35, NPCName: 'Guard', Conversation: 'bdc_guard', Gender: 'female', Bark: '0', NPCBand: '0'};
mappages["blackdragon"].npcs[3] = {name : 'PrinceNPC', x : 37, y : 12, NPCName: 'Prince Lance', Conversation: 'lance', Gender: 'male', Bark: '0', NPCBand: '0'};
mappages["blackdragon"].npcs[4] = {name : 'BlackDragonNPC', x : 39, y : 15, NPCName: 'Black Dragon', Conversation: 'blackdragon', Gender: 'male', Leash: 2, Bark: '0', NPCBand: '0'};
mappages["blackdragon"].npcs[5] = {name : 'TownGuardNPC', x : 34, y : 20, NPCName: 'Guard', Conversation: 'bdc_throne_guard', Gender: 'male', Bark: '0', NPCBand: '0'};
mappages["blackdragon"].npcs[6] = {name : 'TownGuardNPC', x : 33, y : 16, NPCName: 'Guard', Conversation: 'bdc_throne_guard', Gender: 'female', Bark: '0', NPCBand: '0'};
mappages["blackdragon"].npcs[7] = {name : 'TownGuardNPC', x : 8, y : 34, NPCName: 'Guard', Conversation: 'bdc_guard', Gender: 'male', Bark: '0', NPCBand: '0'};
mappages["blackdragon"].npcs[8] = {name : 'TownGuardNPC', x : 8, y : 27, NPCName: 'Guard', Conversation: 'bdc_guard', Gender: 'monster', Bark: '0', NPCBand: '0'};
mappages["blackdragon"].npcs[9] = {name : 'TownsfolkVillagerNPC', x : 16, y : 9, NPCName: 'Laurie', Conversation: 'laurie', Gender: 'female', Bark: '0', NPCBand: '0', OverrideGraphic: '310.gif'};
mappages["blackdragon"].npcs[10] = {name : 'MageVillagerNPC', x : 26, y : 20, NPCName: 'Justice', Conversation: 'justice', Gender: 'female', Bark: '0', NPCBand: '0', OverrideGraphic: '303.gif'};

mappages["blackdragon"].desc = "Black Dragon Castle";
mappages["blackdragon"].music = 'Dark Towne';
mappages["blackdragon"].exitmap = 'darkunknown';
mappages["blackdragon"].exitx = '49';
mappages["blackdragon"].exity = '90';
mappages["blackdragon"].wraps = 'None';
mappages["blackdragon"].enterx = '10';
mappages["blackdragon"].entery = '43';
mappages["blackdragon"].seeBelow = '';
mappages["blackdragon"].lightLevel = 'bright';
mappages["blackdragon"].alwaysRemember = '0';
mappages["blackdragon"].scale = '1';
mappages["blackdragon"].underground = '0';
mappages["blackdragon"].enterscript = '';
mappages["blackdragon"].entertestscript = '';
mappages["blackdragon"].exitscript = 'maps_exit';
mappages["blackdragon"].exittestscript = '';
mappages["blackdragon"].returnmap = 'darkunknown';
mappages["blackdragon"].returnx = '69';
mappages["blackdragon"].returny = '74';
mappages["blackdragon"].returninfused = '0';
mappages["blackdragon"].linkedMaps = [""];

mappages["blackdragon"].onload = function(mapref) {
  // check for act 1 to be over, if so, gate is open
  if (DU.gameflags.getFlag("act2")) {
    Open_BDC_Gate(this);
  }
}

mappages["blackdragon"].maps_exit = function() {
  this.Exit = function(who,tomap,fromx,fromy,tox,toy) {
    DU.gameflags.deleteFlag("bdc_gate_open");
  }
}

function Open_BDC_Gate(mapref) {
  // makes sense for this to be here. Called in onload if rebellion is over, and by the outer guard if you have the pin
  // working here
  if (mapref.getName() === "blackdragon") {
    mapref.getTile(11,39).getTopFeature().setGraphicArray(["moatLever-on.gif","moatLever-on.gif",0,0]);
    var gate = mapref.getTile(12,38).getTopFeature();
    gate.unlockMe();
    gate.use();
    var planks = localFactory.createTile("PlanksNS");
    mapref.setTerrain(11,41,planks);
    mapref.setTerrain(12,41,planks);
    mapref.setTerrain(13,41,planks);
    mapref.setTerrain(11,42,planks);
    mapref.setTerrain(12,42,planks);
    mapref.setTerrain(13,42,planks);
    DrawMainFrame("draw",PC.getHomeMap().getName(),PC.getx(),PC.gety());
  }
}