"use strict";

// MAP BEGINS HERE
mappages["grotto"] = {};
mappages["grotto"].terrain = [];
 mappages["grotto"].terrain[0] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["grotto"].terrain[1] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["grotto"].terrain[2] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["grotto"].terrain[3] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["grotto"].terrain[4] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["grotto"].terrain[5] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["grotto"].terrain[6] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["grotto"].terrain[7] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["grotto"].terrain[8] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["grotto"].terrain[9] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[10] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[11] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[12] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[13] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[14] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[15] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cf BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[16] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[17] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[18] = 'BK BK BK BK BK BK BK BK BK cw cw cw cw BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[19] = 'BK BK BK BK BK BK BK cw cw cw .. .. cw cw cw BK BK BK BK BK BK BK BK cw cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[20] = 'BK BK BK BK BK BK cw cw .. .. .. .. .. .. cw cw cw BK BK BK BK BK BK cw cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[21] = 'BK BK BK BK BK BK cw ww |. .. .. .. .. .. .. bd cw BK BK BK BK BK BK cw .. .. .. cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[22] = 'BK BK BK BK BK BK cw ww `. __ __ __ __ .. .. bd cw BK BK BK BK BK BK cw ww ww ww cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[23] = 'BK BK BK BK BK BK cw ww ww ww ww ww ww `. .. bd cw BK BK BK BK cw cw cw ww ww ww cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[24] = 'BK BK BK BK BK BK cw W0 W6 ww ww ww ww ww |. cw cw BK BK BK cw cw ww ww ww ww ww ww cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[25] = 'BK BK BK BK BK BK cw cw W9 W6 ww ww ww cw cw cw BK BK cw cw cw ww ww ww /. -- .` ww cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[26] = 'BK BK BK BK BK BK BK cw cw W9 W6 ww ww cw BK BK BK cw cw ww ww ww ww ww `. __ ./ ww cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[27] = 'BK BK BK BK BK BK BK BK cw cw W3 ww ww cw cw cw cw cw ww ww ww ww ww ww ww ww ww ww ww cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[28] = 'BK BK BK BK BK BK BK BK BK cw W9 W6 ww ww cw ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[29] = 'BK BK BK BK BK BK BK BK BK cw WW W3 ww ww ww ww ww ww ww ww /. -- .` ww ww ww ww ww ww ww cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[30] = 'BK BK BK BK BK BK BK BK BK cw WW W9 W0 W6 ww ww ww ww /. -- .. .. .| w10 ww ww ww ww ww ww ww ww cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[31] = 'BK BK BK BK BK BK BK BK BK cw cw WW WW W9 W6 ww ww ww |. .. .. .. .| w11 ww ww ww ww ww ww ww ww ww cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[32] = 'BK BK BK BK BK BK BK BK BK cw cw WW WW WW W9 W6 ww ww |. .. .. .. ./ ww ww ww ww ww ww ww ww ww ww ww cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[33] = 'BK BK BK BK BK BK BK BK cw cw W+ WW WW WW WW W3 ww ww `. __ __ ./ ww ww W4 W6 ww ww ww ww ww ww ww ww W2 cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[34] = 'BK BK BK BK BK BK BK cw cw ww W5 W1 W1 W+ WW W9 W6 ww ww w9 w11 ww ww ww W5 W7 ww ww ww ww ww ww ww ww W2 WW cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[35] = 'BK BK BK BK BK BK cw cw ww ww ww ww ww W5 W+ WW W9 W6 ww ww ww W4 W0 W6 ww w8 w1 w1 w1 w1 w10 ww ww ww W2 WW WW WW WW cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[36] = 'BK BK BK BK cw cw cw w2 ww ww /. -- .` ww W5 W+ WW W9 W6 ww ww W5 W1 W7 ww w3 uu uu uu uu w5 w10 ww W4 W= WW WW WW W8 W7 cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[37] = 'BK BK BK BK cw uu uu w2 ww ww |. .. .. .` ww W2 WW WW W3 ww ww ww ww ww /. -- -- -- -- .` uu w2 ww W2 WW WW WW WW W3 ww cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[38] = 'BK BK BK BK cw uu /. -- .` ww `. __ __ ./ ww W5 W+ WW W9 W6 ww ww ww /. .. .. .. .. .. .. .` w2 ww W2 WW WW WW WW W3 ww ww cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[39] = 'BK BK BK BK cw uu `. __ ./ ww ww ww ww ww ww ww W2 WW WW W3 ww ww w8 |. .. .. .. .. .. .. .| w11 ww W2 WW WW WW WW W3 ww ww cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[40] = 'BK BK BK BK cw uu uu w2 ww ww ww ww ww ww ww ww W2 WW WW W9 W6 ww w3 `. __ .. .. .. .. .. .| ww W4 W= WW WW WW W8 W7 ww ww ww cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[41] = 'BK BK BK BK cw cw w4 w11 ww ww ww ww ww ww cw ww W2 WW WW WW W9 W6 w3 uu uu `. __ __ __ __ ./ ww W2 WW WW WW WW W3 ww ww ww ww ww cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[42] = 'BK BK BK BK BK cw cw ww ww ww ww ww ww cw cw cw cw WW WW WW WW W3 w9 w0 w0 w0 w11 ww ww ww ww ww W2 WW WW WW WW W3 ww /. .` ww ww ww cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[43] = 'BK BK BK BK BK BK cw cw cw ww ww cw cw cw BK BK cw cw cw cw WW W3 ww ww ww ww ww ww ww ww ww ww W2 cw WW WW W8 W7 ww |. .. -- .` ww ww cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[44] = 'BK BK BK BK BK BK BK BK cw cw cw cw BK BK BK BK BK BK cw cw WW W3 ww ww ww cw cw cw cw cw cw cw cw cw cw cw W7 ww ww `. .. .. .| ww ww ww cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[45] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw W8 W1 W7 ww ww ww ww cw cw cw cw cw BK BK BK BK cw cw ww ww ww `. __ ./ ww ww ww cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[46] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw ww W5 W1 W7 ww ww ww ww ww ww ww ww ww ww cw cw BK BK BK BK cw cw cw ww ww ww ww ww ww ww cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[47] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw ww ww ww ww ww ww /. .` ww ww ww ww ww ww ww ww cw cw BK BK BK BK BK cw ww ww ww ww ww ww cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[48] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK cw ww ww ww ww ww ww ww `. ./ ww w8 w1 w1 w10 ww ww ww ww cw BK BK BK BK BK cw cw ww ww cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[49] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK cw ww w3 uu uu uu w2 ww ww ww ww w3 uu uu w5 w10 ww ww ww cw BK BK BK BK BK BK cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[50] = 'BK BK BK BK BK BK BK BK BK BK BK BK cw cw ww w3 uu w4 w0 w11 ww ww ww ww w9 w0 w6 uu w2 ww ww ww cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[51] = 'BK BK BK BK BK BK BK BK BK BK BK BK cw ww ww w3 uu w2 ww ww /. -- -- .` ww ww w9 w0 w11 w8 w1 w10 cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[52] = 'BK BK BK BK BK BK BK BK BK BK BK BK cw ww ww w3 uu w2 ww ww |. .. .. .. -- .` ww ww ww w3 uu w2 ww cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[53] = 'BK BK BK BK BK BK BK BK BK BK BK BK cw ww ww w9 w0 w11 ww ww |. .. .. .. .. .| ww ww ww w3 uu w2 ww cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[54] = 'BK BK BK BK BK BK BK BK BK BK BK BK cw ww ww w8 w1 w10 ww ww |. .. .. .. .. ./ ww ww ww w9 w0 w11 ww cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[55] = 'BK BK BK BK BK BK BK BK BK BK BK BK cw cw ww w3 uu w5 w10 ww `. __ __ __ ./ ww w8 w1 w1 w10 ww ww ww cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[56] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK cw ww w3 uu uu w2 ww ww ww ww ww ww ww w3 uu uu w2 ww ww ww cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[57] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw w9 w6 uu w2 ww ww ww ww ww w8 w1 w7 uu w4 w11 ww ww cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[58] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw w9 w0 w11 ww ww ww ww ww w3 uu uu uu w2 ww ww ww cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[59] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw ww ww ww ww ww ww ww w9 w0 w0 w0 w11 ww ww cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[60] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw ww ww ww ww ww ww ww ww ww cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[61] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw cw cw cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[62] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto"].terrain[63] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';

mappages["grotto"].features = [];
mappages["grotto"].features[0] = {name : 'LadderUp', x : 22, y : 53, entermap : 'ellusus', enterx : 27, entery : 30};
mappages["grotto"].features[1] = {name : 'GrottoLeverOff', x : 15, y : 22};
mappages["grotto"].features[2] = {name : 'Chest', x : 40, y : 43, lootgroup : 'mostlygold', lootedid : 'grot5'};
mappages["grotto"].features[3] = {name : 'Chest', x : 41, y : 43, lootgroup : 'mostlygold', lootedid : 'grot6'};
mappages["grotto"].features[4] = {name : 'Chest', x : 41, y : 44, lootgroup : 'mostlygold', lootedid : 'grot8'};
mappages["grotto"].features[5] = {name : 'Chest', x : 40, y : 44, lootgroup : 'mostlygold', lootedid : 'grot7'};
mappages["grotto"].features[6] = {name : 'Chest', x : 11, y : 37, lootgroup : 'mostlygold', lootedid : 'grot3'};
mappages["grotto"].features[7] = {name : 'Chest', x : 11, y : 38, lootgroup : 'mostlygold', lootedid : 'grot4'};
mappages["grotto"].features[8] = {name : 'Chest', x : 7, y : 39, lootgroup : 'mostlygold', lootedid : 'grot2'};
mappages["grotto"].features[9] = {name : 'Chest', x : 7, y : 38, lootgroup : 'mostlygold', lootedid : 'grot1'};
mappages["grotto"].features[10] = {name : 'Chest', x : 25, y : 26, lootgroup : 'mostlygold', lootedid : 'grot9'};
mappages["grotto"].features[11] = {name : 'PileOfRocks', x : 23, y : 54};
mappages["grotto"].features[12] = {name : 'PileOfRocks', x : 26, y : 39};
mappages["grotto"].features[13] = {name : 'PileOfRocks', x : 29, y : 39};
mappages["grotto"].features[14] = {name : 'EnergyField', x : 24, y : 21};
mappages["grotto"].features[15] = {name : 'EnergyField', x : 25, y : 21};
mappages["grotto"].features[16] = {name : 'EnergyField', x : 26, y : 21};
mappages["grotto"].features[17] = {name : 'Coral', x : 18, y : 57};
mappages["grotto"].features[18] = {name : 'Coral', x : 18, y : 56};
mappages["grotto"].features[19] = {name : 'Coral', x : 17, y : 55};
mappages["grotto"].features[20] = {name : 'Coral', x : 16, y : 53};
mappages["grotto"].features[21] = {name : 'Coral', x : 15, y : 53};
mappages["grotto"].features[22] = {name : 'Coral', x : 15, y : 52};
mappages["grotto"].features[23] = {name : 'Coral', x : 15, y : 51};
mappages["grotto"].features[24] = {name : 'Coral', x : 17, y : 48};
mappages["grotto"].features[25] = {name : 'Coral', x : 18, y : 48};
mappages["grotto"].features[26] = {name : 'Coral', x : 26, y : 48};
mappages["grotto"].features[27] = {name : 'Coral', x : 27, y : 48};
mappages["grotto"].features[28] = {name : 'Coral', x : 27, y : 49};
mappages["grotto"].features[29] = {name : 'Coral', x : 28, y : 49};
mappages["grotto"].features[30] = {name : 'Coral', x : 29, y : 52};
mappages["grotto"].features[31] = {name : 'Coral', x : 29, y : 53};
mappages["grotto"].features[32] = {name : 'Coral', x : 29, y : 54};
mappages["grotto"].features[33] = {name : 'Coral', x : 30, y : 54};
mappages["grotto"].features[34] = {name : 'Coral', x : 25, y : 57};
mappages["grotto"].features[35] = {name : 'Coral', x : 26, y : 57};
mappages["grotto"].features[36] = {name : 'Coral', x : 28, y : 57};
mappages["grotto"].features[37] = {name : 'Coral', x : 28, y : 58};
mappages["grotto"].features[38] = {name : 'Coral', x : 8, y : 41};
mappages["grotto"].features[39] = {name : 'Coral', x : 9, y : 41};
mappages["grotto"].features[40] = {name : 'Coral', x : 10, y : 41};
mappages["grotto"].features[41] = {name : 'Coral', x : 10, y : 40};
mappages["grotto"].features[42] = {name : 'Coral', x : 10, y : 33};
mappages["grotto"].features[43] = {name : 'Coral', x : 10, y : 34};
mappages["grotto"].features[44] = {name : 'Coral', x : 11, y : 34};
mappages["grotto"].features[45] = {name : 'Coral', x : 12, y : 34};
mappages["grotto"].features[46] = {name : 'Coral', x : 12, y : 29};
mappages["grotto"].features[47] = {name : 'Coral', x : 19, y : 37};
mappages["grotto"].features[48] = {name : 'Coral', x : 20, y : 37};
mappages["grotto"].features[49] = {name : 'Coral', x : 19, y : 27};
mappages["grotto"].features[50] = {name : 'Coral', x : 20, y : 27};
mappages["grotto"].features[51] = {name : 'Coral', x : 22, y : 26};
mappages["grotto"].features[52] = {name : 'Coral', x : 22, y : 27};
mappages["grotto"].features[53] = {name : 'Coral', x : 23, y : 27};
mappages["grotto"].features[54] = {name : 'Coral', x : 26, y : 29};
mappages["grotto"].features[55] = {name : 'Coral', x : 26, y : 30};
mappages["grotto"].features[56] = {name : 'Coral', x : 27, y : 30};
mappages["grotto"].features[57] = {name : 'Coral', x : 27, y : 31};
mappages["grotto"].features[58] = {name : 'Coral', x : 29, y : 33};
mappages["grotto"].features[59] = {name : 'Coral', x : 30, y : 33};
mappages["grotto"].features[60] = {name : 'Coral', x : 31, y : 33};
mappages["grotto"].features[61] = {name : 'Coral', x : 31, y : 34};
mappages["grotto"].features[62] = {name : 'Coral', x : 39, y : 39};
mappages["grotto"].features[63] = {name : 'Coral', x : 39, y : 40};
mappages["grotto"].features[64] = {name : 'Coral', x : 40, y : 40};


mappages["grotto"].npcs = [];

mappages["grotto"].desc = "Underwater Grotto";
mappages["grotto"].longdesc = `You carefully pick your way down into the cave and to the waters under the earth. Here and there, islands of rock emerge from the waters. You feel the Rune of Earth pulsing in your skin, with the rhythm of the subtle waves.`;
mappages["grotto"].music = 'Cave';
mappages["grotto"].savename = `Grotto`;
mappages["grotto"].exitmap = 'ellusus';
mappages["grotto"].exitx = '27';
mappages["grotto"].exity = '30';
mappages["grotto"].wraps = '';
mappages["grotto"].enterx = '22';
mappages["grotto"].entery = '53';
mappages["grotto"].seeBelow = '';
mappages["grotto"].lightLevel = 'dark';
mappages["grotto"].alwaysRemember = '0';
mappages["grotto"].scale = '1';
mappages["grotto"].underground = '1';
mappages["grotto"].undergroundDesc = 'Underwater Grotto';
mappages["grotto"].enterscript = '';
mappages["grotto"].entertestscript = '';
mappages["grotto"].exitscript = '';
mappages["grotto"].exittestscript = '';
mappages["grotto"].returnmap = 'ellusus';
mappages["grotto"].returnx = '27';
mappages["grotto"].returny = '30';
mappages["grotto"].returninfused = '0';
mappages["grotto"].linkedMaps = ["grotto2","undergrotto"];
mappages["grotto"].editorLabels = '{}';
// MAP ENDS HERE

// MAP BEGINS HERE
mappages["grotto2"] = {};
mappages["grotto2"].terrain = [];
 mappages["grotto2"].terrain[0] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["grotto2"].terrain[1] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["grotto2"].terrain[2] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["grotto2"].terrain[3] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["grotto2"].terrain[4] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["grotto2"].terrain[5] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw WW WW cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["grotto2"].terrain[6] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw WW WW WW WW WW WW cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["grotto2"].terrain[7] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw WW WW WW WW WW WW WW WW cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["grotto2"].terrain[8] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw WW WW WW WW WW WW WW WW WW WW cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["grotto2"].terrain[9] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw cw cw W1 W+ WW WW WW WW WW WW WW WW cw BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw WW WW WW cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[10] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw w3 `. __ __ cw w2 ww W2 WW WW WW WW WW WW WW cw cw BK BK BK BK BK BK BK BK BK BK BK BK cw cw W8 W1 W1 W+ WW cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[11] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw w2 ww ww ww w3 uu uu uu uu w2 ww W5 W+ WW WW WW WW WW cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK cw WW W3 ww ww W2 WW WW cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw cw cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[12] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw w0 w11 ww ww ww w9 w0 w6 uu uu w2 ww ww W5 W+ cw cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw WW W9 W0 W0 W= WW WW cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw ww ww ww ww ww ww `. .. cw cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[13] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw ww ww ww ww ww /. cw cw w9 w0 w0 w11 ww ww ww cw cw BK BK BK BK BK BK cw cw cw cw cw BK BK BK BK BK BK BK cw WW WW WW WW WW WW WW cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw W4 W0 W0 W0 W6 ww ww ww ww ww `. __ __ cw .. cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[14] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw ww ww ww ww cw cw cw cw cw ww ww ww ww ww cw cw BK BK BK BK BK BK cw cw .. .. .. cw cw cw BK BK BK BK BK cw cw WW WW WW WW WW WW cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw ww ww ww W2 W8 W1 W1 W7 ww ww ww ww ww ww ww ww ww `. .. .. cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[15] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw ./ w2 ww ww ww ww cw cw cw BK BK BK cw ww ww ww ww cw cw BK BK BK BK BK BK BK cw .. .. .. .. ,, .. cw BK BK BK BK BK BK cw WW WW WW WW WW WW W3 cw cw BK BK BK BK BK cw cw cw cw cw cw cw cw cw w8 w1 w7 w2 W4 W0 W0 W= W3 ww ww ww ww ww W4 W0 W0 W0 W0 W6 ww ww `. .. cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[16] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw uu w2 ww ww ww cw cw BK BK BK BK cw cw ww ww ww ww cw cw BK BK BK BK BK BK BK cw .. ,, .. .. .. .. cw BK BK BK BK BK BK cw cw WW WW WW WW W8 W7 ww cw cw cw cw cw cw cw w8 w1 w10 w8 w1 w10 ww ww w3 uu uu w2 W2 W8 W1 W1 W7 ww W4 W0 W0 W6 W2 W8 W1 W1 W+ W3 ww ww ww `. __ cw BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[17] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw uu uu w5 w1 cw cw cw BK BK BK BK BK cw ww ww /. .` ww ww cw BK BK BK BK BK BK BK cw .. .. ,, .. .. .. cw cw BK BK BK BK BK BK cw cw cw WW W8 W7 ww ww ww ww cf cf cf cf w8 w7 uu w2 w3 uu w2 ww ww w9 w0 w0 w11 W2 W3 ww ww ww W4 W= WW WW W9 W= W3 ww ww W2 W9 W6 ww ww ww ww cw BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[18] = 'BK BK BK BK BK BK BK BK BK cw cw cw cw BK BK BK BK BK BK BK BK BK BK cw .` uu uu uu cw BK BK BK BK BK BK BK cw ww ww `. ./ ww ww cw cw BK BK BK BK BK BK cw .. .. .. .. .. ./ uu cw BK BK BK BK BK BK BK BK cw W1 W7 ww ww ww ww ww ww ww ww ww w3 uu w4 w11 w9 w0 w11 ww ww ww ww ww ww W2 W9 W0 W6 ww W2 WW WW WW WW WW W9 W6 ww W5 W+ W9 W6 ww ww w8 cw cw BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[19] = 'BK BK BK BK BK BK BK cw cw cw .. .. cw cw cw BK BK BK BK BK BK BK BK cw .| uu uu cw cw BK BK BK BK BK BK BK cw ww ww ww ww ww ww ww cw cw cw BK BK BK BK cw cw .. __ __ ./ uu uu cw BK BK BK BK BK BK BK cw cw ww ww ww ww ww ww ww ww ww ww ww w9 w0 w11 ww ww ww ww ww ww ww ww ww ww W5 W1 W+ W3 ww W2 WW WW /. -- .` WW W3 ww ww W5 W+ W3 ww ww w3 uu cw BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[20] = 'BK BK BK BK BK BK cw cw .. .. .. .. .. .. cw cw cw BK BK BK BK BK BK cw .| uu uu cw BK BK BK BK BK BK BK BK cw cw ww ww ww ww ww ww ww ww cw cw BK BK BK BK cw cw uu uu uu uu cw cw BK BK BK BK BK BK cw cw ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww /. -- -- -- .` ww ww ww ww ww ww W2 W3 ww W5 W+ WW `. __ ./ WW W3 ww ww W4 W= W3 ww ww w3 uu cw BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[21] = 'BK BK BK BK BK BK cw WW |. .. .. .. .. .. .. bd cw BK BK BK BK BK BK cw ./ uu uu cw BK BK BK BK BK BK BK BK BK cw cw cw ww ww ww ww ww ww ww cw cw cw cw cw BK cw cw uu uu uu cw cw BK BK BK BK BK BK cw ww W4 W0 W0 W0 W6 ww ww ww ww ww ww ww ww ww /. -- .. .. __ __ ./ ww ww ww ww ww ww W2 W3 ww ww W5 W+ WW WW WW WW W3 ww ww W2 W8 W7 ww ww w3 uu cw BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[22] = 'BK BK BK BK BK BK cw WW `. __ __ __ __ .. .. bd cw BK BK BK BK BK BK cw uu uu uu cw BK BK BK BK BK BK BK BK BK BK BK cw cw ww ww ww ww ww ww ww ww ww ww cw cw cw w3 uu uu uu uu cw cw BK BK BK BK cw cw ww W2 WW WW WW W9 W6 ww ww ww ww ww ww ww ww `. .. .. ./ ww ww ww w8 w1 w10 ww ww ww W2 W9 W0 W0 W6 W5 W1 W1 W1 W+ W3 ww ww W2 W3 ww ww ww w9 cw cw BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[23] = 'BK BK BK BK BK BK cw WW WW W3 ww ww ww `. .. bd cw BK BK BK BK cw cw cw uu uu uu cw cw BK BK BK BK BK BK cw cw cw cw cw cw cw ww ww ww ww ww ww ww ww w8 w1 w1 w10 w9 w6 uu uu uu uu cw BK BK BK BK cw ww ww W2 WW WW WW WW W3 ww ww ww w8 w1 w10 ww ww ww `. ./ ww ww w8 w1 w7 uu w5 ww ww ww W5 W1 W1 W+ W9 W0 W0 W0 W0 W= W3 ww W4 W= W3 ww ww ww ww cw BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[24] = 'BK BK BK BK BK BK cw WW WW W9 W6 ww ww ww |. cw cw BK BK BK cw cw uu uu uu uu uu uu cw BK BK BK BK BK cw cw WW WW WW WW WW W9 W6 ww ww ww ww ww ww ww w3 uu uu w2 ww w9 w0 w6 uu uu cw BK BK BK BK cw ww ww W2 WW WW WW W8 W7 ww ww w8 w7 uu w2 ww ww ww ww ww ww ww w9 w0 w6 uu uu w10 ww ww ww ww ww W5 W1 W1 W1 W1 W1 W1 W7 ww W2 W8 W7 ww ww ww ww cw BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[25] = 'BK BK BK BK BK BK cw cw WW WW W9 W6 ww cw cw cw BK BK cw cw cw uu uu uu /. -- .` uu cw BK BK BK BK BK cw W2 WW WW ww WW WW WW W9 W6 ww ww ww ww ww w8 w7 /. -- -- .` w8 w1 w7 uu cw cw BK BK BK cw cw ww ww W5 W+ WW W8 W7 ww ww /d -d d` uu w2 ww ww ww ww ww ww cw cw cw w9 w6 uu w2 ww ww ww ww ww ww ww ww ww ww ww ww ww ww W2 W3 ww ww ww ww ww cw BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[26] = 'BK BK BK BK BK BK BK cw cw WW WW W3 ww cw BK BK BK cw cw uu uu uu uu uu `. __ ./ uu cw cw BK BK BK cw cw W= WW WW WW ww WW WW WW W3 ww cw cw ww ww w3 uu |. .. .. .. -- .` uu w4 cw BK BK BK BK cw ww ww ww ww W5 W1 W7 ww /d -d ., ., d| uu w5 w10 ww ww cw cw cw cw BK cw cw w3 uu w2 ww ww /. -- -- .` ww ww ww ww W4 W0 W0 W0 W= W3 ww w8 w1 cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[27] = 'BK BK BK BK BK BK BK BK cw cw WW W3 ww cw cw cw cw cw uu uu uu uu uu uu uu uu uu uu uu cw cw BK BK cw W2 WW WW WW WW WW WW WW WW W3 cw cw cw ww ww w3 uu |. .. .. .. .. .| uu w2 cw BK BK BK BK cw ww ww ww w8 w1 w10 ww /d ., ., ., .* d| uu uu w2 cf cw cw BK BK BK BK BK cw cw cw w2 ww /. .. .. .. .. -- .` ww ww W5 W1 W1 W1 W1 W7 ww w3 uu cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[28] = 'BK BK BK BK BK BK BK BK BK cw WW W3 w8 w7 cw uu uu uu uu /. -- -- .` uu uu uu uu uu uu uu cw BK BK cw W2 WW WW WW WW WW ww WW WW W9 cw BK cw cw ww w3 uu `. __ .. .. ,, .| w0 w11 cw cw BK BK BK cw ww ww ww w3 uu w5 w10 |d .* ., ., _d d/ uu uu cw cw cw BK BK BK BK BK BK BK BK cw cw cw cw .. .. .. .. .. .. .` ww ww ww ww ww ww ww /. -- -- cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[29] = 'BK BK BK BK BK BK BK BK BK cw W1 W7 w9 w6 uu uu uu /. -- .. .. .. .. .` uu uu uu uu uu uu cw cw cw cw cw W+ WW WW WW WW WW ww WW cw cw BK BK cw cw w3 uu uu uu `. __ __ ./ ww ww ww cw BK BK BK cw .` ww ww w9 w6 uu w2 |d ., ., d/ uu uu uu uu cw BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw .. .. .. .. .. .. -- -- -- -- -- -- -- .. ,, .. cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[30] = 'BK BK BK BK BK BK BK BK BK cw ww ww ww w3 uu uu /. .. .. .. .. .. .. .. .` uu uu uu uu uu uu uu cw cw cw cw W+ WW WW WW WW WW WW cw BK BK BK BK cw cw w0 w6 uu uu uu w2 ww ww ww ww cw BK BK BK cw cw ww ww ww w9 w0 w11 `d _d d/ uu uu w4 w0 cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw .. .. .. __ __ .. __ __ __ __ __ .. .. ,, .. cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[31] = 'BK BK BK BK BK BK BK BK BK cw cw ww ww w9 w6 /. .. .. .. .. .. .. .. .. .| w6 uu uu uu uu uu uu uu cw cw cw cw W1 W+ WW WW WW cw cw BK BK BK BK cw ww ww w9 w0 w0 w0 w11 ww ww ww ww cw BK BK cw cw ww ww ww ww ww ww ww ww w3 uu w4 w0 w11 cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw __ ./ ch ch ch ch ch ch ch ch `. __ .. cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[32] = 'BK BK BK BK BK BK BK BK BK cw cw ww ww ww w9 |. .. .. .. .. .. .. .. .. .| w9 w6 uu uu uu uu uu uu uu cw cw cw cw cw cw cw cw cw BK BK BK BK BK cw ww ww w8 w1 w10 ww ww ww ww ww ww cw BK BK cw ww ww ww ww ww ww ww ww ww w9 w0 w11 W4 W0 cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw ch ch ch ch ch ch ch ch ch ch ch ch cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[33] = 'BK BK BK BK BK BK BK BK cw cw w2 ww ww ww ww `. __ .. .. .. .. .. .. __ ./ ww w9 w0 w6 uu uu uu uu uu w4 cw cw BK BK BK BK BK BK BK BK BK BK BK cw ww ww w3 uu w2 ww ww ww ww ww cw cw cw cw cw ww ww ww ww ww ww ww ww ww ww cw W0 W= WW cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw ch ch ch ch ch ch ch ch ch ch ch ch cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[34] = 'BK BK BK BK BK BK BK cw cw uu w5 w1 w10 ww ww ww w3 `. __ __ __ __ ./ ww ww ww ww ww w3 uu uu uu uu uu w2 ww cw cw cw cw BK BK BK BK BK BK BK BK cw cw ww w9 w0 w11 ww ww ww ww ww cw cw cw ww ww ww ww ww ww ww ww ww ww cw cw cw W8 W1 W+ W3 ww ww cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw -- .` ch ch ch ch ch ch ch ch /. -- cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[35] = 'BK BK BK BK BK BK cw cw uu uu uu uu /. .` ww ww w9 w6 uu uu w2 ww ww ww /. -- .` ww w3 uu uu uu uu uu w2 ww ww ww ww cw cw BK BK BK BK BK BK BK BK cw ww ww ww ww ww ww ww ww ww cw cw ww ww ww ww ww ww ww ww ww cw cw cw BK cw W3 ww W2 W9 W0 W0 cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw .. -- -- .. -- -- -- -- -- .. cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[36] = 'BK BK BK BK cw cw cw uu uu uu /. -- .. .. .` ww ww w9 w6 uu w2 ww /. -- .. .. .. -- -- -- .` uu uu w4 w11 ww ww ww w8 w7 cw BK BK BK BK BK BK BK BK cw cw ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww cw BK BK BK cw W3 ww W2 WW W8 W1 W+ cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw .. .. .. .. .. .. .. .. cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[37] = 'BK BK BK BK cw ff ff .` uu /. .. .. .. .. .| ww ww ww w3 uu w5 w1 |. .. .. .. .. .. .. .. .. .` uu w2 ww ww ww ww w3 uu cw cw BK BK BK BK BK BK BK cw cw ww ww ww /. -- -- -- .` ww ww ww ww ww cw ww ww ww ww cw cw BK BK BK cw cw W0 W= W8 W7 ww cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw ,, .. .. .. ,, cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[38] = 'BK BK BK BK cw ff .. .. -- .. __ .. .. .. .| w10 ww ww w9 w6 uu uu |. .. .. .. .. .. .. .. .. .| uu w2 ww ww ww ww w3 uu uu cw BK BK BK BK BK BK BK cw .| ww ww ww `. __ __ __ ./ ww ww ww ww cw cw cw cw cw cw cw BK BK BK BK BK cw cw WW W3 ww cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw ,, .. .. .. .. cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[39] = 'BK BK BK BK cw ff .. .. __ ./ uu `. __ __ ./ w2 ww ww ww w9 w0 w6 `. .. .. .. .. .. .. .. .. .| uu w2 ww ww ww ww w3 uu w4 cw cw BK BK BK BK BK BK cw .. .` ww ww ww ww ww ww ww ww cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw __ __ ./ `. .. cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[40] = 'BK BK BK BK cw .. .. ./ uu uu uu uu uu uu uu w2 ww W4 W0 W0 W6 w9 w6 `. __ .. .. .. .. .. .. .| w4 w11 ww ww ww w8 w7 uu w2 ww cw cw BK BK BK BK BK cw cw cw cw w1 w1 w1 w10 ww ww cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw ww ww ww ww `. cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[41] = 'BK BK BK BK cw cw .| uu uu uu uu uu uu uu cw w2 W4 W= WW WW W9 W6 w3 uu uu `. __ __ __ __ __ ./ w2 ww ww ww ww w9 w6 uu w5 w1 w7 cw cw BK BK BK BK BK BK BK cw uu uu uu w5 w10 ww cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw ww ww ww ww ww ww ww cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[42] = 'BK BK BK BK BK cw cw uu uu uu uu uu uu cw cw cw cw WW WW WW WW W3 w3 w4 w0 w6 uu uu uu uu uu uu w2 ww ww ww ww ww w3 /. .` uu uu uu cw cw BK BK BK BK BK BK cw cw cw uu uu cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw ww ww ww ww ww ww ww ww ww cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[43] = 'BK BK BK BK BK BK cw cw cw uu uu cw cw cw BK BK cw cw cw cw W1 W7 w3 w2 ww w3 uu uu uu uu uu uu w5 cw ww ww ww ww w3 |. .. -- .` uu uu cw cw BK BK BK BK BK BK BK cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw w10 W4 W0 W6 ww W4 W0 W6 ww ww ww cw BK BK BK BK BK BK cw cw cw cw BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[44] = 'BK BK BK BK BK BK BK BK cw cw cw cw BK BK BK BK BK BK cw cw ww w8 w7 w5 w1 cw cw cw cw cw cw cw cw cw cw cw ww w8 w7 `. .. .. .| uu uu uu cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw uu w2 W2 WW W3 ww W2 WW W3 ww ww ww cw cw BK BK BK cw cw cw .. .. cw cw BK BK BK BK BK BK';
mappages["grotto2"].terrain[45] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw ww ww w3 uu uu uu uu cw cw cw cw cw BK BK BK BK cw cw w7 uu uu `. __ ./ uu uu uu cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw uu uu w2 W2 WW W3 ww W2 WW W3 ww ww ww ww cw BK BK BK cw .. .. .. .. .. cw BK BK BK BK BK BK';
mappages["grotto2"].terrain[46] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw uu w2 ww ww w8 w7 uu uu uu uu uu uu uu uu cw cw BK BK BK BK cw cw cw uu uu uu uu uu uu uu cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw uu uu w2 W2 WW W3 ww W2 WW W3 ww ww ww ww cw BK BK BK cw .. .. .. .. .. cw BK BK BK BK BK BK';
mappages["grotto2"].terrain[47] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw uu uu w5 w1 w1 w7 /. .` uu uu uu uu uu uu uu uu cw cw BK BK BK BK BK cw uu uu uu uu uu uu cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw uu w2 W5 W1 W7 ww W5 W1 W7 ww w8 w1 cw cw BK BK BK cw .. .. !! .. .. cw BK BK BK BK BK BK';
mappages["grotto2"].terrain[48] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK cw .| uu uu uu uu uu /. .. .| uu uu uu uu uu uu uu uu uu cw BK BK BK BK BK cw cw uu uu cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw w11 ww ww ww ww ww ww ww w8 w7 uu cw cw cw BK BK cw cw .. !! .. .. cw BK BK BK BK BK BK';
mappages["grotto2"].terrain[49] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK cw ./ uu uu uu uu uu |. .. .. .` uu uu uu uu uu uu uu uu cw BK BK BK BK BK BK cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw ww ww ww ww ww ww w8 w7 uu uu |. .. cw cw cw cw cw .. .. .. cw cw BK BK BK BK BK BK';
mappages["grotto2"].terrain[50] = 'BK BK BK BK BK BK BK BK BK BK BK BK cw cw uu uu uu uu uu /. .. .. .. .. .` uu uu uu uu uu uu uu cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw ww ww ww ww ww w3 uu uu /. .. .. .. .. .. .. .. .. .. .. cw BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[51] = 'BK BK BK BK BK BK BK BK BK BK BK BK cw ./ uu uu uu uu /. .. .. .. .. .. .| uu uu uu uu uu uu uu cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw ww ww ww w9 cw cw cw .. .. .. .. .. .. .. .. .. cw cw BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[52] = 'BK BK BK BK BK BK BK BK BK BK BK BK cw uu uu uu uu uu |. .. .. .. .. .. .. .` uu uu uu uu uu uu uu cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw cw BK cw cw cw .. .. .. .. cw cw cw cw BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[53] = 'BK BK BK BK BK BK BK BK BK BK BK BK cw uu uu uu uu uu `. .. .. .. .. .. .. .. .` uu uu uu uu uu uu cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[54] = 'BK BK BK BK BK BK BK BK BK BK BK BK cw uu uu uu uu uu uu |. .. .. .. .. .. .. ./ uu uu uu uu uu uu cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[55] = 'BK BK BK BK BK BK BK BK BK BK BK BK cw cw uu uu uu uu uu `. .. .. .. .. .. .| uu uu uu uu uu /. -- cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[56] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK cw .` uu uu uu uu uu |. .. .. .. __ ./ uu uu uu uu uu |. ff cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[57] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw uu uu uu uu uu |. .. .. .| uu uu uu uu uu uu /. .. cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[58] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw .` uu uu uu |. .. __ ./ uu uu uu uu uu uu |. ff cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[59] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw uu uu uu `. ./ uu uu uu uu uu uu uu uu |. cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[60] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw uu uu uu uu uu uu uu uu uu cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[61] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw cw cw cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[62] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["grotto2"].terrain[63] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';

mappages["grotto2"].features = [];
mappages["grotto2"].features[0] = {name : 'GrottoWhirlpool', x : 70, y : 23};
mappages["grotto2"].features[1] = {name : 'OrbDexterity', x : 102, y : 20};
mappages["grotto2"].features[2] = {name : 'WallOfWaves', x : 103, y : 47};
mappages["grotto2"].features[3] = {name : 'PlatformOfWaves', x : 118, y : 46};
mappages["grotto2"].features[4] = {name : 'BridgeNS', x : 102, y : 31};
mappages["grotto2"].features[5] = {name : 'CoralVoid', x : 52, y : 18};
mappages["grotto2"].features[6] = {name : 'CoralVoid', x : 53, y : 19};
mappages["grotto2"].features[7] = {name : 'CoralVoid', x : 75, y : 27};
mappages["grotto2"].features[8] = {name : 'GrottoBridgeLever1', x : 98, y : 30};
mappages["grotto2"].features[9] = {name : 'GrottoBridgeLever2', x : 99, y : 30};
mappages["grotto2"].features[10] = {name : 'GrottoBridgeLever3', x : 100, y : 30};
mappages["grotto2"].features[11] = {name : 'PileOfRocks', x : 23, y : 54};
mappages["grotto2"].features[12] = {name : 'PileOfRocks', x : 26, y : 39};
mappages["grotto2"].features[13] = {name : 'PileOfRocks', x : 29, y : 39};
mappages["grotto2"].features[14] = {name : 'PileOfRocks', x : 73, y : 29};
mappages["grotto2"].features[15] = {name : 'Chest', x : 57, y : 15, lootgroup : 'grotto'};
mappages["grotto2"].features[16] = {name : 'Chest', x : 57, y : 16, lootgroup : 'grotto'};
mappages["grotto2"].features[17] = {name : 'Chest', x : 50, y : 39, lootgroup : 'grotto'};
mappages["grotto2"].features[18] = {name : 'Chest', x : 81, y : 27, lootgroup : 'grotto'};
mappages["grotto2"].features[19] = {name : 'Chest', x : 78, y : 17, lootgroup : 'grotto'};
mappages["grotto2"].features[20] = {name : 'Coral', x : 46, y : 8};
mappages["grotto2"].features[21] = {name : 'Coral', x : 48, y : 7};
mappages["grotto2"].features[22] = {name : 'Coral', x : 48, y : 8};
mappages["grotto2"].features[23] = {name : 'Coral', x : 41, y : 12};
mappages["grotto2"].features[24] = {name : 'Coral', x : 42, y : 12};
mappages["grotto2"].features[25] = {name : 'Coral', x : 41, y : 13};
mappages["grotto2"].features[26] = {name : 'Coral', x : 42, y : 21};
mappages["grotto2"].features[27] = {name : 'Coral', x : 42, y : 22};
mappages["grotto2"].features[28] = {name : 'Coral', x : 44, y : 21};
mappages["grotto2"].features[29] = {name : 'Coral', x : 38, y : 25};
mappages["grotto2"].features[30] = {name : 'Coral', x : 39, y : 26};
mappages["grotto2"].features[31] = {name : 'Coral', x : 40, y : 28};
mappages["grotto2"].features[32] = {name : 'Coral', x : 41, y : 29};
mappages["grotto2"].features[33] = {name : 'Coral', x : 55, y : 23};
mappages["grotto2"].features[34] = {name : 'Coral', x : 55, y : 24};
mappages["grotto2"].features[35] = {name : 'Coral', x : 56, y : 24};
mappages["grotto2"].features[36] = {name : 'Coral', x : 53, y : 35};
mappages["grotto2"].features[37] = {name : 'Coral', x : 52, y : 35};
mappages["grotto2"].features[38] = {name : 'Coral', x : 53, y : 36};
mappages["grotto2"].features[39] = {name : 'Coral', x : 53, y : 34};
mappages["grotto2"].features[40] = {name : 'Coral', x : 55, y : 40};
mappages["grotto2"].features[41] = {name : 'Coral', x : 56, y : 40};
mappages["grotto2"].features[42] = {name : 'Coral', x : 66, y : 36};
mappages["grotto2"].features[43] = {name : 'Coral', x : 67, y : 36};
mappages["grotto2"].features[44] = {name : 'Coral', x : 65, y : 32};
mappages["grotto2"].features[45] = {name : 'Coral', x : 66, y : 32};
mappages["grotto2"].features[46] = {name : 'Coral', x : 68, y : 32};
mappages["grotto2"].features[47] = {name : 'Coral', x : 68, y : 31};
mappages["grotto2"].features[48] = {name : 'Coral', x : 67, y : 25};
mappages["grotto2"].features[49] = {name : 'Coral', x : 68, y : 26};
mappages["grotto2"].features[50] = {name : 'Coral', x : 76, y : 35};
mappages["grotto2"].features[51] = {name : 'Coral', x : 76, y : 36};
mappages["grotto2"].features[52] = {name : 'Coral', x : 67, y : 11};
mappages["grotto2"].features[53] = {name : 'Coral', x : 68, y : 11};
mappages["grotto2"].features[54] = {name : 'Coral', x : 75, y : 20};
mappages["grotto2"].features[55] = {name : 'Coral', x : 76, y : 21};
mappages["grotto2"].features[56] = {name : 'Coral', x : 77, y : 21};
mappages["grotto2"].features[57] = {name : 'Coral', x : 88, y : 18};
mappages["grotto2"].features[58] = {name : 'Coral', x : 89, y : 18};
mappages["grotto2"].features[59] = {name : 'Coral', x : 93, y : 23};
mappages["grotto2"].features[60] = {name : 'Coral', x : 103, y : 13};
mappages["grotto2"].features[61] = {name : 'Coral', x : 104, y : 13};
mappages["grotto2"].features[62] = {name : 'Coral', x : 105, y : 14};
mappages["grotto2"].features[63] = {name : 'Coral', x : 110, y : 16};
mappages["grotto2"].features[64] = {name : 'Coral', x : 105, y : 19};
mappages["grotto2"].features[65] = {name : 'Brazier', x : 98, y : 31};
mappages["grotto2"].features[66] = {name : 'Coral', x : 32, y : 14};
mappages["grotto2"].features[67] = {name : 'Coral', x : 32, y : 13};
mappages["grotto2"].features[68] = {name : 'Coral', x : 47, y : 26};
mappages["grotto2"].features[69] = {name : 'Coral', x : 48, y : 26};
mappages["grotto2"].features[70] = {name : 'Coral', x : 47, y : 25};
mappages["grotto2"].features[71] = {name : 'Coral', x : 58, y : 32};
mappages["grotto2"].features[72] = {name : 'Coral', x : 59, y : 32};
mappages["grotto2"].features[73] = {name : 'Coral', x : 62, y : 38};
mappages["grotto2"].features[74] = {name : 'Coral', x : 63, y : 37};
mappages["grotto2"].features[75] = {name : 'Coral', x : 78, y : 30};
mappages["grotto2"].features[76] = {name : 'Coral', x : 77, y : 30};
mappages["grotto2"].features[77] = {name : 'Coral', x : 68, y : 15};
mappages["grotto2"].features[78] = {name : 'Coral', x : 69, y : 15};
mappages["grotto2"].features[79] = {name : 'Coral', x : 69, y : 14};
mappages["grotto2"].features[80] = {name : 'Coral', x : 80, y : 17};
mappages["grotto2"].features[81] = {name : 'Coral', x : 80, y : 18};
mappages["grotto2"].features[82] = {name : 'Coral', x : 84, y : 25};
mappages["grotto2"].features[83] = {name : 'Coral', x : 85, y : 25};
mappages["grotto2"].features[84] = {name : 'Coral', x : 85, y : 24};
mappages["grotto2"].features[85] = {name : 'Coral', x : 97, y : 14};
mappages["grotto2"].features[86] = {name : 'Coral', x : 96, y : 14};
mappages["grotto2"].features[87] = {name : 'Coral', x : 96, y : 13};
mappages["grotto2"].features[88] = {name : 'Coral', x : 102, y : 26};
mappages["grotto2"].features[89] = {name : 'Coral', x : 107, y : 42};
mappages["grotto2"].features[90] = {name : 'Coral', x : 108, y : 43};
mappages["grotto2"].features[91] = {name : 'Coral', x : 109, y : 44};
mappages["grotto2"].features[92] = {name : 'Coral', x : 100, y : 43};
mappages["grotto2"].features[93] = {name : 'Coral', x : 100, y : 44};
mappages["grotto2"].features[94] = {name : 'Coral', x : 99, y : 45};
mappages["grotto2"].features[95] = {name : 'Coral', x : 104, y : 50};
mappages["grotto2"].features[96] = {name : 'Coral', x : 104, y : 51};
mappages["grotto2"].features[97] = {name : 'Coral', x : 105, y : 51};
mappages["grotto2"].features[98] = {name : 'Coral', x : 103, y : 51};
mappages["grotto2"].features[99] = {name : 'Brazier', x : 101, y : 35};
mappages["grotto2"].features[100] = {name : 'Brazier', x : 103, y : 35};
mappages["grotto2"].features[101] = {name : 'Coral', x : 104, y : 28};
mappages["grotto2"].features[102] = {name : 'Coral', x : 105, y : 28};
mappages["grotto2"].features[103] = {name : 'Coral', x : 101, y : 24};
mappages["grotto2"].features[104] = {name : 'Coral', x : 102, y : 24};
mappages["grotto2"].features[105] = {name : 'Coral', x : 103, y : 24};


mappages["grotto2"].npcs = [];
mappages["grotto2"].npcs[0] = {name : 'NixNPC', x : 43, y : 9, Gender: 'monster', NPCBand: '2', skintone: 1};
mappages["grotto2"].npcs[1] = {name : 'NixNPC', x : 44, y : 7, Gender: 'monster', NPCBand: '2', skintone: 1};
mappages["grotto2"].npcs[2] = {name : 'NixNPC', x : 47, y : 9, Gender: 'monster', NPCBand: '2', skintone: 1};
mappages["grotto2"].npcs[3] = {name : 'NixNPC', x : 49, y : 9, Gender: 'monster', NPCBand: '2', skintone: 1};
mappages["grotto2"].npcs[4] = {name : 'NixNPC', x : 47, y : 6, Gender: 'monster', NPCBand: '2', skintone: 1};
mappages["grotto2"].npcs[5] = {name : 'NixNPC', x : 40, y : 25, Gender: 'monster', NPCBand: '1', skintone: 1};
mappages["grotto2"].npcs[6] = {name : 'NixNPC', x : 42, y : 27, Gender: 'monster', NPCBand: '1', skintone: 1};
mappages["grotto2"].npcs[7] = {name : 'NixNPC', x : 73, y : 21, Gender: 'monster', NPCBand: '4', skintone: 1};
mappages["grotto2"].npcs[8] = {name : 'NixNPC', x : 79, y : 24, Gender: 'monster', NPCBand: '4', skintone: 1};
mappages["grotto2"].npcs[9] = {name : 'NixNPC', x : 79, y : 20, Gender: 'monster', NPCBand: '4', skintone: 1};
mappages["grotto2"].npcs[10] = {name : 'DeepNixNPC', x : 37, y : 27, Gender: 'monster', NPCBand: '1', skintone: 1};
mappages["grotto2"].npcs[11] = {name : 'DeepNixNPC', x : 39, y : 29, Gender: 'monster', NPCBand: '1', skintone: 1};
mappages["grotto2"].npcs[12] = {name : 'DeepNixNPC', x : 55, y : 33, skintone: 1};
mappages["grotto2"].npcs[13] = {name : 'DeepNixNPC', x : 77, y : 34, Gender: 'monster', NPCBand: '5', skintone: 1};
mappages["grotto2"].npcs[14] = {name : 'DeepNixNPC', x : 79, y : 35, Gender: 'monster', NPCBand: '5', skintone: 1};
mappages["grotto2"].npcs[15] = {name : 'DeepNixNPC', x : 77, y : 37, Gender: 'monster', NPCBand: '5', skintone: 1};
mappages["grotto2"].npcs[16] = {name : 'DeepNixNPC', x : 96, y : 23, skintone: 1};
mappages["grotto2"].npcs[17] = {name : 'DeepNixNPC', x : 94, y : 16, skintone: 1};
mappages["grotto2"].npcs[18] = {name : 'SeaSerpentNPC', x : 91, y : 18, skintone: 1};
mappages["grotto2"].npcs[19] = {name : 'SeaSerpentNPC', x : 67, y : 14, Gender: 'monster', NPCBand: '3', skintone: 1};
mappages["grotto2"].npcs[20] = {name : 'SeaSerpentNPC', x : 68, y : 12, Gender: 'monster', NPCBand: '3', skintone: 1};
mappages["grotto2"].npcs[21] = {name : 'SeaSerpentNPC', x : 70, y : 12, Gender: 'monster', NPCBand: '3', skintone: 1};
mappages["grotto2"].npcs[22] = {name : 'KrakenNPC', x : 90, y : 24, skintone: 1};
mappages["grotto2"].npcs[23] = {name : 'KrakenNPC', x : 66, y : 34, skintone: 1};
mappages["grotto2"].npcs[24] = {name : 'WaterElementalNPC', x : 101, y : 45, Gender: 'monster', NPCBand: '6', skintone: 1};
mappages["grotto2"].npcs[25] = {name : 'WaterElementalNPC', x : 105, y : 45, Gender: 'monster', NPCBand: '6', skintone: 1};
mappages["grotto2"].npcs[26] = {name : 'SeaSerpentNPC', x : 108, y : 25, skintone: 1};
mappages["grotto2"].npcs[27] = {name : 'SeaSerpentNPC', x : 110, y : 24, skintone: 1};

mappages["grotto2"].transover = '{"6,37":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-224,-640]],"5,38":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-96,-640]],"5,39":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-224,-640]],"31,58":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-128,-640]],"32,56":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-128,-640]]}';

mappages["grotto2"].desc = "Underwater Grotto";
mappages["grotto2"].longdesc = ``;
mappages["grotto2"].music = 'Cave';
mappages["grotto2"].savename = `Grotto`;
mappages["grotto2"].exitmap = 'ellusus';
mappages["grotto2"].exitx = '27';
mappages["grotto2"].exity = '30';
mappages["grotto2"].wraps = '';
mappages["grotto2"].enterx = '22';
mappages["grotto2"].entery = '53';
mappages["grotto2"].seeBelow = '';
mappages["grotto2"].lightLevel = 'dark';
mappages["grotto2"].alwaysRemember = '0';
mappages["grotto2"].scale = '1';
mappages["grotto2"].underground = '1';
mappages["grotto2"].undergroundDesc = 'Underwater Grotto';
mappages["grotto2"].enterscript = '';
mappages["grotto2"].entertestscript = '';
mappages["grotto2"].exitscript = '';
mappages["grotto2"].exittestscript = '';
mappages["grotto2"].returnmap = 'ellusus';
mappages["grotto2"].returnx = '27';
mappages["grotto2"].returny = '30';
mappages["grotto2"].returninfused = '0';
mappages["grotto2"].linkedMaps = ["grotto","undergrotto"];
mappages["grotto2"].editorLabels = '{}';
// MAP ENDS HERE

mappages["grotto2"].onload = function(mapref) {
  if ((gamestate.getMode() !== "loadgame") && (!DU.gameflags.getFlag("editor"))) {
    let spawn = localFactory.createTile("Spawner");
    let spawngroup = ["NixNPC","DeepNixNPC"];

    spawn.setSpawngroup(spawngroup);
    spawn.setMaxSpawns(5);
    spawn.setSpawnRadius(8);

    let freq = 70 + Dice.roll("1d20");
    spawn.setSpawnFreq(freq);
  
    mapref.placeThing(55,31,spawn);

    spawn = localFactory.createTile("Spawner");
    spawngroup = ["FlukeNPC"];

    spawn.setSpawngroup(spawngroup);
    spawn.setMaxSpawns(1);
    spawn.setSpawnRadius(3);

    freq = 70 + Dice.roll("1d20");
    spawn.setSpawnFreq(freq);
  
    mapref.placeThing(41,19,spawn);


    spawn = localFactory.createTile("Spawner");
    spawngroup = ["DeepNixNPC","SeaSerpentNPC"];

    spawn.setSpawngroup(spawngroup);
    spawn.setMaxSpawns(4);
    spawn.setSpawnRadius(6);

    freq = 70 + Dice.roll("1d20");
    spawn.setSpawnFreq(freq);
  
    mapref.placeThing(75,23,spawn);

    let monster = mapref.getTile(91,18).getTopNPC();
    spawn.addSpawned(monster);
    monster.setSpawnedBy(spawn);

    monster = mapref.getTile(107,25).getTopNPC();
    spawn.addSpawned(monster);
    monster.setSpawnedBy(spawn);

    monster = mapref.getTile(96,23).getTopNPC();
    spawn.addSpawned(monster);
    monster.setSpawnedBy(spawn);

    monster = mapref.getTile(94,16).getTopNPC();
    spawn.addSpawned(monster);
    monster.setSpawnedBy(spawn);

    spawn = localFactory.createTile("Spawner");
    spawngroup = ["DeepNixNPC","KrakenNPC","SeaSerpentNPC"];

    spawn.setSpawngroup(spawngroup);
    spawn.setMaxSpawns(2);
    spawn.setSpawnRadius(6);

    freq = 70 + Dice.roll("1d20");
    spawn.setSpawnFreq(freq);
  
    mapref.placeThing(96,19,spawn);

    monster = mapref.getTile(90,24).getTopNPC();
    spawn.addSpawned(monster);
    monster.setSpawnedBy(spawn);

    monster = mapref.getTile(66,34).getTopNPC();
    spawn.addSpawned(monster);
    monster.setSpawnedBy(spawn);

    let tele = mapref.getTile(118,46).getTopFeature();
    tele.setDestination({map: "ellusus", x: 27, y: 30}) ;
  }
}

// MAP BEGINS HERE
mappages["undergrotto"] = {};
mappages["undergrotto"].terrain = [];
 mappages["undergrotto"].terrain[0] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["undergrotto"].terrain[1] = 'BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["undergrotto"].terrain[2] = 'BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["undergrotto"].terrain[3] = 'BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["undergrotto"].terrain[4] = 'BK cw cw cw cw cw BK BK BK cw cw cf cf cf cw cw cf cf cw cw BK BK cw cw cw cw cw cw BK BK BK BK';
 mappages["undergrotto"].terrain[5] = 'cw cw cf cf cf cw BK BK cw cw cf cf cf cw cw cw cw cf cf cw BK cw cw ww ww ww ww cw cw BK BK BK';
 mappages["undergrotto"].terrain[6] = 'cw cf cf cf cf cw BK BK cw cf cf cf cw cw BK BK cw cf cf cw cw cw ww ww ww ww ww ww cw cw BK BK';
 mappages["undergrotto"].terrain[7] = 'cw cf cf cf cf cw BK cw cw cf cf cw cw BK BK BK cw cf cf cf cw cw ww ww ww ww ww ww ww cw BK BK';
 mappages["undergrotto"].terrain[8] = 'cw cw cw cf cf cw cw cw cf cf cf cw BK BK BK BK cw cw cf cf cw cw ww ww ww ww ww ww ww cw BK BK';
 mappages["undergrotto"].terrain[9] = 'BK BK cw cf cf cw cw cf cf cf cw cw BK BK BK BK BK cw cw cf cw cw cw ww ww ww ww ww cw cw BK BK';
mappages["undergrotto"].terrain[10] = 'BK BK cw cf cf cw cf cf cf cw cw BK BK BK BK BK BK BK cw cf cf cw cw cw -c -c -c cw cw BK BK BK';
mappages["undergrotto"].terrain[11] = 'BK BK cw cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK cw cf cf cf cw cw cw cf cf cw BK BK BK BK';
mappages["undergrotto"].terrain[12] = 'BK BK cw cw cf cf cf cf cw BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cw cw BK BK BK BK';
mappages["undergrotto"].terrain[13] = 'BK BK BK cw cw cw cw cw cw BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw cw cw cw BK BK BK BK BK';
mappages["undergrotto"].terrain[14] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["undergrotto"].terrain[15] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';

mappages["undergrotto"].features = [];
mappages["undergrotto"].features[0] = {name : 'LadderUp', x : 2, y : 6, entermap : 'grotto2', enterx : 73, entery : 28};


mappages["undergrotto"].npcs = [];

mappages["undergrotto"].desc = "Underwater Grotto";
mappages["undergrotto"].longdesc = ``;
mappages["undergrotto"].music = 'Cave';
mappages["undergrotto"].savename = `Grotto`;
mappages["undergrotto"].exitmap = 'ellusus';
mappages["undergrotto"].exitx = '27';
mappages["undergrotto"].exity = '30';
mappages["undergrotto"].wraps = 'None';
mappages["undergrotto"].enterx = '25';
mappages["undergrotto"].entery = '7';
mappages["undergrotto"].seeBelow = '';
mappages["undergrotto"].lightLevel = 'dark';
mappages["undergrotto"].alwaysRemember = '0';
mappages["undergrotto"].scale = '1';
mappages["undergrotto"].underground = '0';
mappages["undergrotto"].undergroundDesc = '';
mappages["undergrotto"].enterscript = '';
mappages["undergrotto"].entertestscript = '';
mappages["undergrotto"].exitscript = '';
mappages["undergrotto"].exittestscript = '';
mappages["undergrotto"].returnmap = 'ellusus';
mappages["undergrotto"].returnx = '27';
mappages["undergrotto"].returny = '30';
mappages["undergrotto"].returninfused = '0';
mappages["undergrotto"].linkedMaps = ["grotto","grotto2"];
mappages["undergrotto"].editorLabels = '{}';
// MAP ENDS HERE
