"use strict";

mappages["hildendain"] = {};
mappages["hildendain"].terrain = [];
 mappages["hildendain"].terrain[0] = '.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..';
 mappages["hildendain"].terrain[1] = '.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..';
 mappages["hildendain"].terrain[2] = '.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..';
 mappages["hildendain"].terrain[3] = '.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..';
 mappages["hildendain"].terrain[4] = '.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..';
 mappages["hildendain"].terrain[5] = '.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..';
 mappages["hildendain"].terrain[6] = '.. .. .. .. .. .. .. .. .. .. .. .. !# !# !# !# !# !# !# !# !# !# !# !# !# !# !# !# !# !# !# !# !# !# !# !# !# !# !# !# !# !# !# .. .. .. .. .. .. ..';
 mappages["hildendain"].terrain[7] = '.. .. .. .. .. .. .. .. .. .. .. .. !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# .. .. .. .. .. .. ..';
 mappages["hildendain"].terrain[8] = '.. .. .. .. .. .. .. .. .. .. .. .. !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# .. .. .. .. .. .. ..';
 mappages["hildendain"].terrain[9] = '.. .. .. .. .. .. .. .. .. .. .. .. !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# .. .. .. .. .. .. ..';
mappages["hildendain"].terrain[10] = '.. .. .. .. .. .. .. .. .. .. .. .. !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# .. .. .. .. .. .. ..';
mappages["hildendain"].terrain[11] = '.. .. .. .. .. .. .. .. .. .. .. .. !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ !# .. .. .. .. .. .. ..';
mappages["hildendain"].terrain[12] = '.. .. .. .. .. .. .. .. .. .. .. .. !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# .. .. .. .. .. .. ..';
mappages["hildendain"].terrain[13] = '.. .. .. .. .. .. .. .. .. .. .. .. !# ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# .. .. .. .. .. .. ..';
mappages["hildendain"].terrain[14] = '.. .. .. .. .. .. .. .. .. .. .. .. !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# .. .. .. .. .. .. ..';
mappages["hildendain"].terrain[15] = '.. .. .. .. .. .. .. .. .. .. .. .. !# !# !# !# !# !# !# !# !# !# !# !# !# =~ ~~ ~_ ++ _~ ~= !# !# !# !# !# =~ ~_ ++ ++ _~ ~= !# .. .. .. .. .. .. ..';
mappages["hildendain"].terrain[16] = '.. .. .. .. .. .. .. .. .. .. .. .. !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# .. .. .. .. .. .. ..';
mappages["hildendain"].terrain[17] = '.. .. .. .. .. .. .. .. .. .. .. .. !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# .. .. .. .. .. .. ..';
mappages["hildendain"].terrain[18] = '.. .. .. .. .. .. .. .. .. .. .. .. !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# .. .. .. .. .. .. ..';
mappages["hildendain"].terrain[19] = '.. .. .. .. .. .. .. .. .. .. .. .. !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# .. .. .. .. .. .. ..';
mappages["hildendain"].terrain[20] = '.. ,; .. ,; .. .. .. .. .. .. .. ,; !# ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ !# ,; .. .. ,; .. .. ,;';
mappages["hildendain"].terrain[21] = '.. .. .. .. .. .. .. .. ,; .. .. ,; !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# ++ ++ ++ ++ ++ ++ ++ ++ ++ !# ,; .. ,; ,; .. ,; ..';
mappages["hildendain"].terrain[22] = '.. ,; ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ++ ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ++ ## ## ## ## ## ## ## ## ## ## ## ## .. ,;';
mappages["hildendain"].terrain[23] = '.. .. ## .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ## ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. ,;';
mappages["hildendain"].terrain[24] = '.. .. ## .. .. .. .. .. .. .. .. .. .. ,; .. .. .. ,; _, _, __ ,, .. .. ## ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ,; ..';
mappages["hildendain"].terrain[25] = '.. .. ## .. .. .. .. .. ,, .. .. .. .. .. .. ,; ,, ./ uu uu uu `. .. .. ## ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ,; ,;';
mappages["hildendain"].terrain[26] = ',; .. ## .. .. .. .. .. ,, .. ,; .. .. .. .. .. .| uu ww uu ww uu |. .. ## ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. ,;';
mappages["hildendain"].terrain[27] = '.. ,; ## .. .. .. .. .. .. .. .. .. .. ,; .. .. .. .` uu uu uu /. .. .. ## ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ,; ..';
mappages["hildendain"].terrain[28] = '.. ,; ## .. .. .. .. .. .. .. ,, .. .. .. .. .. .. ,; -- -- -- .. .. .. ## ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ,; ..';
mappages["hildendain"].terrain[29] = '.. .. ## .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ## ## ## ++ ## ## ## ## ## ## ## ## ## ## ## ## ## ## ++ ## ## ## ## ## ,; ..';
mappages["hildendain"].terrain[30] = '.. ,; ## ## ++ ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## .. ,, .. .. .. .. ++ .. .. .. .. .. ,; ,; ,, .. .. .. .. .. .. .. .. .. ,; .. ## .. ,;';
mappages["hildendain"].terrain[31] = '.. .. ## ++ ++ [: ++ ++ ++ :] ## ++ ++ ## ++ ++ ++ ++ ++ ++ ## .. .. .. .. .. ,, ++ .. .. .. .. .. .. .. ,; .. ,, ,; .. ,; ,; .. ,; .. .. ,, ## ,; ,;';
mappages["hildendain"].terrain[32] = ',; .. ## ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ## ++ ++ ++ ++ ++ ++ ## .. ,; ,; .. ,, ++ ++ .. .. ,; .. .. .. .. .. .. .. ,, ,; .. ,, .. .. ,; .. ,; ## ,; ,;';
mappages["hildendain"].terrain[33] = '.. ,; ## ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ## ++ ++ ++ ++ ++ ++ ## .. ,; .. .. ,, ++ ++ .. ,; ,; .. ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ,; ,;';
mappages["hildendain"].terrain[34] = ',; ,; ## ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ## ++ ++ ++ ++ ++ ++ ## .. .. .. .. .. ++ ++ .. .. .. .. ## ++ ++ ++ ++ ++ +* +* +* +* ++ ++ ++ ++ ++ ## ,; ..';
mappages["hildendain"].terrain[35] = ',; .. ## ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ## ++ ++ ++ ++ ++ ++ ## .. .. .. .. .. ++ ++ ,, .. .. .. ## ++ ++ ++ ++ ++ +* +* +* +* ++ ++ ++ ++ ++ ## ,; ,;';
mappages["hildendain"].terrain[36] = '.. .. ## ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ## ++ ++ ++ ++ ++ ++ ## ,; .. .. .. .. ++ ++ ,, .. .. .. ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ,; ..';
mappages["hildendain"].terrain[37] = '.. .. ## ++ ++ ++ ++ ++ ++ ++ ## ## ## ## ## ## ## ## ## ++ ## ,; .. ,, .. .. ++ ++ .. .. ,; .. ## ++ ++ ++ ++ ++ +* +* +* +* ## ++ ++ ++ ++ ## ,; ,;';
mappages["hildendain"].terrain[38] = '.. ,; ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .. .. .. ++ ++ ++ .. .. .. ## ++ ++ ++ ++ ++ +* +* +* +* ## ++ ++ ++ ++ ## .. ,;';
mappages["hildendain"].terrain[39] = '.. .. ## ## ## ## ## ## ## ## ## ## ## ## ++ ## ## ## ## ## ## .. .. .. .. ,, ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ## .. ,;';
mappages["hildendain"].terrain[40] = ',; ,; ## .. .. .. .. .. #% ,, .. .. .. .. ++ .. .. .. ,, ,, .. .. .. .. .. ++ ++ ++ ++ .. .. .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ,; ,;';
mappages["hildendain"].terrain[41] = '.. ,; ## .. ,; .. .. .. .. .. .. .. .. ++ ++ ++ .. .. .. .. .. .. .. ,, ++ ++ ++ ,, .. .. ,; .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ## ,; ,;';
mappages["hildendain"].terrain[42] = '.. .. ## .. .. .. .. ,, .. .. .. .. ,, ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ .. .. .. .. ,; .. ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## .. ,;';
mappages["hildendain"].terrain[43] = '.. .. ## .. .. ,; .. ,, .. .. ,; .. .. ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ .. ,; .. .. .. .. .. .. .. .. ,; .. .. .. .. ,, .. ,; .. ,, .. ## ,; ,;';
mappages["hildendain"].terrain[44] = '.. ,; ## .. .. .. .. .. .. ,; .. .. .. .. .. .. .. .. .. .. .. .. ,, .. ++ ++ .. .. .. .. .. .. .. ,, .. ,; ,; .. .. .. .. .. .. .. .. .. .. ## ,; ,;';
mappages["hildendain"].terrain[45] = ',; .. ## .. .. .. ,; .. .. .. .. .. .. .. ,, .. .. .. .. .. .. .. .. ,, ++ ++ .. .. .. ,, .. .. .. .. .. .. .. .. .. ,; .. .. ,, ,, .. .. .. ## ,; ,;';
mappages["hildendain"].terrain[46] = '.. .. ## ,; .. .. .. .. ## ## ## ## #O ## ## ## ## .. .. .. ,, .. .. .. ++ ++ .. .. .. .. ,, .. ,; ## ## ## ## #O ## ## ## ## .. .. .. ,; ,, ## .. ,;';
mappages["hildendain"].terrain[47] = '.. ,; ## ## ## #O ## ## ## ++ ++ ++ ++ ++ ++ ++ ## ## #O ## ## ## .. .. ++ ++ .. .. ## ## ## #O ## ## ## ++ ++ ++ ++ ++ ++ ## ## ## #O ## ## ## ,; ,;';
mappages["hildendain"].terrain[48] = '.. .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. ++ ++ .. .. ## ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ## .. ..';
mappages["hildendain"].terrain[49] = ',; ,; ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. ++ ++ ++ ++ .. ## ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ,; ..';
mappages["hildendain"].terrain[50] = ',; .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ## ## ## ++ ## ## ## ## ## ## ## ## ## ,; ,;';
mappages["hildendain"].terrain[51] = '.. .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. ++ ++ ++ ++ .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ,; ..';
mappages["hildendain"].terrain[52] = '.. .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. ++ ++ .. .. ## ++ ++ ++ ++ ++ ## ## ## ## ## ## ## ## ## ## ++ ## ## ## .. ,;';
mappages["hildendain"].terrain[53] = ',; .. ## ## ## ## ++ ## ++ ## ## ## ## ## ## ## ## ++ ++ ++ ++ ## .. .. ++ ++ .. .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ## ,; ..';
mappages["hildendain"].terrain[54] = '.. ,; ## ++ ++ ++ ++ ## ++ ++ ++ ++ ## ++ ++ ++ ## ++ ++ ++ ++ #O .. .. ++ ++ .. .. #O ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ## ++ ++ ++ ++ ++ ## ,; ,;';
mappages["hildendain"].terrain[55] = ',; ,; ## ++ ++ ++ ++ ## ++ ++ ++ ++ ## ++ ++ ++ ## ++ ++ ++ ++ ## .. .. ++ ++ .. .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ## ,; ,;';
mappages["hildendain"].terrain[56] = ',; ,; ## ++ ++ ++ ++ ## ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. ++ ++ .. .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ## ++ ++ ++ ++ ++ ## .. ..';
mappages["hildendain"].terrain[57] = '.. .. ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ++ ++ ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ,; ..';
mappages["hildendain"].terrain[58] = '.. ,; ,; .. ,; .. .. ,; ,; ,; .. .. .. ,; ,; .. .. ,; ,; .. .. ,; ,; .. .. .. .. .. .. ,; ,; ,; .. .. ,; .. .. ,; ,; .. ,; ,; ,; .. ,; ,; ,; ,; .. ,;';
mappages["hildendain"].terrain[59] = '.. ,; .. .. ,; .. .. .. .. ,; ,; .. ,; .. ,; ,; ,; .. ,; .. ,; ,; .. .. .. .. .. .. .. .. .. .. .. .. ,; ,; .. .. ,; .. .. ,; .. ,; ,; ,; .. .. ,; ..';

mappages["hildendain"].features = [];
mappages["hildendain"].features[0] = {name : 'DoorWindow', x : 21, y : 50, desc : "locked door", locked : 1};
mappages["hildendain"].features[1] = {name : 'DoorWindow', x : 28, y : 50};
mappages["hildendain"].features[2] = {name : 'Well', x : 5, y : 25};
mappages["hildendain"].features[3] = {name : 'DoorWindow', x : 14, y : 39};
mappages["hildendain"].features[4] = {name : 'DoorWindow', x : 32, y : 39};
mappages["hildendain"].features[5] = {name : 'DoorWindow', x : 27, y : 29};
mappages["hildendain"].features[6] = {name : 'EnergyField', x : 38, y : 37};
mappages["hildendain"].features[7] = {name : 'FireField', x : 39, y : 37};
mappages["hildendain"].features[8] = {name : 'PoisonField', x : 40, y : 37};
mappages["hildendain"].features[9] = {name : 'SleepField', x : 41, y : 37};
mappages["hildendain"].features[10] = {name : 'Doorway', x : 24, y : 57};
mappages["hildendain"].features[11] = {name : 'Doorway', x : 25, y : 57};
mappages["hildendain"].features[12] = {name : 'SmallTable', x : 14, y : 36};
mappages["hildendain"].features[13] = {name : 'SmallTable', x : 9, y : 34};
mappages["hildendain"].features[14] = {name : 'TopChair', x : 9, y : 33};
mappages["hildendain"].features[15] = {name : 'Doorway', x : 41, y : 49};
mappages["hildendain"].features[16] = {name : 'DoorWindow', x : 34, y : 51};
mappages["hildendain"].features[17] = {name : 'Door', x : 38, y : 50, desc : "locked door", locked : 1};
mappages["hildendain"].features[18] = {name : 'Campfire', x : 3, y : 25};
mappages["hildendain"].features[19] = {name : 'Door', x : 44, y : 52};
mappages["hildendain"].features[20] = {name : 'Door', x : 41, y : 49};
mappages["hildendain"].features[21] = {name : 'RightTable', x : 19, y : 33};
mappages["hildendain"].features[22] = {name : 'RightTable', x : 6, y : 36};
mappages["hildendain"].features[23] = {name : 'MiddleTable', x : 18, y : 33};
mappages["hildendain"].features[24] = {name : 'MiddleTable', x : 17, y : 33};
mappages["hildendain"].features[25] = {name : 'MiddleTable', x : 5, y : 36};
mappages["hildendain"].features[26] = {name : 'MiddleTable', x : 4, y : 36};
mappages["hildendain"].features[27] = {name : 'LeftTable', x : 16, y : 33};
mappages["hildendain"].features[28] = {name : 'LeftTable', x : 3, y : 36};
mappages["hildendain"].features[29] = {name : 'LeftTable', x : 29, y : 55};
mappages["hildendain"].features[30] = {name : 'MiddleTable', x : 30, y : 55};
mappages["hildendain"].features[31] = {name : 'RightTable', x : 31, y : 55};
mappages["hildendain"].features[32] = {name : 'BedHead', x : 39, y : 47};
mappages["hildendain"].features[33] = {name : 'BedFoot', x : 40, y : 47};
mappages["hildendain"].features[34] = {name : 'BedFoot', x : 43, y : 56};
mappages["hildendain"].features[35] = {name : 'BedHead', x : 42, y : 56};
mappages["hildendain"].features[36] = {name : 'Mirror', x : 35, y : 47};
mappages["hildendain"].features[37] = {name : 'Door', x : 16, y : 56, desc : "locked door", locked : 1};
mappages["hildendain"].features[38] = {name : 'DoorWindow', x : 8, y : 53, desc : "locked door", locked : 1};
mappages["hildendain"].features[39] = {name : 'DoorWindow', x : 6, y : 53, desc : "locked door", locked : 1};
mappages["hildendain"].features[40] = {name : 'Fireplace', x : 40, y : 55};
mappages["hildendain"].features[41] = {name : 'Door', x : 42, y : 40, desc : "locked door", locked : 1};
mappages["hildendain"].features[42] = {name : 'DoorWindow', x : 19, y : 37};
mappages["hildendain"].features[43] = {name : 'DoorWindow', x : 10, y : 38};
mappages["hildendain"].features[44] = {name : 'Door', x : 4, y : 30};
mappages["hildendain"].features[45] = {name : 'ArmorCounterLeather', x : 6, y : 31};
mappages["hildendain"].features[46] = {name : 'ArmorCounterChain', x : 7, y : 31};
mappages["hildendain"].features[47] = {name : 'ArmorCounterPlate', x : 8, y : 31};
mappages["hildendain"].features[48] = {name : 'ArmorRackChain', x : 3, y : 33};
mappages["hildendain"].features[49] = {name : 'SingleSignpost', x : 16, y : 41};
mappages["hildendain"].features[50] = {name : 'SingleSignpost', x : 12, y : 41};
mappages["hildendain"].features[51] = {name : 'MagicShoppeSign', x : 30, y : 38, prefix : "a", desc : "sign: Magic Shoppe"};
mappages["hildendain"].features[52] = {name : 'SignpostLeft', x : 29, y : 38};
mappages["hildendain"].features[53] = {name : 'SignpostRight', x : 31, y : 38};
mappages["hildendain"].features[54] = {name : 'InnSign', x : 27, y : 51, prefix : "a", desc : "sign: Gauntlet Inn"};
mappages["hildendain"].features[55] = {name : 'SingleSignpost', x : 27, y : 52};
mappages["hildendain"].features[56] = {name : 'MiddleTable', x : 19, y : 55};
mappages["hildendain"].features[57] = {name : 'LeftTable', x : 18, y : 55};
mappages["hildendain"].features[58] = {name : 'RightTable', x : 20, y : 55};
mappages["hildendain"].features[59] = {name : 'BottomChair', x : 19, y : 56};
mappages["hildendain"].features[60] = {name : 'LeftTable', x : 10, y : 48};
mappages["hildendain"].features[61] = {name : 'RightTable', x : 14, y : 48};
mappages["hildendain"].features[62] = {name : 'MiddleTable', x : 11, y : 48};
mappages["hildendain"].features[63] = {name : 'MiddleTable', x : 12, y : 48};
mappages["hildendain"].features[64] = {name : 'MiddleTable', x : 13, y : 48};
mappages["hildendain"].features[65] = {name : 'BookshelfLeft', x : 19, y : 48};
mappages["hildendain"].features[66] = {name : 'BookshelfRight', x : 20, y : 48};
mappages["hildendain"].features[67] = {name : 'TopChair', x : 13, y : 47};
mappages["hildendain"].features[68] = {name : 'TopChair', x : 11, y : 47};
mappages["hildendain"].features[69] = {name : 'Brazier', x : 20, y : 52};
mappages["hildendain"].features[70] = {name : 'UnlitBrazier', x : 3, y : 50};
mappages["hildendain"].features[71] = {name : 'BedHead', x : 3, y : 56};
mappages["hildendain"].features[72] = {name : 'BedFoot', x : 4, y : 56};
mappages["hildendain"].features[73] = {name : 'BedFoot', x : 11, y : 56};
mappages["hildendain"].features[74] = {name : 'BedHead', x : 10, y : 56};
mappages["hildendain"].features[75] = {name : 'WeaponSign', x : 16, y : 40, prefix : "a", desc : "sign: Right Side Weapons"};
mappages["hildendain"].features[76] = {name : 'ArmourySign', x : 12, y : 40, prefix : "a", desc : "sign: Left Side Armor"};
mappages["hildendain"].features[77] = {name : 'BookshelfLeft', x : 33, y : 37};
mappages["hildendain"].features[78] = {name : 'BookshelfRight', x : 34, y : 37};
mappages["hildendain"].features[79] = {name : 'BookshelfOne', x : 35, y : 37};
mappages["hildendain"].features[80] = {name : 'Mirror', x : 37, y : 37};
mappages["hildendain"].features[81] = {name : 'UnlitBrazier', x : 36, y : 40};
mappages["hildendain"].features[82] = {name : 'Altar', x : 45, y : 37};
mappages["hildendain"].features[83] = {name : 'EnergyField', x : 46, y : 37};
mappages["hildendain"].features[84] = {name : 'EnergyField', x : 44, y : 37};
mappages["hildendain"].features[85] = {name : 'Anvil', x : 4, y : 26};
mappages["hildendain"].features[86] = {name : 'LeftTable', x : 36, y : 54};
mappages["hildendain"].features[87] = {name : 'RightTable', x : 38, y : 54};
mappages["hildendain"].features[88] = {name : 'MiddleTable', x : 37, y : 54};
mappages["hildendain"].features[89] = {name : 'BottomChair', x : 36, y : 55};
mappages["hildendain"].features[90] = {name : 'BottomChair', x : 38, y : 55};
mappages["hildendain"].features[91] = {name : 'TopChair', x : 37, y : 53};
mappages["hildendain"].features[92] = {name : 'TrainingDummy', x : 29, y : 23};
mappages["hildendain"].features[93] = {name : 'TrainingDummy', x : 31, y : 23};
mappages["hildendain"].features[94] = {name : 'BookshelfOne', x : 25, y : 23};
mappages["hildendain"].features[95] = {name : 'BedHead', x : 30, y : 26};
mappages["hildendain"].features[96] = {name : 'BedHead', x : 30, y : 28};
mappages["hildendain"].features[97] = {name : 'BedFoot', x : 31, y : 26};
mappages["hildendain"].features[98] = {name : 'BedFoot', x : 31, y : 28};
mappages["hildendain"].features[99] = {name : 'SmallBox', x : 32, y : 26, lootgroup : 'smallguard', karmaPenalty : '1', lootedid : 'hilden_guard1'};
mappages["hildendain"].features[100] = {name : 'SmallBox', x : 32, y : 28, lootgroup : 'smallguard', karmaPenalty : '1', lootedid : 'hilden_guard2'};
mappages["hildendain"].features[101] = {name : 'TorchWest', x : 34, y : 24};
mappages["hildendain"].features[102] = {name : 'Fountain', x : 19, y : 26};
mappages["hildendain"].features[103] = {name : 'TorchEast', x : 36, y : 24};
mappages["hildendain"].features[104] = {name : 'DoorWindow', x : 42, y : 29};
mappages["hildendain"].features[105] = {name : 'WallDoorway', x : 35, y : 22};
mappages["hildendain"].features[106] = {name : 'WallPortcullis', x : 19, y : 22, locked : 1};
mappages["hildendain"].features[107] = {name : 'Door', x : 32, y : 20, desc : "locked door", locked : 1};
mappages["hildendain"].features[108] = {name : 'Door', x : 22, y : 20, desc : "locked door", locked : 1};
mappages["hildendain"].features[109] = {name : 'Doorway', x : 32, y : 11};
mappages["hildendain"].features[110] = {name : 'Door', x : 22, y : 13};
mappages["hildendain"].features[111] = {name : 'Fireplace', x : 41, y : 53};
mappages["hildendain"].features[112] = {name : 'Mirror', x : 46, y : 53};
mappages["hildendain"].features[113] = {name : 'SmallTable', x : 46, y : 56};
mappages["hildendain"].features[114] = {name : 'WeaponCounterDagger', x : 14, y : 31};
mappages["hildendain"].features[115] = {name : 'WeaponCounterMace', x : 14, y : 32};
mappages["hildendain"].features[116] = {name : 'WeaponCounterSword', x : 14, y : 33};
mappages["hildendain"].features[117] = {name : 'TopChair', x : 9, y : 33};

mappages["hildendain"].npcs = [];
mappages["hildendain"].npcs[0] = {name : 'MageVillagerNPC', x : 39, y : 38, NPCName: 'Alexis', Conversation: 'alexis', ConversationFlag: 'alexis', Gender: 'female', Merch: 'alexis', Bark: '0', NPCBand: '0', OverrideGraphic: '303.gif'};
mappages["hildendain"].npcs[1] = {name : 'FighterVillagerNPC', x : 4, y : 27, NPCName: 'Dave', Conversation: 'dave', ConversationFlag: 'dave', Gender: 'male', Bark: '0', NPCBand: '0', OverrideGraphic: '308.gif'};
mappages["hildendain"].npcs[2] = {name : 'PaladinVillagerNPC', x : 10, y : 44, NPCName: 'Sarah', Conversation: 'sarah', ConversationFlag: 'sarah', Gender: 'female', Leash: 2, Bark: '0', NPCBand: '0', OverrideGraphic: 'paladin-offcolor.gif'};
mappages["hildendain"].npcs[3] = {name : 'TownsfolkVillagerNPC', x : 34, y : 31, NPCName: 'Anna', Conversation: 'anna', ConversationFlag: 'anna', Gender: 'female', Bark: '0', NPCBand: '0', OverrideGraphic: '310.2.gif'};
mappages["hildendain"].npcs[4] = {name : 'RangerVillagerNPC', x : 27, y : 24, NPCName: 'Garrick', Conversation: 'garrick', ConversationFlag: 'garrick', Gender: 'male', Leash: 2, Bark: '0', NPCBand: '0', OverrideGraphic: 'ranger-offcolor.gif'};
mappages["hildendain"].npcs[5] = {name : 'TownsfolkVillagerNPC', x : 30, y : 56, NPCName: 'Rhiannon', Desc: 'innkeeper', Conversation: 'rhiannon', ConversationFlag: 'rhiannon', Gender: 'female', Bark: '0', NPCBand: '0', OverrideGraphic: '310.gif'};
mappages["hildendain"].npcs[6] = {name : 'TownsfolkVillagerNPC', x : 18, y : 32, NPCName: 'Aaron', Desc: 'merchant', Conversation: 'aaron', ConversationFlag: 'aaron', Gender: 'male', Merch: 'aaron', Bark: '0', NPCBand: '0', OverrideGraphic: '310.gif'};
mappages["hildendain"].npcs[7] = {name : 'AdventurerVillagerNPC', x : 5, y : 37, NPCName: 'Erin', Desc: 'merchant', Prefix: 'a', Conversation: 'erin', ConversationFlag: 'erin', Gender: 'female', Merch: 'erin', Bark: '0', NPCBand: '0', OverrideGraphic: '306.gif'};
mappages["hildendain"].npcs[8] = {name : 'TinkerVillagerNPC', x : 23, y : 39, NPCName: 'Kiba', Conversation: 'kiba', ConversationFlag: 'kiba', Gender: 'female', Leash: 3, Bark: '0', NPCBand: '0', OverrideGraphic: 'tinker-offcolor.gif'};
mappages["hildendain"].npcs[9] = {name : 'TownGuardNPC', x : 25, y : 25, NPCName: 'Aoife', Conversation: 'aoife', ConversationFlag: 'aoife', Gender: 'female', Leash: 2, Bark: '0', NPCBand: '0'};
mappages["hildendain"].npcs[10] = {name : 'TownGuardNPC', x : 27, y : 46, NPCName: 'Guard', Conversation: 'hildendain_guard', Gender: 'male', Leash: 3, Bark: '0', NPCBand: '0'};
mappages["hildendain"].npcs[11] = {name : 'TownGuardNPC', x : 11, y : 50, NPCName: 'Guard', Conversation: 'hildendain_prison', Gender: 'male', Bark: '0', NPCBand: '0'};
mappages["hildendain"].npcs[12] = {name : 'BardVillagerNPC', x : 39, y : 53, NPCName: 'Franklin', Conversation: 'franklin', ConversationFlag: 'franklin', Gender: 'male', Bark: '0', NPCBand: '0', OverrideGraphic: '311.gif'};

mappages["hildendain"].desc = "The Towne of Hildendain";
mappages["hildendain"].music = 'Towne';
mappages["hildendain"].savename = 'Hildendain';
mappages["hildendain"].exitmap = 'darkunknown';
mappages["hildendain"].exitx = '52';
mappages["hildendain"].exity = '63';
mappages["hildendain"].wraps = 'None';
mappages["hildendain"].enterx = '25';
mappages["hildendain"].entery = '58';
mappages["hildendain"].seeBelow = '';
mappages["hildendain"].lightLevel = 'bright';
mappages["hildendain"].alwaysRemember = '0';
mappages["hildendain"].scale = '1';
mappages["hildendain"].underground = '0';
mappages["hildendain"].enterscript = '';
mappages["hildendain"].entertestscript = '';
mappages["hildendain"].exitscript = 'check_anne';
mappages["hildendain"].exittestscript = '';
mappages["hildendain"].returnmap = 'darkunknown';
mappages["hildendain"].returnx = '69';
mappages["hildendain"].returny = '74';
mappages["hildendain"].returninfused = '0';
mappages["hildendain"].linkedMaps = [""];

mappages["hildendain"].onload = function(mapref) {
  if (DU.gameflags.anna_return) {
    var tile = mapref.getTile(34,11);
    var anna = tile.getTopNPC();
    if (anna) {
      mapref.deleteThing(anna);
      DUTime.removeEntityFrom(anna);
    }
  }
  
  if (DU.gameflags.garrick_flipout) {
    var tile = mapref.getTile(27,4);
    var garrick = tile.getTopNPC();
    if (garrick) {
      mapref.moveThing(9,35,garrick);
      garrick.startx = 9;
      garrick.starty = 35;
    } 
  }
  
}

mappages["hildendain"].check_anne = function(mapref) {
  mapref.Exit = function(who,tomap,fromx,fromy,tox,toy) {
    if ((who === PC) && DU.gameflags.anna_return) { DU.gameflags.anna_left = 1; }
  }
}