mappages["hotelcalifornia"] = {};
mappages["hotelcalifornia"].terrain = [];
 mappages["hotelcalifornia"].terrain[0] = '.. .. .. .. .. .. .. .. .. .. .. .. .. u, .. .. .. .. .. ..';
 mappages["hotelcalifornia"].terrain[1] = '.. .. .. .. .. .. .. u, .. .. .. .. .. .. .. .. .. .. .. ..';
 mappages["hotelcalifornia"].terrain[2] = '.. .. .. !# !# !# !# !# !# !# !# !# !# !# !# !# !# .. .. ..';
 mappages["hotelcalifornia"].terrain[3] = '.. .. .. !# -= -= -= -= -= -= -= -= -= -= -= -= !# .. .. ..';
 mappages["hotelcalifornia"].terrain[4] = '.. .. u, !# -= -= -= -= -= -= -= -= -= -= -= -= !# .. u, ..';
 mappages["hotelcalifornia"].terrain[5] = '.. .. .. !# -= -= -= -= -= -= -= -= -= -= -= -= !# .. .. ..';
 mappages["hotelcalifornia"].terrain[6] = '.. .. .. !# -= -= -= -= -= -= -= -= -= -= -= -= !# .. .. ..';
 mappages["hotelcalifornia"].terrain[7] = '.. .. .. !# -= -= -= -= -= -= -= -= -= -= -= -= !# .. .. ..';
 mappages["hotelcalifornia"].terrain[8] = '.. .. .. !# -= -= -= -= -= -= -= -= -= -= -= -= !# .. .. ..';
 mappages["hotelcalifornia"].terrain[9] = '.. .. .. !# -= -= -= -= -= -= -= -= -= -= -= -= !# .. .. ..';
mappages["hotelcalifornia"].terrain[10] = '.. .. .. !# -= -= -= -= -= -= -= -= -= -= -= -= !# .. .. u,';
mappages["hotelcalifornia"].terrain[11] = '.. .. .. !# -= -= -= -= -= -= -= -= -= -= -= -= !# .. .. ..';
mappages["hotelcalifornia"].terrain[12] = '.. u, .. !# -= -= -= -= -= -= -= -= -= -= -= -= !# .. .. ..';
mappages["hotelcalifornia"].terrain[13] = '.. .. .. !# -= -= -= -= -= -= -= -= -= -= -= -= !# .. .. ..';
mappages["hotelcalifornia"].terrain[14] = '.. .. .. !# -= -= -= -= -= -= -= -= -= -= -= -= !# u, .. ..';
mappages["hotelcalifornia"].terrain[15] = '.. .. .. !# !# !# !# -= !# !# !# !# !# !# !# !# !# .. .. ..';
mappages["hotelcalifornia"].terrain[16] = '.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..';
mappages["hotelcalifornia"].terrain[17] = '.. .. .. .. .. .. .. .. .. .. .. .. u, .. .. .. .. .. .. ..';
mappages["hotelcalifornia"].terrain[18] = '.. .. .. .. u, .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..';
mappages["hotelcalifornia"].terrain[19] = '.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..';

mappages["hotelcalifornia"].features = [];
mappages["hotelcalifornia"].features[0] = {name : 'Door', x : 7, y : 15};
mappages["hotelcalifornia"].features[1] = {name : 'Tree', x : 17, y : 17};
mappages["hotelcalifornia"].features[2] = {name : 'Tree', x : 13, y : 18};
mappages["hotelcalifornia"].features[3] = {name : 'Tree', x : 9, y : 16};
mappages["hotelcalifornia"].features[4] = {name : 'Tree', x : 4, y : 17};
mappages["hotelcalifornia"].features[5] = {name : 'Tree', x : 1, y : 14};
mappages["hotelcalifornia"].features[6] = {name : 'Tree', x : 2, y : 10};
mappages["hotelcalifornia"].features[7] = {name : 'Tree', x : 0, y : 4};
mappages["hotelcalifornia"].features[8] = {name : 'Tree', x : 5, y : 0};
mappages["hotelcalifornia"].features[9] = {name : 'Tree', x : 11, y : 1};
mappages["hotelcalifornia"].features[10] = {name : 'Tree', x : 18, y : 1};
mappages["hotelcalifornia"].features[11] = {name : 'Tree', x : 17, y : 6};
mappages["hotelcalifornia"].features[12] = {name : 'Tree', x : 18, y : 9};
mappages["hotelcalifornia"].features[13] = {name : 'Tree', x : 18, y : 12};


mappages["hotelcalifornia"].npcs = [];

mappages["hotelcalifornia"].desc = "Mysterious Building";
mappages["hotelcalifornia"].longdesc = '';
mappages["hotelcalifornia"].music = 'Village';
mappages["hotelcalifornia"].savename = 'mystery';
mappages["hotelcalifornia"].exitmap = 'darkunknown';
mappages["hotelcalifornia"].exitx = '65';
mappages["hotelcalifornia"].exity = '70';
mappages["hotelcalifornia"].wraps = '';
mappages["hotelcalifornia"].enterx = '65';
mappages["hotelcalifornia"].entery = '70';
mappages["hotelcalifornia"].seeBelow = '';
mappages["hotelcalifornia"].lightLevel = 'cycle';
mappages["hotelcalifornia"].alwaysRemember = '0';
mappages["hotelcalifornia"].scale = '1';
mappages["hotelcalifornia"].underground = '0';
mappages["hotelcalifornia"].undergroundDesc = '';
mappages["hotelcalifornia"].enterscript = '';
mappages["hotelcalifornia"].entertestscript = '';
mappages["hotelcalifornia"].exitscript = '';
mappages["hotelcalifornia"].exittestscript = '';
mappages["hotelcalifornia"].returnmap = '';
mappages["hotelcalifornia"].returnx = 'NaN';
mappages["hotelcalifornia"].returny = 'NaN';
mappages["hotelcalifornia"].returninfused = '0';
mappages["hotelcalifornia"].linkedMaps = [""];
mappages["hotelcalifornia"].editorLabels = '{}';
