mappages["Island"] = new Object();
mappages["Island"].terrain = new Array;
 mappages["Island"].terrain[0] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["Island"].terrain[1] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["Island"].terrain[2] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["Island"].terrain[3] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["Island"].terrain[4] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["Island"].terrain[5] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww WW WW ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["Island"].terrain[6] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww ww WW WW WW WW ww ww ww ww ww WW WW WW ww ww WW WW ww WW WW ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["Island"].terrain[7] = 'WW WW WW WW WW WW WW WW ww ww ww WW ww ww ww ww ww ww ^^ ^^ ^^ ww ww ^^ ^^ ww ww WW WW ww ww /. -, -- .` ww ww ww ww ww WW ww ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW ww ww WW WW WW WW WW WW WW WW WW WW';
 mappages["Island"].terrain[8] = 'WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww ww ww ww /. .. .. .. .. -, -, -- .` ww ww ww ww /. -- -- -- .` ww ww ww ww ww WW WW ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW';
 mappages["Island"].terrain[9] = 'WW WW WW WW WW WW WW WW WW WW ww ww ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww ww ww /. .. .. ,, .. ,, .. .. ,, .| ww ww ww /. .. .. .. .. .. -- -- -- .` ww ww ww ww ^^ ^^ ^^ ^^ ww ww WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[10] = 'WW WW WW WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn ^^ ^^ ^^ ^^ ^^ nn nn nn nn .. .. .. ,, ,, ,, ,, .. ./ ww /. -- .. .. .. .. .. .. .. .. .. .. .` ww ww ^^ ^^ ^^ ^^ ^^ ^^ ww WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[11] = 'WW WW WW WW WW WW WW WW ww ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn ^^ ^^ ^^ ^^ ^^ nn nn nn ,, .. ,, ,, ,, ,, .. .| ww ww |. .. .. .. .. .. ,, ,, .. .. .. .. ^^ ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[12] = 'WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn nn nn ^^ ^^ ^^ nn nn ,, .. .. ,, ,, .. .. .. .| ww /. .. .. .. .. .. ;; ;; .. .. .. .. .. ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[13] = 'WW WW WW WW WW WW ww ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn nn nn nn nn nn nn nn nn .. .. ,, ,, .. .. ,, .. ,, || .. .. .. .. .. ,, ;; ;; ;; ,, .. .. nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[14] = 'WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ nn nn nn ^^ nn nn nn .. .. nn nn nn nn nn ,, .. .. .. .. .. .. ,, .. .. .. || .. .. .. .. ,, ;; ;; ;; ;; ;; .. .. nn nn nn nn nn nn nn ^^ ^^ ww ww WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[15] = 'WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ nn nn nn nn nn nn nn .. .. .. .. nn nn nn nn ,, .. .. .. ,, .. .. .. .. .. .. || .. .. .. .. .. ;; ;; ;; ;; ;; ,, ,, .. .. .. nn nn nn nn ^^ ww ww WW WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[16] = 'WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ nn nn nn nn nn nn nn .. .. .. .. .. nn .. .. .. .. ,, ,, .. .. .. .. .. ,, ,, || .. .. ,, .. ,, ;; ;; ;; ;; ;; ,, ,, .. .. .. nn nn nn ^^ ^^ ww ww WW WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[17] = 'WW WW WW WW WW WW WW ww ^^ ^^ ^^ ^^ ^^ nn nn nn nn .. .. .. .. .. .. .. .. ,, .. .. .. ,, ,, ,, ,, .. /= == == TT =/ .. .. .. .. .. ;; ;; ;; ,, ;; ;; .. .. .. .. .. nn ^^ ^^ ww ww ww WW WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[18] = 'WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ nn nn nn .. .. .. .. .. .. .. ,, ,, .. .. .. ,, ,, ,, ,, ,, .. || .. .. || .. .. .. .. ,, ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; .. .. nn ^^ ^^ ^^ ww ww ww WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[19] = 'WW WW WW WW WW WW WW WW ww ^^ ^^ ^^ ^^ nn nn nn .. .. .. .. .. .. .. .. .. ,, .. ,, ,, .. ,, .. .. .. || .. .. || .. .. .. .. .. ;; ;; ;; ;; ;; ;; ;; ;; ,, ;; ,, .. nn nn ^^ ^^ ^^ ww ww WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[20] = 'WW WW WW WW WW WW WW WW ww ^^ ^^ ^^ ^^ ^^ nn nn nn .. .. .. .. .. .. .. .. .. .. .. .. .. ,, .. .. .. || .. .. `= =` .. .. .. .. .. ,, ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ,, nn nn ^^ ^^ ww ww WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[21] = 'WW WW WW WW WW WW WW ww ww ww ^^ ^^ ^^ ^^ nn nn nn nn .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. =x =/ .. .. .. `= =` .. .. .. .. .. ,, .. ;; ;; ;; ;; ;; ;; ;; ;; ,, ,, ;; ;; .| ww ww WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[22] = 'WW WW WW WW WW WW WW ww ww ww ^^ ^^ ^^ ^^ ^^ nn nn nn .. .. .. .. .. .. .. .. .. .. .. .. .. ,, .. .. .. .. .. .. .. || .. .. .. .. .. .. ,, ,, ;; ;; ;; ;; ;; ;; ;; ;; ,, .. .. .. .` ww ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[23] = 'WW WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn .. .. nn nn .. .. nn .. .. .. .. ,, .. .. .. ,, ,, .. .. |= == == x= .. .. .. ,, ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ,, ;; ;; .. .` ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[24] = 'WW WW WW WW WW WW WW WW ww ^^ ^^ ^^ ^^ ^^ nn nn nn nn nn nn .. .. nn .. .. .. nn nn .. .. .. ,, ,, .. ,, ,, .. .. .. || .. .. .. .. .. .. ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; .. .| ww ww WW WW WW WW WW WW';
mappages["Island"].terrain[25] = 'WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. || .. .. .. .. .. ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ,, .. .| ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[26] = 'WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn .. .. .. nn nn .. .. .. .. .. .. .. ,, .. .. .. .. .. || .. .. .. ,, ;; ;; ;; ;; ;; ,, ;; ;; ;; ,, ;; ;; ;; ;; ;; ;; .. ./ ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[27] = 'WW WW WW WW WW WW WW WW ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn .. .. .. .. .. .. .. .. .. .. .. ,, .. .. .. /= == =/ .. ,, .. ,, ;; ;; ;; ,, .. .. .. ,, ,, ,, ;; ;; ;; ;; ,, .. ./ ww WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[28] = 'WW WW WW WW WW WW WW WW ww ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn .. .. .. .. .. .. .. .. .. .. .. ,, .. .. .. x^ .. .. .. ,, .. .. ,, .. ;; .. .. .. nn nn nn nn ,, ;; ,, ;; ,, nn ww ww ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[29] = 'WW WW WW WW WW WW WW WW ww ww ww ww ww ^^ ^^ ^^ ^^ nn nn nn nn .. .. .. .. .. .. .. nn nn nn .. .. ,, .. .. .. .. .. .. .. ,, ,, ,, .. .. .. .. .. nn nn nn nn nn nn ;; ;; ;; nn nn ww ww ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[30] = 'WW WW WW WW WW WW WW WW WW ww ww ww ww ^^ ^^ ^^ ^^ ^^ nn nn nn .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ,, .. .. .. ,, nn nn nn nn ^^ nn nn nn ;; ;; nn nn nn nn ww ww WW WW WW WW WW WW';
mappages["Island"].terrain[31] = 'WW WW WW WW WW WW WW WW ww ww ww ww ww ^^ ^^ ^^ ^^ ^^ nn nn nn .. .. .. nn nn nn .. .. .. .. .. .. .. .. .. .. .. .. .. .. ,, .. .. .. ,, ,, nn nn nn nn nn ^^ ^^ ^^ nn ;; nn nn nn nn nn ww ww WW WW WW WW WW WW';
mappages["Island"].terrain[32] = 'WW WW WW WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn .. .. .. nn .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ,, nn nn nn nn nn nn nn nn ^^ ^^ ^^ nn nn nn nn nn nn nn nn ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[33] = 'WW WW WW WW WW WW WW WW WW WW ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn .. .. .. .. .. .. nn nn nn nn nn nn .. .. nn nn ,, ,, nn nn nn nn nn nn nn nn nn ^^ ^^ ^^ ^^ nn nn nn nn nn nn nn ww ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[34] = 'WW WW WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn nn nn nn nn .. .. nn nn nn nn nn nn nn nn .. nn nn nn nn nn nn nn nn nn nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn ww ww ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[35] = 'WW WW WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn nn nn nn nn nn nn nn nn ^^ ^^ ^^ ^^ nn nn nn nn nn nn nn nn nn nn nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn ww ww WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[36] = 'WW WW WW WW WW WW WW WW WW ww ww ww ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn ^^ nn nn nn nn nn nn ^^ ^^ ^^ ^^ ^^ nn nn nn nn nn nn nn nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww ww ww WW WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[37] = 'WW WW WW WW WW WW WW WW ww ww ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn ^^ ^^ nn nn nn nn nn ^^ ^^ ^^ ^^ ^^ ^^ nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww ww ww WW WW WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[38] = 'WW WW WW WW WW WW WW WW ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn ^^ ^^ ^^ ^^ nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww ww ww WW WW WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[39] = 'WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww ww WW WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[40] = 'WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn ^^ ^^ ^^ ^^ nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww ww ww WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[41] = 'WW WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn ^^ ^^ ^^ ^^ ^^ nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[42] = 'WW WW WW WW WW WW WW WW WW ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ~~ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn ^^ ^^ nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[43] = 'WW WW WW WW WW WW WW WW ww ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ~~ ~~ ~~ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[44] = 'WW WW WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ~~ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[45] = 'WW WW WW WW WW WW WW WW WW ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[46] = 'WW WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn ^^ nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[47] = 'WW WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn ^^ ^^ ^^ ^^ nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[48] = 'WW WW WW WW WW WW WW WW WW ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[49] = 'WW WW WW WW WW WW WW WW WW ww ww ww ^^ ^^ nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn ^^ ^^ ^^ ^^ nn nn ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn ^^ ^^ ^^ ^^ ww ww WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[50] = 'WW WW WW WW WW WW WW WW WW WW ww ww ww nn nn nn nn ^^ ^^ nn nn ^^ ^^ ^^ nn nn nn ^^ ^^ ^^ ^^ ^^ nn nn ^^ ^^ nn nn nn nn nn nn ^^ ^^ nn nn nn nn nn nn nn nn nn nn nn nn ^^ ^^ ^^ ^^ ww ww WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[51] = 'WW WW WW WW WW WW WW WW WW WW ww ww ww nn nn nn nn ^^ ^^ nn nn nn nn nn nn nn nn ^^ nn nn nn nn nn nn ^^ ^^ nn nn .. nn nn nn nn ^^ nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn ^^ ww ww WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[52] = 'WW WW WW WW WW WW WW WW WW ww ww nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn .. .. nn nn nn nn nn .. nn nn nn nn nn nn nn nn nn nn nn nn nn ww ww ww WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[53] = 'WW WW WW WW WW WW WW WW WW ww nn nn nn nn nn nn nn nn nn nn nn nn nn nn .. .. nn nn nn .. .. nn nn nn nn .. .. .. .. .. .. nn nn nn .. .. .. nn nn nn nn nn nn .. .. nn nn nn ww ww ww WW WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[54] = 'WW WW WW WW WW WW WW WW WW ww nn nn nn nn nn nn nn nn nn nn nn nn nn .. .. .. .. .. .. .. .. .. nn nn .. .. .. .. .. .. .. .. nn nn .. .. .. nn nn nn nn .. .. .. .. .. nn nn nn ww ww WW WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[55] = 'WW WW WW WW WW WW WW WW WW ww nn .. .. .. nn nn nn nn nn nn nn nn nn .. .. ,, .. .. .. .. .. .. .. .. .. .. .. .. ,, .. .. .. .. .. .. .. .. .. nn nn nn ,, .. .. nn .. .. .. nn nn ww WW WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[56] = 'WW WW WW WW WW WW WW WW WW ww `. .. .. ,, .. nn nn nn .. .. nn nn .. .. ,, ,, .. .. .. .. .. ,, ,, .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. nn .. .. .. nn .. ,, .. .. .. .. ,| ww ww WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[57] = 'WW WW WW WW WW WW WW WW WW ww ww `. ,, ,, ,, .. .. .. ,, ,, .. nn .. ,, ,, .. .. .. .. ,, .. .. .. .. .. ,, .. .. .. .. .. .. .. .. ,, .. .. .. .. ,, .. .. ,, ,, .. nn .. ,, .. .| ww ww WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[58] = 'WW WW WW WW WW WW WW WW WW WW ww ww |. ,, .. .. ff .. .. ,, .. .. .. .. .. ff ,, .. .. ff .. .. ff ff .. ,, .. .. .. .. .. .. .. .. .. .. ;; ;; .. .. .. ;; ;; ;; .. .. ,, ,, .. ./ ww WW WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[59] = 'WW WW WW WW WW WW WW WW WW ww ww ww |. .. ff .. .. ff ff .. .. ff .. .. .. .. ff .. .. .. /= == == == == == x= .. .. .. .. .. .. .. .. ,, ,, .. ;; ;; ;; ;; ;; .. .. .. .. .. ./ ww ww WW WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[60] = 'WW WW WW WW WW WW WW WW WW WW ww ww == == == == TT == == == =` .. ff ff .. /= == == == == =/ ff ff .. ,, ,, .. .. .. .. ,, .. .. .. .. .. .. ;; ;; ;; ;; ;; ;; ;; ;; ;; .. ./ ww ww ww ww ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[61] = 'WW WW WW WW WW WW WW WW WW WW ww /. .. ff ff .. || .. .. .. `= == == == == =| .. ff ff ff .. .. .. ff .. .. .. .. .. .. .. .. .. .. .. .. .. ,, .. .. ;; ;; ;; ;; ;; .. ./ ww ww ww ww ww ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[62] = 'WW WW WW WW WW WW WW WW WW WW ww |. .. .. ff .. || .. ff ff ff ff .. ff .. || .. .. .. ff ,, ,, .. ff .. .. .. .. .. ff .. .. ff .. .. .. .. .. .. .. .. ;; ;; ;; ,, .| ww ww ww /. -, .` ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[63] = 'WW WW WW WW WW WW WW WW WW ww ww |. .. ,, ff ff `= == =` .. .. ff .. ff ,, || .. ff .. .. .. ff .. .. .. .. .. ff ff .. ff ff ff ff ff ff ff .. .. .. ,, ;; ;; ;; .. ,, -, -, -- ,, .. ,| ww ww WW WW WW WW WW WW';
mappages["Island"].terrain[64] = 'WW WW WW WW WW WW WW WW WW ww /. .. ,, ,, .. .. .. .. || .. ,, ff .. .. ,, `= == == == =` .. .. .. .. .. ff ff .. ff ff ff .. .. ff .. ff .. .. .. .. ,, ;; ;; ;; ;; .. .. .. ,, .. _, ./ ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[65] = 'WW WW WW WW WW WW WW WW ww ww |. .. ,, .. ,, ,, .. ,, x^ .. ,, .. .. .. .. ff ff .. .. `= == == x= .. .. .. ff .. ff .. .. .. .. .. .. .. .. ff ff .. ;; ;; ;; ;; .. .. _, _, __ ./ ww ww ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[66] = 'WW WW WW WW WW WW WW WW ww ww |. .. __ __ .. .. ,, .. .. .. .. .. .. .. .. ff .. ff .. .. .. ff ff .. ff .. .. .. .. .. ff ff .. ff .. ff .. .. .. .. ;; ;; ;; ;; .. ;| ww ww ww ww ww ww WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[67] = 'WW WW WW WW WW WW WW WW WW ww `. ./ ww ww `. .. .. .. .. nn nn nn .. .. .. ,, .. .. ,, .. .. ff .. .. ff ff .. .. .. ff ff .. ff ff ff .. ff .. .. .. .. ;; ;; ,, ;; .. .` ww ww ww ww ww WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[68] = 'WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww |. .. .. nn nn nn nn nn .. .. .. ,, .. .. ,, .. .. .. .. .. .. ff ff .. .. ff ff ff .. ff .. ff .. .. .. .. ;; ;; ;; ;; .. ,, .` ww ww ww ww ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[69] = 'WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww |. nn nn nn ^^ ^^ nn nn nn nn .. .. .. .. ff .. .. .. ,, .. .. ff ff ff ff .. ff ff .. ff ff .. ,, ,, .. ;; ;; ;; ;; ;; .. .. .. -- .` ww ww WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[70] = 'WW WW WW WW WW WW WW WW WW ww ww ww nn ww nn nn nn nn ^^ ^^ ^^ nn nn nn nn .. .. .. ,, .. ,, ,, .. ,, .. .. .. .. ff ff .. .. ff ff .. .. ,, ,, .. .. .. ;; ;; ,, .. ,, ,, .. ,, .. .` ww ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[71] = 'WW WW WW WW WW WW WW WW ww ww nn nn nn nn nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn nn nn .. .. .. .. ,, .. .. .. ff ff .. ff ff .. .. .. .. .. .. .. ,, ,, .. .. .. .. ,, ;; .. ,, ;; ,, .` ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[72] = 'WW WW WW WW WW WW WW ww ww ww nn nn nn nn nn ^^ ^^ ^^ ^^ ^^ nn nn nn nn nn nn nn nn nn nn .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ,, .. ,, .. .. ;; ,, .. ;; ;; .. ;; .. ,, .. ,| ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[73] = 'WW WW WW WW WW WW WW ww ww nn nn nn nn ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn nn nn nn ^^ nn nn nn nn nn .. nn nn .. .. .. .. .. .. .. .. .. .. ,, .. ;; ;; .. ;; ;; ;; ;; ,, ;; ,, ;; ;; ;; ;; ./ ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[74] = 'WW WW WW WW WW WW WW WW ww nn nn nn ^^ ^^ ^^ ^^ ^^ nn nn nn .. .. nn nn nn ^^ ^^ nn nn nn ^^ nn nn nn nn nn nn .. .. .. .. .. .. .. .. ,, ,, ;; .. .. .. ;; ;; ;; .. ;; ;; ;; ;; ;; ;; ww ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[75] = 'WW WW WW WW WW WW WW WW ww ww nn nn ^^ ^^ ^^ nn nn nn nn __ __ .. .. nn nn ^^ ^^ ^^ nn ^^ ^^ nn ^^ ^^ ^^ ^^ nn nn .. .. .. .. .. .. ,, .. ,, ,, .. ;; ;; ;; ;; ,, ,, ,, ;; .. ;; .. .| ww ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[76] = 'WW WW WW WW WW WW WW WW ww ww nn nn nn ^^ nn nn nn nn ww ww ww `. .. nn nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn .. .. .. ,, .. .. ;; .. .. .. ;; ,, ,, .. ;; .. ;; ;; ;; ;; ;; ,, .` ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[77] = 'WW WW WW WW WW WW WW WW WW ww nn nn nn nn nn nn nn ww ww ww ww ww |. .. nn nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn .. .. .. .. .. ,, .. ;; ;; ;; .. ,, .. ,, .. ;; ;; ;; ;; ;; ,, ;; .. ;| ww ww WW WW WW WW WW WW';
mappages["Island"].terrain[78] = 'WW WW WW WW WW WW WW WW WW ww ww nn nn nn nn nn nn ww ww WW ww ww |. .. .. nn nn nn nn ^^ nn nn nn nn nn nn nn .. .. .. .. .. ,, .. ;; ;; ;; ;; .. .. ;| `. _; .. .. ;; ;; .. .. ;; ;; .| ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[79] = 'WW WW WW WW WW WW WW WW WW WW ww nn nn nn nn ww ww ww WW WW WW ww `. .. .. .. nn nn nn nn nn nn nn .. nn nn .. .. .. .. .. .. ,, ;; ;; ;; ;; ,, ;; .. ./ ww ww |, ,, .. ;; ;; ;; ,, ;; ,| ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[80] = 'WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww WW WW WW WW WW ww ww `. .. .. .. .. nn .. ./ ww ww `. .. .. .. .. .. __ __ .. .. ,, ;; .. ;; ,, .. ./ ww ww ww |, .. ;; ;; .. ;; ,, __ ./ ww WW WW WW WW WW WW WW';
mappages["Island"].terrain[81] = 'WW WW WW WW WW WW WW WW ww ww WW WW WW WW WW WW WW WW WW WW WW WW ww ww `. .. .. .. .. .| ww ww ww ww `. __ __ __ ./ ww ww `. .. ;; .. ,, .. .. ./ ww ww ww ww `. .. ;; ,, ,, .. ./ ww ww WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[82] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww `. __ __ __ ./ ww ww ww ww ww ww ww ww ww ww ww ww `. __ _; __ _; ./ ww ww WW WW ww ww `. _; _; __ ./ ww ww WW WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[83] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww ww ww ww WW WW WW WW ww ww ww ww ww ww ww ww ww ww WW WW WW WW ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[84] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[85] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[86] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[87] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[88] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["Island"].terrain[89] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';

mappages["Island"].features = new Array;
mappages["Island"].features[0] = {name : 'Cave', x : 33, y : 47, entermap : 'null', enterx : 0, entery : 0};
mappages["Island"].features[1] = {name : 'Cave', x : 30, y : 40, entermap : 'null', enterx : 0, entery : 0};
mappages["Island"].features[2] = {name : 'Cave', x : 15, y : 48, entermap : 'null', enterx : 0, entery : 0};
mappages["Island"].features[3] = {name : 'HillTower', x : 58, y : 33, entermap : 'null', enterx : 0, entery : 0};
mappages["Island"].features[4] = {name : 'Cave', x : 13, y : 13, entermap : 'null', enterx : 0, entery : 0};
mappages["Island"].features[5] = {name : 'Shrine', x : 56, y : 15};
mappages["Island"].features[6] = {name : 'Shrine', x : 14, y : 76};
mappages["Island"].features[7] = {name : 'LeftCastle', x : 41, y : 65};
mappages["Island"].features[8] = {name : 'Castle', x : 42, y : 65, entermap : 'null', enterx : 0, entery : 0};
mappages["Island"].features[9] = {name : 'RightCastle', x : 43, y : 65};
mappages["Island"].features[10] = {name : 'BrokenShrine', x : 60, y : 63};


mappages["Island"].npcs = new Array;

mappages["Island"].desc = 'A Distant Island';
mappages["Island"].music = 'Island';
mappages["Island"].exitmap = '';
mappages["Island"].exitx = '';
mappages["Island"].exity = '';
mappages["Island"].wraps = 'None';
mappages["Island"].enterx = '14';
mappages["Island"].entery = '76';
mappages["Island"].seeBelow = '';
mappages["Island"].lightLevel = 'bright';
mappages["Island"].linkedMaps = new Array("");
