mappages["island"] = new Object();
mappages["island"].terrain = new Array;
 mappages["island"].terrain[0] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["island"].terrain[1] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["island"].terrain[2] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["island"].terrain[3] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["island"].terrain[4] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["island"].terrain[5] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww WW WW ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["island"].terrain[6] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww ww WW WW WW WW ww ww ww ww ww WW WW WW ww ww WW WW ww WW WW ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["island"].terrain[7] = 'WW WW WW WW WW WW WW WW ww ww ww WW ww ww ww ww ww ww ^^ ^^ ^^ ww ww ^^ ^^ ww ww WW WW ww ww /. -, -- .` ww ww ww ww ww WW ww ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW ww ww WW WW WW WW WW WW WW WW WW WW';
 mappages["island"].terrain[8] = 'WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww ww ww ww /. .. .. .. .. -, -, -- .` ww ww ww ww /. -- -- -- .` ww ww ww ww ww WW WW ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW';
 mappages["island"].terrain[9] = 'WW WW WW WW WW WW WW WW WW WW ww ww ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww ww ww /. .. .. ,, .. ,, .. .. ,, .| ww ww ww /. .. .. .. .. .. -- -- -- .` ww ww ww ww ^^ ^^ ^^ ^^ ww ww WW WW WW WW WW WW WW WW';
mappages["island"].terrain[10] = 'WW WW WW WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn ^^ ^^ ^^ ^^ ^^ nn nn nn nn .. .. .. ,, ,, ,, ,, .. ./ ww /. -- .. .. .. .. .. .. .. .. .. .. .` ww ww ^^ ^^ ^^ ^^ ^^ ^^ ww WW WW WW WW WW WW WW WW';
mappages["island"].terrain[11] = 'WW WW WW WW WW WW WW WW ww ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn ^^ ^^ ^^ ^^ ^^ nn nn nn ,, .. ,, ,, ,, ,, .. .| ww ww |. .. .. .. .. .. ,, ,, .. .. .. .. ^^ ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww ww WW WW WW WW WW WW WW';
mappages["island"].terrain[12] = 'WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn nn nn ^^ ^^ ^^ nn nn ,, .. .. ,, ,, .. .. .. .| ww /. .. .. .. .. .. ;; ;; .. .. .. .. .. ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww ww WW WW WW WW WW WW WW';
mappages["island"].terrain[13] = 'WW WW WW WW WW WW ww ww ww ^^ ^^ ^^ ^^ nn ^^ ^^ ^^ nn nn nn nn nn nn nn nn nn nn nn nn .. .. ,, ,, .. .. ,, .. ,, RR .. .. .. .. .. ,, ;; ;; ;; ,, .. .. nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww WW WW WW WW WW WW WW WW';
mappages["island"].terrain[14] = 'WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ nn nn nn ^^ nn nn nn .. .. nn nn nn nn nn ,, .. .. .. .. .. .. ,, .. .. .. RR .. .. .. .. ,, ;; ;; ;; ;; ;; .. .. nn nn nn nn nn nn nn ^^ ^^ ww ww WW WW WW WW WW WW WW WW';
mappages["island"].terrain[15] = 'WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ nn nn nn nn nn nn nn .. .. .. .. nn nn nn nn ,, .. .. .. ,, .. .. .. .. .. .. RR .. .. .. .. .. ;; ;; ;; ;; ;; ,, ,, .. .. .. nn nn nn nn ^^ ww ww WW WW WW WW WW WW WW WW WW';
mappages["island"].terrain[16] = 'WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ nn nn nn nn nn nn nn .. .. .. .. .. nn .. .. .. .. ,, ,, .. .. .. .. .. ,, ,, RR .. .. ,, .. ,, ;; ;; ;; ;; ;; ,, ,, .. .. .. nn nn nn ^^ ^^ ww ww WW WW WW WW WW WW WW WW WW';
mappages["island"].terrain[17] = 'WW WW WW WW WW WW WW ww ^^ ^^ ^^ ^^ ^^ nn nn nn nn .. .. .. .. .. .. .. .. ,, .. .. .. ,, ,, ,, ,, .. RR RR RR RR RR .. .. .. .. .. ;; ;; ;; ,, ;; ;; .. .. .. .. .. nn ^^ ^^ ww ww ww WW WW WW WW WW WW WW WW WW';
mappages["island"].terrain[18] = 'WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ nn nn nn .. .. .. .. .. .. .. ,, ,, .. .. .. ,, ,, ,, ,, ,, .. RR .. .. RR .. .. .. .. ,, ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; .. .. nn ^^ ^^ ^^ ww ww ww WW WW WW WW WW WW WW WW';
mappages["island"].terrain[19] = 'WW WW WW WW WW WW WW WW ww ^^ ^^ ^^ ^^ nn nn nn .. .. .. .. .. .. .. .. .. ,, .. ,, ,, .. ,, .. .. .. RR .. .. RR .. .. .. .. .. ;; ;; ;; ;; ;; ;; ;; ;; ,, ;; ,, .. nn nn ^^ ^^ ^^ ww ww WW WW WW WW WW WW WW WW';
mappages["island"].terrain[20] = 'WW WW WW WW WW WW WW WW ww ^^ ^^ ^^ ^^ ^^ nn nn nn .. .. .. .. .. .. .. .. .. .. .. .. .. ,, .. .. .. RR .. .. RR RR .. .. .. .. .. ,, ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ,, nn nn ^^ ^^ ww ww WW WW WW WW WW WW WW WW';
mappages["island"].terrain[21] = 'WW WW WW WW WW WW WW ww ww ww ^^ ^^ ^^ ^^ nn nn nn nn .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. RR RR .. .. .. RR RR .. .. .. .. .. ,, .. ;; ;; ;; ;; ;; ;; ;; ;; ,, ,, ;; ;; .| ww ww WW WW WW WW WW WW WW WW';
mappages["island"].terrain[22] = 'WW WW WW WW WW WW WW ww ww ww ^^ ^^ ^^ ^^ ^^ nn nn nn .. .. .. .. .. .. .. .. .. .. .. .. .. ,, .. .. .. .. .. .. .. RR .. .. .. .. .. .. ,, ,, ;; ;; ;; ;; ;; ;; ;; ;; ,, .. .. .. .` ww ww WW WW WW WW WW WW WW';
mappages["island"].terrain[23] = 'WW WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn .. .. nn nn .. .. nn .. .. .. .. ,, .. .. .. ,, ,, .. .. RR RR RR RR .. .. .. ,, ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ,, ;; ;; .. .` ww WW WW WW WW WW WW WW';
mappages["island"].terrain[24] = 'WW WW WW WW WW WW WW WW ww ^^ ^^ ^^ ^^ ^^ nn nn nn nn nn nn .. .. nn .. .. .. nn nn .. .. .. ,, ,, .. ,, ,, .. .. .. RR .. .. .. .. .. .. ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; .. .| ww ww WW WW WW WW WW WW';
mappages["island"].terrain[25] = 'WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. RR .. .. .. .. .. ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ,, .. .| ww WW WW WW WW WW WW WW';
mappages["island"].terrain[26] = 'WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn .. .. .. nn nn .. .. .. .. .. .. .. ,, .. .. .. .. .. RR .. .. .. ,, ;; ;; ;; ;; ;; ,, ;; ;; ;; ,, ;; ;; ;; ;; ;; ;; .. ./ ww WW WW WW WW WW WW WW';
mappages["island"].terrain[27] = 'WW WW WW WW WW WW WW WW ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn .. .. .. .. .. .. .. .. .. .. .. ,, .. .. .. RR RR RR .. ,, .. ,, ;; ;; ;; ,, .. .. .. ,, ,, ,, ;; ;; ;; ;; ,, .. ./ ww WW WW WW WW WW WW WW WW';
mappages["island"].terrain[28] = 'WW WW WW WW WW WW WW WW ww ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn .. .. .. .. .. .. .. .. .. .. .. ,, .. .. .. RR .. .. .. ,, .. .. ,, .. ;; .. .. .. nn nn nn nn ,, ;; ,, ;; ,, nn ww ww ww WW WW WW WW WW WW WW';
mappages["island"].terrain[29] = 'WW WW WW WW WW WW WW WW ww ww ww ww ww ^^ ^^ ^^ ^^ nn nn nn nn .. .. .. .. .. .. .. nn nn nn .. .. ,, .. .. .. .. .. .. .. ,, ,, ,, .. .. .. .. .. nn nn nn nn nn nn ;; ;; ;; nn nn ww ww ww WW WW WW WW WW WW WW';
mappages["island"].terrain[30] = 'WW WW WW WW WW WW WW WW WW ww ww ww ww ^^ ^^ ^^ ^^ ^^ nn nn nn .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ,, .. .. .. ,, nn nn nn nn ^^ nn nn nn ;; ;; nn nn nn nn ww ww WW WW WW WW WW WW';
mappages["island"].terrain[31] = 'WW WW WW WW WW WW WW WW ww ww ww ww ww ^^ ^^ ^^ ^^ ^^ nn nn nn .. .. .. nn nn nn .. .. .. .. .. .. .. .. .. .. .. .. .. .. ,, .. .. .. ,, ,, nn nn nn nn nn ^^ ^^ ^^ nn ;; nn nn nn nn nn ww ww WW WW WW WW WW WW';
mappages["island"].terrain[32] = 'WW WW WW WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn .. .. .. nn .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ,, nn nn nn nn nn nn nn nn ^^ ^^ ^^ nn nn nn nn nn nn nn nn ww WW WW WW WW WW WW WW';
mappages["island"].terrain[33] = 'WW WW WW WW WW WW WW WW WW WW ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn .. .. .. .. .. .. nn nn nn nn nn nn .. .. nn nn ,, ,, nn nn nn nn nn nn nn nn nn ^^ ^^ ^^ ^^ nn nn nn nn nn nn nn ww ww WW WW WW WW WW WW WW';
mappages["island"].terrain[34] = 'WW WW WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn nn nn nn nn .. .. nn nn nn nn nn nn nn nn .. nn nn nn nn nn nn nn nn nn nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn ww ww ww WW WW WW WW WW WW WW';
mappages["island"].terrain[35] = 'WW WW WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn nn nn nn nn nn nn nn nn ^^ ^^ ^^ ^^ nn nn nn nn nn nn nn nn nn nn nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn ww ww WW WW WW WW WW WW WW WW';
mappages["island"].terrain[36] = 'WW WW WW WW WW WW WW WW WW ww ww ww ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn ^^ nn nn nn nn nn nn ^^ ^^ ^^ ^^ ^^ nn nn nn nn nn nn nn nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww ww ww WW WW WW WW WW WW WW WW WW';
mappages["island"].terrain[37] = 'WW WW WW WW WW WW WW WW ww ww ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn ^^ ^^ nn nn nn nn nn ^^ ^^ ^^ ^^ ^^ ^^ nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww ww ww WW WW WW WW WW WW WW WW WW WW';
mappages["island"].terrain[38] = 'WW WW WW WW WW WW WW WW ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn ^^ ^^ ^^ ^^ nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww ww ww WW WW WW WW WW WW WW WW WW WW';
mappages["island"].terrain[39] = 'WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww ww WW WW WW WW WW WW WW WW WW';
mappages["island"].terrain[40] = 'WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn ^^ ^^ ^^ nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww ww ww WW WW WW WW WW WW WW WW';
mappages["island"].terrain[41] = 'WW WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn ^^ ^^ ^^ ^^ ^^ nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww ww WW WW WW WW WW WW WW';
mappages["island"].terrain[42] = 'WW WW WW WW WW WW WW WW WW ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ~~ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn ^^ ^^ nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww WW WW WW WW WW WW WW';
mappages["island"].terrain[43] = 'WW WW WW WW WW WW WW WW ww ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ~~ ~~ ~~ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww WW WW WW WW WW WW WW';
mappages["island"].terrain[44] = 'WW WW WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ~~ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww WW WW WW WW WW WW WW';
mappages["island"].terrain[45] = 'WW WW WW WW WW WW WW WW WW ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww ww WW WW WW WW WW WW WW';
mappages["island"].terrain[46] = 'WW WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn ^^ nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww WW WW WW WW WW WW WW WW';
mappages["island"].terrain[47] = 'WW WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn ^^ ^^ ^^ ^^ nn nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww ww WW WW WW WW WW WW WW';
mappages["island"].terrain[48] = 'WW WW WW WW WW WW WW WW WW ww ^^ ^^ ^^ ^^ ^^ nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww WW WW WW WW WW WW WW WW';
mappages["island"].terrain[49] = 'WW WW WW WW WW WW WW WW WW ww ww ww ^^ ^^ nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn ^^ ^^ ^^ ^^ nn nn ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn ^^ ^^ ^^ ^^ ww ww WW WW WW WW WW WW WW WW';
mappages["island"].terrain[50] = 'WW WW WW WW WW WW WW WW WW WW ww ww ww nn nn nn nn ^^ ^^ nn nn ^^ ^^ ^^ nn nn nn ^^ ^^ ^^ ^^ ^^ nn nn ^^ ^^ nn nn nn nn nn nn ^^ ^^ nn nn nn nn nn nn nn nn nn nn nn nn ^^ ^^ ^^ ^^ ww ww WW WW WW WW WW WW WW WW';
mappages["island"].terrain[51] = 'WW WW WW WW WW WW WW WW WW WW ww ww ww nn nn nn nn ^^ ^^ nn nn nn nn nn nn nn nn ^^ nn nn nn nn nn nn ^^ ^^ nn nn .. nn nn nn nn ^^ nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn ^^ ww ww WW WW WW WW WW WW WW WW';
mappages["island"].terrain[52] = 'WW WW WW WW WW WW WW WW WW ww ww nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn .. .. nn nn nn nn nn .. nn nn nn nn nn nn nn nn nn nn nn nn nn ww ww ww WW WW WW WW WW WW WW WW';
mappages["island"].terrain[53] = 'WW WW WW WW WW WW WW WW WW ww nn nn nn nn nn nn nn nn nn nn nn nn nn nn .. .. nn nn nn .. .. nn nn nn nn .. .. .. .. .. .. nn nn nn .. .. .. nn nn nn nn nn nn .. .. nn nn nn ww ww ww WW WW WW WW WW WW WW WW WW';
mappages["island"].terrain[54] = 'WW WW WW WW WW WW WW WW WW ww nn nn nn nn nn nn nn nn nn nn nn nn nn .. .. .. .. .. .. .. .. .. nn nn .. .. .. .. .. .. .. .. nn nn .. .. .. nn nn nn nn .. .. .. .. .. nn nn nn ww ww WW WW WW WW WW WW WW WW WW';
mappages["island"].terrain[55] = 'WW WW WW WW WW WW WW WW WW ww nn .. .. .. nn nn nn nn nn nn nn nn nn .. .. ,, .. .. .. .. .. .. .. .. .. .. .. .. ,, .. .. .. .. .. .. .. .. .. nn nn nn ,, .. .. nn .. .. .. nn nn ww WW WW WW WW WW WW WW WW WW';
mappages["island"].terrain[56] = 'WW WW WW WW WW WW WW WW WW ww `. .. .. ,, .. nn nn nn .. .. nn nn .. .. ,, ,, .. .. .. .. .. ,, ,, .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. nn .. .. .. nn .. ,, .. .. .. .. ,| ww ww WW WW WW WW WW WW WW WW';
mappages["island"].terrain[57] = 'WW WW WW WW WW WW WW WW WW ww ww `. ,, ,, ,, .. .. .. ,, ,, .. nn .. ,, ,, .. .. .. .. ,, .. .. .. .. .. ,, .. .. .. .. .. .. .. .. ,, .. .. .. .. ,, .. .. ,, ,, .. nn .. ,, .. .| ww ww WW WW WW WW WW WW WW WW';
mappages["island"].terrain[58] = 'WW WW WW WW WW WW WW WW WW WW ww ww |. ,, .. .. ff .. .. ,, .. .. .. .. .. ff ,, .. .. ff .. .. ff ff .. ,, .. .. .. .. .. .. .. .. .. .. ;; ;; .. .. .. ;; ;; ;; .. .. ,, ,, .. ./ ww WW WW WW WW WW WW WW WW WW';
mappages["island"].terrain[59] = 'WW WW WW WW WW WW WW WW WW ww ww ww |. .. ff .. .. ff ff .. .. ff .. .. .. .. ff .. .. .. RR RR RR RR RR RR RR .. .. .. .. .. .. .. .. ,, ,, .. ;; ;; ;; ;; ;; .. .. .. .. .. ./ ww ww WW WW WW WW WW WW WW WW WW';
mappages["island"].terrain[60] = 'WW WW WW WW WW WW WW WW WW WW ww ww RR RR RR RR RR RR RR RR RR .. ff ff .. RR RR RR RR RR RR ff ff .. ,, ,, .. .. .. .. ,, .. .. .. .. .. .. ;; ;; ;; ;; ;; ;; ;; ;; ;; .. ./ ww ww ww ww ww WW WW WW WW WW WW WW';
mappages["island"].terrain[61] = 'WW WW WW WW WW WW WW WW WW WW ww /. .. ff ff .. RR .. .. .. RR RR RR RR RR RR .. ff ff ff .. .. .. ff .. .. .. .. .. .. .. .. .. .. .. .. .. ,, .. .. ;; ;; ;; ;; ;; .. ./ ww ww ww ww ww ww WW WW WW WW WW WW WW';
mappages["island"].terrain[62] = 'WW WW WW WW WW WW WW WW WW WW ww |. .. .. ff .. RR .. ff ff ff ff .. ff .. RR .. .. .. ff ,, ,, .. ff .. .. .. .. .. ff .. .. ff .. .. .. .. .. .. .. .. ;; ;; ;; ,, .| ww ww ww /. -, .` ww WW WW WW WW WW WW WW';
mappages["island"].terrain[63] = 'WW WW WW WW WW WW WW WW WW ww ww |. .. ,, ff ff RR RR RR .. .. ff .. ff ,, RR .. ff .. .. .. ff .. .. .. .. .. ff ff .. ff ff ff ff ff ff ff .. .. .. ,, ;; ;; ;; .. ,, -, -, -- ,, .. ,| ww ww WW WW WW WW WW WW';
mappages["island"].terrain[64] = 'WW WW WW WW WW WW WW WW WW ww /. .. ,, ,, .. .. .. .. RR .. ,, ff .. .. ,, RR RR RR RR RR .. .. .. .. .. ff ff .. ff ff ff .. .. ff .. ff .. .. .. .. ,, ;; ;; ;; ;; .. .. .. ,, .. _, ./ ww WW WW WW WW WW WW WW';
mappages["island"].terrain[65] = 'WW WW WW WW WW WW WW WW ww ww |. .. ,, .. ,, ,, .. ,, RR .. ,, .. .. .. .. ff ff .. .. RR RR RR RR .. .. .. ff .. ff .. .. .. .. .. .. .. .. ff ff .. ;; ;; ;; ;; .. .. _, _, __ ./ ww ww ww WW WW WW WW WW WW WW';
mappages["island"].terrain[66] = 'WW WW WW WW WW WW WW WW ww ww |. .. __ __ .. .. ,, .. .. .. .. .. .. .. .. ff .. ff .. .. .. ff ff .. ff .. .. .. .. .. ff ff .. ff .. ff .. .. .. .. ;; ;; ;; ;; .. ;| ww ww ww ww ww ww WW WW WW WW WW WW WW WW';
mappages["island"].terrain[67] = 'WW WW WW WW WW WW WW WW WW ww `. ./ ww ww `. .. .. .. .. nn nn nn .. .. .. ,, .. .. ,, .. .. ff .. .. ff ff .. .. .. ff ff .. ff ff ff .. ff .. .. .. .. ;; ;; ,, ;; .. .` ww ww ww ww ww WW WW WW WW WW WW WW WW';
mappages["island"].terrain[68] = 'WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww |. .. .. nn nn nn nn nn .. .. .. ,, .. .. ,, .. .. .. .. .. .. ff ff .. .. ff ff ff .. ff .. ff .. .. .. .. ;; ;; ;; ;; .. ,, .` ww ww ww ww ww WW WW WW WW WW WW WW';
mappages["island"].terrain[69] = 'WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww |. nn nn nn ^^ ^^ nn nn nn nn .. .. .. .. ff .. .. .. ,, .. .. ff ff ff ff .. ff ff .. ff ff .. ,, ,, .. ;; ;; ;; ;; ;; .. .. .. -- .` ww ww WW WW WW WW WW WW WW WW';
mappages["island"].terrain[70] = 'WW WW WW WW WW WW WW WW WW ww ww ww nn ww nn nn nn nn ^^ ^^ ^^ nn nn nn nn .. .. .. ,, .. ,, ,, .. ,, .. .. .. .. ff ff .. .. ff ff .. .. ,, ,, .. .. .. ;; ;; ,, .. ,, ,, .. ,, .. .` ww ww WW WW WW WW WW WW WW';
mappages["island"].terrain[71] = 'WW WW WW WW WW WW WW WW ww ww nn nn nn nn nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn nn nn .. .. .. .. ,, .. .. .. ff ff .. ff ff .. .. .. .. .. .. .. ,, ,, .. .. .. .. ,, ;; .. ,, ;; ,, .` ww WW WW WW WW WW WW WW';
mappages["island"].terrain[72] = 'WW WW WW WW WW WW WW ww ww ww nn nn nn nn nn ^^ ^^ ^^ ^^ ^^ nn nn nn nn nn nn nn nn nn nn .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ,, .. ,, .. .. ;; ,, .. ;; ;; .. ;; .. ,, .. ,| ww WW WW WW WW WW WW WW';
mappages["island"].terrain[73] = 'WW WW WW WW WW WW WW ww ww nn nn nn nn ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn nn nn nn ^^ nn nn nn nn nn .. nn nn .. .. .. .. .. .. .. .. .. .. ,, .. ;; ;; .. ;; ;; ;; ;; ,, ;; ,, ;; ;; ;; ;; ./ ww WW WW WW WW WW WW WW';
mappages["island"].terrain[74] = 'WW WW WW WW WW WW WW WW ww nn nn nn ^^ ^^ ^^ ^^ ^^ nn nn nn .. .. nn nn nn ^^ ^^ nn nn nn ^^ nn nn nn nn nn nn .. .. .. .. .. .. .. .. ,, ,, ;; .. .. .. ;; ;; ;; .. ;; ;; ;; ;; ;; ;; ww ww WW WW WW WW WW WW WW';
mappages["island"].terrain[75] = 'WW WW WW WW WW WW WW WW ww ww nn nn ^^ ^^ ^^ nn nn nn nn __ __ .. .. nn nn ^^ ^^ ^^ nn ^^ ^^ nn ^^ ^^ ^^ ^^ nn nn .. .. .. .. .. .. ,, .. ,, ,, .. ;; ;; ;; ;; ,, ,, ,, ;; .. ;; .. .| ww ww WW WW WW WW WW WW WW';
mappages["island"].terrain[76] = 'WW WW WW WW WW WW WW WW ww ww nn nn nn ^^ nn nn nn nn ww ww ww `. .. nn nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn .. .. .. ,, .. .. ;; .. .. .. ;; ,, ,, .. ;; .. ;; ;; ;; ;; ;; ,, .` ww WW WW WW WW WW WW WW';
mappages["island"].terrain[77] = 'WW WW WW WW WW WW WW WW WW ww nn nn nn nn nn nn nn ww ww ww ww ww |. .. nn nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn .. .. .. .. .. ,, .. ;; ;; ;; .. ,, .. ,, .. ;; ;; ;; ;; ;; ,, ;; .. ;| ww ww WW WW WW WW WW WW';
mappages["island"].terrain[78] = 'WW WW WW WW WW WW WW WW WW ww ww nn nn nn nn nn nn ww ww WW ww ww |. .. .. nn nn nn nn ^^ nn nn nn nn nn nn nn .. .. .. .. .. ,, .. ;; ;; ;; ;; .. .. ;| `. _; .. .. ;; ;; .. .. ;; ;; .| ww WW WW WW WW WW WW WW';
mappages["island"].terrain[79] = 'WW WW WW WW WW WW WW WW WW WW ww nn nn nn nn ww ww ww WW WW WW ww `. .. .. .. nn nn nn nn nn nn nn .. nn nn .. .. .. .. .. .. ,, ;; ;; ;; ;; ,, ;; .. ./ ww ww |, ,, .. ;; ;; ;; ,, ;; ,| ww WW WW WW WW WW WW WW';
mappages["island"].terrain[80] = 'WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww WW WW WW WW WW ww ww `. .. .. .. .. nn .. ./ ww ww `. .. .. .. .. .. __ __ .. .. ,, ;; .. ;; ,, .. ./ ww ww ww |, .. ;; ;; .. ;; ,, __ ./ ww WW WW WW WW WW WW WW';
mappages["island"].terrain[81] = 'WW WW WW WW WW WW WW WW ww ww WW WW WW WW WW WW WW WW WW WW WW WW ww ww `. .. .. .. .. .| ww ww ww ww `. __ __ __ ./ ww ww `. .. ;; .. ,, .. .. ./ ww ww ww ww `. .. ;; ,, ,, .. ./ ww ww WW WW WW WW WW WW WW WW';
mappages["island"].terrain[82] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww `. __ __ __ ./ ww ww ww ww ww ww ww ww ww ww ww ww `. __ _; __ _; ./ ww ww WW WW ww ww `. _; _; __ ./ ww ww WW WW WW WW WW WW WW WW WW';
mappages["island"].terrain[83] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww ww ww ww WW WW WW WW ww ww ww ww ww ww ww ww ww ww WW WW WW WW ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW';
mappages["island"].terrain[84] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["island"].terrain[85] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["island"].terrain[86] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["island"].terrain[87] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["island"].terrain[88] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["island"].terrain[89] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';

mappages["island"].features = new Array;
mappages["island"].features[0] = {name : 'Cave', x : 33, y : 47, entermap : 'island_cave', enterx : 33, entery : 69};
mappages["island"].features[1] = {name : 'Cave', x : 30, y : 40, entermap : 'island_cave', enterx : 43, entery : 0};
mappages["island"].features[2] = {name : 'Cave', x : 15, y : 48, entermap : 'null', enterx : 0, entery : 0};
mappages["island"].features[3] = {name : 'HillTower', x : 58, y : 33, entermap : 'null', enterx : 0, entery : 0};
mappages["island"].features[4] = {name : 'Cave', x : 13, y : 13, entermap : 'null', enterx : 0, entery : 0};
mappages["island"].features[5] = {name : 'Shrine', x : 56, y : 15};
mappages["island"].features[6] = {name : 'Shrine', x : 14, y : 76};
mappages["island"].features[7] = {name : 'LeftCastle', x : 41, y : 65};
mappages["island"].features[8] = {name : 'Castle', x : 42, y : 65, entermap : 'null', enterx : 0, entery : 0};
mappages["island"].features[9] = {name : 'RightCastle', x : 43, y : 65};
mappages["island"].features[10] = {name : 'BrokenShrine', x : 60, y : 63};


mappages["island"].npcs = new Array;

mappages["island"].desc = 'A Distant Island';
mappages["island"].music = 'Island';
mappages["island"].exitmap = '';
mappages["island"].exitx = '';
mappages["island"].exity = '';
mappages["island"].wraps = 'None';
mappages["island"].enterx = '14';
mappages["island"].entery = '76';
mappages["island"].seeBelow = '';
mappages["island"].lightLevel = 'bright';
mappages["island"].alwaysRemember = '1';
mappages["island"].linkedMaps = new Array("");
mappages["island"].scale = '0';

mappages["island_cave"] = new Object();
mappages["island_cave"].terrain = new Array;
 mappages["island_cave"].terrain[0] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["island_cave"].terrain[1] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["island_cave"].terrain[2] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw cf cf cf cf cf cf cw cw cw BK BK BK BK BK BK BK BK BK cw cw cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["island_cave"].terrain[3] = 'BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw cw cw cf cf cf cf cf cf cf cf cf cf cf cf cw cw cw BK BK BK BK BK cw cw cw cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["island_cave"].terrain[4] = 'BK BK BK BK BK BK BK BK cw cw cw cw cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cw cw BK BK BK BK cw cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["island_cave"].terrain[5] = 'BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cw cw cf cf cf cf cf cf cf cw BK BK BK BK cw cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["island_cave"].terrain[6] = 'BK BK BK BK BK BK BK cw cf cf cf cf cf cf cf cf cf cf cw cw cw cw cw cw cw cw cw cf cf cf cf cf cf cw BK BK BK cw cw cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["island_cave"].terrain[7] = 'BK BK BK BK BK BK BK cw cf cf cf cf cw cw cw cw cw cw cw BK BK BK BK BK BK BK cw cf cf cf cf cf cf cw BK BK BK cw cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["island_cave"].terrain[8] = 'BK BK BK BK BK BK BK cw cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cw cw BK BK cw cw cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["island_cave"].terrain[9] = 'BK BK BK BK BK BK BK cw cw cf cf cf cf cw cw BK BK BK BK cw cw cw cw BK BK BK cw cw cf cf cf cw cw BK BK BK cw cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[10] = 'BK BK BK BK BK BK BK BK cw cw cf cf cf cf cw cw BK cw cw cw cf cf cw BK BK BK BK cw cw cw cw cw BK BK BK BK cw cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[11] = 'BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cw cw cw cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[12] = 'BK BK BK BK BK BK BK BK BK cw cw cw cf cf cf cw cf cf cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[13] = 'BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cf cf cf cf cf cf cw cw cw BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ^^ ^^ ^^ ^^ BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[14] = 'BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cw cw cf cf cf cf cf cw cw cw cw BK BK BK BK BK BK BK BK cw cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ^^ ~~ ~~ ^^ BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[15] = 'BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cw cw cw cw cf cf cf cf cf cf cw BK BK BK BK BK BK BK cw cw cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ^^ ^^ ~~ ~~ ^^ BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[16] = 'BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw cw cw BK BK cw cw cf cf cf cf cf cw cw BK BK BK BK BK BK cw cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ^^ ~~ ~~ ~~ ^^ BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[17] = 'BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw BK BK BK BK BK cw cw cf cf cf cf cf cw cw BK BK BK cw cw cw cf cf cf cw cw BK BK BK BK BK BK BK cw cw cw cw cw cw cw cw cw ^^ ~~ ~~ ~~ ^^ BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[18] = 'BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cw cw BK BK BK BK BK BK cw cw cf cf cf cf cf cw cw cw cw cw cf cf cf cf cf cw BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cf ~~ ~~ ~~ ^^ ^^ BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[19] = 'BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cw cw BK BK BK BK BK BK BK cw cf cf cf cf cf cf cf cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK cw cf cf cf cf cf cf cf cf ~~ ~~ ~~ ~~ ^^ BK BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[20] = 'BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw BK BK BK BK BK BK BK cw cf cf cf cf cf cf cf cf cf cf cf cf cw cw cw BK BK BK BK BK BK BK BK cw cf cf cf cf cw cw cw ~~ ~~ ~~ ~~ cf cw cw BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[21] = 'BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cw BK BK BK BK BK BK BK cw cw cw cf cf cf cf cf cf cf cf cw cw cw BK BK BK BK BK BK BK BK BK cw cw cf cf cf cw cw ^^ ^^ ~~ ~~ ~~ cf cf cf cw cw BK BK BK BK BK BK';
mappages["island_cave"].terrain[22] = 'BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK cw cw cw cw cw cw cw cw cw cw BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cw cw ^^ ^^ ~~ ~~ ~~ ^^ cw cf cf cf cw BK BK BK BK BK BK';
mappages["island_cave"].terrain[23] = 'BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw BK ^^ ~~ ~~ ~~ ^^ ^^ cw cf cf cf cw BK BK BK BK BK BK';
mappages["island_cave"].terrain[24] = 'BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw BK ^^ ~~ ~~ ~~ ^^ BK cw cf cf cf cw BK BK BK BK BK BK';
mappages["island_cave"].terrain[25] = 'BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cw cw ^^ ^^ ^^ ^^ ^^ cw cw cf cf cf cw BK BK BK BK BK BK';
mappages["island_cave"].terrain[26] = 'BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cf cw BK BK BK BK BK cw cf cf cf cf cw BK BK BK BK BK BK';
mappages["island_cave"].terrain[27] = 'BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cf cw cw cw BK BK cw cw cf cf cf cf cw BK BK BK BK BK BK';
mappages["island_cave"].terrain[28] = 'BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cw BK BK cw cf cf cf cf cw cw BK BK BK BK BK BK';
mappages["island_cave"].terrain[29] = 'BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw BK BK BK BK BK BK BK BK BK cw cw cw cf cf cf cf cf cw BK cw cw cf cf cf cf cw BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[30] = 'BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw cf cf cw cw cw cw BK BK BK BK BK BK BK BK cw cf cf cf cf cw cw BK cw cf cf cf cf cf cw BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[31] = 'BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cw BK BK BK BK BK BK BK BK BK cw cw cw cf cf cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK cw cf cf cw cw cw BK BK cw cf cf cf cf cf cw BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[32] = 'BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cw BK BK BK BK BK BK BK cw cw cw cf cf cf cf cf cf cf cf cf cf cf cf cw BK BK BK BK BK BK BK cw cw cw cw BK BK BK BK cw cf cf cf cf cw cw BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[33] = 'BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cw cw BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cf cf cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw BK BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[34] = 'BK BK BK BK BK BK BK BK BK cw cw cw cw cf cf cf cw BK BK BK BK BK BK BK cw cf cf cf cf cf cf cw cw cw cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw BK BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[35] = 'BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cw BK BK BK BK BK BK cw cw cf cf cf cf cf cw cw BK cw cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cw cw BK BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[36] = 'BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cw cw BK BK BK BK BK cw cf cf cf cf cf cw cw BK BK cw cw cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cw BK BK BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[37] = 'BK BK BK BK BK BK cw cw cf cf cf cf cf cw cf cf cf cw BK BK BK BK cw cw cf cf cf cf cw cw BK BK BK BK cw cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[38] = 'BK BK BK BK BK cw cw cf cf cf cf cf cf cf cf cf cf cw BK BK BK BK cw cf cf cf cf cf cw BK BK BK BK BK cw cw cf cf cf cf cf cf cw cw cw cw cw BK BK BK BK BK BK cw cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[39] = 'BK BK BK BK BK cw cf cf cf cf cf cw cf cf cf cf cf cw BK BK BK cw cw cf cf cf cf cw cw BK BK BK BK BK BK cw cw cw cf cf cf cf cf cf cf cf cw cw cw BK BK cw cw cw cf cf cf cw cw cw cw cw cw cw cw cw BK BK BK BK';
mappages["island_cave"].terrain[40] = 'BK BK BK BK BK cw cf cf cw cf cf cf cf cf cf cf cw cw BK cw cw cw cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cf cf cf cf cf cw cw cw cw cf cf cf cf cf cf cf cf cf cf cf cf cf cw cw BK BK BK';
mappages["island_cave"].terrain[41] = 'BK BK BK BK BK cw cf cf cf cf cf cf cf cf cf cf cw cw cw cw cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cw BK BK BK';
mappages["island_cave"].terrain[42] = 'BK BK BK BK BK cw cw cf cf cf cf cf cf cf cf cw cw cw cf cf cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cf cf cf cf cw cw cw cw cw cw cw cw cf cf cf cf cw BK BK BK';
mappages["island_cave"].terrain[43] = 'BK BK BK BK BK BK cw cw cf cf cf cf cw cf cf cw cw cw cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK cw cf cf cf cf cw cw BK BK';
mappages["island_cave"].terrain[44] = 'BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cw cw cf cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw cw cw cw cw cw cw cw cf cf cf cf cf cw cw BK BK BK BK BK BK BK cw cw cf cf cf cf cw BK BK';
mappages["island_cave"].terrain[45] = 'BK BK BK BK BK BK BK BK cw cw cw cw cf cf cf cf cf cf cf cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK cw cw cf cf cw cw cf cf cw BK BK BK cw cw cf cf cf cf cw cw BK BK BK BK BK BK BK BK cw cw cf cf cf cw cw BK';
mappages["island_cave"].terrain[46] = 'BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cw cf cf cf cw cw BK BK BK BK BK BK BK BK cw cf cf cf cf cf cf cf cw BK BK BK BK cw cw cf cf cf cf cw BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw BK';
mappages["island_cave"].terrain[47] = 'BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cw cw cw cf cf cf cf cw cw BK BK BK BK BK BK BK cw cf cf cf cf cf cf cf cw BK BK BK BK cw cw cf cf cf cf cw cw BK BK BK BK BK BK BK BK cw cw cf cf cf cw cw';
mappages["island_cave"].terrain[48] = 'BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cw cw BK cw cf cf cf cf cf cw cw cw BK BK BK BK cw cw cf cf cf cw cf cf cf cw BK BK BK cw cw cf cf cf cf cf cf cw cw BK BK BK BK BK BK cw cw cw cf cf cf cf cw';
mappages["island_cave"].terrain[49] = 'BK BK BK BK BK BK BK BK BK cw cw cw cf cf cf cf cf cw BK BK cw cw cf cf cf cf cf cf cw cw cw cw cw cw cf cf cf cf cw cw cw cw cw BK BK BK cw cf cf cf cf cf cf cf cf cw BK BK BK BK BK cw cw cf cf cf cf cf cf cw';
mappages["island_cave"].terrain[50] = 'BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cw cw BK BK BK cw cw cf cf cf cf cf cf cf cf cw cw cf cf cf cf cw cw BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cf cw BK BK BK BK BK cw cf cf cf cf cf cf cw cw';
mappages["island_cave"].terrain[51] = 'BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw cw BK BK BK BK BK cw cw cw cf cf cf cf cf cf cf cf cf cf cf cf cw BK BK BK BK BK BK BK cw cf cf cf cf cf cf cf cf cw cw BK BK BK BK cw cw cf cf cf cf cf cf cw BK';
mappages["island_cave"].terrain[52] = 'BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cw BK BK BK BK BK BK BK BK cw cw cw cw cf cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK cw cw cw cf cf cf cf cf cf cf cw BK BK BK BK cw cf cf cf cf cf cf cw cw BK';
mappages["island_cave"].terrain[53] = 'BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cw cw cw BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cf cf cf cw BK BK BK BK cw cf cf cw cf cf cf cw BK BK';
mappages["island_cave"].terrain[54] = 'BK BK BK BK BK BK BK BK cw cw cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw cw cw BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cw cw cw cw cw BK BK BK BK cw cw cw cw cw cw cw cw BK BK';
mappages["island_cave"].terrain[55] = 'BK BK BK BK BK BK cw cw cw cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw cw cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[56] = 'BK BK BK BK BK cw cw cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cf cf cf cf cf cf cf cf cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[57] = 'BK BK BK BK BK cw cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK cw cw cw cw cw BK BK BK BK BK BK BK BK BK BK cw cw cw cf cf cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[58] = 'BK BK BK BK BK cw cf cf cf cf cw cw BK BK BK BK BK BK BK BK cw cw cf cf cf cw BK BK BK BK BK BK BK cw cw cw cw cf cf cf cf cf cf cf cf cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[59] = 'BK BK BK BK BK cw cf cf cf cf cw BK BK BK BK BK BK BK BK cw cw cf cf cf cf cw BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cw cw cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[60] = 'BK BK BK BK BK cw cf cf cf cw cw BK BK BK BK BK BK BK cw cw cf cf cf cf cf cw BK BK BK BK BK BK cw cf cf cf cf cf cf cw cw cw cw cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[61] = 'BK BK BK BK BK cw cf cf cf cw cw BK BK BK BK BK BK cw cw cf cf cf cf cf cw cw BK BK BK BK BK BK cw cf cf cf cf cw cw cw BK BK cw cw cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[62] = 'BK BK BK BK BK cw cf cf cf cf cw cw cw BK BK BK BK cw cf cf cf cf cf cw cw BK BK BK BK BK BK BK cw cf cf cw cw cw BK BK BK BK BK cw cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[63] = 'BK BK BK BK BK cw cf cf cf cf cf cf cw BK cw cw cw cw cf cf cf cf cw cw BK BK BK BK BK BK BK BK cw cf cf cw BK BK BK BK BK BK BK cw cw cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[64] = 'BK BK BK BK BK cw cw cf cf cf cf cf cw cw cw cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK cw cw cf cf cw BK BK BK BK BK BK cw cw cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[65] = 'BK BK BK BK BK BK cw cw cw cf cf cf cf cf cf cf cf cf cf cw cw cw BK BK BK BK BK BK BK BK BK cw cf cf cf cw BK BK BK BK BK BK cw cf cf cw cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[66] = 'BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK cw cf cf cw cw BK BK BK BK BK BK cw cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[67] = 'BK BK BK BK BK BK BK BK BK cw cw cw cf cf cf cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cw BK BK BK BK BK BK BK cw cw cw cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[68] = 'BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cw BK BK BK BK BK BK BK BK BK cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["island_cave"].terrain[69] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';

mappages["island_cave"].features = new Array;
mappages["island_cave"].features[0] = {name : 'WalkOn', x : 42, y : 0, walkonscript : 'exit_north'};
mappages["island_cave"].features[1] = {name : 'WalkOn', x : 43, y : 0, walkonscript : 'exit_north'};
mappages["island_cave"].features[2] = {name : 'WalkOn', x : 44, y : 0, walkonscript : 'exit_north'};
mappages["island_cave"].features[3] = {name : 'WalkOn', x : 32, y : 69, walkonscript : 'exit_south'};
mappages["island_cave"].features[4] = {name : 'WalkOn', x : 33, y : 69, walkonscript : 'exit_south'};


mappages["island_cave"].npcs = new Array;

mappages["island_cave"].desc = 'Cave';
mappages["island_cave"].music = 'Cave';
mappages["island_cave"].exitmap = 'island';
mappages["island_cave"].exitx = '33';
mappages["island_cave"].exity = '47';
mappages["island_cave"].wraps = 'None';
mappages["island_cave"].enterx = '';
mappages["island_cave"].entery = '';
mappages["island_cave"].seeBelow = '';
mappages["island_cave"].lightLevel = 'dark';
mappages["island_cave"].linkedMaps = new Array("");

// Added manually below

mappages["island_cave"].exit_north = function(feature) {
	feature.walkon = function(walker) {
		var themap=walker.getHomeMap();
		themap.setExitToX(30);
		themap.setExitToY(40);
//		alert("Changed exit to north.");
	}
}

mappages["island_cave"].exit_south = function(feature) {
	feature.walkon = function(walker) {
		var themap=walker.getHomeMap();
		themap.setExitToX(33);
		themap.setExitToY(47);
//		alert("Changed exit to south.");
	}	
}
