mappages["lighthouse1"] = {};
mappages["lighthouse1"].terrain = [];
 mappages["lighthouse1"].terrain[0] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["lighthouse1"].terrain[1] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["lighthouse1"].terrain[2] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww WW WW WW WW ww WW ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["lighthouse1"].terrain[3] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["lighthouse1"].terrain[4] = 'WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww WW ww WW WW WW WW WW WW WW WW WW WW WW';
 mappages["lighthouse1"].terrain[5] = 'WW WW WW WW WW ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww WW WW WW WW';
 mappages["lighthouse1"].terrain[6] = 'WW WW WW ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww uu uu ww uu uu uu ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww';
 mappages["lighthouse1"].terrain[7] = 'WW ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww uu uu uu ww ww ww ww ww ww uu uu uu ww uu ww ww uu uu uu ww ww ww ww ww ww ww ww ww ww';
 mappages["lighthouse1"].terrain[8] = 'ww ww ww ww ww ww ww ww ww ww ww ww ww ww uu uu uu uu ww ww ww ww !! !! !! !! ww ww ww ww ww ww ww ww ww ww ww uu uu uu ww ww ww ww ww ww';
 mappages["lighthouse1"].terrain[9] = 'ww ww ww ww ww ww ww ww ww ww ww uu uu ww uu ww ww ww ww ww ww ww !! !! !! !! ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww uu ww uu ww ww';
mappages["lighthouse1"].terrain[10] = 'ww ww ww ww ww ww ww ww uu uu uu ww ww ww ww ww ww ww ww ww uu uu !! !! !! !! ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww uu ww';
mappages["lighthouse1"].terrain[11] = 'ww ww ww ww ww uu uu uu uu ww ww ww ww ww ww ww ww ww uu uu ww ww !! !! !! !! uu uu ww uu ww uu ww uu ww uu uu uu ww ww ww ww ww ww ww ww';
mappages["lighthouse1"].terrain[12] = 'ww ww ww uu uu ww ww ww ww ww ww ww ww ww ww ww uu uu uu ww /b -b !! !! !! !! -b b` ww ww ww ww uu ww ww ww ww ww uu uu ww ww ww ww ww ww';
mappages["lighthouse1"].terrain[13] = 'ww ww uu uu ww ww ww ww ww ww ww ww uu uu uu uu ww ww /b -b ., ., ., ., ., ., ., ., -b b` ww ww ww ww uu ww uu uu ww ww uu uu ww ww ww ww';
mappages["lighthouse1"].terrain[14] = 'uu uu ww ww ww ww ww ww uu uu ww uu ww ww /b -b -b -b ., ., ., ., ., ., ., ., ., ., ., ., -b -b b` ww ww ww ww ww uu uu ww uu uu uu ww ww';
mappages["lighthouse1"].terrain[15] = 'uu ww ww ww ww ww uu uu ww ww ww ww ww /b ., ., ., ., ., ,% ., ., ., ., ., ., ., ., ., ., ., ,% ., -b -b -b -b -b b` ww ww ww ww ww uu ww';
mappages["lighthouse1"].terrain[16] = 'ww ww ww ww uu uu ww ww ww ww /b -b -b ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., -b -b -b b` ww uu uu';
mappages["lighthouse1"].terrain[17] = 'ww ww ww uu uu ww ww ww /b -b ., ., ., ., ., ., ,% ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ,% ., ., ., ., ., b` ww ww';
mappages["lighthouse1"].terrain[18] = 'ww uu uu uu ww ww ww /b ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ,% ., ., ., ., ., ., ., ., b` ww';
mappages["lighthouse1"].terrain[19] = 'uu uu ww ww ww /b -b ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., -b';
mappages["lighthouse1"].terrain[20] = 'uu ww ww /b -b ., ., ., ,% ., ,% ,% ., ., ., ., ., ., ., ., ., ., nn nn nn nn nn nn nn nn nn nn ., ., ., ., ., ., ., ., ., ., ,% ., ., .,';
mappages["lighthouse1"].terrain[21] = 'ww /b -b ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., nn nn nn nn nn nn nn nn nn nn nn nn nn ., ., ., ., ., ., ., ., ., ., ., ,%';
mappages["lighthouse1"].terrain[22] = '-b ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., nn nn ## ## #O ## ## ## ## #O ## ## nn nn ., ., ., ., ., ., ., ., ., ., .,';
mappages["lighthouse1"].terrain[23] = '., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., nn nn ## ## -= -= -= -= -= -= -= -= ## ## nn nn ., ., ., ., ., ., ., ., ., .,';
mappages["lighthouse1"].terrain[24] = '., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., nn nn ## -= -= -= -= -= -= -= -= -= -= ## nn nn ., ., ., ., ., ., ., ., ., .,';
mappages["lighthouse1"].terrain[25] = '., ., ., ,% ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., nn nn nn ## -= -= -= -= -= -= -= -= -= -= ## nn nn nn ., ., ., ., ., ., ., ., .,';
mappages["lighthouse1"].terrain[26] = '., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., nn nn nn ## -= -= -= -= -= -= -= -= -= -= ## nn nn nn ., ., ., ., ., ., ., ., .,';
mappages["lighthouse1"].terrain[27] = '., ,% ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., nn nn #O -= -= -= -= -= -= -= -= -= -= #O nn nn nn ., ., ., ., ., ., ., ., .,';
mappages["lighthouse1"].terrain[28] = '., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., nn nn ## -= -= -= -= -= -= -= -= -= -= ## nn nn nn ., ., ., ., ., ., ., ., .,';
mappages["lighthouse1"].terrain[29] = '., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., nn nn nn ## -= -= -= -= -= -= -= -= -= -= ## nn nn ., ., ., ., ., ., ., ., ., .,';
mappages["lighthouse1"].terrain[30] = '., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., nn nn nn ## -= -= -= -= -= -= -= -= -= -= ## nn nn nn ., ., ., ., ., ., ., ., .,';
mappages["lighthouse1"].terrain[31] = '., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., nn nn nn ## -= -= -= -= -= -= -= -= -= -= ## nn nn ., ., ., ., ., ., ., ., ., .,';
mappages["lighthouse1"].terrain[32] = '., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., nn nn ## ## -= -= -= -= -= -= -= -= ## ## nn nn nn ., ., ., ., ., ., ., ., .,';
mappages["lighthouse1"].terrain[33] = '., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., nn nn ## ## #O ## ## -= ## ## ## ## nn nn ., ., ., ., ., ., ., ., ., ., .,';
mappages["lighthouse1"].terrain[34] = '., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., nn nn nn ., ., ., ., ., nn nn nn nn ., ., ., ., ., ., ., ., ., ., ., .,';
mappages["lighthouse1"].terrain[35] = '., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., nn nn nn ., ., ., ., ., ., nn nn nn ., ., ., ., ., ., ., ., ., ., ., .,';
mappages["lighthouse1"].terrain[36] = '., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., .,';
mappages["lighthouse1"].terrain[37] = '., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., .,';
mappages["lighthouse1"].terrain[38] = '., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., .,';
mappages["lighthouse1"].terrain[39] = '., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., .,';
mappages["lighthouse1"].terrain[40] = '., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., .,';
mappages["lighthouse1"].terrain[41] = '., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., ., .,';

mappages["lighthouse1"].features = [];
mappages["lighthouse1"].features[0] = {name : 'DoorWindow', x : 28, y : 33};


mappages["lighthouse1"].npcs = [];

mappages["lighthouse1"].desc = "Lighthouse of Cabra";
mappages["lighthouse1"].music = 'Cave';
mappages["lighthouse1"].exitmap = 'darkunknown';
mappages["lighthouse1"].exitx = '69';
mappages["lighthouse1"].exity = '125';
mappages["lighthouse1"].wraps = 'None';
mappages["lighthouse1"].enterx = '26';
mappages["lighthouse1"].entery = '39';
mappages["lighthouse1"].seeBelow = '';
mappages["lighthouse1"].lightLevel = 'bright';
mappages["lighthouse1"].alwaysRemember = '0';
mappages["lighthouse1"].scale = '1';
mappages["lighthouse1"].enterscript = '';
mappages["lighthouse1"].entertestscript = '';
mappages["lighthouse1"].exitscript = '';
mappages["lighthouse1"].exittestscript = '';
mappages["lighthouse1"].returnmap = 'darkunknown';
mappages["lighthouse1"].returnx = '69';
mappages["lighthouse1"].returny = '74';
mappages["lighthouse1"].returninfused = '0';
mappages["lighthouse1"].linkedMaps = [""];
