mappages["darkunknown"] = {};
mappages["darkunknown"].terrain = [];
  mappages["darkunknown"].terrain[0] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
  mappages["darkunknown"].terrain[1] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW /. -- .` WW WW';
  mappages["darkunknown"].terrain[2] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW |. ^^ .| WW WW';
  mappages["darkunknown"].terrain[3] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW `. __ ./ WW WW';
  mappages["darkunknown"].terrain[4] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
  mappages["darkunknown"].terrain[5] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
  mappages["darkunknown"].terrain[6] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
  mappages["darkunknown"].terrain[7] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww WW WW WW WW WW ww ww WW WW ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww WW WW WW ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
  mappages["darkunknown"].terrain[8] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww WW WW ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
  mappages["darkunknown"].terrain[9] = 'WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww WW WW WW ww ww WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww WW WW ww ww ww ww ww ww ww ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[10] = 'WW WW WW WW WW WW WW WW WW WW ww ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww /. -- -- -- -- .` ww ww ww /. -- -- -- .` ww ww ww ww ww ww ww ww ww ww WW WW WW WW WW WW WW ww ww ww ww /. ;; ;; .` ww ww ww ww ww ww ww /. -, -- -, -, .` ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ^^ ^^ ^^ ww ww ww ^^ ^^ ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[11] = 'WW WW WW WW WW WW WW WW WW ww ww ww ^^ ^^ nn nn nn nn nn nn nn nn nn nn ^^ ww ww WW WW WW WW WW WW WW WW WW WW ww ww ww /. -- .. .. .. .. .. .. -- -- -- .. .. .. .. .. .` ww ww ww ww ww ww ww ww ww ww WW WW ww ww ww ww ww ww ww ww |; ;; ;; ;; .` ww ww ww ww ww /. ,, ,, ,, ,, ,, ,, -, .` ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[12] = 'WW WW WW WW WW WW WW WW WW ww ww ^^ ^^ nn nn nn nn ,, nn ,, ;; nn nn nn ^^ ^^ ww WW WW WW WW WW WW WW WW WW ww ww ww /. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. -- -- -- -- -- .` ww ww ww ww ww ww ww ww ww ww ww ww ww ww |; ;; ;; ;; ;; .` ww ww /. -- ,, .. ,, ,, ,, ;; ,, ,, ,, -, -, .` ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ^^ nn nn nn nn nn nn nn nn ^^ ^^ ^^ ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[13] = 'WW WW WW WW WW WW WW WW WW ww ww ^^ nn nn nn ,, ,, ,, ,, ;; ;; ,, .. nn nn ^^ ww ww WW WW WW WW WW WW WW WW ww ww ww |. .. .. .. .. .. .. .. ,, .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .` ww ww ww ww ww ww ww ww ww ww ww ww `. ;; ;; ;; ;; ;; .` ww |. ,, .. .. .. ,, ;; ;; ,, ,, ,, ,, ,, ,, .` ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW ww ww ^^ nn nn nn nn nn nn nn nn ^^ ^^ ^^ ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[14] = 'WW WW WW WW WW WW WW WW WW ww ww ^^ nn nn ;; ;; ;; ;; ;; ;; ;; ;; ;; .. nn ^^ ww ww WW WW WW WW WW WW WW WW ww ww ww |. .. .. .. .. .. ,, ,, ,, ,, .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. -- -- .` uu /. -, -, .` ww ww ww ww ww `. ;; ;; ;; ;; ;; -, .. .. .. ,, ,, ;; ;; ;; ;; ;; ,, ,, .. ,, ,, ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww nn nn nn nn rd nn nn nn nn nn ^^ ^^ ww ww ww ww WW WW WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[15] = 'WW WW WW WW WW WW WW WW ww ww ww ^^ nn ;; ;; ;; ;; ,, ;; ;; ;; ;; ,, .. ,, ^^ ww ww WW WW WW WW WW WW WW WW WW ww ww `. .. .. .. .. .. ,, ,, ,, ,, ,, .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. -- .. ,, ,, ,| ww ww ww ww ww ww `. ;; ;; ;; ;; ,, ,, .. ,, .. ;; ;; ;; ;; ;; ;; ,, ,, ,, ,, ./ ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww nn nn nn rd nn nn nn nn ;; ^^ ^^ ^^ ww ww ww ww WW WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[16] = 'WW WW WW WW WW WW WW WW ww ww ^^ ^^ ;; ;; ;; .. ;; ;; ;; ;; ;; ,, ,, .. .. ^^ ww ww WW WW WW WW WW WW WW WW WW ww ww ww `. __ .. .. .. .. ,, .. ,, ,, ,, .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ;; ;; ;; ;| ww ww ww ww ww ww ww `. ;; ;; ;; ;; ;; ,, .. .. ;; ;; ;; ;; ;; ;; ;; ,, ,, ./ ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww nn nn rd rd rd ;; ,, ;; ;; ,, ^^ ^^ ww ww ww ww ww WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[17] = 'WW WW WW WW WW WW WW WW ww ww ^^ ^^ ;; ,, ;; ;; ;; ;; ;; ,, ,, ,, ,, .. .. ^^ ww ww ww WW WW WW WW WW WW WW WW WW WW ww ww ww `. .. .. .. .. .. ,, .. rd rd rd rd rd rd .. .. .. .. ,, .. .. .. .. .. .. .. ,, ;; ;; ;; ;; .` ww ww ww WW ww ww ww |; ;; ;; ;; ;; ;; .. .. ;; ;; ;; ;; ;; ;; ;; ;; ./ ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww nn nn nn nn rd rd rd ;; ;; ;; ^^ ^^ ^^ ww ww ww ww ww ww WW WW WW WW WW';
 mappages["darkunknown"].terrain[18] = 'WW WW WW WW WW WW WW WW ww ww ^^ ^^ ;; ,, ,, ;; ;; ;; ;; ,, ,, .. .. .. .. ^^ ^^ ww ww WW WW WW WW WW WW WW WW WW WW WW ww ww ww |. .. .. .. .. .. ,, rd ,, ,, ;; ,, rd rd rd rd rd ,, ,, ,, .. .. .. .. ;; ;; ;; ;; ;; ;; .. .` ww ww WW WW ww ww |; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;| ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww nn nn ,, ;; ;; rd rd rd ;; ,, ;; ^^ ^^ ww ww WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[19] = 'WW WW WW WW WW WW WW WW WW ww ^^ ^^ ;; ,, ;; ;; ;; ,, ,, .. .. .. .. __ __ ^^ ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW ww ww `. .. .. .. .. .. ,, rd ,, ;; ;; ;; ,, .. ,, .. rd .. ,, .. .. .. .. ,, ;; ;; ;; ;; ;; ,, .. ./ ww ww WW WW ww ww `. ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; _; ./ ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww `. ;; ;; ;; ;; ,, rd ;; ;; ;; ^^ ^^ ww ww WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[20] = 'WW WW WW WW WW WW WW WW WW ww ww ^^ ;; ,, ;; ;; ;; ,, .. .. .. .. ^^ uu uu ^^ ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww `. .. .. .. .. rd rd ,, ^^ ;; ;; ;; ,, ,, ,, rd rd rd rd rd .. ;; ;; ;; ;; ;; ;; .. .. .| ww ww ww WW WW ww ww ww |. ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; .| ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww `. _; ;; ;; ;; rd ;; ;; ;; ;; ;| ww ww ww WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[21] = 'WW WW WW WW WW WW WW WW WW ww ww ^^ ^^ ;; ;; ;; ,, .. .. .. .. .. ^^ uu uu ^^ ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww `. .. .. .. rd ,, ,, ^^ ;; ;; ;; ;; ;; ;; .. ,, ,, ,, rd ,, ;; ;; ;; ;; ;; ;; ,, .. .| ww ww ww WW ww ww ww /. .. ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ./ ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww |. ;; ;; rd ;; ;; ;; ;; ;| ww ww ww WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[22] = 'WW WW WW WW WW WW WW WW WW ww ww ^^ ^^ ;; ;; ,, ,, .. .. .. .. ^^ ^^ uu ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww `. .. .. rd .. ,, ^^ ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; rd rd rd rd rd rd rd ;; ,, .. .. .` ww ww ww ww ww ww |. .. .. .. ;; ;; ;; ;; ;; ;; ;; ;; ./ ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww /. ;; ;; ;; rd ;; ;; ;; ;; .| ww ww ww WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[23] = 'WW WW WW WW WW WW WW WW WW ww ww ^^ ^^ ;; ;; ,, ,, .. .. ff ^^ ^^ ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww |. .. rd .. ^^ ^^ ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; rd rd rd rd .. .. .` ww ww ww ww /. rd .. .. .. ,, ;; ,, ;; ;; ;; ;; ;| ww ww ww ww WW WW WW WW WW ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww |; ;; ;; ;; rd ;; ;; ;; ;; ;; .` ww ww ww WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[24] = 'WW WW WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ,, ,, ,, ff ff ^^ ^^ ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww |. .. rd .. .. ^^ ^^ ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ^^ ;; ;; ;; ;; rd rd .. .. -- RR -- -- .. rd .. .. .. .. ,, ;; ;; ;; ;; ;; ;| ww ww ww ww ww ww WW WW ww ww ww WW WW WW WW WW WW WW WW WW WW ww ww WW WW WW ww ww ww ww ww ww |. ;; ;; ;; rd ;; ;; ;; ;; ;; ;; .` ww ww ww WW WW WW WW WW';
 mappages["darkunknown"].terrain[25] = 'WW WW WW WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww |. .. rd .. .. ^^ ^^ ^^ ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ^^ ^^ ;; ;; ,, nn rd rd .. .. RR .. .. .. rd .. .. .. .. ,, ;; ,, ;; ;; ;; ;; .` ww ww ww ww ww ww ww ww ww ww ww WW WW ww WW WW ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww |; ;; ;; ;; rd ;; ;; ;; ;; ;; ;; ;| ww ww WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[26] = 'WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW ww ww ww rd ww ww ww ww /. .. rd rd .. .. .. ^^ ^^ ^^ ;; ;; ;; ;; ;; ;; ;; ;; ;; ^^ ^^ ^^ ^^ ^^ ^^ nn nn .. rd .. .. RR .. .. .. rd .. .. .. .. .. ;; ;; ;; ;; ;; ;; ;; -; -; .` ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww |; ;; ;; ;; rd ;; ;; ;; ;; ;; .. ;| ww ww WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[27] = 'WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW ww ww /. rd .` ww ww /. .. rd rd .. .. nn ^^ ^^ ;; ^^ ^^ ;; ;; ;; ;; ;; ;; ;; ;; ^^ ^^ ^^ ^^ nn nn nn .. .. rd .. .. RR RR .. .. rd .. .. .. .. .. ;; ,, ;; ;; ;; ;; ;; ;; ;; ;; .` ww ww ww ww ^^ ww ww ww ww ww ww uu uu ww ww ww ww ww ww ww ww ww ww ww ww ww /. ;; ;; ;; ;; rd ;; ;; ;; ;; ;; .. .| ww ww WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[28] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww nn ww ww ww WW WW WW WW WW WW WW ww ww |. rd rd -- -- .. .. rd .. .. nn ^^ ^^ nn ;; ;; ;; ;; ;; ;; ;; ;; ;; nn ^^ ^^ ^^ nn nn nn nn nn .. .. rd .. .. .. RR RR .. rd .. .. .. .. .. ;; ;; ;; ;; ;; ;; ;; ;; ff .. .. -- -- ff ^^ ^^ ff ff ff ff ff .` uu uu uu /. -- -- .` ww ww ww ww ww ww /. -; ;; ;; ;; ;; ;; rd ;; ;; ;; ;; .. .. .| ww ww WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[29] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww nn ^^ nn ww ww WW WW WW WW WW WW WW WW ww `. .. rd rd rd rd rd rd nn nn nn ^^ ^^ ;; ;; ;; ;; ;; ;; ;; ;; nn nn ^^ ^^ ^^ nn nn nn nn nn .. .. .. rd rd rd rd rd RR rd rd rd rd rd .. .. ,, ;; ;; ,, ;; ;; ;; ff .. ff ff .. ff ff ^^ nn ff ff ff ff ff ff uu uu /. .. .. nn .. .` ww ww ww ww /. ;; ;; ;; ;; ;; rd rd rd ;; ;; ;; ;; .. .. .| ww ww WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[30] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww nn nn nn nn ww ww WW WW WW WW WW WW WW WW ww ww `. __ __ .. .. .. .. .. nn nn nn ^^ ^^ ^^ ;; ;; ;; ;; ;; ;; nn ^^ ^^ ^^ nn nn nn nn .. .. .. .. .. rd .. .. .. ,, RR .. .. .. .. rd .. .. .. ,, ;; ;; ;; ;; ,, ^^ ^^ ^^ ff ff nn ^^ ^^ ^^ ^^ nn nn nn ff ff uu uu nn .. nn nn nn .. -- -- -- -, ;; ;; .. ;; ;; ;; rd ;; ;; ;; ;; ;; .. .. .. ^^ ww ww WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[31] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww nn nn nn ww ww ww WW WW WW WW WW WW WW WW WW ww ww ww ww `. __ .. .. nn nn nn nn ^^ ;; ^^ ;; ;; ;; nn nn nn ^^ ^^ ^^ nn nn .. .. .. .. .. rd rd rd rd .. .. ,, .. RR ,, ,, .. .. rd rd rd rd .. ;; ;; ;; ,, ^^ ^^ ^^ nn ff ff nn ^^ ^^ ^^ ^^ ^^ ^^ nn ff ff uu uu nn nn nn nn nn nn .. .. .. .. ,, ,, .. ,, ;; ;; rd ;; ;; ;; ;; ;; .. .. .. ^^ ww ww WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[32] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww `. nn nn nn nn nn ^^ ;; ;; ;; ;; ;; nn ^^ ^^ ^^ ^^ nn nn nn .. .. .. .. .. rd .. .. .. .. .. ,, ff RR ,, ,, ,, .. .. .. .. rd rd ;; ;; ;; ,, ,, ,, ^^ ^^ nn nn ^^ ^^ uu uu uu uu ^^ ^^ nn ^^ uu uu nn nn nn nn nn .. .. .. .. .. .. .. rd rd rd rd rd ;; ;; ;; ,, .. .. .. .. ^^ ww ww ww WW WW WW WW WW';
 mappages["darkunknown"].terrain[33] = 'WW WW WW WW WW WW WW WW WW ww ww WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww nn nn nn nn ^^ ^^ nn ;; ;; ;; ;; ;; nn ^^ ^^ ^^ nn nn .. .. .. rd rd rd rd .. .. .. __ _, ./ ww ww ww `. _, __ __ .. .. .. rd rd .. ;; ;; ,, ,, ,, ^^ ^^ ^^ ^^ uu uu uu uu uu ^^ ^^ ^^ ^^ uu uu |; nn nn .. .. ,, .. .. .. .. .. rd rd ;; ;; ;; ;; ;; ;; ;; ;; ,, .. .. .. ^^ ww ww ww WW WW WW WW WW';
 mappages["darkunknown"].terrain[34] = 'WW WW WW WW WW WW WW WW ww ww ww WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ^^ ^^ ^^ ^^ ^^ nn ;; ^^ ;; ;; ;; ;; ;; ^^ ^^ nn nn .. .. .. rd .. .. .. .. __ ./ ww ww ww ww ww ww ww ww ww ww `. __ .. .. rd rd ;; ,, ;; ;; ,, ,, nn ^^ ^^ ^^ ^^ ^^ uu uu uu uu uu uu uu uu |; ;; ;; .. ,, ,, .. .. .. .. .. rd .. .. .. .. ;; ;; ;; ;; ,, .. .. .. .. ^^ ww ww WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[35] = 'WW WW WW WW WW WW WW WW WW ww WW WW WW WW WW WW WW WW WW WW WW WW ww ^^ ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ^^ ^^ ^^ nn ;; ;; ^^ ^^ ;; ;; ;; nn ^^ ^^ nn .. .. .. .. rd .. .. .. ./ ww ww ww ww ww ww ww ww ww ww ww ww ww ww `. .. .. rd ,, ;; ;; ;; ;; ;; .. .. nn nn ^^ ^^ uu uu uu uu uu uu uu /. .. ;; ;; ;; .. ,, .. .. ,, ,, ,, rd .. .. .. ;; ;; ;; ;; ;; .. .. .. .. .. ^^ ww ww WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[36] = 'WW WW WW WW WW WW WW WW ww ww WW WW WW WW WW WW WW WW WW WW WW ww ww ^^ ^^ ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww `. ^^ ^^ nn ;; ^^ ^^ nn ;; ^^ ^^ ^^ nn nn .. .. .. .. rd .. .. .| ww ww ww ww ww WW WW WW WW WW WW ww ww ww ww uu `. .. rd rd rd rd rd rd .. .. .. .. nn ^^ ^^ ^^ ^^ uu /. -- -- -- .. .. ,, ;; ;; ,, .. .. .. ,, ,, .. rd .. .. .. ;; ;; ;; ,, .. .. .. .. .. ^^ ^^ ww ww ww WW WW WW WW WW';
 mappages["darkunknown"].terrain[37] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ^^ ^^ ww ww ww ww ww WW WW WW WW WW WW WW ww WW WW WW WW ww ww ww ww ww ww ww ww ww ^^ ;; ;; ;; ^^ nn nn nn ^^ ^^ ^^ nn .. .. .. .. rd rd .. .. .. .` uu ww ww ww WW WW WW WW WW WW ww ww ww ww uu uu RR .. ,, ;; ;; ,, rd .. .. .. .. .. nn nn ^^ ^^ RR ,, .. .. .. .. .. .. ,, ,, ,, .. .. rd rd rd rd rd .. .. .. .. ;; ;; ,, .. .. .. .. ^^ ^^ ^^ ww ww ww WW WW WW WW WW';
 mappages["darkunknown"].terrain[38] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ^^ ^^ -; -, .` ww ww WW WW WW WW WW ww ww ww ww WW WW WW ww ww ww ww ww ww ww ww ww ^^ nn ;; ;; ^^ ^^ ^^ ^^ ^^ ^^ nn nn .. .. .. rd rd ,, .. .. .. .| uu ww ww ww ww ww ww ww ww ww ww ww ww uu /. -- .. .. .. .. .. .. rd .. .. .. .. .. .. .. nn ^^ RR ,, .. .. .. .. .. .. .. .. .. .. .. rd .. .. .. .. .. .. .. .. .. ;; .. .. .. .. .. ^^ ww ww ww ww WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[39] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww WW ww ww ww ^^ ^^ nn ;; ;; ,, .` ww ww ww WW WW ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ^^ ^^ ;; nn nn ^^ ^^ ^^ nn nn nn .. .. .. rd rd ,, ,, ,, .. .. .. .` uu uu uu ww ww ww ww ww uu uu uu /. RR .. .. .. .. .. .. .. .. rd rd rd rd .. .. .. RR ^^ ^^ RR RR RR RR RR nn nn .. .. .. rd rd rd rd .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ^^ ww ww ww WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[40] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww /. .. ^^ nn nn nn ;; ,| ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ^^ ^^ ww ^^ ^^ nn nn nn ^^ ^^ nn .. .. .. .. .. .. .. rd .. ,, ,, .. .. .. .. .. RR -- .` uu uu uu uu uu /. -- -- .. RR .. ,, .. .. .. .. .. .. .. .. .. rd .. .. RR RR RR RR RR ,, .. .. RR RR nn nn .. .. rd .. .. .. ,, ,, .. .. .. ,, .. .. .. .. .. .. .. .. .. ^^ ww ww WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[41] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww uu |. .. ^^ ^^ ^^ nn nn ,, .` ww ww ww ww ww ww ww ^^ ww ww ww ww ww ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ .. .. .. .. .. rd rd rd rd .. .. .. .. .. .. .. .. RR .. .. -- -- -- -- -- .. .. ,, .. RR RR .. ,, .. .. .. .. .. .. .. .. rd .. .. .. ,, ,, RR ,, .. .. .. nn nn nn nn .. .. rd .. .. ,, RR ff ,, .. .. ,, .. ,, .. .. .. .. .. .. .. ^^ ww WW WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[42] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww /. .. ;; ;; nn ^^ ^^ ;; ;; ;; -; .` ww ww ww /. -; ^^ ^^ ww ww ww ww ww ^^ ^^ ^^ ^^ nn nn nn .. .. .. .. .. .. .. .. .. .. rd rd .. .. .. .. .. .. .. .. ,, ,, .. RR .. ,, .. .. ,, .. .. .. .. .. ,, .. RR .. .. .. .. .. .. .. .. .. .. rd .. .. .. .. ,, RR .. .. .. .. .. nn nn .. rd rd rd .. .. ,, RR RR ,, ,, .. .. .. ,, .. .. ,, .. .. .. .. ^^ ww WW WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[43] = 'WW WW WW WW WW WW WW WW WW ww ww WW WW WW WW ww ww ww ww /. .. ;; ;; ;; ,, nn ^^ ^^ ;; ;; ;; ;; .` ww /. ;; ;; ^^ ^^ ^^ ^^ ww ww ww ^^ ^^ ^^ nn nn nn .. .. .. ,, .. ;; ,, .. .. .. .. rd .. .. .. .. .. .. .. .. .. .. RR RR RR .. ,, .. .. .. .. .. .. .. .. .. ,, RR .. .. ,, .. ,, .. .. .. ,, .. rd .. .. .. .. .. RR RR ,, .. .. .. .. .. .. rd .. .. .. ,, ff ,, RR ff ,, RR ,, .. .. ,, .. .. .. .. .. .. ^^ ww ww WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[44] = 'WW WW WW WW WW WW WW WW ww ww WW WW WW WW ww ww ww ww /. ;; ;; ;; ;; ,, .. nn ^^ nn ^^ ,, ,, ,, ;; -- ,, ,, .. .. ff ^^ ^^ ^^ ww ^^ ^^ ^^ ^^ nn nn .. .. .. .. .. ;; ;; ;; ,, .. .. .. rd .. ,, ,, .. .. .. .. .. ,, .. RR .. ,, .. .. ,, .. .. ,, .. ,, .. .. .. ,, RR RR RR .. .. ,, .. RR .. ,, .. rd rd rd .. .. .. .. RR RR RR RR .. .. .. .. rd .. .. .. ,, ,, ,, RR ,, .. RR ,, .. .. ,, ,, .. .. .. .. .. ^^ ww ww WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[45] = 'WW WW WW WW WW WW WW WW ww ww WW WW WW WW ww ww ww /. ,, ;; ;; ,, ,, .. .. ^^ ^^ nn nn nn .. .. ,, .. .. .. ff ff ff ^^ ^^ ^^ ^^ ^^ ^^ nn nn .. .. .. .. .. ,, ;; ;; ;; ;; ,, .. .. .. rd .. RR RR RR RR .. ,, .. .. RR RR .. ,, .. .. .. ,, .. ,, ,, .. .. .. .. ,, .. .. RR .. .. .. .. RR ,, ,, .. .. .. rd .. ,, .. ,, .. .. .. RR .. .. .. .. rd .. .. ,, ,, ,, ,, RR RR ff RR .. .. .. .. .. .. .. .. .. ^^ ^^ ww ww WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[46] = 'WW WW WW WW WW WW WW ww ww WW WW WW WW ww ww ww ww |, ;; ;; nn nn ^^ ^^ ^^ ^^ nn ,, ,, ,, ;; ,, ,, ,, ;; ;; ff ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn .. .. .. .. .. ;; ;; .. ,, ;; ;; ,, .. .. rd .. .. .. .. RR RR RR RR RR RR ,, ,, .. .. .. .. .. ,, ,, ,, ,, ,, .. .. ,, ,, ,, RR RR RR RR .. RR .. .. .. .. .. rd .. .. ,, .. .. .. .. RR RR RR .. ,, rd .. .. ,, .. ,, ,, ,, RR RR RR .. .. .. .. .. .. .. .. .. ^^ ^^ ww ww WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[47] = 'WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww /. ;; ;; ,, ;; ^^ ^^ nn nn nn nn ;; ,, ;; ;; ;; ;; ;; ;; ;; ;; ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn .. .. .. ,, ;; ;; ,, ,, ,, .. .. .. .. rd .. .. .. ,, .. .. .. .. .. RR .. ,, .. .. .. .. .. ,, ,, ,, ,, ,, .. .. .. .. .. .. RR .. RR RR RR RR RR ,, .. .. rd rd rd rd rd rd .. .. .. ,, RR ,, ,, rd .. .. .. ,, ,, .. ff RR ,, .. ,, ,, ,, .. ,, .. .. .. .. ^^ ww ww ww WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[48] = 'WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww /. ,, ;; ;; ;; ;; ;; ,, ;; ,, nn ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ^^ ^^ ^^ nn ^^ nn .. nn nn nn .. .. .. .. ,, ,, .. ,, .. .. .. .. .. .. .. rd rd .. .. .. ,, .. ,, .. .. RR .. .. .. ,, .. .. .. .. .. ,, .. .. .. .. ,, .. .. RR RR .. .. .. ,, .. RR .. ,, .. .. .. .. .. .. rd .. .. ,, ,, RR ,, ,, rd ,, .. .. .. .. .. ,, RR .. ,, ,, ,, ,, ,, ,, .. .. .. ^^ ^^ ww ww ww WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[49] = 'WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww |. ,, ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ,, ;; ;; ;; ;; ;; ^^ ^^ ^^ ^^ nn nn nn nn nn .. .. .. .. .. .. .. .. .. .. .. .. .. ,, ,, ,, .. .. rd .. .. .. .. .. ,, .. RR RR RR RR .. .. .. .. .. .. .. .. .. .. .. .. ,, .. RR RR .. ,, .. .. .. ,, RR RR .. .. .. .. .. .. .. rd .. ,, ,, ,, RR ,, ,, rd ,, ,, .. .. .. .. .. RR ,, ,, ,, .. ,, ,, .. .. .. .. ^^ ^^ ww ww WW WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[50] = 'WW WW WW WW WW WW WW WW WW WW ww ww ww ww /. ,, ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ,, ,, ;; ;; ;; ;; ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn .. .. ,, .. ,, .. .. ,, .. .. .. .. .. ,, ,, ,, .. .. .. rd .. .. .. .. .. .. RR RR .. .. RR .. ,, ,, .. .. .. .. .. .. .. .. .. .. .. RR .. .. ,, .. .. .. .. .. ,, .. .. .. .. .. .. .. rd .. ,, ,, .. ,, ,, rd rd ,, .. .. .. .. .. ./ uu `. ,, .. .. .. .. .. .. .. .. ^^ ww ww WW WW WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[51] = 'WW WW WW WW WW WW WW WW WW WW WW ww ww ww |, ;; ,, ;; ;; ;; ,, ;; ;; ;; ;; ;; ;; .. .. ,, ,, ;; ;; ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn .. .. .. ,, .. ;; ,, .. .. .. .. .. .. ,, ,, ,, ,, .. .. .. rd rd .. ,, .. .. RR RR .. ,, .. RR RR .. .. ,, .. .. .. .. .. .. .. .. .. ,, RR .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. rd rd rd rd ,, ,, ,, rd ,, ,, ,, .. .. .. ./ uu ww uu `. __ .. .. .. .. .. .. .. ^^ ww WW WW WW WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[52] = 'WW WW WW WW WW WW WW WW WW WW ww ww ww /. .. ;; ;; ;; ;; ,, ,, ;; ;; ;; ;; ,, .. .. ,, ,, .. ;; ;; nn ^^ ^^ ^^ ^^ ^^ nn nn nn nn ,, ,, .. ;; ;; ;; .. .. .. .. .. ,, ,, ;; .. .. ,, .. .. .. rd .. .. .. RR RR .. .. ,, .. .. RR .. .. .. .. .. .. .. .. .. .. .. .. .. RR ,, .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ,, ,, ,, rd rd rd rd rd ,, .. ,, .. .. .| uu ww ww ww uu uu `. .. .. .. .. .. .. ^^ ww WW WW WW WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[53] = 'WW WW WW WW WW WW WW WW WW ww ww ww ww |. ,, ;; ;; ;; ;; ;; ;; ;; ;; ,, ,, .. .. ,, ,, .. .. ,, ;; ;; ^^ ^^ ^^ ^^ nn nn nn nn ,, ,, .. .. ;; ;; ;; .. .. .. .. .. ,, ;; ;; ,, ,, ,, ,, .. .. rd .. .. .. RR .. ,, .. ,, ,, .. RR RR .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ,, ,, rd ,, ,, ,, ,, .. .. .. .. .| uu ww ww ww ww ww /. .. .. .. .. .. .. ^^ ww ww WW WW WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[54] = 'WW WW WW WW WW WW WW WW WW WW ww ww ww |; ,, ;; ;; ;; ;; ;; ;; ;; ;; .. .. ,, ,, .. ,, .. .. ;; ;; ;; nn ^^ ^^ nn nn nn .. nn .. .. .. ,, ;; ,, .. .. .. .. .. ,, ;; ;; ;; ;; ,, .. ,, ,, .. rd rd .. .. RR .. .. .. .. .. .. .. RR .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. rd .. ,, .. .. .. .. .. .. .| ww ww ww ww ww ww |. .. .. .. .. .. .. ^^ ww ww WW WW WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[55] = 'WW WW WW WW WW WW WW WW WW WW WW ww ww |, ;; ;; ;; ;; ;; ;; ;; ;; ;; ,, ,, .. .. ,, .. .. ,, ;; ;; nn nn ^^ nn nn .. .. .. .. .. .. .. .. .. ,, ,, .. .. .. ,, ;; ;; ;; ;; ;; ;; ,, ,, .. .. .. rd .. ,, .. .. .. .. .. ,, .. .. .. .. .. .. .. .. ,, .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. nn nn nn nn nn nn nn nn .. .. .. .. rd .. .. .. .. .. nn .. .. .| ww ww WW WW ww ww `. .. .. .. .. .. .. ^^ ww ww WW WW WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[56] = 'WW WW WW WW WW WW WW WW WW WW WW ww ww |; ;; ,, ^^ ;; ^^ ;; ;; ,, .. .. ,, ,, .. .. ,, ,, ,, ^^ ^^ ^^ ^^ ^^ ^^ nn .. ,, .. .. .. .. .. .. .. .. .. .. .. ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; .. .. .. rd .. ,, .. .. .. .. ,, .. ,, .. .. .. .. .. ,, ;; ;; ;; .. .. .. .. .. .. .. .. .. .. .. .. .. nn nn ^^ ^^ ^^ ^^ ^^ ^^ nn .. .. .. .. rd .. .. .. .. nn nn nn .. ./ ww ww WW WW ww ww uu |. .. .. .. .. ^^ ^^ ww ww ww WW WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[57] = 'WW WW WW WW WW WW WW WW WW WW WW ww ww |; ;; ^^ ^^ ^^ ^^ ,, ;; .. .. .. .. .. ,, .. .. ,, .. ,, ^^ ^^ ^^ nn ^^ nn ,, ,, .. .. ,, .. .. .. .. .. .. .. .. ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ,, .. .. rd .. .. .. .. .. .. ,, .. .. .. .. .. .. .. ;; ;; ;; ;; ;; .. .. .. .. .. .. .. .. .. .. .. .. nn ^^ ^^ ^^ nn ^^ ^^ ^^ ^^ nn nn .. rd rd .. .. .. nn nn nn nn .| ww ww ww WW WW ww ww /. .. .. .. .. .. ^^ ^^ ww ww ww ww WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[58] = 'WW WW WW WW WW WW WW WW WW WW WW ww ww |. ,, ^^ ^^ nn .. ,, .. .. .. .. ,, .. .. .. .. .. nn nn nn ^^ ^^ nn nn .. .. .. .. .. .. .. .. .. .. .. .. .. ,, ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ,, ;; .. rd .. .. .. .. .. .. .. .. .. .. .. .. .. ;; ;; ;; ,, ;; ;; ;; .. .. .. .. .. .. .. .. .. .. nn nn nn nn nn .. nn nn nn ^^ nn nn rd rd .. .. .. .. nn nn nn nn .| ww ww ww ww WW ww ww |. .. .. .. .. .. ^^ ^^ ^^ ^^ ww ww ww WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[59] = 'WW WW WW WW WW WW WW WW WW WW WW ww ww `. ,, ^^ ^^ .. .. .. .. .. RR .. .. ,, .. .. .. .. .. nn nn nn ^^ ^^ nn .. .. .. ,, .. .. .. ,, .. .. .. .. .. ,, ;; ,, ;; ;; ;; ;; ;; ;; ;; ;; ;; ,, .. rd .. .. .. .. .. .. .. .. .. .. .. .. ;; ;; ;; ,, ;; ;; ,, ;; .. .. .. .. .. .. .. .. .. .. .. nn .. .. .. .. .. .. .. nn nn rd rd .. .. .. .. .. nn nn nn .. .| ww ww ww ww WW ww ww `. .. .. .. .. .. .. ^^ ^^ ^^ ww ww ww WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[60] = 'WW WW WW WW WW WW WW WW WW WW WW ww ww ww `. ^^ .. .. ,, .. .. ,, RR .. .. .. ,, ,, .. ,, .. RR RR nn nn nn nn ,, .. .. ,, ,, .. ,, .. .. .. ,, ;; ,, .. ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ,, rd .. .. .. .. .. .. .. .. .. .. ,, ;; ;; ;; ,, ;; ;; ,, ;; ;; ;; .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. rd .. nn nn .. .. .. .. nn .. .. .| ww ww ww ww WW ww ww ww `. .. .. .. .. .. .. ^^ ^^ ^^ ww ww ww WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[61] = 'WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ^^ .. ,, .. .. .. RR RR .. ,, .. .. .. RR RR RR RR nn nn ^^ nn .. .. .. ,, .. ,, .. .. .. .. .. ;; ;; ,, .. ,, ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ,, rd .. .. .. .. .. .. .. .. .. ,, ;; ;; ,, ;; ;; ;; ,, ;; ;; ;; ;; .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. rd rd rd rd rd .. nn nn nn .. .. .. .. .. .. .. .` ww ww ww WW WW ww ww ww |. .. .. .. .. .. .. ^^ ^^ ^^ ww ww WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[62] = 'WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ^^ ^^ .. .. .. ,, RR ,, .. ,, .. RR RR RR .. nn ^^ ^^ ^^ ^^ nn ,, .. .. .. ,, ,, .. .. .. .. ,, ;; ,, .. ,, .. ,, ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; .. rd .. .. .. .. .. .. .. .. .. ,, ;; ;; ;; ;; ,, ;; ;; ;; ;; ,, ,, ;; .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. rd .. .. .. nn nn nn nn nn nn nn .. .. .. .. .. .| ww ww WW WW WW WW ww ww |. .. .. .. .. .. .. .. ^^ ^^ ww ww WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[63] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ^^ ^^ .. ,, .. ,, RR ,, .. RR RR RR .. .. .. .. nn nn ^^ ,, ,, ,, .. .. .. .. .. .. .. .. .. .. ;; ,, .. ,, ,, rd ,, ;; ;; ;; ;; ;; ;; ,, ;; ,, .. rd .. .. .. .. .. .. .. .. ,, ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. rd .. .. .. .. nn nn nn ^^ ^^ ^^ .. .. .. .. .. .| ww ww WW WW WW WW ww ww |. .. .. .. .. .. .. .. ^^ ^^ ww ww WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[64] = 'WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww `. .. .. .. RR RR RR RR ,, .. ,, .. ,, .. .. .. nn .. .. .. .. .. .. .. .. .. .. .. .. .. ;; ;; .. .. ,, rd ;; ;; ;; ;; ;; ;; ;; ,, ;; ;; ,, rd .. .. .. .. .. .. .. ,, ;; ;; ,, ;; ;; ;; ;; ;; ;; ;; ;; ;; ,, ;; ;; ,, .. .. .. .. .. .. .. .. .. .. .. .. .. rd .. .. .. .. nn nn ^^ ^^ ^^ nn nn .. .. .. .. .| ww ww ww WW WW WW ww ww |. .. .. .. .. .. .. ^^ ^^ ww ww ww WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[65] = 'WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww |. ,, .. .. .. ,, RR ,, .. ,, ,, ,, ;; ;; .. .. .. .. .. .. .. .. ,, .. ,, rd rd rd rd rd rd rd rd rd rd rd ;; ;; ;; ;; ,, ,, ;; ;; ,, .. rd .. .. .. .. .. .. .. ,, ;; ,, ;; ,, ;; ,, ;; ;; ,, ,, ;; ;; ;; ;; ;; ;; .. .. .. .. .. .. .. .. .. .. .. .. .. rd .. .. .. .. .. nn ^^ ^^ nn nn nn nn .. .. .. .| uu ww ww ww WW WW ww ww |. .. .. .. .. .. .. ^^ ^^ ww ww WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[66] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww `. .. ,, ,, ,, .. RR .. ,, .. ;; ;; ;; ;; .. .. __ .. .. .. .. .. .. .. .. rd .. ,, ;; ;; ;; ;; ,, ;; ;; rd rd rd ;; ;; ;; ,, ;; .. .. .. rd .. .. .. .. .. .. .. ,, ;; ;; RR ;; ,, ,, ;; ,, ,, ,, ;; ;; ;; ,, ,, ;; ;; .. .. .. .. .. .. .. .. .. .. .. .. rd .. .. .. .. .. ^^ ^^ ^^ ^^ ^^ ^^ nn .. .. .. .. .` uu ww WW WW ww ww ww ^^ ^^ .. .. .. .. ^^ ^^ ww ww WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[67] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww `. .. .. .. .. RR .. ,, ;; ;; ;; ;; .. .. ./ ww `. _, .. .. .. .. .. .. rd .. ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; rd rd ;; ;; ;; ;; .. .. .. rd .. .. .. .. .. .. .. .. ;; ,, RR ;; ;; ,, ;; ;; .. ff ,, ;; ;; ;; ;; ;; ;; .. .. .. .. .. .. .. .. .. .. .. .. rd .. .. .. .. .. .. ^^ ^^ ^^ ^_ ^^ nn nn .. .. .. .. .` uu ww WW WW ww ww ^^ ^^ ^^ ^^ ff ff ^^ ^^ ww ww WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[68] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww /. .. ,, RR RR RR .. ;; ;; .. ,, .. .. .| uu ww ww uu `. .. ,, ,, .. ,, rd .. ;; ;; ,, ^^ ^^ ,, ;; ;; ;; ;; ;; rd rd rd rd rd rd rd rd rd rd .. .. .. .. .. .. .. ,, ;; RR RR ff ff ;; ,, ff RR ;; ;; ;; ,, ;; ;; ;; .. .. .. .. .. .. .. .. .. .. .. .. rd .. .. .. .. .. .. .. ^^ ^^ ^^ ^^ ^^ nn .. .. .. .. .| uu ww WW WW ww ww ^^ ff .. ff ff ff ,, .| ww ww ww WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[69] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww `. .. ,, RR .. ,, .. .. ;; ;; .. __ __ ./ ww ww ww ww ww |, ,, rd rd rd rd .. ,, ;; ^^ ^^ ^^ ^^ ;; ;; ;; ;; ;; ;; ;; ;; ;; ,, .. .. .. .. rd .. .. .. .. .. .. .. ,, ;; ,, RR RR ff ;; ff ff RR ff ;; ;; ;; ;; ;; .. .. .. .. .. .. .. .. .. .. .. .. .. rd .. .. .. .. .. .. .. .. ^^ ^^ ^^ ^^ ^^ .. ^^ .. .. .| ww ww WW WW ww ww ^^ .. ff ff .. ff ff .| ww ww ww WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[70] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww `. .. RR ,, ,, .. .. .. .. .| uu uu ww ww ww ww ww uu |, .. rd .. .. .. .. .. ,, ;; nn ^^ ^^ ^^ ^^ ;; ;; ;; ,, ;; ;; .. .. .. .. .. .. rd .. .. .. .. .. .. .. ;; ;; ;; ;; RR ,, ff ;; RR RR ff ;; ;; ;; ,, .. .. .. .. .. .. .. .. .. .. .. .. .. .. rd .. .. .. .. .. .. .. .. .. nn ^^ ^^ ^^ ^^ ^^ nn .. .| ww ww WW ww ww ww ^^ ff .. ff ff .. ,, ff ww ww WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[71] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww `. RR .. .. .. .. .. .. .. .` ww ww ww ww ww uu /. .. rd rd ,, ,, .. .. RR RR RR RR RR ^^ ^^ ^^ ^^ ;; ;; ,, ,, ,, .. .. ,, ,, .. .. rd rd .. .. .. .. .. ,, ;; ;; ;; ;; RR ,, ff ;; RR ff ,, ;; ;; ;; .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. rd rd rd rd rd .. .. .. .. .. .. nn ^^ ^^ ^^ ^^ ^^ .. .| ww ww WW ww ww ww ^^ nn .. ,, ff ff ff .| ww ww WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[72] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww `. .. ,, .. ,, .. __ ./ ww ww ww ww ww uu |. .. rd .. .. ,, RR RR RR .. nn ^^ ^^ ^^ ^^ ^^ ;; ;; ;; ;; ,, ;; ;; ;; .. ,, .. .. .. rd .. .. .. .. .. .. .. ,, ;; ;; RR ,, ff RR RR ff ;; ;; ,, .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. rd .. .. .. .. .. .. .. nn nn nn ^^ ^^ .. .| ww ww WW WW ww ww ^^ ^^ nn nn ^^ ^^ ff .| ww ww ww WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[73] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww |. ,, ,, .. ./ uu uu ww ww ww ww ww ww RR RR RR RR RR RR RR .. .. ,, ^^ ^^ ^^ ^^ ^^ ^^ ;; ;; ,, ;; ,, ;; ;; ;; ,, .. .. .. .. rd .. .. rd .. .. .. .. .. ;; ;; RR RR RR RR ff ff ;; ;; .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. rd .. .. .. .. .. .. nn nn nn nn ^^ ^^ .. .| ww WW WW WW ww ^^ ^^ ^^ ^^ nn ^^ ^^ ff ff ww ww ww ww WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[74] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww `. __ _, ./ ww ww ww ww ww ww ww ww ww |. .. rd .. RR .. ,, .. .. nn ^^ ^^ ^^ ^^ ;; ;; ;; ;; ;; ;; ;; ;; ;; ,, ,, ,, .. .. .. rd rd rd rd rd .. .. .. .. ,, ./ uu |, ,, ;; ;; ;; ;; ;; .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. rd .. .. .. .. .. .. .. .. nn ^^ ^^ ^^ .. .| ww ww WW WW ww ww ww ww ^^ nn nn ^^ ff ff .` ww ww ww WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[75] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww /. .. .. rd .. RR .. .. ,, nn ^^ ^^ ^^ ^^ ^^ ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; _; _, _, __ __ __ .. .. .. rd rd rd .. .. ./ uu /. ,, ;; ;; ;; ;; ;; ,, .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. rd .. .. .. .. .. .. .. .. ^^ ^^ ^^ ^^ .. .| ww ww ww WW WW ww ww ^^ ^^ ^^ nn ^^ ,, ff ,, .` ww ww WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[76] = 'WW WW WW WW WW WW WW WW WW WW WW ww ww ww WW WW ww WW ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww /. .. .. ,, rd .. RR RR nn ^^ ^^ ^^ ^^ ^^ ^^ ;; ;; ;; ;; ;; ;; ;; ;; ;; ,, ./ ww ww ww ww ww ww `. .. .. .. .. .. .. ./ uu uu |; ;; ,, ;; ;; ;; .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. rd .. .. .. .. .. .. .. nn ^^ ^^ nn ^^ nn .| ww ww ww WW WW ww ww ^^ ww ^^ ^^ ^^ ff ff .. ff ww ww WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[77] = 'WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww uu uu |. .. .. .. rd .. .. RR RR RR ^^ ^^ ^^ ^^ ;; ;; ;; ,, ;; ;; ./ `. _; _; ./ ww ww ww ww ww ww ww ww `. __ __ __ __ ./ uu uu uu |; ,, ;; ,, ;; ,, .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. rd .. .. .. .. .. .. .. nn ^^ ^^ nn nn nn nn ^^ ww ww WW WW WW ww ww ww ww ^^ ^^ .. ff ff ff ww ww WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[78] = 'WW WW WW WW WW WW WW WW WW WW ww ww uu uu ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww uu uu ww uu /. .. ,, .. .. rd .. .. nn ^^ ^^ ^^ ^^ ^^ ^^ ;; ,, ;; ;; ;; ;| ww ww ww ww ww ww ww ww ww WW ww WW ww ww ww uu uu uu uu uu uu uu |; ;; ;; ;; ,, .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. rd rd rd rd .. .. .. .. .. ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww ww ww WW WW ww ww ww ww ^^ ^^ ^^ ff ff ,| ww ww WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[79] = 'WW WW WW WW WW WW WW WW WW ww ww ww nn nn nn ww ww ww ww ww ww ww ww ww ww ww ww ww ww /. .` uu uu /. .. .. ,, .. .. rd .. .. .. ^^ ^^ ^^ ^^ ^^ ^^ ;; ;; ;; ;; ;; ./ ww ww ww ww ww ww WW WW WW WW WW WW WW ww ww ww ww ww uu uu uu uu `. _; ,, ,, .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. rd .. .. .. .. .. nn ^^ ^^ ^^ ^^ ^^ ww ww ww WW WW WW WW ww ww ww ^^ ^^ nn ff ff ff ww ww ww WW WW WW WW WW';
 mappages["darkunknown"].terrain[80] = 'WW WW WW WW WW WW WW WW WW ww ww ^^ ^^ ^^ ^^ ^^ nn nn ^^ ww ww ww ww ww ww ww ww /. -- .. .. -, -- ,, ,, .. .. .. .. rd ,, .. .. nn nn ^^ ^^ ^^ ^^ ^^ ;; ;; ;; ./ ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww ww ww `. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ,, ;; ;; ;; .. .. .. .. .. .. .. .. rd .. .. .. .. .. .. nn ^^ ^^ ^^ nn ww ww ww WW WW WW WW WW ww ww ww ^^ ^^ ^^ ^^ ^^ ww ww ww WW WW WW WW WW';
 mappages["darkunknown"].terrain[81] = 'WW WW WW WW WW WW WW WW WW ww nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn ww ww ww ww nn -- -- ;; ;; ,, ;; .. ,, ;; ;; ,, .. .. .. rd rd .. .. nn .. nn ^^ ^^ ^^ ^^ ^^ ;; ;| ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww `. __ __ .. .. .. .. .. .. .. .. .. .. .. .. .. ,, ;; ;; ;; ,, .. .. .. .. .. .. .. .. rd rd rd rd rd rd .. nn ^^ ^^ nn nn ww ww ww WW WW WW WW WW ww ww ww ww ^^ ^^ ^^ ^^ ww ww ww WW WW WW WW WW';
 mappages["darkunknown"].terrain[82] = 'WW WW WW WW WW WW WW WW WW ww ww ^^ ^^ nn nn nn ^^ ^^ ^^ ^^ ^^ RR ^^ ^^ ^^ nn nn nn ;; ;; ;; .. ;; ;; .. ,, .. .. .. ,, rd .. .. .. nn nn nn ^^ ^^ ^^ ^^ ^^ ^^ ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww WW ww ww ww ww `. __ .. .. .. .. .. .. .. .. .. .. ;; ;; ;; ;; ,, .. .. .. ;; ,, .. .. .. .. .. .. .. .. .. rd .. .. ^^ ^^ nn .| ww ww ww ww WW WW WW WW ww ww ww ww ww ^^ ^^ ww ww ww WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[83] = 'WW WW WW WW WW WW WW WW ww ww nn ^^ ^^ nn nn nn nn ^^ ^^ ^^ ^^ RR ^^ ^^ ^^ ^^ nn .. .. ;; ;; ;; .. .. ;; .. .. .. .. .. rd ,, .. nn nn nn nn ^^ ^^ ^^ ^^ ^^ ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww `. .. .. .. .. .. .. .. .. .. ,, ;; ;; ;; .. ,, .. ,, ;; ;; .. .. .. .. .. .. .. .. .. rd .. .. nn ^^ .. .. .` ww ww ww ww WW WW WW WW ww ww ww ww ww ww ww ww ww WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[84] = 'WW WW WW WW WW WW WW WW WW ww nn ^^ ^^ ^^ ^^ nn .. ^^ ^^ ^^ ^^ RR ^^ ^^ ^^ ^^ nn .. ,, ,, ,, ;; ;; ,, ;; ;; ,, .. .. .. rd .. .. nn .. nn nn nn ^^ ^^ ^^ ^^ ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww `. .. .. .. .. .. .. .. .. ,, ;; ;; ;; ,, .. ;; ;; ;; ;; .. .. .. .. .. .. ,, .. .. rd .. .. .. .. .. .. .. .` ww ww ww WW WW WW WW WW WW ww ww ww ww ww ww WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[85] = 'WW WW WW WW WW WW WW WW ww ww ww ^^ ^^ ^^ nn .. nn ^^ nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn .. ,, ;; ;; .. ,, ,, .. .. .. .. .. rd rd .. .. .. .. .. nn ^^ ^^ ^^ ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww `. .. .. .. .. .. ,, ,, ;; ;; ;; ;; RR ,, ;; ;; ;; ,, .. .. .. .. .. ,, RR .. .. rd rd rd .. .. .. .. .. .| ww ww ww WW WW WW WW WW WW WW WW ww ww ww WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[86] = 'WW WW WW WW WW WW WW WW WW ww ww ww ww nn ,, ,, .. .. nn nn ^^ ^^ ^^ ^^ ^^ nn nn nn .. .. ;; ;; ;; .. .. .. ,, .. .. ,, .. rd .. ,, .. .. nn nn nn ^^ ^^ ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww `. .. .. .. ;; ;; ;; ;; ;; ;; ,, RR ;; ;; ;; ,, ;; ,, .. .. .. .. .. RR ,, .. .. .. rd rd ,, ,, .. .. .| ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[87] = 'WW WW WW WW WW WW WW WW WW WW ww ww ww `. __ ,, ,, ,, .. ,, .. ^^ ^^ ^^ ^^ nn nn nn nn .. .. ;; ;; .. .. ,, ,, .. .. .. .. rd ,, .. .. .. .. nn nn ^^ ^^ ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww |. .. ;; ;; ;; ;; ,, _; ,, ;; RR ;; ;; ;; ;; ;; .. .. .. .. .. .. RR .. .. .. .. ,, rd .. ,, ,, .. .| ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[88] = 'WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww `. ,, ,, ,, .. ,, nn nn nn nn .. nn nn .. .. .. .. .. .. ,, ,, ,, ,, .. .. .. rd .. .. ,, .. .. nn nn ^^ ^^ ^^ ^^ ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww |; ;; ;; ,, ;; ;; ./ uu RR RR RR ;; ;; ;; .. .. .. .. .. .. .. RR RR .. .. .. ,, ,, rd ,, .. .. .. .| ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[89] = 'WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww `. .. .. .. ,, .. nn nn nn .. .. .. .. .. .. .. .. ,, .. ,, ,, ,, ,, .. .. rd .. .. .. .. .. .. .. nn ^^ ^^ ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww |, ;; ;; _; _, ./ uu /. ;; ;; ;; ,, ;; ,, .. .. .. .. .. ,, ,, RR .. ,, RR RR .. ,, rd ,, .. .. .. ;| ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[90] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww |, ,, ,, .. .. ,, .. nn .. .. .. .. .. .. ,, .. .. .. ,, ,, .. .. .. .. rd rd rd rd rd rd rd rd rd ./ ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww `. _; ./ uu uu uu uu |; ,, ;; ,, ;; ;; ;; .. .. .. .. .. ,, .. RR RR RR RR ,, ,, .. rd .. .. .. ;; ;| ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[91] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww `. __ ,, ,, ,, .. .. .. .. .. .. .. .. ,, ,, ,, ,, .. .. ,, .. ,, ,, ,, rd .. .. .. .. .. .. .. .| ww ww ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW ww ww ^^ ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww uu uu uu /. ;; ,, ;; ,, ;; ;; ,, .. .. .. .. .. .. RR RR .. .. .. .. ,, ,, rd ,, .. ;; ;; ,, .` ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[92] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww |, .. .. .. .. .. .. .. .. .. .. .. ,, ,, .. ,, .. .. .. ,, .. ,, rd .. .. .. __ __ __ __ ./ ww ww ww ww ^^ ww ww ww ww WW WW WW WW WW ww ww ww ww ww ^^ ^^ ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww uu uu /. -; ;; ;; ;; ;; ;; ;; ,, .. .. ,, ,, RR RR RR RR .. ,, ,, .. .. .. rd rd .. .. ,, ;; ,, ;; .` ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[93] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww `. .. .. ,, .. .. .. .. .. .. .. .. .. .. .. ,, ,, ,, .. .. rd rd rd .. .. ./ ww ww ww ww ww ww ww ww ^^ ^^ ww ww ww ww ww WW WW WW WW ww ww ww ww ^^ ^^ ^^ ^^ ww ww ww WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww uu /. ,, ;; ;; ,, ;; ;; ;; ;; .. .. ,, .. RR RR ,, ,, .. ,, ,, .. .. .. rd rd .. ,, .. .. ;; ;; ,, ;; .` ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[94] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww `. ,, .. .. .. .. .. .. .. .. .. .. .. ,, ,, ,, ,, ,, .. rd ,, .. .. .| ww ww ww ww ww ww ww ^^ ww ^^ ^^ ^^ ww ww ww ww ww ww ww ww ww ww ww ^^ ^^ ^^ ^^ ^^ ^^ ww ww ww WW WW WW WW WW WW WW WW ww ww ww ww ww ww /. -; ;; ;; ;; ;; ;; .. .. .. .. .. .. .. RR RR ,, .. .. .. .. .. .. .. .. rd ,, ,, .. ,, ;; ;; ;; ;; ;; ,, .` ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[95] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww `. .. .. .. ,, ,, ,, .. .. .. .. .. .. ,, .. ,, ,, ,, rd .. .. __ ./ ww ww ww ww ww ww ww ^^ ^^ ^^ nn ^^ ^^ ww ww ww ww ww ww ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww ww WW WW WW WW WW WW WW ww ww ww ww ww ww /. ;; ;; ;; ;; ;; .. .. .. .. .. .. .. ,, RR RR .. ,, .. .. .. .. .. .. ,, .. rd ,, .. ,, ;; ;; ;; ;; ;; ;; ;; ;| ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[96] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww `. .. .. .. ,, ,, .. .. .. .. .. .. .. .. ,, ,, rd rd .. ./ ww ww ww ww WW WW ww ww ww |. nn nn nn ^^ ww ww ww ww ww ww ww ww ww ww ^^ ^^ ^^ nn ^^ ^^ ww ww ww ww WW WW WW WW WW WW ww ww ww ww ww /. RR ;; ;; ;; ;; ,, ,, .. .. .. .. .. .. ,, ,, RR .. ,, .. .. .. .. .. .. .. .. .. rd .. .. .. ;; ;; ;; ;; ;; ;; ;; ;| ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[97] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww |. .. .. ,, .. .. .. .. .. .. .. .. .. .. .. rd .. .| ww ww ww ww WW WW WW ww ww ww nn nn nn nn ^^ ^^ ww ww ww ww ww WW WW ww ww ww ^^ ^^ nn ^^ ww ww ww ww ww ww WW WW ww ww ww ww ww ww ww /. ,, RR ;; ;; ;; ,, .. .. .. .. .. .. .. .. .. __ RR .. .. .. .. .. ,, .. .. .. .. .. rd .. .. ,, ;; ;; ;; ;; ;; ;; ;; ;| ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[98] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww /. ,, .. .. .. .. .. .. .. .. ,, .. .. .. .. .. rd .. .| ww ww ww WW WW WW ww ww ww ww |. nn nn nn nn .| ww ww ww ww WW WW WW WW ww ww ww ww uu ww ww ww ww ww ww ww ww ww ww ww ww ww ww /. -; ;; ;; RR RR .. .. .. .. .. .. .. .. .. .. .. ./ ww ww `. .. .. .. ,, ,, ,, .. .. .. .. rd ,, ,, ;; ;; ;; ;; ;; ;; ;; ;; ;; .` ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["darkunknown"].terrain[99] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww |. .. .. .. .. .. .. ,, RR RR .. .. .. .. .. .. rd .. .| ww ww ww WW WW WW ww ww ww nn nn nn .. nn nn nn ww ww ww ww WW WW WW WW ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww /. ,, ,, ;; ,, ,, RR RR RR .. .. ,, .. .. .. .. __ ./ ww ww ww ww `. .. .. ,, ,, .. .. ,, ,, .. rd ,, ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; .| ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[100] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww /. .. .. .. .. ,, .. ,, .. RR ff ,, .. .. .. .. .. rd .. .| ww ww ww ww WW ww ww ww /. nn nn nn nn nn nn .. -- .` ww ww ww WW WW WW WW WW ww ww ww ww ww WW WW WW ww ww ww ww ww ww /. -- ,, .. .. .. .. .. RR ,, RR .. ,, ,, ,, .. .. ./ ww ww ww ww ww ww ww |. .. .. .. .. .. .. ,, ;; rd rd rd rd rd ;; ;; ;; ;; ;; ;; .. .. .` ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[101] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww |. .. ,, ,, .. .. ff RR RR RR RR RR .. .. .. .. .. rd .. .. .` ww ww ww ww ww ww ww |. .. nn .. nn .. nn nn .. .| ww ww ww ww WW WW WW WW WW WW ww WW WW WW WW WW WW ww ww ww ww /. ,, ,, .. .. .. .. RR RR RR ,, RR RR RR ,, ,, ,, ./ ww ww ww ww ww ww ww ww `. __ .. .. .. .. .. ;; ;; ;; ;; ;; ;; rd rd rd ;; ;; ;; ;; .. .. .| ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[102] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww RR RR RR RR RR ff RR RR ,, ff ff ,, .. ,, .. .. .. rd rd .. .. .` ww ww ww ww ww /. .. ,, .. .. .. .. .. .. .. .. .` ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww /. .. .. ,, ,, .. .. ,, RR ,, ,, ,, ,, .. RR RR RR RR ww ww ww ww ww ww ww ww ww ww ww `. ,, ,, ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; rd ,, ,, ;; ;; ;; .. .. .` ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[103] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww |. ,, ,, ff RR RR RR .. ff ,, .. .. ,, .. .. .. .. .. rd rd .. .| ww ww ww ww /. .. .. ,, .. ,, .. ,, .. ,, .. ,, ./ ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww |. ,, ,, ,, .. .. .. RR RR .. ,, ,, ,, .. .. ,, ,, ./ ww ww ww ww ww ww ww ww ww ww ww /. ;; ;; ;; ;; _; _; _; _; _; _, .. ;; rd .. ,, ;; ;; ;; .. .. .. .` ww ww ww ww WW WW WW WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[104] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww /. .. ,, .. .. .. ,, RR RR RR RR .. ,, ,, .. .. .. .. .. .. rd .. .. .` ww /. -- .. .. ,, .. .. .. ,, ,, ,, ,, .. .| ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww |. .. ,, .. ,, .. .. RR .. .. .. ,, ^^ ^^ ^^ ^^ ^^ ww ww ww ww ww ww WW ww ww ww ww /. ;; ;; ;; ;; ./ ww ww ww ww ww ww |. rd rd .. nn ^^ ;; .. .. .. .. .| ww ww ww ww WW WW WW WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[105] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww /. .. .. .. .. .. .. .. ,, .. ff RR RR RR .. .. .. .. .. .. .. rd .. .. .. -- ,, .. .. .. .. .. ,, .. .. .. .. .. .. .| ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww |, .. .. .. .. .. ,, RR ,, ,, .. .. ^^ ;; ^^ ^^ ^^ ^^ ww ww ww ww WW WW WW ww ww ww |; ;; ;; ;; ;| ww ww ww ww ww ww ww `. .. .. .. nn ^^ ;; ;; .. .. .. ./ ww ww ww ww WW WW WW WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[106] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww |. .. ,, .. ,, .. .. .. .. .. .. ,, ,, .. .. .. .. .. .. .. .. rd .. .. .. .. .. ,, .. .. ,, ,, .. .. ,, ,, ,, .. ,, .. .` ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ RR ,, .. ^^ ^^ ^^ ;; ;; ;; ^^ ^^ ^^ ww ww ww ww WW WW ww ww /. ;; ;; ;; ;; ;| ww ww ww ww ww ww ww ww `. .. .. nn ^^ ^^ ^^ .. .. .. .` ww ww ww ww ww WW WW WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[107] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww /. .. .. ,, .. .. .. .. .. ,, ,, .. .. ,, .. .. .. .. .. .. .. .. rd rd rd .. .. .. .. .. .. ,, .. ,, .. .. .. .. .. ,, ,, .. .` ww ww ww WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ^^ ;; ^^ ;; ;; ^^ ^^ ^^ ,, ,, ^^ ;; ^^ ^^ ;; ;; ;; ^^ ^^ ^^ ww ww ww WW ww ww ww |; ;; ;; ;; _; ./ ww ww ww ww ww ww ww ww ww nn nn ^^ ^^ ^^ nn .. .. .. .. .` ww ww ww ww WW WW WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[108] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww /. .. .. .. .. .. ,, ,, .. .. ,, .. .. .. .. .. .. .. .. .. .. .. .. .. .. rd .. ,, ,, ,, .. .. .. .. .. .. ,, ,, .. RR RR RR RR RR ww ww ww ww WW WW WW WW WW WW WW WW WW ww ww ww ^^ ^^ ^^ ;; ;; ;; ;; ;; ;; ^^ ^^ ^^ ^^ ;; ;; ;; ;; ;; ,, .. ^^ ^^ ww ww ww ww ww ww ww |; ;; ;; ./ ww ww ww ww ww WW ww ww ww ^^ nn nn ^^ ^^ ^^ nn nn .. .. .. .. .. .` ww ww ww WW WW WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[109] = 'WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww |. .. .. .. ,, ,, .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ,, .. rd rd rd ,, .. RR RR RR RR RR .. .. RR RR RR .. .. .. .. .` ww ww ww WW WW WW WW WW WW WW WW ww ww ww ww ^^ ;; ;; ^^ ;; ;; ;; ;; ^^ ^^ ;; ;; ^^ ^^ ;; ;; ;; ,, .. .. ^^ ww ww ww ww ww ww ww ww `. _; ./ ww ww ww ww WW WW WW ww ww ww ^^ ^^ ^^ ^^ ^^ nn .. .. .. .. .. .. .. .| ww ww ww WW WW WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[110] = 'WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww /. .. .. .. .. ,, ,, .. .. ;; .. .. .. .. .. .. .. .. .. .. .. .. .. .. ,, ,, .. ,, rd rd .. .. .. ,, .. RR RR RR RR .. .. ,, ;; .. .. .. .` ww ww ww WW WW WW WW WW WW WW ww ww /. -- .. .. ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ,, ,, ^^ ^^ ^^ ^^ ww ww ww WW WW ww ww ww ww ww ww ww ww ww WW WW WW ww ww ww ^^ ^^ ;; nn nn nn .. ,, .. .. .. .. .. ./ ww ww ww WW WW WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[111] = 'WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww /. .. .. .. .. nn nn nn .. ;; ;; ;; .. .. .. .. .. .. .. .. .. .. .. ,, .. .. .. .. .. .. rd .. ,, ,, .. .. .. .. RR .. .. ,, ;; ;; .. .. .. .| ww ww ww WW WW WW WW WW WW ww ww ww |. .. .. ,, ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ,, .. .. ^^ ^^ ^^ ww ww ww ww WW WW WW ww ww ww ww ww ww WW WW WW WW WW ww ww ww ^^ ^^ ;; ;; nn .. .. ,, ,, .. .. .. .| ww ww ww ww ww WW WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[112] = 'WW WW WW WW WW WW WW WW WW ww ww ww /. -- -- .. .. .. nn nn nn ^^ ^^ ;; ;; ;; ;; .. .. .. .. .. .. .. .. .. .. ,, ,, ,, .. ;; .. .. .. rd .. .. .. .. RR RR RR RR .. ;; ,, ;; ,, .. .. .. .| ww ww ww WW WW WW WW WW WW ww ww ww |. ,, ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ,, ^^ ^^ ^^ ww ww ww ww ww WW WW WW WW WW ww ww ww ww WW WW WW WW WW WW ww ww ww ww ^^ nn ;; ;; .. .. .. .. .. .. .. .| ww ww ww ww ww WW WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[113] = 'WW WW WW WW WW WW WW WW WW ww ww ww |. .. .. .. .. nn nn nn ^^ ^^ ^^ ^^ ;; ;; .. .. ;; ;; .. .. .. .. .. .. .. .. ,, ,, ,, ;; ;; .. .. rd rd .. .. .. RR .. .. ,, ,, ;; ;; ;; ,, ,, .. .. .| ww ww ww WW WW WW WW WW ww ww ww ww |. ,, ;; ;; ;; ;; ;; ;; ;; ;; ;; ^^ ^^ ^^ ;; ;; ;; ;; ^^ ^^ ^^ ^^ ww ww ww WW WW WW WW WW WW WW ww ww ww ww WW WW WW WW WW WW ww ww ww ^^ nn ;; ;; ;; .. .. .. .. .. .. .. .` ww ww ww ww WW WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[114] = 'WW WW WW WW WW WW WW WW WW ww ww /. .. .. .. .. nn nn nn ^^ ^^ ^^ ^^ ^^ ;; ;; ;; .. ;; ;; .. .. .. .. ,, RR .. .. ,, ,, ,, ;; ;; .. .. .. rd ,, .. .. RR .. .. ;; ;; ;; ;; ,, ;; ,, ;; .. .| ww ww WW WW WW WW WW WW ww ww ww ww |, ;; ;; ;; ;; ;; ;; ;; ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ;; ;; ^^ ww ww ww ww ww ww WW WW WW WW WW WW ww ww ww ww ww ww ww WW WW ww ww ww ww ww ww |; ;; ;; ;; ,, .. ,, .. .. .. .. .| ww ww ww WW WW WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[115] = 'WW WW WW WW WW WW WW WW ww ww ww |. .. .. .. nn nn nn nn ^^ ^^ ^^ ^^ ;; ;; ;; ;; ;; ;; .. .. .. .. .. .. RR ,, ,, .. ;; ;; RR .. .. .. .. rd ,, ,, RR RR .. ,, ,, ;; ,, ;; ;; ;; ;; ;; .. .| ww ww ww WW WW WW WW WW ww ww ww /. ;; ;; ;; ;; ;; ;; ;; ;; ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ;; ;; ^^ ^^ ww ww ww ww ww ww WW WW WW WW WW WW ww ww ww ww ww ww ww ww ww ww ww ww ww /. ;; ;; ;; ;; ,, .. ,, ,, .. .. .. .. .` ww ww WW WW WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[116] = 'WW WW WW WW WW WW WW WW ww ww ww `. .. .. .. .. nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ;; ;; ;; ;; .. .. .. .. .. ,, RR RR .. ,, ;; ;; RR ,, .. .. .. rd rd rd ,, .. ,, ;; ;; ;; ,, ;; ;; ;; ;; ,, .. .. .` ww ww ww WW WW WW ww ww ww /. ,, ;; ;; ^^ ^^ nn ;; ;; ;; ;; ;; ;; ^^ ^^ ^^ ^^ ^^ ^^ ;; ^^ ww ww ^^ ww ww ww ww ww WW WW WW WW ww ww ww ^^ ww ww ww ww ww ww ww ww /. -; ;; ;; ;; ;; ;; .. .. ,, ,, ,, .. .. .. .| ww ww ww WW WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[117] = 'WW WW WW WW WW WW WW ww ww ww ww ww |. .. .. nn nn nn ^^ ^^ ^^ ^^ nn ^^ ^^ nn ;; ;; ;; ;; ;; .. .. .. .. .. RR RR ff ff ,, RR ,, ;; .. .. .. .. rd rd .. ;; ,, rd rd rd rd rd rd rd ,, .. .. .. .` ww ww ww ww ww ww ww ww |, .. ;; nn ^^ ^^ nn nn ;; ;; ;; ;; ;; ;; ;; ^^ ^^ ^^ ^^ ;; ^^ ^^ ^^ ^^ ww ww ww ww ww ww ww WW WW ww ww ww ^^ ^^ ww ww ww ww ww ww /. ;; ;; ;; ;; ;; ,, ,, .. .. .. .. ,, .. .. .. .. .` ww ww ww WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[118] = 'WW WW WW WW WW WW WW ww ww ww ww /. .. .. .. .. nn ^^ ^^ ^^ ^^ ^^ nn nn nn nn ;; ;; ;; ;; ;; ;; .. .. .. .. ,, RR RR ff RR RR ,, ;; ;; .. .. .. ;; rd rd rd rd rd ,, ;; ;; ,, ;; rd rd rd rd .. .| ww ww ww ww ww ww ww ww |, ,, ^^ ^^ ^^ ^^ ^^ nn ^^ ^^ ;; ;; ;; ;; ;; ;; ^^ ^^ ;; ;; ;; ^^ ^^ ^^ ^^ ^^ -; .` ww ww ww ww ww ww ww ww ^^ ^^ ^^ ^^ ww ww ^^ ^^ ;; ;; ;; ;; ,, ,, .. .. .. .. .. .. .. .. ,, .. .. .. .` ww ww ww WW WW WW WW WW WW';
mappages["darkunknown"].terrain[119] = 'WW WW WW WW WW WW WW WW ww ww ww |. .. .. .. nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn ;; ;; ;; ;; ;; ;; ;; .. .. .. ,, .. .. RR RR RR ,, .. .. ;; .. .. ,, ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ,, rd rd rd ww ww ww ww ww ww ww ww `. ,, ^^ ^^ ^^ ^^ ^^ nn ^^ ^^ nn ;; ;; ;; ;; ^^ ^^ ^^ ;; ;; ;; ;; ^^ ^^ ^^ ^^ ^^ ;; .` ww ww ww ww ww ww ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ;; ;; ;; ;; ,, .. .. ,, ,, .. .. ,, ,, .. .. ,, .. .. .| ww ww WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[120] = 'WW WW WW WW WW WW WW WW ww ww ww |. .. .. .. .. nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ;; ;; ;; ;; ;; ;; .. .. .. .. .. .. ,, ff RR ff ,, ;; ;; ;; .. .. ;; ;; ;; ;; ,, ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;| ww ww ww ww WW ww ww ww ww |; ;; nn ^^ ^^ nn ;; nn ^^ ^^ nn ;; ;; ;; ^^ ^^ ^^ ^^ ;; ;; ;; ;; ;; ^^ ^^ ^^ ;; ;; .` ww ww ww ww ww ww ww |. ^^ ^^ ;; ;; ;; ;; ;; ;; .. .. .. .. .. .. .. ,, ff ff ff ff .. .. .. .. ./ ww ww WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[121] = 'WW WW WW WW WW WW WW ww ww ww /. .. .. .. .. .. nn nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ;; ;; ;; ;; ;; .. .. .. .. .. ,, ff RR RR ,, .. ;; ,, ;; .. ,, ;; ;; ;; ;; ;; ,, ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;| ww ww ww WW WW ww ww ww /. ;; ;; nn ;; ;; ;; ;; nn ^^ ^^ nn ;; ;; ;; ;; ^^ ^^ ^^ ^^ ;; ;; ;; ^^ ^^ ^^ ;; ;; ;; ;| ww ww ww ww ww ww ww |. .. ^^ ;; ;; ;; ;; ;; ;; .. .. .. .. ,, ,, ff ff ,, ,, ff ff ff .. ,, .| ww ww ww WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[122] = 'WW WW WW WW WW WW WW ww ww ww |. .. .. .. .. ;; ;; ;; ;; ^^ ^^ ^^ ^^ ;; ;; ;; ;; ;; ;; ;; ;; .. .. .. .. ,, .. ,, RR ff .. RR RR RR RR .. ,, ;; ;; ,, ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ,, ;; ;; ;; ;| ww ww ww WW WW WW ww ww |; ;; ;; ;; ;; ;; ;; ;; ;; nn ^^ ^^ nn nn ;; ;; ^^ ^^ ^^ ^^ ^^ ^^ ;; ;; ;; ;; ;; ;; ;; ;| ww ww ww ww ww ww ww `. .. ^^ ^^ ^^ ,, ,, ;; ,, .. .. .. ff ff ff ff .. .. ff ff ff ,, .. .. .| ww ww ww WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[123] = 'WW WW WW WW WW WW WW ww ww ww |. ;; ;; .. .. ;; ;; ;; ^^ ^^ ^^ ^^ ^^ ^^ ;; ;; ;; ;; ;; ;; ;; .. .. .. .. .. ,, ,, RR RR RR RR .. ;; ;; .. ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;| ww ww ww ww WW WW ww ww |; ;; ;; ;; ;; ;; ;; ;; ;; nn nn ^^ ^^ ^^ ;; ;; ^^ ^^ ^^ ^^ ^^ ^^ ;; ;; ;; ;; ;; ;; ;; ;; .` ww ww ww ww ww ww ww ^^ ^^ ^^ ^^ ,, .. ;; ,, .. .. .. ,, ff ff ff ff ff ff ff ,, ff ff .. ./ ww ww ww WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[124] = 'WW WW WW WW WW WW ww ww ww ww |. ;; ;; ;; ;; ;; ;; ^^ ^^ ^^ ^^ ^^ ^^ ;; ;; ;; ;; ;; ;; .. .. .. .. .. .. ,, .. ff RR ,, ff .. ,, .. ;; ;; ;; ,, ;; ;; ,, ;; ;; ;; ;; ;; ,, ;; ;; ;; ;; ;; ;; ;; ;| ww ww ww ww ww ww ww ww |. .. nn ;; ^^ nn ;; ;; ;; ;; ;; nn ^^ nn ;; ;; ;; ;; .. ^^ ^^ ^^ ;; ;; ;; ^^ ;; ;; ^^ ^^ ^^ ^^ ww ww ^^ ^^ ^^ ^^ ^^ ^^ ,, ,, .. .. .. .. ,, ff ff ff ff ff ff ff ff .. ff ff ff ff .| ww ww ww WW WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[125] = 'WW WW WW WW WW WW ww ww ww ww |; ;; ;; ;; ;; ;; ^^ ^^ ^^ ^^ ^^ ^^ nn ;; ;; ;; ;; ;; ;; .. .. .. .. .. .. ,, ,, __ RR __ .. .. .. .. ;; ;; .. .. ,, ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ./ ww ww ww ww nn ww ww ww `. nn nn nn ^^ ^^ ;; ;; ;; ;; ;; ;; ^^ nn ;; ;; ;; ;; .. .. ^^ ^^ ;; ;; ^^ ^^ ;; ;; ^^ ^^ nn ^^ ^^ ^^ ^^ ^^ nn nn nn ^^ nn .. .. .. .. .. ,, ff ff ff .. ff ff ff ff ff ff ff ,, .. .| ww ww ww ww WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[126] = 'WW WW WW WW WW WW WW ww ww ww |; ;; ;; ;; ;; ;; nn nn ^^ ^^ ^^ ^^ ;; ;; ;; ;; ;; .. .. .. .. .. .. .. .. .. ./ ww ww ww `. .. .. .. __ .. .. .. ,, ,, .. ;; ;; ;; ;; ;; ;; ;; ;; ,, ;; ;; ;; ;| ww ww ww ww nn nn nn ww ww ww nn nn nn ^^ ^^ ^^ ^^ ^^ ^^ ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn ^^ nn nn nn .. nn nn .. .. .. .. ,, ff ff ff .. ,, ff ff ff ff ,, ff ff .. ff .. ,, .` ww ww ww ww WW WW WW WW WW WW';
mappages["darkunknown"].terrain[127] = 'WW WW WW WW WW WW WW ww ww ww `. _; ;; ;; ;; ;; ;; nn nn ^^ ^^ nn ;; ;; ;; ;; ;; .. .. .. .. .. .. .. __ ./ ww ww ww ww ww `. __ ./ ww `. _, _, __ .. ,, ;; ;; ;; ;; ,, ;; ;; ;; ;; ;; ;; ;; ;| ww ww ww ww ww nn nn ww ww ww `. ;; ;; nn nn ^^ ^^ ^^ ^^ ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ^^ nn nn nn ^^ ^^ ^^ ^^ ^^ ^^ nn __ nn nn nn __ nn nn nn nn nn .. .. .. ff ff .. ff ff ff ff ,, ,, .. ff ff ,, ff ff .. ,, ,| ww ww ww ww WW WW WW WW WW WW';
mappages["darkunknown"].terrain[128] = 'WW WW WW WW WW WW WW WW ww ww ww ww `. ;; ;; ;; ;; nn ;; ;; ^^ ;; ;; ;; ;; .. .. .. .. .. .. .. __ ./ ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww `. _; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;; ,, ;; ;| ww ww ww ww ww ww ww ww ww ww ww |; ;; ;; nn ^^ ^^ nn ^^ ;; ;; ;; ,, ,, ^^ ^^ ^^ ;; nn nn nn nn nn nn ^^ ww ww ww ww ww ww ww ww ww ww ww ww ww ww nn .. ,, ff ,, ,, ff ,, ff .. ff ff ff __ .. ff ff ff ff ff .. .. .` ww ww ww WW WW WW WW WW WW';
mappages["darkunknown"].terrain[129] = 'WW WW WW WW WW WW WW WW WW ww ww ww ww `. _; _; ;; ;; ;; ;; ;; ;; ;; ;; ;; .. .. .. .. __ __ ./ ww ww ww ww ww WW ww ww ww ww ww ww ww ww ww ww ww ww ww `. _; _; ;; ;; ;; ;; ;; ;; ;; ;; ;; ;| ww ww ww WW ww ww ww ww ww ww ww `. _; _; nn ^^ ^^ nn nn ;; ;; ;; ,, ^^ ^^ ^^ ^^ _; _; nn nn nn nn ^^ ^^ ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww `. __ .. ,, ff ff .. .. ,, .. __ ./ ww `. __ .. .. .. ff ff ff .. .` ww ww ww WW WW WW WW WW';
mappages["darkunknown"].terrain[130] = 'WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww `. ;; ;; ;; ;; ;; ;; _; __ .. .. __ ./ ww ww ww ww ww ww WW WW WW WW WW ww ww ww ww ww ww ww ww ww ww ww ww ww ww `. _; ;; ;; ;; ;; ;; ;; ;; ./ ww ww WW WW WW WW WW WW WW WW ww ww ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww ww ww ww ww nn nn ww ww ww ww WW WW WW ww ww ww ww ww ww ww ww ww ww ww ww ww `. .. ff .. ff ff ,, ./ ww ww ww ww ww `. __ .. .. .. ff .. ./ ww ww WW WW WW WW WW WW';
mappages["darkunknown"].terrain[131] = 'WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww `. _; _; _; _; ./ ww ww `. ./ ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww `. _; _; ./ `. _; ./ ww ww ww WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ^^ ^^ ^^ ^^ ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww WW WW WW WW WW WW WW ww WW WW WW ww ww ww ww ww ww `. __ ,, ff .. .| ww ww ww ww ww ww ww ww `. __ _, _, ./ ww ww ww WW WW WW WW WW WW';
mappages["darkunknown"].terrain[132] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww `. _, _, ./ ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[133] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww ww WW WW WW WW ww ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[134] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww WW ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww WW WW ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww WW WW WW WW WW WW WW WW ww ww ww ww WW WW WW WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[135] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[136] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[137] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[138] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[139] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[140] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["darkunknown"].terrain[141] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';

mappages["darkunknown"].features = [];
mappages["darkunknown"].features[0] = {name : 'Shrine', x : 15, y : 16};
mappages["darkunknown"].features[1] = {name : 'Towne', x : 123, y : 14, desc : "Towne of Wealth", prefix : "the", entermap : 'wealth', enterx : 0, entery : 0};
mappages["darkunknown"].features[2] = {name : 'Dungeon', x : 96, y : 31, entermap : 'shadow', enterx : 0, entery : 0};
mappages["darkunknown"].features[3] = {name : 'Towne', x : 81, y : 23, desc : "Towne of Clear Lagoon", prefix : "the", entermap : 'clearlagoon', enterx : 1, entery : 37};
mappages["darkunknown"].features[4] = {name : 'Towne', x : 41, y : 26, desc : "Towne of Poverty", prefix : "the", entermap : 'poverty', enterx : 17, entery : 38};
mappages["darkunknown"].features[5] = {name : 'Dungeon', x : 39, y : 48, entermap : 'deathunending', enterx : 0, entery : 0};
mappages["darkunknown"].features[6] = {name : 'Towne', x : 52, y : 63, desc : "Towne of Gauntlet", prefix : "the", entermap : 'gauntlet', enterx : 25, entery : 38};
mappages["darkunknown"].features[7] = {name : 'Dungeon', x : 27, y : 44, entermap : 'worldsending', enterx : 0, entery : 0};
mappages["darkunknown"].features[8] = {name : 'Village', x : 72, y : 75, desc : "Village of Nassau", prefix : "the", entermap : 'nassau', enterx : 16, entery : 30};
mappages["darkunknown"].features[9] = {name : 'LeftCastle', x : 68, y : 73};
mappages["darkunknown"].features[10] = {name : 'Castle', x : 69, y : 73, entermap : 'olympus1', enterx : 29, entery : 42};
mappages["darkunknown"].features[11] = {name : 'RightCastle', x : 70, y : 73};
mappages["darkunknown"].features[12] = {name : 'Dungeon', x : 117, y : 76, entermap : 'pitdespair', enterx : 8, entery : 19};
mappages["darkunknown"].features[13] = {name : 'Dungeon', x : 133, y : 79, entermap : 'mtdrash1', enterx : 7, entery : 13};
mappages["darkunknown"].features[14] = {name : 'Dungeon', x : 69, y : 96, entermap : 'guilddeath', enterx : 0, entery : 0};
mappages["darkunknown"].features[15] = {name : 'Keep', x : 49, y : 90, desc : "Black Dragon's Castle", prefix : "the", entermap : 'blackdragon', enterx : 0, entery : 0};
mappages["darkunknown"].features[16] = {name : 'Shrine', x : 13, y : 82};
mappages["darkunknown"].features[17] = {name : 'Towne', x : 120, y : 104, desc : "Towne of Stout", prefix : "the", entermap : 'stout', enterx : 0, entery : 0};
mappages["darkunknown"].features[18] = {name : 'Dungeon', x : 81, y : 128, entermap : 'vault', enterx : 0, entery : 0};
mappages["darkunknown"].features[19] = {name : 'Towne', x : 64, y : 119, desc : "Towne of Onyx", prefix : "the", entermap : 'onyx', enterx : 0, entery : 0};
mappages["darkunknown"].features[20] = {name : 'Dungeon', x : 22, y : 117, entermap : 'metaltwister', enterx : 20, entery : 24};
mappages["darkunknown"].features[21] = {name : 'BridgeEW', x : 79, y : 29};
mappages["darkunknown"].features[22] = {name : 'HillTower', x : 56, y : 37, entermap : 'asharden1', enterx : 32, entery : 32};
mappages["darkunknown"].features[23] = {name : 'Lighthouse', x : 69, y : 125, entermap : 'lighthouse', enterx : 0, entery : 0};
mappages["darkunknown"].features[24] = {name : 'BridgeNS', x : 39, y : 73};
mappages["darkunknown"].features[25] = {name : 'BridgeEW', x : 87, y : 42};
mappages["darkunknown"].features[26] = {name : 'BridgeEW', x : 72, y : 44};
mappages["darkunknown"].features[27] = {name : 'HillTower', x : 102, y : 126, entermap : 'toshin1', enterx : 30, entery : 13};
mappages["darkunknown"].features[28] = {name : 'BridgeNS', x : 92, y : 101};
mappages["darkunknown"].features[29] = {name : 'BridgeEW', x : 87, y : 102};
mappages["darkunknown"].features[30] = {name : 'HillTower', x : 18, y : 11, entermap : 'towerofwizardry', enterx : 0, entery : 0};


mappages["darkunknown"].npcs = [];

mappages["darkunknown"].desc = "Lands of Olympus";
mappages["darkunknown"].music = 'Mainland';
mappages["darkunknown"].exitmap = '';
mappages["darkunknown"].exitx = '65';
mappages["darkunknown"].exity = '70';
mappages["darkunknown"].wraps = 'Both';
mappages["darkunknown"].enterx = '64';
mappages["darkunknown"].entery = '71';
mappages["darkunknown"].seeBelow = '';
mappages["darkunknown"].lightLevel = 'bright';
mappages["darkunknown"].alwaysRemember = '1';
mappages["darkunknown"].scale = '0';
mappages["darkunknown"].enterscript = '';
mappages["darkunknown"].entertestscript = '';
mappages["darkunknown"].exitscript = '';
mappages["darkunknown"].exittestscript = '';
mappages["darkunknown"].returnmap = 'darkunknown';
mappages["darkunknown"].returnx = '69';
mappages["darkunknown"].returny = '74';
mappages["darkunknown"].returninfused = '0';
mappages["darkunknown"].linkedMaps = [""];

mappages["darkunknown"].onload = function(mapref) {
    
  // Place spawners  
  if (gamestate.getMode() !== "loadgame") {
    Placeonyxspawn(mapref);
  // give specs to teleporters
    var shrinetile = mapref.getTile(13,82);
    var shrine = shrinetile.getTopFeature();
    if (shrine) {
      shrine.gotomap = "island";
      shrine.gotox = 14;
      shrine.gotoy = 76;
    }
  
    shrinetile = mapref.getTile(15,16);
    shrine = shrinetile.getTopFeature();
    if (shrine) {
      shrine.gotomap = "island";
      shrine.gotox = 56;
      shrine.gotoy = 15;
    }
  }
  CreateNetwork(mapref);
  
  
}

function Placeonyxspawn(mapref) {
  
  var onyxspawn = localFactory.createTile("Spawner");
  var onyxgroup = [];
  onyxgroup[0] = "HoodGroupSmall";
  onyxgroup[1] = "HoodGroupSmall";
  onyxgroup[2] = "HoodGroupLarge";
  onyxgroup[3] = "RogueGroupSmall";

  onyxspawn.setSpawngroup(onyxgroup);
  onyxspawn.setSpawnRadius(3);
  onyxspawn.setSpawnLeash(0);
  onyxspawn.setSpawnSoftLeash(0);

  onyxspawn.evolve[2] = [];
  onyxspawn.evolve[2][0] = "spawngroup";
  onyxspawn.evolve[2][1] = new Array("HoodGroupSmall","HoodGroupLarge","RogueGroupSmall","RogueGroupLarge","RogueGroupLarge","ThiefGroupSmall");

  onyxspawn.evolve[3] = [];
  onyxspawn.evolve[3][0] = "spawngroup";
  onyxspawn.evolve[3][1] = new Array("HoodGroupLarge","RogueGroupSmall","RogueGroupLarge","ThiefGroupSmall","ThiefGroupLarge");
  
  mapref.placeThing(57,122,onyxspawn);
    
}


function CreateNetwork(mapref) {
  
  mapref.network["road"] = [];
  mapref.network["road"][0] =  new PointOfInterest(55,115);
  mapref.network["road"][1] =  new PointOfInterest(44,90);
  mapref.network["road"][2] =  new PointOfInterest(36,100);
  mapref.network["road"][3] =  new PointOfInterest(45,65);
  mapref.network["road"][4] =  new PointOfInterest(65,68);
  mapref.network["road"][5] =  new PointOfInterest(62,64);
  mapref.network["road"][6] =  new PointOfInterest(76,29);
  mapref.network["road"][7] =  new PointOfInterest(48,27);
  mapref.network["road"][8] =  new PointOfInterest(110,52);
  mapref.network["road"][9] =  new PointOfInterest(129,18);
  mapref.network["road"][10] = new PointOfInterest(102,67);
  mapref.network["road"][11] = new PointOfInterest(119,100);
  
  mapref.network["road"][0].connections = [mapref.network["road"][2]];
  mapref.network["road"][1].connections = [mapref.network["road"][2], mapref.network["road"][3]];
  mapref.network["road"][2].connections = [mapref.network["road"][0], mapref.network["road"][1]];
  mapref.network["road"][3].connections = [mapref.network["road"][1], mapref.network["road"][4], mapref.network["road"][5]];
  mapref.network["road"][4].connections = [mapref.network["road"][3], mapref.network["road"][5]];
  mapref.network["road"][5].connections = [mapref.network["road"][3], mapref.network["road"][4], mapref.network["road"][6], mapref.network["road"][7]];
  mapref.network["road"][6].connections = [mapref.network["road"][5], mapref.network["road"][7], mapref.network["road"][8]];
  mapref.network["road"][7].connections = [mapref.network["road"][5], mapref.network["road"][6]];
  mapref.network["road"][8].connections = [mapref.network["road"][6], mapref.network["road"][9], mapref.network["road"][10]];
  mapref.network["road"][9].connections = [mapref.network["road"][8]];
  mapref.network["road"][10].connections = [mapref.network["road"][8], mapref.network["road"][11]];
  mapref.network["road"][11].connections = [mapref.network["road"][10]];
  
  mapref.network["wild"] = [];
  mapref.network["wild"][0] =  new PointOfInterest(115,32);
  mapref.network["wild"][1] =  new PointOfInterest(23,109);  
  mapref.network["wild"][2] =  new PointOfInterest(58,127);
  mapref.network["wild"][3] =  new PointOfInterest(53,100);
  mapref.network["wild"][4] =  new PointOfInterest(26,125);
  mapref.network["wild"][5] =  new PointOfInterest(13,123);
  mapref.network["wild"][6] =  new PointOfInterest(36,100);
  mapref.network["wild"][7] =  new PointOfInterest(18,87);
  mapref.network["wild"][8] =  new PointOfInterest(107,126);
  mapref.network["wild"][9] =  new PointOfInterest(130,125);
  mapref.network["wild"][10] = new PointOfInterest(29,66);
  mapref.network["wild"][11] = new PointOfInterest(18,59);
  mapref.network["wild"][12] = new PointOfInterest(31,44);
  mapref.network["wild"][13] = new PointOfInterest(47,47);
  mapref.network["wild"][14] = new PointOfInterest(109,96);
  mapref.network["wild"][15] = new PointOfInterest(92,98);
  mapref.network["wild"][16] = new PointOfInterest(94,84);
  mapref.network["wild"][17] = new PointOfInterest(134,73);
  mapref.network["wild"][18] = new PointOfInterest(57,31);
  mapref.network["wild"][19] = new PointOfInterest(44,13);
  mapref.network["wild"][20] = new PointOfInterest(71,18);
  mapref.network["wild"][21] = new PointOfInterest(70,57);
  mapref.network["wild"][22] = new PointOfInterest(81,47);
  mapref.network["wild"][23] = new PointOfInterest(84,76);
  mapref.network["wild"][24] = new PointOfInterest(90,15);
  mapref.network["wild"][25] = new PointOfInterest(98,60);
  mapref.network["wild"][26] = new PointOfInterest(111,71);
  mapref.network["wild"][27] = new PointOfInterest(119,71);
  mapref.network["wild"][28] = new PointOfInterest(128,48);
  mapref.network["wild"][29] = new PointOfInterest(133,24);
  
  
  mapref.network["wild"][0].connections = [mapref.network["wild"][24], mapref.network["wild"][25], mapref.network["wild"][28], mapref.network["wild"][29]];
  mapref.network["wild"][1].connections = [mapref.network["wild"][5], mapref.network["wild"][7], mapref.network["wild"][6], mapref.network["wild"][4]];
  mapref.network["wild"][2].connections = [mapref.network["wild"][4], mapref.network["wild"][6]];
  mapref.network["wild"][3].connections = [mapref.network["wild"][6]];
  mapref.network["wild"][4].connections = [mapref.network["wild"][2], mapref.network["wild"][5], mapref.network["wild"][6], mapref.network["wild"][1]];
  mapref.network["wild"][5].connections = [mapref.network["wild"][4], mapref.network["wild"][6], mapref.network["wild"][1]];
  mapref.network["wild"][6].connections = [mapref.network["wild"][4], mapref.network["wild"][1], mapref.network["wild"][5], mapref.network["wild"][7], mapref.network["wild"][3], mapref.network["wild"][10], mapref.network["wild"][13]];
  mapref.network["wild"][7].connections = [mapref.network["wild"][1], mapref.network["wild"][6], mapref.network["wild"][10]];
  mapref.network["wild"][8].connections = [mapref.network["wild"][14], mapref.network["wild"][9]];
  mapref.network["wild"][9].connections = [mapref.network["wild"][8], mapref.network["wild"][14], mapref.network["wild"][26]];
  mapref.network["wild"][10].connections = [mapref.network["wild"][7], mapref.network["wild"][6], mapref.network["wild"][11], mapref.network["wild"][13], mapref.network["wild"][12]];
  mapref.network["wild"][11].connections = [mapref.network["wild"][10], mapref.network["wild"][12], mapref.network["wild"][13]];
  mapref.network["wild"][12].connections = [mapref.network["wild"][10], mapref.network["wild"][11], mapref.network["wild"][13]];
  mapref.network["wild"][13].connections = [mapref.network["wild"][6], mapref.network["wild"][10], mapref.network["wild"][11], mapref.network["wild"][12], mapref.network["wild"][18], mapref.network["wild"][20], mapref.network["wild"][21]];
  mapref.network["wild"][14].connections = [mapref.network["wild"][15], mapref.network["wild"][16], mapref.network["wild"][26], mapref.network["wild"][9], mapref.network["wild"][8]];
  mapref.network["wild"][15].connections = [mapref.network["wild"][16], mapref.network["wild"][26], mapref.network["wild"][14]];
  mapref.network["wild"][16].connections = [mapref.network["wild"][23], mapref.network["wild"][25], mapref.network["wild"][26], mapref.network["wild"][14], mapref.network["wild"][15]];
  mapref.network["wild"][17].connections = [mapref.network["wild"][28]];
  mapref.network["wild"][18].connections = [mapref.network["wild"][13], mapref.network["wild"][19], mapref.network["wild"][20]];
  mapref.network["wild"][19].connections = [mapref.network["wild"][18], mapref.network["wild"][20]];
  mapref.network["wild"][20].connections = [mapref.network["wild"][13], mapref.network["wild"][18], mapref.network["wild"][19], mapref.network["wild"][24]];
  mapref.network["wild"][21].connections = [mapref.network["wild"][13], mapref.network["wild"][22], mapref.network["wild"][23]];
  mapref.network["wild"][22].connections = [mapref.network["wild"][21], mapref.network["wild"][23], mapref.network["wild"][25], mapref.network["wild"][24]];
  mapref.network["wild"][23].connections = [mapref.network["wild"][21], mapref.network["wild"][22], mapref.network["wild"][25], mapref.network["wild"][26], mapref.network["wild"][16]];
  mapref.network["wild"][24].connections = [mapref.network["wild"][20], mapref.network["wild"][22], mapref.network["wild"][25], mapref.network["wild"][0]];
  mapref.network["wild"][25].connections = [mapref.network["wild"][22], mapref.network["wild"][24], mapref.network["wild"][0], mapref.network["wild"][28], mapref.network["wild"][27], mapref.network["wild"][26], mapref.network["wild"][16], mapref.network["wild"][23]];
  mapref.network["wild"][26].connections = [mapref.network["wild"][23], mapref.network["wild"][25], mapref.network["wild"][27], mapref.network["wild"][9], mapref.network["wild"][14], mapref.network["wild"][15], mapref.network["wild"][16]];
  mapref.network["wild"][27].connections = [mapref.network["wild"][25], mapref.network["wild"][28], mapref.network["wild"][26]];
  mapref.network["wild"][28].connections = [mapref.network["wild"][0], mapref.network["wild"][17], mapref.network["wild"][27], mapref.network["wild"][25], mapref.network["wild"][29]];
  mapref.network["wild"][29].connections = [mapref.network["wild"][0], mapref.network["wild"][28]];
  
  mapref.network["mordor"] = [];
  mapref.network["mordor"][0] = new PointOfInterest(92,110);
  mapref.network["mordor"][1] = new PointOfInterest(98,123);
  mapref.network["mordor"][2] = new PointOfInterest(79,114);
  mapref.network["mordor"][3] = new PointOfInterest(85,127);
  
  mapref.network["mordor"][0].connections = [mapref.network["mordor"][1], mapref.network["mordor"][2], mapref.network["mordor"][3]];
  mapref.network["mordor"][1].connections = [mapref.network["mordor"][0], mapref.network["mordor"][2], mapref.network["mordor"][3]];
  mapref.network["mordor"][2].connections = [mapref.network["mordor"][0], mapref.network["mordor"][1], mapref.network["mordor"][3]];
  mapref.network["mordor"][3].connections = [mapref.network["mordor"][0], mapref.network["mordor"][1], mapref.network["mordor"][2]];
  
//  if (debug) { TestNetwork(mapref, "wild"); }
}