"use strict";

mappages["miningvillage"] = {};
mappages["miningvillage"].terrain = [];
 mappages["miningvillage"].terrain[0] = 'nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn';
 mappages["miningvillage"].terrain[1] = 'nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn';
 mappages["miningvillage"].terrain[2] = 'nn nn nn nn nn nn nn nn nn nn nn .. .. .. nn nn .. .. .. .. .. nn nn nn nn nn .. .. nn nn nn nn';
 mappages["miningvillage"].terrain[3] = 'nn nn .. .. .. .. nn .. .. .. .. .. .. .. .. .. .. .. .. .. nn nn nn .. .. .. .. .. .. .. .. ..';
 mappages["miningvillage"].terrain[4] = '.. nn .. .. .. .. .. .. .. .. .. .. !# .. .. !# !# !# !# .. nn nn .. .. .. .. .. .. .. .. .. ..';
 mappages["miningvillage"].terrain[5] = '.. .. .. .. .. .. .. .. .. .. .. .. !# -= -= -= -= -= !# .. .. nn .. .. .. !# .. .. .. !# .. ..';
 mappages["miningvillage"].terrain[6] = '.. .. !# !# !# !# !# !# !# !# .. .. !# -= -= -= -= -= !# .. .. .. .. .. .. !# -= -= -= !# .. ..';
 mappages["miningvillage"].terrain[7] = '.. .. !# -= -= -= -= -= -= !# .. .. !# -= -= -= -= -= !# .. .. .. .. !# !# !# -= -= -= !# .. ..';
 mappages["miningvillage"].terrain[8] = '.. .. !# -= -= -= -= -= -= !# .. .. !# -= -= -= -= -= !# .. .. .. .. !# -= -= -= -= -= !# .. ..';
 mappages["miningvillage"].terrain[9] = '.. .. !# -= -= -= -= -= -= !# .. .. !# -= -= -= -= -= !# .. .. .. .. !# -= -= -= -= -= !# .. ..';
mappages["miningvillage"].terrain[10] = '.. .. !# -= -= -= -= -= -= !# .. .. !# -= -= -= -= -= !# .. .. .. .. !# -= -= -= -= -= !# .. ..';
mappages["miningvillage"].terrain[11] = '.. .. !# -= -= -= -= -= -= !# .. .. !# -= -= -= !# !# !# .. .. .. .. !# -= -= -= -= -= !# .. ..';
mappages["miningvillage"].terrain[12] = '.. .. !# !# -= -= -= -= -= !# .. .. .. .. .. .. .. .. .. .. .. .. .. !# !# -= -= -= -= !# .. ..';
mappages["miningvillage"].terrain[13] = '.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..';
mappages["miningvillage"].terrain[14] = '.. ., ., .. ., ., .. ff ., ., ., ff ., ., .. ., .. ., ff ., ., ., .. ., ., ., .. ., ., ., ff ..';
mappages["miningvillage"].terrain[15] = '.. ., ., ., ., .. ., ., ., ., .. .. ., ., ., ., ff ., ., ., ., ., .. ff ., ., ., .. ., ., ., ..';
mappages["miningvillage"].terrain[16] = '.. ., .. ., ff .. ., ., ., .. .. ., ., ff ., .. .. .. ., ., .. ., .. .. .. ., ., ., ., ., ., ..';
mappages["miningvillage"].terrain[17] = '.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..';
mappages["miningvillage"].terrain[18] = '.. .. .. .. !# !# !# !# -= -= -= !# .. .. !# -= -= -= -= !# .. .. .. .. .. .. .. .. .. .. .. ..';
mappages["miningvillage"].terrain[19] = '.. .. .. .. !# -= -= -= -= -= -= !# .. .. !# -= -= -= -= !# .. .. .. .. !# .. .. .. !# !# .. ..';
mappages["miningvillage"].terrain[20] = '.. .. .. .. !# -= -= -= -= -= -= !# .. .. !# -= -= -= -= !# .. .. .. .. !# -= -= -= -= !# .. ..';
mappages["miningvillage"].terrain[21] = '.. .. .. .. !# -= -= -= -= -= -= !# .. .. !# -= -= -= -= !# .. .. .. .. !# -= -= -= -= !# .. ..';
mappages["miningvillage"].terrain[22] = '.. .. .. .. !# -= -= -= -= -= -= !# .. .. !# -= -= -= -= !# .. .. .. .. !# -= -= -= -= !# .. ..';
mappages["miningvillage"].terrain[23] = '.. .. .. .. !# !# !# !# -= -= -= !# .. .. !# -= -= -= -= !# .. .. .. .. !# -= -= -= -= !# .. ..';
mappages["miningvillage"].terrain[24] = '.. .. .. .. .. .. .. !# -= -= -= !# .. .. !# !# !# !# !# !# .. .. .. .. !# !# -= -= !# !# .. ..';
mappages["miningvillage"].terrain[25] = '.. .. .. .. .. .. .. !# !# !# !# !# .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..';
mappages["miningvillage"].terrain[26] = '.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..';
mappages["miningvillage"].terrain[27] = '.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. nn';
mappages["miningvillage"].terrain[28] = '.. .. nn nn nn nn nn nn nn .. .. .. .. .. .. .. .. nn nn nn .. nn nn nn nn .. .. .. .. .. .. nn';
mappages["miningvillage"].terrain[29] = '.. nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn';
mappages["miningvillage"].terrain[30] = 'nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn';
mappages["miningvillage"].terrain[31] = 'nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn';

mappages["miningvillage"].features = [];
mappages["miningvillage"].features[0] = {name : 'RuinsWallTallLeftMidRight', x : 4, y : 12};
mappages["miningvillage"].features[1] = {name : 'RuinsWallMidLeftBottomRight', x : 5, y : 12};
mappages["miningvillage"].features[2] = {name : 'RuinsWallBottomLeftMidRight', x : 7, y : 12};
mappages["miningvillage"].features[3] = {name : 'RuinsWallMidLeftTallRight', x : 8, y : 12};
mappages["miningvillage"].features[4] = {name : 'RuinsWallTallLeftMidRight', x : 13, y : 11};
mappages["miningvillage"].features[5] = {name : 'RuinsWallMidLeftBottomRight', x : 14, y : 11};
mappages["miningvillage"].features[6] = {name : 'RuinsWallTallLeftMidRight', x : 13, y : 4};
mappages["miningvillage"].features[7] = {name : 'RuinsWallMidLeftTallRight', x : 14, y : 4};
mappages["miningvillage"].features[8] = {name : 'RuinsWallTallLeftMidRight', x : 26, y : 5};
mappages["miningvillage"].features[9] = {name : 'RuinsWallMidLeftMidRight', x : 27, y : 5};
mappages["miningvillage"].features[10] = {name : 'RuinsWallMidLeftTallRight', x : 28, y : 5};
mappages["miningvillage"].features[11] = {name : 'RuinsWallMidLeftTallRight', x : 28, y : 12};
mappages["miningvillage"].features[12] = {name : 'RuinsWallMidLeftMidRight', x : 27, y : 12};
mappages["miningvillage"].features[13] = {name : 'RuinsWallTallLeftMidRight', x : 25, y : 12};
mappages["miningvillage"].features[14] = {name : 'RuinsWallMidLeftBottomRight', x : 25, y : 19};
mappages["miningvillage"].features[15] = {name : 'RuinsWallMidLeftTallRight', x : 27, y : 19};
mappages["miningvillage"].features[16] = {name : 'RuinsWallMidLeftTallRight', x : 27, y : 24};
mappages["miningvillage"].features[17] = {name : 'RuinsWallTallLeftMidRight', x : 26, y : 24};
mappages["miningvillage"].features[18] = {name : 'RuinsWallTallLeftMidRight', x : 15, y : 18};
mappages["miningvillage"].features[19] = {name : 'RuinsWallMidLeftTallRight', x : 18, y : 18};
mappages["miningvillage"].features[20] = {name : 'RuinsWallBottomLeftMidRight', x : 17, y : 18};
mappages["miningvillage"].features[21] = {name : 'RuinsWallTallLeftMidRight', x : 9, y : 18};
mappages["miningvillage"].features[22] = {name : 'RuinsWallMidLeftTallRight', x : 10, y : 18};


mappages["miningvillage"].npcs = [];

mappages["miningvillage"].desc = "";
mappages["miningvillage"].longdesc = '';
mappages["miningvillage"].music = '';
mappages["miningvillage"].savename = ``;
mappages["miningvillage"].exitmap = '';
mappages["miningvillage"].exitx = '65';
mappages["miningvillage"].exity = '70';
mappages["miningvillage"].wraps = '';
mappages["miningvillage"].enterx = '65';
mappages["miningvillage"].entery = '70';
mappages["miningvillage"].seeBelow = '';
mappages["miningvillage"].lightLevel = '';
mappages["miningvillage"].alwaysRemember = '0';
mappages["miningvillage"].scale = '1';
mappages["miningvillage"].underground = '0';
mappages["miningvillage"].undergroundDesc = '';
mappages["miningvillage"].enterscript = '';
mappages["miningvillage"].entertestscript = '';
mappages["miningvillage"].exitscript = '';
mappages["miningvillage"].exittestscript = '';
mappages["miningvillage"].returnmap = '';
mappages["miningvillage"].returnx = 'NaN';
mappages["miningvillage"].returny = 'NaN';
mappages["miningvillage"].returninfused = '0';
mappages["miningvillage"].linkedMaps = [];
mappages["miningvillage"].editorLabels = '{}';
