"use strict";

// MAP BEGINS HERE
mappages["miningvillage"] = {};
mappages["miningvillage"].terrain = [];
 mappages["miningvillage"].terrain[0] = 'nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn';
 mappages["miningvillage"].terrain[1] = 'nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn';
 mappages["miningvillage"].terrain[2] = 'nn nn nn nn nn nn nn nn nn nn nn ,, .. .. nn nn .. .. .. .. ,, nn nn nn nn nn .. ff nn nn nn nn';
 mappages["miningvillage"].terrain[3] = 'nn nn ff .. .. ff nn .. .. .. .. .. .. .. .. .. .. .. .. .. nn nn nn .. .. ff .. .. .. ,, .. ..';
 mappages["miningvillage"].terrain[4] = '.. nn .. .. .. ,, .. ff .. .. .. .. !# .. .. !# !# !# !# .. nn nn ,, .. .. .. .. .. .. .. .. ..';
 mappages["miningvillage"].terrain[5] = '.. .. u, .. .. .. .. .. .. .. .. .. !# f= f= f= f= f= !# .. .. nn .. .. .. !# .. .. .. !# ff ..';
 mappages["miningvillage"].terrain[6] = '.. .. !# !# !# !# !# !# !# !# .. ff !# f= f= f= f= f= !# .. .. ff .. .. u, !# f= f= f= !# .. ..';
 mappages["miningvillage"].terrain[7] = '.. .. !# f= f= f= f= f= f= !# .. .. !# !# f= !# f= f= !# .. .. .. .. !# !# !# f= f= f= !# .. ..';
 mappages["miningvillage"].terrain[8] = '.. ff !# f= f= f= f= f= f= !# .. ff !# f= f= f= f= f= !# .. .. .. ff !# f= !# !# f= !# !# .. ..';
 mappages["miningvillage"].terrain[9] = '.. .. !# f= f= f= f= f= f= !# ff .. !# f= f= f= f= f= !# ff .. .. ,, !# f= f= f= f= f= !# ff ..';
mappages["miningvillage"].terrain[10] = '.. .. !# f= f= f= f= f= f= !# .. .. !# f= f= f= f= f= !# .. ff .. .. !# f= f= f= f= f= !# .. ..';
mappages["miningvillage"].terrain[11] = '.. .. !# f= f= f= f= f= f= !# ff .. !# f= f= f= !# !# !# .. ff .. .. !# f= f= f= f= f= !# .. ..';
mappages["miningvillage"].terrain[12] = '.. .. !# !# f= f= f= f= f= !# .. .. .. .. .. .. .. .. .. .. .. .. .. !# !# f= f= f= f= !# .. ..';
mappages["miningvillage"].terrain[13] = '.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..';
mappages["miningvillage"].terrain[14] = '.. ., ., .. ., ., .. ff ., ., ., ff ., ., .. ., .. ., ff ., ., ., .. ., ., ., .. ., ., ., ff ..';
mappages["miningvillage"].terrain[15] = '.. ., ., ., ., .. ., ., ., ., .. .. ., ., ., ., ff ., ., ., ., ., .. ff ., ., ., .. ., ., ., ..';
mappages["miningvillage"].terrain[16] = '.. ., .. ., ff .. ., ., ., .. .. ., ., ff ., .. .. .. ., ., .. ., .. .. .. ., ., ., ., ., ., ..';
mappages["miningvillage"].terrain[17] = '.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..';
mappages["miningvillage"].terrain[18] = '.. .. .. .. !# !# !# !# f= .. .. !# .. .. !# .. .. .. .. !# .. .. .. .. .. .. .. .. .. .. .. ..';
mappages["miningvillage"].terrain[19] = '.. .. .. .. !# f= f= f= f= f= f= !# .. ff !# f= f= f= f= !# ff .. .. .. !# .. .. .. !# !# .. ..';
mappages["miningvillage"].terrain[20] = '.. ff .. .. !# f= f= f= f= f= f= !# .. ,, !# f= f= f= f= !# .. .. .. ff !# f= f= f= f= !# .. ..';
mappages["miningvillage"].terrain[21] = '.. .. ff .. !# f= f= f= f= f= f= !# .. .. !# !# !# !# f= !# .. ff .. .. !# f= f= f= f= !# u, ..';
mappages["miningvillage"].terrain[22] = '.. .. .. .. !# f= f= !# !# !# f= !# ff .. !# f= f= !# f= !# .. .. .. .. !# f= f= f= f= !# .. ..';
mappages["miningvillage"].terrain[23] = '.. .. .. .. !# !# !# !# f= f= f= !# .. .. !# f= f= f= f= !# u, .. .. ,, !# f= f= f= f= !# ff ..';
mappages["miningvillage"].terrain[24] = '.. .. .. .. .. ff ff !# f= f= f= !# .. .. !# !# !# !# !# !# .. .. .. .. !# !# f= f= !# !# .. ..';
mappages["miningvillage"].terrain[25] = '.. ,, .. .. .. .. .. !# !# !# !# !# .. .. .. .. .. ff ff .. .. .. .. .. .. .. .. .. .. .. .. ..';
mappages["miningvillage"].terrain[26] = '.. .. .. .. ,, .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ff .. .. .. ..';
mappages["miningvillage"].terrain[27] = '.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. nn';
mappages["miningvillage"].terrain[28] = '.. .. nn nn nn nn nn nn nn .. .. .. .. .. .. .. .. nn nn nn .. nn nn nn nn .. .. .. .. .. .. nn';
mappages["miningvillage"].terrain[29] = '.. nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn';
mappages["miningvillage"].terrain[30] = 'nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn';
mappages["miningvillage"].terrain[31] = 'nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn';

mappages["miningvillage"].features = [];
mappages["miningvillage"].features[0] = {name : 'RuinsWallTallLeftMidRight', x : 4, y : 12};
mappages["miningvillage"].features[1] = {name : 'RuinsWallMidLeftBottomRight', x : 5, y : 12};
mappages["miningvillage"].features[2] = {name : 'RuinsWallBottomLeftMidRight', x : 7, y : 12};
mappages["miningvillage"].features[3] = {name : 'RuinsWallMidLeftTallRight', x : 8, y : 12};
mappages["miningvillage"].features[4] = {name : 'RuinsWallTallLeftMidRight', x : 13, y : 11};
mappages["miningvillage"].features[5] = {name : 'RuinsWallMidLeftBottomRight', x : 14, y : 11};
mappages["miningvillage"].features[6] = {name : 'RuinsWallTallLeftMidRight', x : 13, y : 4};
mappages["miningvillage"].features[7] = {name : 'RuinsWallMidLeftTallRight', x : 14, y : 4};
mappages["miningvillage"].features[8] = {name : 'RuinsWallTallLeftMidRight', x : 26, y : 5};
mappages["miningvillage"].features[9] = {name : 'RuinsWallMidLeftMidRight', x : 27, y : 5};
mappages["miningvillage"].features[10] = {name : 'RuinsWallMidLeftTallRight', x : 28, y : 5};
mappages["miningvillage"].features[11] = {name : 'RuinsWallMidLeftTallRight', x : 28, y : 12};
mappages["miningvillage"].features[12] = {name : 'RuinsWallMidLeftMidRight', x : 27, y : 12};
mappages["miningvillage"].features[13] = {name : 'RuinsWallTallLeftMidRight', x : 25, y : 12};
mappages["miningvillage"].features[14] = {name : 'RuinsWallMidLeftBottomRight', x : 25, y : 19};
mappages["miningvillage"].features[15] = {name : 'RuinsWallMidLeftTallRight', x : 27, y : 19};
mappages["miningvillage"].features[16] = {name : 'RuinsWallMidLeftTallRight', x : 27, y : 24};
mappages["miningvillage"].features[17] = {name : 'RuinsWallTallLeftMidRight', x : 26, y : 24};
mappages["miningvillage"].features[18] = {name : 'RuinsWallTallLeftMidRight', x : 15, y : 18};
mappages["miningvillage"].features[19] = {name : 'RuinsWallMidLeftTallRight', x : 18, y : 18};
mappages["miningvillage"].features[20] = {name : 'RuinsWallBottomLeftMidRight', x : 17, y : 18};
mappages["miningvillage"].features[21] = {name : 'RuinsWallTallLeftMidRight', x : 9, y : 18};
mappages["miningvillage"].features[22] = {name : 'RuinsWallMidLeftTallRight', x : 10, y : 18};
mappages["miningvillage"].features[23] = {name : 'RuinsWallTallLeftMidRight', x : 16, y : 7};
mappages["miningvillage"].features[24] = {name : 'RuinsWallMidLeftTallRight', x : 17, y : 7};
mappages["miningvillage"].features[25] = {name : 'BedHead', x : 13, y : 5};
mappages["miningvillage"].features[26] = {name : 'BedFoot', x : 14, y : 5};
mappages["miningvillage"].features[27] = {name : 'LeftTable', x : 15, y : 9};
mappages["miningvillage"].features[28] = {name : 'RightTable', x : 16, y : 9};
mappages["miningvillage"].features[29] = {name : 'SmallBox', x : 17, y : 6, lootgroup : 'Townsfolk', lootedid : 'abanvil3'};
mappages["miningvillage"].features[30] = {name : 'TopChair', x : 16, y : 8};
mappages["miningvillage"].features[31] = {name : 'BottomChair', x : 13, y : 10};
mappages["miningvillage"].features[32] = {name : 'Evergreen', x : 19, y : 7};
mappages["miningvillage"].features[33] = {name : 'Evergreen', x : 20, y : 20};
mappages["miningvillage"].features[34] = {name : 'Evergreen', x : 4, y : 5};
mappages["miningvillage"].features[35] = {name : 'Evergreen', x : 1, y : 12};
mappages["miningvillage"].features[36] = {name : 'Evergreen', x : 2, y : 19};
mappages["miningvillage"].features[37] = {name : 'Evergreen', x : 13, y : 25};
mappages["miningvillage"].features[38] = {name : 'Evergreen', x : 9, y : 27};
mappages["miningvillage"].features[39] = {name : 'Evergreen', x : 25, y : 26};
mappages["miningvillage"].features[40] = {name : 'Evergreen', x : 31, y : 25};
mappages["miningvillage"].features[41] = {name : 'Evergreen', x : 29, y : 18};
mappages["miningvillage"].features[42] = {name : 'Mirror', x : 24, y : 8};
mappages["miningvillage"].features[43] = {name : 'BedHead', x : 27, y : 6};
mappages["miningvillage"].features[44] = {name : 'BedFoot', x : 28, y : 6};
mappages["miningvillage"].features[45] = {name : 'LeftTable', x : 25, y : 10};
mappages["miningvillage"].features[46] = {name : 'MiddleTable', x : 26, y : 10};
mappages["miningvillage"].features[47] = {name : 'RightTable', x : 27, y : 10};
mappages["miningvillage"].features[48] = {name : 'LeftChair', x : 26, y : 9};
mappages["miningvillage"].features[49] = {name : 'RightChair', x : 27, y : 11};
mappages["miningvillage"].features[50] = {name : 'Well', x : 9, y : 4};
mappages["miningvillage"].features[51] = {name : 'Woodpile', x : 20, y : 21, desc : "rotten wood pile"};
mappages["miningvillage"].features[52] = {name : 'PileOfRocks', x : 3, y : 8};
mappages["miningvillage"].features[53] = {name : 'PileOfRocks', x : 5, y : 8};
mappages["miningvillage"].features[54] = {name : 'PileOfRocks', x : 5, y : 9};
mappages["miningvillage"].features[55] = {name : 'PileOfRocks', x : 7, y : 9};
mappages["miningvillage"].features[56] = {name : 'PileOfRocks', x : 8, y : 11};
mappages["miningvillage"].features[57] = {name : 'BedHead', x : 15, y : 22};
mappages["miningvillage"].features[58] = {name : 'BedHead', x : 5, y : 22};
mappages["miningvillage"].features[59] = {name : 'BedHead', x : 25, y : 23};
mappages["miningvillage"].features[60] = {name : 'BedFoot', x : 26, y : 23};
mappages["miningvillage"].features[61] = {name : 'BedFoot', x : 16, y : 22};
mappages["miningvillage"].features[62] = {name : 'BedFoot', x : 6, y : 22};
mappages["miningvillage"].features[63] = {name : 'VoidstoneSculpture', x : 8, y : 23};
mappages["miningvillage"].features[64] = {name : 'Chest', x : 8, y : 24, lootgroup : 'Level1', lootedid : 'abanvil5'};
mappages["miningvillage"].features[65] = {name : 'Chest', x : 9, y : 23, lootgroup : 'Townsfolk', lootedid : 'abanvil4'};
mappages["miningvillage"].features[66] = {name : 'Chest', x : 8, y : 7, lootgroup : 'potslow', lootedid : 'abanvil2'};
mappages["miningvillage"].features[67] = {name : 'Chest', x : 4, y : 7, lootgroup : 'potslow', lootedid : 'abanvil1'};
mappages["miningvillage"].features[68] = {name : 'TopChair', x : 6, y : 19};
mappages["miningvillage"].features[69] = {name : 'BookshelfOne', x : 5, y : 19, searchyield : 'MapOfLostHope'};
mappages["miningvillage"].features[70] = {name : 'SmallTable', x : 26, y : 21};
mappages["miningvillage"].features[71] = {name : 'TopChair', x : 26, y : 18};
mappages["miningvillage"].features[72] = {name : 'SmallTable', x : 15, y : 20};
mappages["miningvillage"].features[73] = {name : 'LeftTable', x : 8, y : 21};
mappages["miningvillage"].features[74] = {name : 'RightTable', x : 9, y : 21};
mappages["miningvillage"].features[75] = {name : 'UnlitBrazier', x : 17, y : 5};
mappages["miningvillage"].features[76] = {name : 'UnlitBrazier', x : 10, y : 19};
mappages["miningvillage"].features[77] = {name : 'UnlitBrazier', x : 18, y : 19};
mappages["miningvillage"].features[78] = {name : 'UnlitBrazier', x : 28, y : 20};
mappages["miningvillage"].features[79] = {name : 'UnlitBrazier', x : 13, y : 8};
mappages["miningvillage"].features[80] = {name : 'UnlitBrazier', x : 26, y : 6};


mappages["miningvillage"].npcs = [];

mappages["miningvillage"].transover = '{"0,3":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-32,-448]],"0,30":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-448]],"1,3":[["","",null,null],["static.gif","spacer.gif",-288,0],["TerrainBlend.gif","spacer.gif",-96,-448]],"1,4":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-352,-448]],"1,29":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-128,-448]],"2,2":[["","",null,null],["static.gif","spacer.gif",-288,0],["TerrainBlend.gif","spacer.gif",-32,-448]],"2,28":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-128,-448]],"3,2":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-32,-448]],"3,28":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-448]],"4,2":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-32,-448]],"4,28":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-448]],"5,2":[["","",null,null],["static.gif","spacer.gif",-288,0],["TerrainBlend.gif","spacer.gif",-32,-448]],"5,28":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-448]],"6,3":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-352,-448]],"6,28":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-448]],"7,2":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-32,-448]],"7,28":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-448]],"8,2":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-32,-448]],"8,28":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-160,-448]],"9,2":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-32,-448]],"9,29":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-448]],"10,2":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-224,-448]],"10,29":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-448]],"11,1":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-32,-448]],"11,29":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-448]],"12,1":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-32,-448]],"12,29":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-448]],"13,1":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-32,-448]],"13,29":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-448]],"14,2":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-192,-448]],"14,29":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-448]],"15,2":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-224,-448]],"15,29":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-448]],"16,1":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-32,-448]],"16,29":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-448]],"17,1":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-32,-448]],"17,28":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-128,-448]],"18,1":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-32,-448]],"18,28":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-448]],"19,1":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-32,-448]],"19,28":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-160,-448]],"20,1":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-32,-448]],"20,3":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-128,-448]],"20,4":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-192,-448]],"20,29":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-448]],"21,2":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-64,-448]],"21,4":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-96,-448]],"21,5":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-352,-448]],"21,28":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-128,-448]],"22,3":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-224,-448]],"22,28":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-448]],"23,2":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-32,-448]],"23,28":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-448]],"24,2":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-32,-448]],"24,28":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-160,-448]],"25,2":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-224,-448]],"25,29":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-448]],"26,1":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-32,-448]],"26,29":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-448]],"27,1":[["","",null,null],["static.gif","spacer.gif",-288,0],["TerrainBlend.gif","spacer.gif",-32,-448]],"27,29":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-448]],"28,2":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-192,-448]],"28,29":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-448]],"29,2":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-32,-448]],"29,29":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-448]],"30,2":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-32,-448]],"30,29":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-448]],"31,2":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-32,-448]],"31,27":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-128,-448]],"31,28":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-64,-448]],"1,8":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-448,-640]],"1,20":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-448,-640]],"2,3":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-224,-640]],"2,21":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-448,-640]],"4,16":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-224,-640]],"5,3":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-352,-640]],"5,24":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-256,-640]],"7,4":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-448,-640]],"7,14":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-128,-640]],"10,9":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-448,-640]],"10,11":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-448,-640]],"11,6":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-448,-640]],"11,8":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-448,-640]],"11,14":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-384,-640]],"12,22":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-448,-640]],"13,16":[["","",null,null],["static.gif","spacer.gif",0,-64],["TerrainBlend.gif","spacer.gif",-448,-640]],"13,19":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-448,-640]],"16,15":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-384,-640]],"17,25":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-256,-640]],"18,14":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-640]],"18,25":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-288,-640]],"19,9":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-448,-640]],"20,10":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-320,-640]],"20,11":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-352,-640]],"20,19":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-448,-640]],"21,6":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-352,-640]],"21,21":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-448,-640]],"22,8":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-448,-640]],"23,15":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-192,-640]],"23,20":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-448,-640]],"25,3":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-448,-640]],"27,2":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-352,-640]],"27,26":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-448,-640]],"30,5":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-448,-640]],"30,9":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-448,-640]],"30,14":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-160,-640]],"30,23":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-448,-640]],"1,14":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-128,-576]],"1,15":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-64,-576]],"1,16":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-352,-576]],"2,14":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-160,-576]],"2,15":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-32,-576]],"3,15":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-576]],"3,16":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-192,-576]],"4,14":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-128,-576]],"4,15":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-96,-576]],"5,14":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-288,-576]],"6,15":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-128,-576]],"6,16":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-192,-576]],"7,16":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-32,-576]],"8,14":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-576]],"8,16":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-224,-576]],"9,14":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-576]],"9,15":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-224,-576]],"10,14":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-384,-576]],"11,16":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-256,-576]],"12,14":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-576]],"12,15":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-64,-576]],"12,16":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-32,-576]],"13,14":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-160,-576]],"14,15":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-576]],"14,16":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-224,-576]],"15,14":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-320,-576]],"15,15":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-32,-576]],"17,14":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-128,-576]],"17,15":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-32,-576]],"18,16":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-192,-576]],"19,14":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-576]],"19,16":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-224,-576]],"20,14":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-576]],"20,15":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-32,-576]],"21,14":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-160,-576]],"21,15":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-96,-576]],"21,16":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-352,-576]],"23,14":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-128,-576]],"24,14":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-576]],"24,15":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-32,-576]],"25,14":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-160,-576]],"25,16":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-192,-576]],"26,15":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-160,-576]],"26,16":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-32,-576]],"27,14":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-256,-576]],"27,16":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-384,-576]],"28,14":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-576]],"28,15":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-64,-576]],"28,16":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-32,-576]],"29,14":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",0,-576]],"29,16":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-32,-576]],"30,15":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-96,-576]],"30,16":[["","",null,null],["static.gif","spacer.gif",-192,0],["TerrainBlend.gif","spacer.gif",-224,-576]]}';

mappages["miningvillage"].desc = "Mining Village";
mappages["miningvillage"].longdesc = `A chill wind blows through this empty village. Ramshackle dwellings built in the valley between two hills still stand, but the degradation due to time is evident.`;
mappages["miningvillage"].music = 'Village';
mappages["miningvillage"].savename = `Mining Village`;
mappages["miningvillage"].exitmap = 'island';
mappages["miningvillage"].exitx = '31';
mappages["miningvillage"].exity = '78';
mappages["miningvillage"].wraps = '';
mappages["miningvillage"].enterx = '1';
mappages["miningvillage"].entery = '15';
mappages["miningvillage"].seeBelow = '';
mappages["miningvillage"].lightLevel = 'cycle';
mappages["miningvillage"].alwaysRemember = '0';
mappages["miningvillage"].scale = '1';
mappages["miningvillage"].underground = '0';
mappages["miningvillage"].undergroundDesc = '';
mappages["miningvillage"].enterscript = '';
mappages["miningvillage"].entertestscript = '';
mappages["miningvillage"].exitscript = '';
mappages["miningvillage"].exittestscript = '';
mappages["miningvillage"].returnmap = 'ellusus';
mappages["miningvillage"].returnx = '69';
mappages["miningvillage"].returny = '74';
mappages["miningvillage"].returninfused = '1';
mappages["miningvillage"].automap = '1';
mappages["miningvillage"].linkedMaps = [""];
mappages["miningvillage"].editorLabels = '{}';
// MAP ENDS HERE

mappages["miningvillage"].onload = function(mapref) {
  if ((gamestate.getMode() !== "loadgame") && (!DU.gameflags.getFlag("editor"))) {
    if (PC.checkInventory("VoidstoneSculpture") || DU.gameflags.getFlag("infinite_scroll")) {
      let art = mapref.getTile(8,23).getTopFeature();
      mapref.deleteThing(art);
    }
  }
}