mappages["nassau"] = {};
mappages["nassau"].terrain = [];
 mappages["nassau"].terrain[0] = '.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..';
 mappages["nassau"].terrain[1] = '.. .. ## ## ## ## ## #O ## ## ## ## ## ## ## #O ## ## ## .. ,, .. .. .. ,, .. .. .. ,; .. .. ..';
 mappages["nassau"].terrain[2] = '.. ,, ## ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ,, .. .. ,, .. .. ,; ,, .. .. ,, .. ..';
 mappages["nassau"].terrain[3] = '.. .. ## ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .. .. ,, ,, .. .. ,, ,, .. .. ..';
 mappages["nassau"].terrain[4] = '.. .. ## ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. ,, .. .. .. .. .. .. .. .. .. ..';
 mappages["nassau"].terrain[5] = ',, .. ## ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .. .. ,, .. ,, .. .. .. .. .. ..';
 mappages["nassau"].terrain[6] = '.. .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. ,, .. .. .. .. .. .. .. ,, .. .. ..';
 mappages["nassau"].terrain[7] = '.. .. ## ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .. ,, ,, .. ,, .. .. .. .. ,, ..';
 mappages["nassau"].terrain[8] = '.. .. ## ## ## ## ## ## ## ## ## ## ## ## ## ## ++ ## ## ,, ,, .. .. .. .. .. ,, .. .. .. .. ..';
 mappages["nassau"].terrain[9] = '.. ,, .. .. ,, .. .. ,, .. .. ,, .. ,, ,, ,, .. .. .. .. ,, .. .. .. .. .. .. .. .. .. .. .. ..';
mappages["nassau"].terrain[10] = ',, .. ,, .. .. .. .. ,, ,, .. .. ,, ,, .. .. .. .. .. ,, ,, .. ## ## ## ## ## ## ## ## ## ## ,,';
mappages["nassau"].terrain[11] = '.. .. .. ,, .. .. ,, .. .. .. .. .. .. .. ,, .. .. .. ,, .. .. ## ++ ++ ++ ++ ++ ++ ++ ++ ## ,,';
mappages["nassau"].terrain[12] = '.. ,, ,, ,, .. ,, ,, ,, ,, ,, .. ,, .. ,, ,, .. .. .. ,, ,, ,, ## ++ ++ ++ ++ ++ ++ ++ ++ ## ..';
mappages["nassau"].terrain[13] = '.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ## ++ ++ ++ ++ ++ ++ ++ ++ ## ..';
mappages["nassau"].terrain[14] = '.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ,,';
mappages["nassau"].terrain[15] = '.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ## ++ ++ ++ ++ ++ ++ ++ ++ ## ..';
mappages["nassau"].terrain[16] = ',, .. ,, .. ,, ,, .. ,, .. .. ,, .. .. ,, ,, .. .. .. ,, ,, ,, ## ++ ++ ++ ## ## ## ## ## ## ..';
mappages["nassau"].terrain[17] = '.. ## ## ## ## ## ## ## ## ## ## .. .. .. ,, .. .. .. ,, ,; ,; ## ++ ++ ++ ## ++ ++ ++ ++ ## ..';
mappages["nassau"].terrain[18] = ',, ## ## ## ## ## ++ ## ## ## ## ,, ,, .. .. .. .. .. .. ,; .. ## ++ ++ ++ ## ++ ++ ++ ++ #O ,,';
mappages["nassau"].terrain[19] = '.. ## ++ ++ ++ ++ ++ ++ ++ ++ ## ,, .. .. ,, .. .. .. ,, .. ,; ## ++ ++ ++ ## ++ ++ ++ ++ ## ..';
mappages["nassau"].terrain[20] = '.. #O ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. ,, ,, .. .. .. .. ,, .. ## ++ ++ ++ ++ ++ ++ ++ ++ ## ..';
mappages["nassau"].terrain[21] = '.. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ .. .. .. ,, .. .. .. ,, .. .. ## ++ ++ ++ ## ## ## ## ## ## ..';
mappages["nassau"].terrain[22] = '.. ## ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. ,, ,, .. .. .. ,, ,, .. ## ++ ++ ++ ## ++ ++ ++ ++ ## ,,';
mappages["nassau"].terrain[23] = ',, ## ++ ++ ++ ++ ++ ++ ## ++ ## .. ,, .. ,, .. .. .. .. .. .. ## ++ ++ ++ ## ++ ++ ++ ++ #O ..';
mappages["nassau"].terrain[24] = '.. ## ++ ++ ++ ++ ++ ++ ## ++ ## .. .. .. .. .. .. .. ,, .. .. ## ++ ++ ++ ## ++ ++ ++ ++ ## ,,';
mappages["nassau"].terrain[25] = '.. ## ++ ++ ++ ++ ++ ++ ## ++ ## .. .. ,, ,, .. .. .. ,, ,, .. ## ++ ++ ++ ++ ++ ++ ++ ++ ## ..';
mappages["nassau"].terrain[26] = '.. ## ## ## #O ## ## ## ## ## ## .. .. ,, .. .. .. .. ,; ,, .. ## ## ## ## ## ## ## ## ## ## ..';
mappages["nassau"].terrain[27] = '.. .. .. ,, ,, .. .. ,, .. .. .. ,; .. .. ,, .. .. .. ,, .. .. ,, .. ,, ,, .. .. .. .. .. .. ..';
mappages["nassau"].terrain[28] = '.. ,, ,, ,, .. .. ,, .. ,; .. ,, .. ,, .. ,, .. .. .. ,, ,, .. .. .. .. .. .. ,, .. ,, .. .. ..';
mappages["nassau"].terrain[29] = ',, .. ,, .. ,, ,, .. ,; ,; .. ,, ,, .. .. ,, .. .. .. .. .. ,, .. .. ,, ,, .. .. ,, .. .. .. ,,';
mappages["nassau"].terrain[30] = '.. .. ,, .. .. .. ,, .. ,, ,, .. ,, .. ,, ,, .. .. .. ,, .. ,; ,, ,, .. .. ,, .. .. .. ,, .. ..';
mappages["nassau"].terrain[31] = '.. .. .. ,, .. .. .. .. ,, ,, .. .. .. .. ,, .. .. .. ,, ,, .. ,, .. ,; .. .. .. .. .. .. .. ..';

mappages["nassau"].features = [];
mappages["nassau"].features[0] = {name : 'DoorWindow', x : 10, y : 21};
mappages["nassau"].features[1] = {name : 'DoorWindow', x : 21, y : 14};
mappages["nassau"].features[2] = {name : 'Door', x : 25, y : 25};
mappages["nassau"].features[3] = {name : 'Door', x : 25, y : 20};
mappages["nassau"].features[4] = {name : 'DoorWindow', x : 16, y : 8};
mappages["nassau"].features[5] = {name : 'Well', x : 26, y : 4};
mappages["nassau"].features[6] = {name : 'SingleSignpost', x : 19, y : 16};
mappages["nassau"].features[7] = {name : 'InnSign', x : 19, y : 15, prefix : "", desc : "Ye Olde Inn"};
mappages["nassau"].features[8] = {name : 'SignpostLeft', x : 13, y : 10};
mappages["nassau"].features[9] = {name : 'SignpostRight', x : 15, y : 10};
mappages["nassau"].features[10] = {name : 'TavernSign', x : 14, y : 10, prefix : "", desc : "The Red Hen Tavern"};
mappages["nassau"].features[11] = {name : 'LeftTable', x : 4, y : 3};
mappages["nassau"].features[12] = {name : 'MiddleTable', x : 5, y : 3};
mappages["nassau"].features[13] = {name : 'MiddleTable', x : 6, y : 3};
mappages["nassau"].features[14] = {name : 'RightTable', x : 7, y : 3};
mappages["nassau"].features[15] = {name : 'Fireplace', x : 3, y : 6};
mappages["nassau"].features[16] = {name : 'LeftTable', x : 7, y : 6};
mappages["nassau"].features[17] = {name : 'RightTable', x : 8, y : 6};
mappages["nassau"].features[18] = {name : 'LeftTable', x : 12, y : 3};
mappages["nassau"].features[19] = {name : 'RightTable', x : 13, y : 3};
mappages["nassau"].features[20] = {name : 'LeftTable', x : 15, y : 5};
mappages["nassau"].features[21] = {name : 'RightTable', x : 16, y : 5};
mappages["nassau"].features[22] = {name : 'LeftChair', x : 6, y : 6};
mappages["nassau"].features[23] = {name : 'TopChair', x : 13, y : 2};
mappages["nassau"].features[24] = {name : 'TopChair', x : 16, y : 4};
mappages["nassau"].features[25] = {name : 'RightChair', x : 17, y : 5};
mappages["nassau"].features[26] = {name : 'LeftTable', x : 27, y : 13};
mappages["nassau"].features[27] = {name : 'MiddleTable', x : 28, y : 13};
mappages["nassau"].features[28] = {name : 'RightTable', x : 29, y : 13};
mappages["nassau"].features[29] = {name : 'BedHead', x : 28, y : 17};
mappages["nassau"].features[30] = {name : 'BedHead', x : 28, y : 22};
mappages["nassau"].features[31] = {name : 'BedFoot', x : 29, y : 17};
mappages["nassau"].features[32] = {name : 'BedFoot', x : 29, y : 22};
mappages["nassau"].features[33] = {name : 'Mirror', x : 26, y : 17};
mappages["nassau"].features[34] = {name : 'Mirror', x : 26, y : 22};
mappages["nassau"].features[35] = {name : 'UnlitBrazier', x : 29, y : 19};
mappages["nassau"].features[36] = {name : 'UnlitBrazier', x : 29, y : 24};
mappages["nassau"].features[37] = {name : 'Brazier', x : 23, y : 11};
mappages["nassau"].features[38] = {name : 'Fireplace', x : 6, y : 18};
mappages["nassau"].features[39] = {name : 'BedHead', x : 2, y : 22};
mappages["nassau"].features[40] = {name : 'BedHead', x : 2, y : 24};
mappages["nassau"].features[41] = {name : 'BedHead', x : 5, y : 22};
mappages["nassau"].features[42] = {name : 'BedHead', x : 5, y : 24};
mappages["nassau"].features[43] = {name : 'BedFoot', x : 6, y : 22};
mappages["nassau"].features[44] = {name : 'BedFoot', x : 6, y : 24};
mappages["nassau"].features[45] = {name : 'BedFoot', x : 3, y : 24};
mappages["nassau"].features[46] = {name : 'BedFoot', x : 3, y : 22};
mappages["nassau"].features[47] = {name : 'BookshelfLeft', x : 8, y : 19};
mappages["nassau"].features[48] = {name : 'BookshelfRight', x : 9, y : 19};
mappages["nassau"].features[49] = {name : 'LeftTable', x : 4, y : 20};
mappages["nassau"].features[50] = {name : 'RightTable', x : 5, y : 20};
mappages["nassau"].features[51] = {name : 'Door', x : 9, y : 23, desc : "locked door", locked : 1};


mappages["nassau"].npcs = [];
mappages["nassau"].npcs[0] = {name : 'ShepherdVillagerNPC', x : 28, y : 4, NPCName: 'Samuel', Desc: 'blind shepherd', Alignment: 'good', Conversation: 'samuel', Gender: 'male'};
mappages["nassau"].npcs[1] = {name : 'TownsfolkVillagerNPC', x : 28, y : 12, NPCName: 'Daniel', Alignment: 'good', Conversation: 'daniel', Gender: 'male'};
mappages["nassau"].npcs[2] = {name : 'TinkerVillagerNPC', x : 23, y : 24, NPCName: 'Kyvek', Conversation: 'kyvek', ConversationFlag: 'debt_paid', Gender: 'male', Bark: '0', NPCBand: '0'};
mappages["nassau"].npcs[3] = {name : 'DruidVillagerNPC', x : 3, y : 20, NPCName: 'Hazel', Desc: 'healer', Conversation: 'hazel', ConversationFlag: 'given_hood', Gender: 'female', Bark: '0', NPCBand: '0'};
mappages["nassau"].npcs[4] = {name : 'RangerVillagerNPC', x : 11, y : 3, NPCName: 'Garen', Alignment: 'good', Conversation: 'garen', Gender: 'male'};
mappages["nassau"].npcs[5] = {name : 'AdventurerVillagerNPC', x : 13, y : 4, NPCName: 'Warren', Alignment: 'good', Conversation: 'warren', Gender: 'male'};
mappages["nassau"].npcs[6] = {name : 'PaladinVillagerNPC', x : 9, y : 6, NPCName: 'Amaeryl', Alignment: 'good', Conversation: 'amaeryl', Gender: 'female'};
mappages["nassau"].npcs[7] = {name : 'TownGuardNPC', x : 8, y : 13, NPCName: 'Guard', Alignment: 'good', Conversation: 'nassau_guard', Gender: 'male'};
mappages["nassau"].npcs[8] = {name : 'TownsfolkVillagerNPC', x : 25, y : 3, NPCName: 'Kylee', Desc: 'farmer', Alignment: 'good', Conversation: 'kylee', ConversationFlag: 'rescued_sam', Gender: 'female'};
mappages["nassau"].npcs[9] = {name : 'TownsfolkVillagerNPC', x : 5, y : 2, NPCName: 'Ingrid', Alignment: 'good', Conversation: 'ingrid', Gender: 'female'};

mappages["nassau"].desc = "the Village of Nassau";
mappages["nassau"].music = 'Towne';
mappages["nassau"].exitmap = 'darkunknown';
mappages["nassau"].exitx = '72';
mappages["nassau"].exity = '75';
mappages["nassau"].wraps = 'None';
mappages["nassau"].enterx = '16';
mappages["nassau"].entery = '30';
mappages["nassau"].seeBelow = '';
mappages["nassau"].lightLevel = 'bright';
mappages["nassau"].alwaysRemember = '0';
mappages["nassau"].scale = '1';
mappages["nassau"].enterscript = '';
mappages["nassau"].entertestscript = '';
mappages["nassau"].exitscript = '';
mappages["nassau"].exittestscript = '';
mappages["nassau"].returnmap = 'darkunknown';
mappages["nassau"].returnx = '29';
mappages["nassau"].returny = '43';
mappages["nassau"].returninfused = '0';
mappages["nassau"].linkedMaps = [""];

mappages["nassau"].onload = function(mapref) {
  
  if (DU.gameflags["rescued_sam"]) {
    var sam = localFactory.createTile("ChildVillagerNPC");
    sam.setNPCName("Samantha");
    sam.setConversation("samantha2");
    sam.setGender("female");
    sam.setDesc("excited girl");
    sam.setPrefix("an");
    sam.setBark("sam");
    sam.setLeash(3);
    mapref.placeThing(23,4,sam);
  }
}