"use strict";

mappages["naurglen"] = {};
mappages["naurglen"].terrain = [];
 mappages["naurglen"].terrain[0] = '.. ,, .. .. ,, ,, .. .. .. .. ,, .. .. ,, .. .. .. .. .. u, .. .. .. .. .. .. u, .. .. .. .. .. u, .. .. .. .. .. .. .. .. .. .. .. ,, .. .. .. RR .. u, .. ,, .. .. .. .. .. .. .. .. u, .. .. .. ,, .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..';
 mappages["naurglen"].terrain[1] = '.. ,, .. .. .. u, .. .. .. ,, .. .. .. .. #% .. .. .. .. ,, .. .. .. ,, .. ,, .. .. .. ,, .. .. .. ,, ,, .. .. ,, .. .. ,, .. ,, .. .. .. .. .. RR RR RR .. .. .. .. u, .. .. .. .. .. .. .. .. .. .. .. .. ,, .. .. u, .. .. ,, .. .. ,, ,, .. .. .. u, .. ,, .. .. .. .. ,, ,, .. .. .. .. .. .. .. .. ..';
 mappages["naurglen"].terrain[2] = '.. .. .. u, .. .. ## ## ## ## ## ## ## .. .. .. .. #% .. .. .. u, .. .. .. .. ,, .. .. .. .. ,, .. .. ,, .. u, .. ,, .. .. .. .. .. .. ,, .. .. .. u, RR RR .. ,, .. .. ,, .. .. .. ,, .. ,, u, ,, ,, .. .. .. ,, ,, ,, ,, .. .. .. ,, .. ,, .. .. ,, .. .. ,, .. .. ,, .. .. .. .. u, ,, ,, .. .. .. .. ..';
 mappages["naurglen"].terrain[3] = '.. .. ,, ,, .. .. ## -= -= -= -= -= ## .. #% .. .. .. ,, .. ## ## ## #O ## ## ## ## .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ,, .. .. .. .. .. .. RR .. .. .. .. .. .. .. .. .. .. .. .. ,, .. .. ,, .. .. .. .. ,, ,, .. .. .. ,, .. ,, ,, .. .. .. u, ,, .. ,, u, ,, .. .. ,, .. .. .. .. .. ,, ..';
 mappages["naurglen"].terrain[4] = '.. .. .. ,, .. .. #O -= -= -= -= -= -= .. .. .. .. .. .. .. ## -= -= -= -= -= -= ## .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. RR RR RR .. .. .. .. .. .. .. u, .. .. .. .. ,, ,, .. ,, ,, .. .. .. .. .. u, ,, .. .. .. ,, .. ,, ,, .. .. .. .. .. .. .. u, .. .. .. .. ,, .. ,,';
 mappages["naurglen"].terrain[5] = '.. ,, .. .. .. .. ## -= -= -= -= -= ## .. #% .. .. .. .. ,, ## -= -= -= -= -= ## ## ,, .. .. .. .. .. .. .. .. .. .. .. .. ,, .. ## ## ## ## ## ## ## ## ## .. RR .. ,, .. .. .. .. .. ,, ,, .. .. u, ,, .. .. u, .. .. .. ,, .. .. .. .. RR .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..';
 mappages["naurglen"].terrain[6] = '.. .. .. .. .. .. ## -= -= -= -= -= ## .. .. .. .. #% .. .. ## -= -= -= -= -= ## ## .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ## ## ## ## -= ## ## ## ## .. RR RR RR .. ,, .. .. .. .. .. .. ,, .. .. ,, .. .. ,, ,, ,, ,, .. ,, ,, .. RR RR RR ,, .. .. ,, ,, .. .. ,, .. .. .. u, .. .. ,, ,, .. .. u,';
 mappages["naurglen"].terrain[7] = '.. .. ,, .. ,, .. ## ## ## #O ## ## ## .. .. .. .. .. .. .. -= -= -= -= -= -= ## ## .. .. .. .. .. .. .. .. .. .. .. .. .. ,, .. ## -= -= -= -= -= -= -= ## .. ,, .. RR RR .. .. .. .. .. u, .. ,, .. .. .. .. .. .. ,, .. .. u, .. ,, ,, .. .. RR u, .. .. .. .. .. .. .. .. ,, .. .. .. .. ,, .. .. RR ..';
 mappages["naurglen"].terrain[8] = '.. u, .. .. .. .. .. .. .. ,, ,, .. .. .. #% .. .. .. .. .. ## -= -= -= -= -= ## ## .. .. .. .. .. .. .. .. .. .. .. .. ,, .. .. ## -= -= -= -= -= -= -= ## .. .. u, ,, RR .. .. !! RR RR RR RR .. .. RR RR RR .. .. .. .. u, .. .. .. u, .. .. RR .. .. .. .. RR RR RR RR .. .. RR RR RR RR .. RR RR RR ..';
 mappages["naurglen"].terrain[9] = '.. ,, .. .. .. .. .. .. ,, .. .. .. ,, .. .. .. .. .. #% .. ## ## ## #O ## ## ## ## .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. #O -= -= -= -= -= -= -= #O .. ,, .. .. RR RR RR !! .. .. .. RR RR RR RR .. RR RR RR RR RR RR RR .. .. .. RR RR RR RR RR !! RR RR .. .. RR RR RR RR .. u, RR u, RR .. ,, ..';
mappages["naurglen"].terrain[10] = '.. .. .. .. .. ,, .. .. .. .. .. .. .. .. .. .. .. .. .. ,, .. .. .. .. .. .. ,, .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ## -= -= -= -= -= -= -= ## .. RR RR RR RR .. .. .. .. .. ,, .. u, .. ,, .. .. RR u, ,, .. .. RR RR RR RR RR .. .. .. .. .. .. .. .. ,, .. .. .. .. .. .. RR RR RR ,, .. ..';
mappages["naurglen"].terrain[11] = '.. .. .. ,, ,, ,, FF FF FF FF FF FF FF .. .. #% .. .. .. .. .. ,, .. .. .. .. .. .. .. .. .. .. ., ., .. .. .. .. .. .. .. .. .. ## ## ## #O ## -= ## ## ## .. RR .. .. .. #% .. .. .. #% .. ,, .. ,, .. .. .. .. .. ,, ,, ,, .. .. ,, .. .. ,, ,, #% .. .. .. .. u, .. u, .. ,, .. .. .. .. .. RR RR .. ,,';
mappages["naurglen"].terrain[12] = '.. ,, ,, .. u, .. FF FF FF FF FF FF FF ,, .. .. .. .. #% .. .. .. .. .. ,, .. .. ## ## ## .. .. ., ., .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. RR RR .. .. .. .. .. .. .. .. ,, .. ## ## ## #O ## ## ## u, ## ## ## #O ## ## ## .. .. .. .. .. .. #% .. .. ,, ,, .. .. .. ,, .. .. .. RR .. ,,';
mappages["naurglen"].terrain[13] = '.. .. .. .. .. .. FF FF FF FF FF FF FF .. .. .. .. .. .. u, .. .. .. .. .. u, ## ## -= ## ## .. ., .. .. ., ., ., ., ., ., ., .. .. ,, .. .. .. .. .. .. RR RR .. .. .. .. .. .. .. .. #% .. u, ## -= -= -= -= -= ## .. ## -= -= -= -= -= ## u, ,, #% .. .. .. .. .. .. .. .. u, u, .. .. .. .. ,, RR .. ..';
mappages["naurglen"].terrain[14] = '.. .. .. .. .. .. FF FF FF FF FF FF FF .. .. .. .. .. .. .. .. .. ,, .. .. ## ## -= -= -= ## ## ., .. .. ., ., ., ., ., ., ., .. .. .. .. .. .. .. .. RR RR .. ,, .. .. .. #% .. .. .. .. u, ,, -= -= -= -= -= -= ## ,, ## -= -= -= -= -= -= .. .. .. .. .. .. #% .. ,, ## ## ## ## #O ## ## .. .. RR RR ..';
mappages["naurglen"].terrain[15] = '.. ,, ,, .. .. .. FF FF FF FF FF FF FF .. .. #% .. .. .. .. .. .. .. .. .. ## -= -= -= -= -= -= ., .. .. ., ., ., ., ., ., ., .. .. .. ,, .. ,, .. .. RR .. .. .. .. .. .. .. .. .. .. .. ,, .. ## -= -= -= -= -= ## .. ## -= -= -= -= -= ## ,, ,, .. .. .. .. .. ,, .. ## -= -= -= -= -= ## .. u, RR RR ,,';
mappages["naurglen"].terrain[16] = ',, u, .. .. .. .. FF FF FF FF FF FF FF .. .. .. .. .. #% .. .. .. .. .. .. ## ## -= -= -= ## ## ., .. .. ., ., ., ., ., ., ., .. .. ,, .. .. .. .. .. RR .. .. .. .. ,, ,, #% .. .. .. .. #% .. ## -= -= -= -= -= ## ,, ## -= -= -= -= -= ## ,, .. #% .. .. .. #% ,, .. ## -= -= -= -= -= ## .. ,, RR .. ,,';
mappages["naurglen"].terrain[17] = '.. .. .. .. ,, ,, .. .. .. .. .. .. .. .. .. .. .. .. .. ,, .. .. .. .. .. .. ## ## -= ## ## .. ., .. .. ., ., ., ., ., ., ., .. .. .. ,, .. ,, .. RR RR .. .. .. .. ,, .. .. .. .. .. .. .. ,, ## ## ## ## ## ## ## .. ## ## ## ## ## ## ## .. u, .. .. .. .. .. .. .. -= -= -= -= -= -= ## u, .. RR ,, ,,';
mappages["naurglen"].terrain[18] = '.. .. ,, .. .. .. ,, .. .. ,, .. ,, .. .. .. .. .. .. .. .. .. ,, .. .. .. .. ,, ## ## ## .. ., ., ., .. .. .. .. .. .. .. .. .. .. .. .. .. .. RR RR .. .. ,, .. .. .. .. .. .. .. .. .. .. .. .. ,, ,, ,, .. .. .. u, ,, .. ,, ,, u, .. ,, ,, .. #% .. .. .. #% .. ,, ## -= -= -= -= -= ## ,, .. RR ,, ..';
mappages["naurglen"].terrain[19] = '.. .. .. .. ## ## ## ## ## ## ## ## .. .. #% .. .. .. .. .. u, .. u, .. .. .. .. .. .. .. .. ., ., ., ., ., .. .. .. .. .. .. .. .. RR RR .. .. RR .. .. .. .. .. .. .. .. #% .. .. .. #% u, .. ,, .. .. ,, ,, .. ,, ,, ,, u, .. .. .. .. .. .. ,, .. .. .. .. .. .. .. ## -= -= -= -= -= ## .. .. RR .. ..';
mappages["naurglen"].terrain[20] = '.. .. .. u, ## -= -= -= -= -= -= ## .. .. .. .. .. .. #% .. ## ## ## ## #O ## ## ## ## .. ., ., ., RR RR RR RR RR RR RR RR RR RR RR RR RR RR RR RR .. .. .. .. .. .. .. .. .. .. .. .. .. ,, .. ## ## ## ## ## ## #O ## ## ## #O ## ## ## ## .. .. #% .. .. .. #% .. u, ## ## ## ## #O ## ## ,, .. RR RR ..';
mappages["naurglen"].terrain[21] = '.. ,, .. .. ## -= -= -= -= -= -= ## .. .. .. .. .. .. .. .. ## -= -= -= -= -= -= -= ## .. ., .. RR RR gF FF gF FF gF FF gF FF gF .. .. ,, .. RR .. .. ,, .. .. ,, ,, .. .. .. .. .. .. #% ,, u, ## ## -= -= -= -= -= -= -= -= -= -= -= -= ## ,, u, .. .. .. .. .. ,, .. .. .. .. .. .. .. .. .. ,, .. RR ,,';
mappages["naurglen"].terrain[22] = '.. .. ,, .. #O -= -= -= -= -= -= #O .. .. .. .. .. .. .. .. ## -= -= -= -= -= -= -= -= ., ., RR RR .. gF FF gF FF gF FF gF FF gF .. .. .. RR RR .. .. .. .. .. .. .. .. .. #% .. .. .. .. .. ,, ## ## -= -= -= -= -= -= -= -= -= -= -= -= #O .. ,, #% .. .. .. #% .. .. .. u, .. ,, .. ,, ,, ,, .. RR RR ..';
mappages["naurglen"].terrain[23] = 'u, .. .. .. ## -= -= -= -= -= -= ## .. .. .. .. .. .. #% .. ## -= -= -= -= ## ## ## ## .. ., RR .. .. gF FF gF FF gF FF gF FF gF .. .. RR RR .. ,, .. .. ,, .. .. .. ,, .. .. .. .. .. .. ,, u, ## -= -= -= -= -= -= -= -= -= -= -= -= -= ## .. .. .. .. .. .. .. .. ,, ,, .. ,, ,, u, ,, ,, .. .. RR .. ,,';
mappages["naurglen"].terrain[24] = '.. ,, .. .. ## -= -= -= -= -= -= ## .. .. #% .. .. .. .. .. ## -= -= -= -= #O ,, .. .. RR RR RR .. .. gF FF gF FF gF FF gF FF gF .. .. RR .. .. .. .. .. .. .. .. .. .. .. #% .. .. .. #% u, .. ## ## -= -= -= -= -= -= -= -= -= -= -= -= ## .. .. #% .. .. .. #% ,, .. .. .. .. .. u, .. u, .. .. RR RR ..';
mappages["naurglen"].terrain[25] = ',, .. ,, u, ## ## ## -= ## ## ## ## .. .. .. .. .. .. .. .. ## ## ## ## ## ## .. .. RR RR .. .. .. .. gF FF gF FF gF FF gF FF gF .. RR RR ,, .. .. ,, .. .. .. ,, .. .. .. .. .. .. .. .. ,, .. ## ## -= -= -= -= -= -= -= -= -= -= -= -= -= .. .. .. .. .. .. .. .. u, ## ## ## ## ## ## ## ## ,, .. RR ..';
mappages["naurglen"].terrain[26] = '.. u, .. .. ,, .. .. .. .. .. .. .. .. .. .. .. .. .. #% .. .. ,, ,, .. .. .. .. RR RR .. .. .. ,, .. gF FF gF FF gF FF gF FF gF .. RR RR .. .. .. .. .. .. .. .. .. #% .. .. .. .. .. #% .. ,, ## ## ## -= ## ## #O ## ## ## #O ## ## ## ## .. ,, #% .. .. .. .. #% ,, ## ++ ++ ++ ++ ++ ++ ## .. .. RR ..';
mappages["naurglen"].terrain[27] = '.. .. ,, ,, .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. u, .. .. .. ,, .. RR RR .. .. ,, .. .. .. .. .. .. .. .. .. .. .. .. .. ,, RR .. #% .. #% .. .. #% .. .. .. .. .. .. .. .. .. .. ,, .. ,, .. .. .. .. .. ,, ,, ,, .. .. ,, .. .. u, .. .. .. .. .. .. .. .. ## ++ ++ ++ ++ ++ ++ ## u, RR RR ..';
mappages["naurglen"].terrain[28] = '.. ,, .. .. .. .. .. .. #% .. .. .. .. #% .. .. .. .. .. #% .. .. .. .. RR RR RR .. .. #% .. .. .. .. .. #% .. .. ,, .. .. .. .. ,, .. RR .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. #% .. .. #% .. #% .. #% .. #% .. #% .. #% .. #% .. #% .. .. .. .. .. #% ,, ## ++ ++ ++ ++ ++ ++ #O u, RR .. ,,';
mappages["naurglen"].terrain[29] = '.. .. .. .. #% .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. RR RR .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. #% .. .. .. RR RR .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ++ ++ ++ ++ ++ ++ ++ ## .. RR RR ..';
mappages["naurglen"].terrain[30] = '.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. RR .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. RR .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. #% .. ## ++ ++ ++ ++ ++ ++ ## .. ,, RR ,,';
mappages["naurglen"].terrain[31] = '.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. RR RR .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. -= .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ,, ## ++ ++ ## ## ## ## ## ,, ,, RR ..';
mappages["naurglen"].terrain[32] = '.. .. .. .. .. .. .. .. #% .. .. .. .. #% .. .. .. #% .. .. .. RR RR .. .. .. #% .. .. .. .. .. .. .. #% .. .. .. .. .. .. .. .. .. RR .. .. #% .. .. #% .. .. .. .. .. .. .. .. .. #% .. .. #% .. #% .. #% .. #% .. #% .. #% .. .. #% .. #% .. #% .. .. .. .. .. #% .. ## ++ ++ ## ++ ++ ++ ## ,, .. RR ..';
mappages["naurglen"].terrain[33] = '.. .. .. #% .. .. #% .. ,, .. .. .. .. .. .. .. .. .. ,, .. .. RR ,, .. .. .. .. .. .. .. .. ,, .. .. .. ,, .. .. .. #% .. .. .. .. RR .. .. .. .. .. .. .. u, #% .. .. #% .. .. ,, .. .. .. .. ,, ,, .. ,, .. ,, u, .. .. .. u, u, ,, .. u, ,, .. .. .. .. .. .. ,, .. ## ++ ++ ## ++ ++ ++ #O .. RR RR ..';
mappages["naurglen"].terrain[34] = ',, .. .. u, .. .. .. .. .. .. .. .. .. .. ,, .. ,, ,, .. u, .. RR .. .. .. ,, .. .. .. .. .. .. ,, .. .. .. .. .. .. .. .. .. .. RR RR #% .. u, .. ,, .. ,, .. .. .. ,, .. .. .. ,, ,, .. ,, .. .. ## ## ## ## #O ## ## ## ## #O ## ## -= ## ## ,, #% .. .. .. #% .. .. ## ++ ++ ++ ++ ++ ++ ## u, RR .. ,,';
mappages["naurglen"].terrain[35] = '.. .. .. .. .. .. ,, .. .. .. .. .. .. .. .. u, ,, .. .. .. RR RR ,, .. ## ## ## ## ## -= ## ## .. .. FF gF FF gF FF gF FF .. RR RR .. .. ,, .. .. .. ## ## ## #O ## ## ## -= ## ## ## .. ,, u, ,, ## ## -= -= -= -= -= ## -= -= -= -= -= -= ## .. .. .. .. .. .. .. .. ## ++ ++ ## ## ## ## ## u, RR .. ..';
mappages["naurglen"].terrain[36] = '.. u, .. .. ,, .. ## ## ## ## ++ ## ## ## ## ## .. .. .. ,, RR .. .. .. ## -= -= -= -= -= -= ## .. .. FF gF gF gF FF gF FF .. RR .. ,, .. .. .. ,, .. ## -= -= -= -= ## -= -= -= -= ## .. ,, .. .. ## ## -= -= -= -= -= -= -= -= -= -= -= -= #O .. #% .. .. .. .. .. .. ## ++ ++ ## ++ ++ ++ ## .. RR RR ..';
mappages["naurglen"].terrain[37] = '.. ,, .. ,, .. .. ## ++ ++ ++ ++ ++ ++ ++ ## ## ,, .. ,, RR RR .. .. .. #O -= -= -= -= -= -= #O .. .. FF gF FF FF FF gF FF .. RR RR .. ,, ,, ,, .. .. #O -= -= -= -= ## -= -= -= -= #O .. u, u, .. ## -= -= -= -= -= -= ## -= -= -= -= -= -= ## .. .. .. .. .. #% ,, .. ## ++ ++ ## ++ ++ ++ #O ,, u, RR ..';
mappages["naurglen"].terrain[38] = '.. .. .. .. ,, .. ## ++ ++ ++ ++ ++ ++ ++ ## ## .. ,, ,, RR .. .. .. .. ## -= -= -= -= -= -= ## .. .. FF gF FF gF FF gF FF .. .. RR .. .. ,, .. .. .. ## -= -= -= -= -= -= -= -= -= ## ,, ,, ,, .. ## ## -= -= -= -= -= ## -= -= -= -= -= -= ## .. .. .. .. .. .. ,, ,, ## ++ ++ ++ ++ ++ ++ ## ,, .. RR ..';
mappages["naurglen"].terrain[39] = '.. ,, ,, .. .. .. #O ++ ++ ++ ++ ++ ++ ++ ## ## .. .. .. RR .. ,, .. .. ## -= -= -= -= -= -= ## .. .. FF gF FF gF FF gF FF .. u, RR RR u, .. .. ,, .. ## -= -= -= -= ## -= -= -= -= ## .. .. ,, u, ## ## -= -= -= -= -= ## -= -= -= -= -= -= ## .. #% .. .. .. #% .. ,, ## ## ## ## ## ## ## ## .. RR RR ..';
mappages["naurglen"].terrain[40] = '.. u, .. ,, u, .. ## ++ ++ ++ ++ ++ ++ ++ ++ ## ,, .. RR RR .. u, ,, .. ## -= -= -= -= -= -= ## .. u, FF FF FF gF FF gF FF .. .. .. RR RR .. .. ,, u, ## ## ## #O ## ## ## #O ## ## ## .. .. ,, .. ## ## -= -= -= -= -= ## -= -= -= -= -= -= ## ,, .. .. .. .. .. u, ,, u, .. .. .. ,, u, .. ,, .. RR .. ,,';
mappages["naurglen"].terrain[41] = '.. .. .. .. ,, .. ## ++ ++ ++ ++ ++ ++ ++ ## ## .. .. RR .. ,, .. .. .. ## ## ## ## ## ## ## ## ,, .. FF gF FF gF FF gF FF .. .. .. .. RR RR .. ,, .. .. ,, .. .. ,, .. .. ,, u, .. .. u, .. .. ,, ## ## ## ## ## ## ## ## ## ## ## #O ## ## ## .. #% .. .. .. #% .. .. ,, ,, .. u, .. .. ,, u, RR RR ,, ..';
mappages["naurglen"].terrain[42] = '.. ,, u, ,, .. .. ## ++ ++ ++ ++ ++ ++ ++ ## ## .. u, RR RR .. .. .. ,, .. .. .. .. .. .. .. .. .. .. FF gF FF gF FF gF FF .. .. .. .. .. RR .. .. .. .. .. .. u, .. .. .. ,, .. RR RR RR RR .. u, .. .. u, ,, .. ,, .. .. ,, u, .. .. ,, ,, .. u, .. .. .. .. .. ,, .. .. u, ,, ,, .. RR RR RR RR .. .. ..';
mappages["naurglen"].terrain[43] = '.. .. ,, ,, .. .. ## ## ## ## ## ## ## ## ## ## .. ,, .. RR RR .. .. .. .. ,, .. u, .. .. ,, .. .. RR RR RR RR RR RR RR RR RR .. u, RR RR RR .. .. RR RR RR RR .. .. ,, .. .. .. RR .. .. RR RR .. .. ,, .. RR RR RR RR ,, .. .. ,, .. u, .. .. .. .. .. .. .. .. RR RR RR .. .. .. RR RR .. .. .. ,, ,, ..';
mappages["naurglen"].terrain[44] = '.. u, .. .. ,, .. ,, .. .. ,, u, .. .. ,, .. .. .. ,, ,, .. RR RR ,, .. .. .. .. ,, ,, .. .. .. RR RR u, .. .. .. ,, .. .. RR RR RR RR .. RR RR RR RR .. .. RR RR RR .. .. RR RR RR .. .. .. RR RR RR RR RR RR .. .. RR RR RR RR RR RR RR RR RR RR RR RR !! RR RR RR .. RR RR RR RR RR .. .. .. ,, ,, .. ..';
mappages["naurglen"].terrain[45] = ',, .. .. .. .. .. u, .. ,, .. .. u, ,, .. u, .. .. .. .. .. ,, RR .. .. .. ,, .. .. .. .. RR RR RR .. .. .. .. ,, .. .. .. .. .. .. .. .. ,, .. .. .. .. .. .. ,, RR RR RR RR ,, .. .. ,, .. ,, .. .. .. ,, .. ,, .. .. ,, ,, .. .. .. .. .. .. .. ,, .. .. .. .. .. .. .. .. .. .. .. .. ,, .. ,, ,, ,, ..';
mappages["naurglen"].terrain[46] = '.. ,, .. .. .. .. .. .. u, .. .. .. .. .. ,, .. ,, .. .. .. .. RR .. .. .. .. .. .. ,, .. RR .. u, .. ,, .. .. .. .. u, .. ,, .. .. .. .. .. ,, .. ,, .. .. .. .. .. ,, .. .. .. ,, .. .. .. ,, .. .. .. .. .. .. .. .. .. .. .. .. ,, .. .. ,, .. .. .. .. .. .. .. .. ,, ,, .. .. .. .. .. .. .. .. .. ..';

mappages["naurglen"].features = [];
mappages["naurglen"].features[0] = {name : 'HealerSign', x : 80, y : 37, desc : "sign: Healer Hazel"};
mappages["naurglen"].features[1] = {name : 'SingleSignpost', x : 80, y : 38};
mappages["naurglen"].features[2] = {name : 'Door', x : 72, y : 36};
mappages["naurglen"].features[3] = {name : 'DoorWindow', x : 77, y : 34};
mappages["naurglen"].features[4] = {name : 'Fireplace', x : 66, y : 37};
mappages["naurglen"].features[5] = {name : 'LeftTable', x : 74, y : 35};
mappages["naurglen"].features[6] = {name : 'MiddleTable', x : 75, y : 35};
mappages["naurglen"].features[7] = {name : 'RightTable', x : 76, y : 35};
mappages["naurglen"].features[8] = {name : 'BookshelfOne', x : 73, y : 35};
mappages["naurglen"].features[9] = {name : 'BookshelfOne', x : 67, y : 35};
mappages["naurglen"].features[10] = {name : 'BedHead', x : 74, y : 40};
mappages["naurglen"].features[11] = {name : 'BedHead', x : 74, y : 38};
mappages["naurglen"].features[12] = {name : 'BedHead', x : 77, y : 38};
mappages["naurglen"].features[13] = {name : 'BedHead', x : 77, y : 40};
mappages["naurglen"].features[14] = {name : 'BedHead', x : 67, y : 36};
mappages["naurglen"].features[15] = {name : 'BedFoot', x : 68, y : 36};
mappages["naurglen"].features[16] = {name : 'BedFoot', x : 75, y : 38};
mappages["naurglen"].features[17] = {name : 'BedFoot', x : 75, y : 40};
mappages["naurglen"].features[18] = {name : 'BedFoot', x : 78, y : 40};
mappages["naurglen"].features[19] = {name : 'BedFoot', x : 78, y : 38};
mappages["naurglen"].features[20] = {name : 'LeftTable', x : 69, y : 39};
mappages["naurglen"].features[21] = {name : 'RightTable', x : 70, y : 39};
mappages["naurglen"].features[22] = {name : 'TopChair', x : 70, y : 38};
mappages["naurglen"].features[23] = {name : 'BottomChair', x : 69, y : 40};
mappages["naurglen"].features[24] = {name : 'PottedPlant', x : 71, y : 40};
mappages["naurglen"].features[25] = {name : 'Vanity', x : 70, y : 35};
mappages["naurglen"].features[26] = {name : 'Dresser', x : 71, y : 35};
mappages["naurglen"].features[27] = {name : 'GrandfatherClock', x : 67, y : 40};
mappages["naurglen"].features[28] = {name : 'HealerSign', x : 72, y : 33, desc : "sign: Healer Hazel"};
mappages["naurglen"].features[29] = {name : 'SignpostLeft', x : 71, y : 33};
mappages["naurglen"].features[30] = {name : 'SignpostRight', x : 73, y : 33};
mappages["naurglen"].features[31] = {name : 'Door', x : 91, y : 38};
mappages["naurglen"].features[32] = {name : 'BedHead', x : 93, y : 38};
mappages["naurglen"].features[33] = {name : 'BedFoot', x : 94, y : 38};
mappages["naurglen"].features[34] = {name : 'BedHead', x : 93, y : 34};
mappages["naurglen"].features[35] = {name : 'BedFoot', x : 94, y : 34};
mappages["naurglen"].features[36] = {name : 'Mirror', x : 92, y : 32};
mappages["naurglen"].features[37] = {name : 'Mirror', x : 92, y : 36};
mappages["naurglen"].features[38] = {name : 'UnlitBrazier', x : 94, y : 36};
mappages["naurglen"].features[39] = {name : 'UnlitBrazier', x : 94, y : 32};
mappages["naurglen"].features[40] = {name : 'StairUp2', x : 94, y : 30, entermap : 'naurglen2', enterx : 94, entery : 30};
mappages["naurglen"].features[41] = {name : 'LeftTable', x : 92, y : 27};
mappages["naurglen"].features[42] = {name : 'MiddleTable', x : 93, y : 27};
mappages["naurglen"].features[43] = {name : 'RightTable', x : 94, y : 27};
mappages["naurglen"].features[44] = {name : 'TorchWest', x : 89, y : 28};
mappages["naurglen"].features[45] = {name : 'TorchWest', x : 89, y : 30};
mappages["naurglen"].features[46] = {name : 'GrandfatherClock', x : 89, y : 26};
mappages["naurglen"].features[47] = {name : 'PottedPlant', x : 89, y : 38};
mappages["naurglen"].features[48] = {name : 'DoorWindow', x : 88, y : 29};
mappages["naurglen"].features[49] = {name : 'InnSign', x : 86, y : 35, desc : "sign: Ye Olde Inn"};
mappages["naurglen"].features[50] = {name : 'SignpostRight', x : 87, y : 35};
mappages["naurglen"].features[51] = {name : 'Door', x : 88, y : 17};
mappages["naurglen"].features[52] = {name : 'StairUp2', x : 93, y : 17, entermap : 'naurglen2', enterx : 93, entery : 17};
mappages["naurglen"].features[53] = {name : 'LeftTable', x : 90, y : 16};
mappages["naurglen"].features[54] = {name : 'RightTable', x : 91, y : 16};
mappages["naurglen"].features[55] = {name : 'LeftChair', x : 89, y : 16};
mappages["naurglen"].features[56] = {name : 'TopChair', x : 91, y : 15};
mappages["naurglen"].features[57] = {name : 'RightChair', x : 93, y : 19};
mappages["naurglen"].features[58] = {name : 'SmallTable', x : 92, y : 19};
mappages["naurglen"].features[59] = {name : 'PottedPlant', x : 89, y : 19};
mappages["naurglen"].features[60] = {name : 'DoorWindow', x : 67, y : 26};
mappages["naurglen"].features[61] = {name : 'DoorWindow', x : 78, y : 25};
mappages["naurglen"].features[62] = {name : 'LeftTable', x : 74, y : 22};
mappages["naurglen"].features[63] = {name : 'MiddleTable', x : 75, y : 22};
mappages["naurglen"].features[64] = {name : 'RightTable', x : 76, y : 22};
mappages["naurglen"].features[65] = {name : 'LeftTable', x : 71, y : 24};
mappages["naurglen"].features[66] = {name : 'RightTable', x : 72, y : 24};
mappages["naurglen"].features[67] = {name : 'LeftTable', x : 67, y : 24};
mappages["naurglen"].features[68] = {name : 'LeftTable', x : 67, y : 22};
mappages["naurglen"].features[69] = {name : 'MiddleTable', x : 68, y : 22};
mappages["naurglen"].features[70] = {name : 'RightTable', x : 69, y : 22};
mappages["naurglen"].features[71] = {name : 'RightTable', x : 68, y : 24};
mappages["naurglen"].features[72] = {name : 'Fireplace', x : 65, y : 23};
mappages["naurglen"].features[73] = {name : 'SmallTable', x : 72, y : 21};
mappages["naurglen"].features[74] = {name : 'TopChair', x : 76, y : 21};
mappages["naurglen"].features[75] = {name : 'TopChair', x : 75, y : 21};
mappages["naurglen"].features[76] = {name : 'BottomChair', x : 75, y : 23};
mappages["naurglen"].features[77] = {name : 'BottomChair', x : 74, y : 23};
mappages["naurglen"].features[78] = {name : 'RightChair', x : 73, y : 21};
mappages["naurglen"].features[79] = {name : 'TopChair', x : 72, y : 23};
mappages["naurglen"].features[80] = {name : 'LeftChair', x : 70, y : 24};
mappages["naurglen"].features[81] = {name : 'LeftChair', x : 66, y : 24};
mappages["naurglen"].features[82] = {name : 'RightChair', x : 73, y : 21};
mappages["naurglen"].features[83] = {name : 'LeftChair', x : 71, y : 21};
mappages["naurglen"].features[84] = {name : 'TopChair', x : 72, y : 23};
mappages["naurglen"].features[85] = {name : 'TavernSign', x : 79, y : 23, desc : "sign: The Red Hen Tavern"};
mappages["naurglen"].features[86] = {name : 'SingleSignpost', x : 79, y : 24};
mappages["naurglen"].features[87] = {name : 'Door', x : 78, y : 14};
mappages["naurglen"].features[88] = {name : 'Door', x : 64, y : 14};
mappages["naurglen"].features[89] = {name : 'BookshelfLeft', x : 73, y : 13};
mappages["naurglen"].features[90] = {name : 'BookshelfRight', x : 74, y : 13};
mappages["naurglen"].features[91] = {name : 'BookshelfLeft', x : 68, y : 13};
mappages["naurglen"].features[92] = {name : 'BookshelfRight', x : 69, y : 13};
mappages["naurglen"].features[93] = {name : 'StairUp', x : 73, y : 16, entermap : 'naurglen2', enterx : 73, entery : 16};
mappages["naurglen"].features[94] = {name : 'StairUp2', x : 69, y : 16, entermap : 'naurglen2', enterx : 69, entery : 16};
mappages["naurglen"].features[95] = {name : 'LeftTable', x : 75, y : 15};
mappages["naurglen"].features[96] = {name : 'RightTable', x : 76, y : 15};
mappages["naurglen"].features[97] = {name : 'PottedPlant', x : 77, y : 13};
mappages["naurglen"].features[98] = {name : 'BottomChair', x : 75, y : 16};
mappages["naurglen"].features[99] = {name : 'Barrel', x : 76, y : 13};
mappages["naurglen"].features[100] = {name : 'LeftTable', x : 66, y : 15};
mappages["naurglen"].features[101] = {name : 'RightTable', x : 67, y : 15};
mappages["naurglen"].features[102] = {name : 'LeftChair', x : 65, y : 15};
mappages["naurglen"].features[103] = {name : 'SmallBox', x : 65, y : 16};
mappages["naurglen"].features[104] = {name : 'PottedPlant', x : 65, y : 13};
mappages["naurglen"].features[105] = {name : 'Door', x : 91, y : 34, desc : "locked door", locked : 1};
mappages["naurglen"].features[106] = {name : 'Well', x : 52, y : 22};
mappages["naurglen"].features[107] = {name : 'WBridgeNS', x : 82, y : 44};
mappages["naurglen"].features[108] = {name : 'EBridgeNS', x : 84, y : 44};
mappages["naurglen"].features[109] = {name : 'Door', x : 57, y : 35};
mappages["naurglen"].features[110] = {name : 'Door', x : 55, y : 38};
mappages["naurglen"].features[111] = {name : 'Brazier', x : 54, y : 39};
mappages["naurglen"].features[112] = {name : 'Dresser', x : 54, y : 36};
mappages["naurglen"].features[113] = {name : 'GrandfatherClock', x : 51, y : 36};
mappages["naurglen"].features[114] = {name : 'BedHead', x : 51, y : 38};
mappages["naurglen"].features[115] = {name : 'BedFoot', x : 52, y : 38};
mappages["naurglen"].features[116] = {name : 'SmallTable', x : 51, y : 39};
mappages["naurglen"].features[117] = {name : 'BookshelfLeft', x : 58, y : 36};
mappages["naurglen"].features[118] = {name : 'BookshelfRight', x : 59, y : 36};
mappages["naurglen"].features[119] = {name : 'LeftTable', x : 58, y : 38};
mappages["naurglen"].features[120] = {name : 'RightTable', x : 59, y : 38};
mappages["naurglen"].features[121] = {name : 'BottomChair', x : 58, y : 39};
mappages["naurglen"].features[122] = {name : 'Spit', x : 66, y : 21};
mappages["naurglen"].features[123] = {name : 'PottedPlant', x : 56, y : 36};
mappages["naurglen"].features[124] = {name : 'NBridgeEW', x : 44, y : 30};
mappages["naurglen"].features[125] = {name : 'SBridgeEW', x : 44, y : 32};
mappages["naurglen"].features[126] = {name : 'SignpostRight', x : 69, y : 27};
mappages["naurglen"].features[127] = {name : 'TavernSign', x : 68, y : 27, desc : "sign: The Red Hen Tavern"};
mappages["naurglen"].features[128] = {name : 'Door', x : 29, y : 35};
mappages["naurglen"].features[129] = {name : 'BedHead', x : 25, y : 40};
mappages["naurglen"].features[130] = {name : 'BedHead', x : 29, y : 40};
mappages["naurglen"].features[131] = {name : 'BedFoot', x : 30, y : 40};
mappages["naurglen"].features[132] = {name : 'BedFoot', x : 26, y : 40};
mappages["naurglen"].features[133] = {name : 'LeftChair', x : 25, y : 37};
mappages["naurglen"].features[134] = {name : 'BottomChair', x : 27, y : 38};
mappages["naurglen"].features[135] = {name : 'Barrel', x : 30, y : 36};
mappages["naurglen"].features[136] = {name : 'Dresser', x : 27, y : 40};
mappages["naurglen"].features[137] = {name : 'Dresser', x : 28, y : 40};
mappages["naurglen"].features[138] = {name : 'FenceNW', x : 34, y : 12};
mappages["naurglen"].features[139] = {name : 'FenceNE', x : 42, y : 12};
mappages["naurglen"].features[140] = {name : 'FenceEW', x : 35, y : 12};
mappages["naurglen"].features[141] = {name : 'FenceEW', x : 36, y : 12};
mappages["naurglen"].features[142] = {name : 'FenceEW', x : 37, y : 12};
mappages["naurglen"].features[143] = {name : 'FenceEW', x : 38, y : 12};
mappages["naurglen"].features[144] = {name : 'FenceEW', x : 39, y : 12};
mappages["naurglen"].features[145] = {name : 'FenceEW', x : 40, y : 12};
mappages["naurglen"].features[146] = {name : 'FenceEW', x : 41, y : 12};
mappages["naurglen"].features[147] = {name : 'FenceSE', x : 42, y : 18};
mappages["naurglen"].features[148] = {name : 'FenceSW', x : 34, y : 18};
mappages["naurglen"].features[149] = {name : 'FenceEWGate', x : 35, y : 18};
mappages["naurglen"].features[150] = {name : 'FenceEW', x : 36, y : 18};
mappages["naurglen"].features[151] = {name : 'FenceEW', x : 37, y : 18};
mappages["naurglen"].features[152] = {name : 'FenceEW', x : 38, y : 18};
mappages["naurglen"].features[153] = {name : 'FenceEW', x : 39, y : 18};
mappages["naurglen"].features[154] = {name : 'FenceEW', x : 40, y : 18};
mappages["naurglen"].features[155] = {name : 'FenceEW', x : 41, y : 18};
mappages["naurglen"].features[156] = {name : 'FenceNS', x : 42, y : 13};
mappages["naurglen"].features[157] = {name : 'FenceNS', x : 42, y : 14};
mappages["naurglen"].features[158] = {name : 'FenceNS', x : 42, y : 15};
mappages["naurglen"].features[159] = {name : 'FenceNS', x : 42, y : 16};
mappages["naurglen"].features[160] = {name : 'FenceNS', x : 42, y : 17};
mappages["naurglen"].features[161] = {name : 'FenceNS', x : 34, y : 17};
mappages["naurglen"].features[162] = {name : 'FenceNS', x : 34, y : 16};
mappages["naurglen"].features[163] = {name : 'FenceNS', x : 34, y : 15};
mappages["naurglen"].features[164] = {name : 'FenceNS', x : 34, y : 14};
mappages["naurglen"].features[165] = {name : 'FenceNS', x : 34, y : 13};
mappages["naurglen"].features[166] = {name : 'Door', x : 31, y : 15};
mappages["naurglen"].features[167] = {name : 'Barrel', x : 29, y : 14};
mappages["naurglen"].features[168] = {name : 'Barrel', x : 29, y : 14};
mappages["naurglen"].features[169] = {name : 'Barrel', x : 28, y : 14};
mappages["naurglen"].features[170] = {name : 'Barrel', x : 28, y : 13};
mappages["naurglen"].features[171] = {name : 'Barrel', x : 27, y : 14};
mappages["naurglen"].features[172] = {name : 'Barrel', x : 26, y : 15};
mappages["naurglen"].features[173] = {name : 'Barrel', x : 27, y : 15};
mappages["naurglen"].features[174] = {name : 'Barrel', x : 27, y : 16};
mappages["naurglen"].features[175] = {name : 'Barrel', x : 28, y : 16};
mappages["naurglen"].features[176] = {name : 'Barrel', x : 28, y : 17};
mappages["naurglen"].features[177] = {name : 'Barrel', x : 29, y : 16};
mappages["naurglen"].features[178] = {name : 'BridgeEW', x : 23, y : 30};
mappages["naurglen"].features[179] = {name : 'BridgeEW', x : 31, y : 23};
mappages["naurglen"].features[180] = {name : 'Door', x : 28, y : 22};
mappages["naurglen"].features[181] = {name : 'LeftTable', x : 26, y : 37};
mappages["naurglen"].features[182] = {name : 'MiddleTable', x : 27, y : 37};
mappages["naurglen"].features[183] = {name : 'RightTable', x : 28, y : 37};
mappages["naurglen"].features[184] = {name : 'BedHead', x : 21, y : 24};
mappages["naurglen"].features[185] = {name : 'BedFoot', x : 22, y : 24};
mappages["naurglen"].features[186] = {name : 'WBridgeNS', x : 58, y : 9};
mappages["naurglen"].features[187] = {name : 'EBridgeNS', x : 60, y : 8};
mappages["naurglen"].features[188] = {name : 'BridgeEW', x : 50, y : 15};
mappages["naurglen"].features[189] = {name : 'Door', x : 48, y : 11};
mappages["naurglen"].features[190] = {name : 'StairUp', x : 44, y : 7, entermap : 'naurglen2', enterx : 44, entery : 7};
mappages["naurglen"].features[191] = {name : 'BookshelfLeft', x : 49, y : 7};
mappages["naurglen"].features[192] = {name : 'BookshelfRight', x : 50, y : 7};
mappages["naurglen"].features[193] = {name : 'Fireplace', x : 47, y : 6};
mappages["naurglen"].features[194] = {name : 'UnlitBrazier', x : 50, y : 10};
mappages["naurglen"].features[195] = {name : 'LeftTable', x : 45, y : 9};
mappages["naurglen"].features[196] = {name : 'MiddleTable', x : 46, y : 9};
mappages["naurglen"].features[197] = {name : 'RightTable', x : 47, y : 9};
mappages["naurglen"].features[198] = {name : 'BottomChair', x : 47, y : 7};
mappages["naurglen"].features[199] = {name : 'LeftChair', x : 44, y : 9};
mappages["naurglen"].features[200] = {name : 'BottomChair', x : 46, y : 10};
mappages["naurglen"].features[201] = {name : 'FenceEWGate', x : 32, y : 10};
mappages["naurglen"].features[202] = {name : 'FenceEW', x : 33, y : 10};
mappages["naurglen"].features[203] = {name : 'FenceEW', x : 34, y : 10};
mappages["naurglen"].features[204] = {name : 'FenceEW', x : 35, y : 10};
mappages["naurglen"].features[205] = {name : 'FenceEW', x : 36, y : 10};
mappages["naurglen"].features[206] = {name : 'FenceEW', x : 37, y : 10};
mappages["naurglen"].features[207] = {name : 'FenceEW', x : 38, y : 10};
mappages["naurglen"].features[208] = {name : 'FenceEW', x : 31, y : 10};
mappages["naurglen"].features[209] = {name : 'FenceEW', x : 30, y : 10};
mappages["naurglen"].features[210] = {name : 'AppleTree', x : 30, y : 9};
mappages["naurglen"].features[211] = {name : 'AppleTree', x : 30, y : 7};
mappages["naurglen"].features[212] = {name : 'AppleTree', x : 30, y : 5};
mappages["naurglen"].features[213] = {name : 'AppleTree', x : 32, y : 5};
mappages["naurglen"].features[214] = {name : 'AppleTree', x : 32, y : 7};
mappages["naurglen"].features[215] = {name : 'AppleTree', x : 34, y : 7};
mappages["naurglen"].features[216] = {name : 'AppleTree', x : 34, y : 5};
mappages["naurglen"].features[217] = {name : 'AppleTree', x : 34, y : 9};
mappages["naurglen"].features[218] = {name : 'AppleTree', x : 36, y : 9};
mappages["naurglen"].features[219] = {name : 'AppleTree', x : 36, y : 7};
mappages["naurglen"].features[220] = {name : 'AppleTree', x : 36, y : 5};
mappages["naurglen"].features[221] = {name : 'AppleTree', x : 38, y : 5};
mappages["naurglen"].features[222] = {name : 'AppleTree', x : 38, y : 7};
mappages["naurglen"].features[223] = {name : 'AppleTree', x : 38, y : 9};
mappages["naurglen"].features[224] = {name : 'FenceSE', x : 39, y : 10};
mappages["naurglen"].features[225] = {name : 'FenceSW', x : 29, y : 10};
mappages["naurglen"].features[226] = {name : 'FenceNS', x : 29, y : 9};
mappages["naurglen"].features[227] = {name : 'FenceNS', x : 29, y : 8};
mappages["naurglen"].features[228] = {name : 'FenceNS', x : 29, y : 7};
mappages["naurglen"].features[229] = {name : 'FenceNS', x : 29, y : 6};
mappages["naurglen"].features[230] = {name : 'FenceNS', x : 29, y : 5};
mappages["naurglen"].features[231] = {name : 'FenceNW', x : 29, y : 4};
mappages["naurglen"].features[232] = {name : 'FenceEW', x : 30, y : 4};
mappages["naurglen"].features[233] = {name : 'FenceEW', x : 31, y : 4};
mappages["naurglen"].features[234] = {name : 'FenceEW', x : 32, y : 4};
mappages["naurglen"].features[235] = {name : 'FenceEW', x : 33, y : 4};
mappages["naurglen"].features[236] = {name : 'FenceEW', x : 34, y : 4};
mappages["naurglen"].features[237] = {name : 'FenceEW', x : 35, y : 4};
mappages["naurglen"].features[238] = {name : 'FenceEW', x : 36, y : 4};
mappages["naurglen"].features[239] = {name : 'FenceEW', x : 37, y : 4};
mappages["naurglen"].features[240] = {name : 'FenceEW', x : 38, y : 4};
mappages["naurglen"].features[241] = {name : 'FenceNE', x : 39, y : 4};
mappages["naurglen"].features[242] = {name : 'FenceNS', x : 39, y : 5};
mappages["naurglen"].features[243] = {name : 'FenceNS', x : 39, y : 6};
mappages["naurglen"].features[244] = {name : 'FenceNS', x : 39, y : 7};
mappages["naurglen"].features[245] = {name : 'FenceNS', x : 39, y : 8};
mappages["naurglen"].features[246] = {name : 'FenceNS', x : 39, y : 9};
mappages["naurglen"].features[247] = {name : 'Mirror', x : 21, y : 21};
mappages["naurglen"].features[248] = {name : 'Dresser', x : 22, y : 21};
mappages["naurglen"].features[249] = {name : 'SmallTable', x : 24, y : 23};
mappages["naurglen"].features[250] = {name : 'BottomChair', x : 24, y : 24};
mappages["naurglen"].features[251] = {name : 'PottedPlant', x : 27, y : 21};
mappages["naurglen"].features[252] = {name : 'Fireplace', x : 14, y : 40};
mappages["naurglen"].features[253] = {name : 'EBridgeNS', x : 60, y : 9};
mappages["naurglen"].features[254] = {name : 'WBridgeNS', x : 58, y : 8};
mappages["naurglen"].features[255] = {name : 'Door', x : 10, y : 36, desc : "locked door", locked : 1, keyname : "HomeKey"};
mappages["naurglen"].features[256] = {name : 'Door', x : 7, y : 25, desc : "locked door", locked : 1};
mappages["naurglen"].features[257] = {name : 'GrandfatherClock', x : 5, y : 20};
mappages["naurglen"].features[258] = {name : 'Dresser', x : 10, y : 20};
mappages["naurglen"].features[259] = {name : 'Vanity', x : 9, y : 20};
mappages["naurglen"].features[260] = {name : 'BedHead', x : 7, y : 20};
mappages["naurglen"].features[261] = {name : 'BedFoot', x : 8, y : 20};
mappages["naurglen"].features[262] = {name : 'LeftTable', x : 6, y : 22};
mappages["naurglen"].features[263] = {name : 'RightTable', x : 7, y : 22};
mappages["naurglen"].features[264] = {name : 'BottomChair', x : 6, y : 23};
mappages["naurglen"].features[265] = {name : 'Harpsichord', x : 10, y : 24};
mappages["naurglen"].features[266] = {name : 'TopChair', x : 10, y : 23};
mappages["naurglen"].features[267] = {name : 'Door', x : 20, y : 7};
mappages["naurglen"].features[268] = {name : 'UnlitBrazier', x : 5, y : 24};
mappages["naurglen"].features[269] = {name : 'DustyFireplace', x : 26, y : 4};
mappages["naurglen"].features[270] = {name : 'LeftTable', x : 22, y : 7};
mappages["naurglen"].features[271] = {name : 'MiddleTable', x : 23, y : 7};
mappages["naurglen"].features[272] = {name : 'RightTable', x : 24, y : 7};
mappages["naurglen"].features[273] = {name : 'BedHead', x : 23, y : 4};
mappages["naurglen"].features[274] = {name : 'BedFoot', x : 24, y : 4};
mappages["naurglen"].features[275] = {name : 'BottomChair', x : 23, y : 8};
mappages["naurglen"].features[276] = {name : 'Dresser', x : 21, y : 4};
mappages["naurglen"].features[277] = {name : 'SmallBox', x : 22, y : 4};
mappages["naurglen"].features[278] = {name : 'BottomChair', x : 25, y : 5};
mappages["naurglen"].features[279] = {name : 'Door', x : 12, y : 4};
mappages["naurglen"].features[280] = {name : 'BrokenFountain', x : 50, y : 18};
mappages["naurglen"].features[281] = {name : 'Well', x : 43, y : 41};
mappages["naurglen"].features[282] = {name : 'Well', x : 44, y : 22};
mappages["naurglen"].features[283] = {name : 'Well', x : 4, y : 15};
mappages["naurglen"].features[284] = {name : 'Well', x : 92, y : 10};
mappages["naurglen"].features[285] = {name : 'StairUp', x : 7, y : 42, entermap : 'naurglen2', enterx : 7, entery : 42};
mappages["naurglen"].features[286] = {name : 'Evergreen', x : 9, y : 35};
mappages["naurglen"].features[287] = {name : 'Evergreen', x : 11, y : 35};
mappages["naurglen"].features[288] = {name : 'WBridgeNS', x : 82, y : 9};
mappages["naurglen"].features[289] = {name : 'EBridgeNS', x : 84, y : 9};
mappages["naurglen"].features[290] = {name : 'BookshelfLeft', x : 7, y : 37};
mappages["naurglen"].features[291] = {name : 'BookshelfLeft', x : 12, y : 37};
mappages["naurglen"].features[292] = {name : 'BookshelfLeft', x : 7, y : 40};
mappages["naurglen"].features[293] = {name : 'BookshelfRight', x : 8, y : 37};
mappages["naurglen"].features[294] = {name : 'BookshelfRight', x : 8, y : 40};
mappages["naurglen"].features[295] = {name : 'BookshelfRight', x : 13, y : 37};
mappages["naurglen"].features[296] = {name : 'LeftTable', x : 10, y : 41};
mappages["naurglen"].features[297] = {name : 'MiddleTable', x : 11, y : 41};
mappages["naurglen"].features[298] = {name : 'RightTable', x : 12, y : 41};
mappages["naurglen"].features[299] = {name : 'LeftChair', x : 7, y : 38};
mappages["naurglen"].features[300] = {name : 'BottomChair', x : 11, y : 42};
mappages["naurglen"].features[301] = {name : 'GrandfatherClock', x : 13, y : 42};
mappages["naurglen"].features[302] = {name : 'Harpsichord', x : 13, y : 39};
mappages["naurglen"].features[303] = {name : 'TopChair', x : 13, y : 38};
mappages["naurglen"].features[304] = {name : 'PottedPlant', x : 9, y : 37};
mappages["naurglen"].features[305] = {name : 'PottedPlant', x : 11, y : 37};
mappages["naurglen"].features[306] = {name : 'Tree', x : 87, y : 41};
mappages["naurglen"].features[307] = {name : 'Tree', x : 79, y : 43};
mappages["naurglen"].features[308] = {name : 'Tree', x : 62, y : 35};
mappages["naurglen"].features[309] = {name : 'Tree', x : 63, y : 38};
mappages["naurglen"].features[310] = {name : 'Tree', x : 61, y : 44};
mappages["naurglen"].features[311] = {name : 'Tree', x : 69, y : 44};
mappages["naurglen"].features[312] = {name : 'Tree', x : 75, y : 45};
mappages["naurglen"].features[313] = {name : 'Tree', x : 91, y : 46};
mappages["naurglen"].features[314] = {name : 'Tree', x : 97, y : 44};
mappages["naurglen"].features[315] = {name : 'Tree', x : 97, y : 38};
mappages["naurglen"].features[316] = {name : 'Tree', x : 99, y : 32};
mappages["naurglen"].features[317] = {name : 'Tree', x : 97, y : 25};
mappages["naurglen"].features[318] = {name : 'Tree', x : 93, y : 23};
mappages["naurglen"].features[319] = {name : 'Tree', x : 90, y : 22};
mappages["naurglen"].features[320] = {name : 'Tree', x : 87, y : 19};
mappages["naurglen"].features[321] = {name : 'Tree', x : 96, y : 17};
mappages["naurglen"].features[322] = {name : 'Tree', x : 99, y : 17};
mappages["naurglen"].features[323] = {name : 'Tree', x : 98, y : 12};
mappages["naurglen"].features[324] = {name : 'Tree', x : 94, y : 12};
mappages["naurglen"].features[325] = {name : 'Tree', x : 91, y : 12};
mappages["naurglen"].features[326] = {name : 'Tree', x : 88, y : 10};
mappages["naurglen"].features[327] = {name : 'Tree', x : 86, y : 13};
mappages["naurglen"].features[328] = {name : 'Tree', x : 85, y : 3};
mappages["naurglen"].features[329] = {name : 'Tree', x : 84, y : 4};
mappages["naurglen"].features[330] = {name : 'Tree', x : 84, y : 5};
mappages["naurglen"].features[331] = {name : 'Tree', x : 86, y : 5};
mappages["naurglen"].features[332] = {name : 'Tree', x : 87, y : 5};
mappages["naurglen"].features[333] = {name : 'Tree', x : 92, y : 3};
mappages["naurglen"].features[334] = {name : 'Tree', x : 90, y : 1};
mappages["naurglen"].features[335] = {name : 'Tree', x : 90, y : 3};
mappages["naurglen"].features[336] = {name : 'Tree', x : 89, y : 4};
mappages["naurglen"].features[337] = {name : 'Tree', x : 90, y : 5};
mappages["naurglen"].features[338] = {name : 'Tree', x : 91, y : 5};
mappages["naurglen"].features[339] = {name : 'Tree', x : 96, y : 2};
mappages["naurglen"].features[340] = {name : 'Tree', x : 97, y : 3};
mappages["naurglen"].features[341] = {name : 'Tree', x : 95, y : 5};
mappages["naurglen"].features[342] = {name : 'Tree', x : 93, y : 6};
mappages["naurglen"].features[343] = {name : 'Tree', x : 96, y : 4};
mappages["naurglen"].features[344] = {name : 'Tree', x : 93, y : 1};
mappages["naurglen"].features[345] = {name : 'Tree', x : 94, y : 2};
mappages["naurglen"].features[346] = {name : 'Tree', x : 94, y : 3};
mappages["naurglen"].features[347] = {name : 'Tree', x : 88, y : 2};
mappages["naurglen"].features[348] = {name : 'Tree', x : 86, y : 1};
mappages["naurglen"].features[349] = {name : 'Tree', x : 85, y : 1};
mappages["naurglen"].features[350] = {name : 'Tree', x : 81, y : 2};
mappages["naurglen"].features[351] = {name : 'Tree', x : 82, y : 5};
mappages["naurglen"].features[352] = {name : 'Tree', x : 89, y : 6};
mappages["naurglen"].features[353] = {name : 'Tree', x : 85, y : 7};
mappages["naurglen"].features[354] = {name : 'Tree', x : 79, y : 5};
mappages["naurglen"].features[355] = {name : 'Tree', x : 80, y : 1};
mappages["naurglen"].features[356] = {name : 'Tree', x : 85, y : 0};
mappages["naurglen"].features[357] = {name : 'Tree', x : 96, y : 0};
mappages["naurglen"].features[358] = {name : 'Tree', x : 99, y : 2};
mappages["naurglen"].features[359] = {name : 'Tree', x : 49, y : 23};
mappages["naurglen"].features[360] = {name : 'Tree', x : 48, y : 25};
mappages["naurglen"].features[361] = {name : 'Tree', x : 51, y : 25};
mappages["naurglen"].features[362] = {name : 'Tree', x : 53, y : 23};
mappages["naurglen"].features[363] = {name : 'Tree', x : 56, y : 21};
mappages["naurglen"].features[364] = {name : 'Tree', x : 55, y : 18};
mappages["naurglen"].features[365] = {name : 'Tree', x : 53, y : 19};
mappages["naurglen"].features[366] = {name : 'Tree', x : 51, y : 19};
mappages["naurglen"].features[367] = {name : 'Tree', x : 53, y : 17};
mappages["naurglen"].features[368] = {name : 'Tree', x : 53, y : 16};
mappages["naurglen"].features[369] = {name : 'Tree', x : 54, y : 16};
mappages["naurglen"].features[370] = {name : 'Tree', x : 56, y : 13};
mappages["naurglen"].features[371] = {name : 'Tree', x : 54, y : 11};
mappages["naurglen"].features[372] = {name : 'Tree', x : 54, y : 13};
mappages["naurglen"].features[373] = {name : 'Tree', x : 51, y : 17};
mappages["naurglen"].features[374] = {name : 'Evergreen', x : 52, y : 14};
mappages["naurglen"].features[375] = {name : 'Evergreen', x : 46, y : 24};
mappages["naurglen"].features[376] = {name : 'AppleTree', x : 48, y : 21};
mappages["naurglen"].features[377] = {name : 'WoodSign', x : 52, y : 26, desc : "sign: Public Park"};
mappages["naurglen"].features[378] = {name : 'Tree', x : 78, y : 8};
mappages["naurglen"].features[379] = {name : 'Tree', x : 75, y : 3};
mappages["naurglen"].features[380] = {name : 'Tree', x : 73, y : 1};
mappages["naurglen"].features[381] = {name : 'Tree', x : 68, y : 5};
mappages["naurglen"].features[382] = {name : 'Tree', x : 69, y : 8};
mappages["naurglen"].features[383] = {name : 'Tree', x : 66, y : 2};
mappages["naurglen"].features[384] = {name : 'Tree', x : 64, y : 1};
mappages["naurglen"].features[385] = {name : 'Tree', x : 63, y : 6};
mappages["naurglen"].features[386] = {name : 'Tree', x : 72, y : 6};
mappages["naurglen"].features[387] = {name : 'Tree', x : 62, y : 20};
mappages["naurglen"].features[388] = {name : 'Tree', x : 69, y : 18};
mappages["naurglen"].features[389] = {name : 'Tree', x : 55, y : 42};
mappages["naurglen"].features[390] = {name : 'Tree', x : 48, y : 40};
mappages["naurglen"].features[391] = {name : 'Tree', x : 45, y : 36};
mappages["naurglen"].features[392] = {name : 'Tree', x : 51, y : 45};
mappages["naurglen"].features[393] = {name : 'Tree', x : 44, y : 45};
mappages["naurglen"].features[394] = {name : 'Tree', x : 20, y : 13};
mappages["naurglen"].features[395] = {name : 'Tree', x : 23, y : 17};
mappages["naurglen"].features[396] = {name : 'Tree', x : 1, y : 23};
mappages["naurglen"].features[397] = {name : 'Tree', x : 2, y : 38};
mappages["naurglen"].features[398] = {name : 'Tree', x : 3, y : 45};
mappages["naurglen"].features[399] = {name : 'Tree', x : 11, y : 44};
mappages["naurglen"].features[400] = {name : 'Tree', x : 26, y : 44};
mappages["naurglen"].features[401] = {name : 'Tree', x : 2, y : 4};
mappages["naurglen"].features[402] = {name : 'Tree', x : 8, y : 1};
mappages["naurglen"].features[403] = {name : 'Tree', x : 24, y : 1};
mappages["naurglen"].features[404] = {name : 'Tree', x : 33, y : 2};
mappages["naurglen"].features[405] = {name : 'Tree', x : 41, y : 2};
mappages["naurglen"].features[406] = {name : 'Tree', x : 48, y : 3};
mappages["naurglen"].features[407] = {name : 'BedHead', x : 67, y : 38};
mappages["naurglen"].features[408] = {name : 'BedFoot', x : 68, y : 38};
mappages["naurglen"].features[409] = {name : 'BridgeEW', x : 21, y : 34};


mappages["naurglen"].npcs = [];
mappages["naurglen"].npcs[0] = {name : 'DruidVillagerNPC', x : 67, y : 36, NPCName: 'Hazel', Desc: 'healer', Conversation: 'hazel', ConversationFlag: 'hazel', Gender: 'female', Leash: 2, OverrideGraphic: 'druid-offcolor.1.gif'};
mappages["naurglen"].npcs[1] = {name : 'TownsfolkVillagerNPC', x : 93, y : 26, NPCName: 'Daniel', Conversation: 'daniel', ConversationFlag: 'daniel', Gender: 'male', OverrideGraphic: '310.gif'};
mappages["naurglen"].npcs[2] = {name : 'TinkerVillagerNPC', x : 93, y : 34, NPCName: 'Kyvek', Conversation: 'kyvek', ConversationFlag: 'kyvek', Gender: 'male', OverrideGraphic: '304.2.gif'};
mappages["naurglen"].npcs[3] = {name : 'TownsfolkVillagerNPC', x :21, y : 24, NPCName: 'Derek', Conversation: 'derek', PeaceAI: 'scheduled', Schedule: 'derek', ConversationFlag: 'derek', Gender: 'male', Leash: 4, Bark: '0', NPCBand: '0', OverrideGraphic: '310.gif'};
mappages["naurglen"].npcs[4] = {name : 'ChildVillagerNPC', x : 67, y : 38, NPCName: 'Amy', Conversation: 'amy', ConversationFlag: 'amy', Gender: 'female', Leash: 4, Bark: '0', NPCBand: '0'};
mappages["naurglen"].npcs[5] = {name : 'PaladinVillagerNPC', x : 51, y : 38, NPCName: 'Amaeryl', PeaceAI: 'scheduled', Schedule: 'amaeryl', Conversation: 'amaeryl', ConversationFlag: 'amaeryl', Gender: 'female', OverrideGraphic: '307.2.gif'};
mappages["naurglen"].npcs[6] = {name : 'TownGuardNPC', x : 59, y : 30, NPCName: 'Grayson', Alignment: '', Conversation: 'grayson', PeaceAI: 'scheduled', Schedule: 'grayson', ConversationFlag: 'grayson', Gender: 'male', Bark: '0', NPCBand: '0'};
mappages["naurglen"].npcs[7] = {name : 'ShepherdVillagerNPC', x :23, y : 4, NPCName: 'Samuel', Desc: 'blind shepherd', Conversation: 'samuel', Schedule: 'samuel', ConversationFlag: 'samuel', Gender: 'male', OverrideGraphic: '301.gif'};
mappages["naurglen"].npcs[8] = {name : 'TownsfolkVillagerNPC', x : 29, y : 40, NPCName: 'Kylee', Desc: 'farmer', Conversation: 'kylee', ConversationFlag: 'kylee', Gender: 'female', OverrideGraphic: '310.2.gif'};
mappages["naurglen"].npcs[9] = {name : 'ChickenNPC', x : 36, y : 14};
mappages["naurglen"].npcs[10] = {name : 'ChickenNPC', x : 38, y : 15};
mappages["naurglen"].npcs[11] = {name : 'ChickenNPC', x : 40, y : 14};
mappages["naurglen"].npcs[12] = {name : 'ChickenNPC', x : 40, y : 17};

mappages["naurglen"].desc = "Naurglen";
mappages["naurglen"].music = 'Village';
mappages["naurglen"].savename = 'Naurglen';
mappages["naurglen"].exitmap = 'darkunknown';
mappages["naurglen"].exitx = '73';
mappages["naurglen"].exity = '74';
mappages["naurglen"].wraps = '';
mappages["naurglen"].enterx = '66';
mappages["naurglen"].entery = '98';
mappages["naurglen"].seeBelow = '';
mappages["naurglen"].lightLevel = 'cycle';
mappages["naurglen"].alwaysRemember = '0';
mappages["naurglen"].scale = '1';
mappages["naurglen"].underground = '0';
mappages["naurglen"].enterscript = '';
mappages["naurglen"].entertestscript = '';
mappages["naurglen"].exitscript = '';
mappages["naurglen"].exittestscript = '';
mappages["naurglen"].returnmap = 'darkunknown';
mappages["naurglen"].returnx = '72';
mappages["naurglen"].returny = '75';
mappages["naurglen"].returninfused = '0';
mappages["naurglen"].linkedMaps = ["naurglen2","naurglen_limbo"];
mappages["naurglen"].editorLabels = '{"div_tile66x16":"Evelyn","div_tile74x14":"Grayson","div_tile89x17":"Dora and Ingrid","div_tile92x33":"Kyvek Room","div_tile56x37":"Amaeryl","div_tile26x39":"Kylee and Sam","div_tile45x8":"Warren and Garen","div_tile23x22":"Derek","div_tile9x38":"PC Home","div_tile74x37":"Hazel","div_tile22x6":"Soldier","div_tile7x23":"Soldier"}';

mappages["naurglen"].onload = function(mapref) {
  
  if (DU.gameflags["rescued_sam"]) {
    var npcs = mapref.npcs.getAll();
    for (var i=0;i<npcs.length;i++) {
      if (npcs[i].getNPCName() === "Kylee"){
        npcs[i].setSchedule("kylee2");
        break;
      }
    }
    var sam = localFactory.createTile("ChildVillagerNPC");
    sam.setNPCName("Samantha");
    sam.setConversation("samantha2");
    sam.setGender("female");
    sam.setDesc("excited girl");
    sam.setPrefix("an");
    sam.setBark("sam");
    sam.setSchedule("samantha2");
    sam.setPeaceAI("scheduled");
    sam.setLeash(3);
    var loc = DU.schedules["samantha2"].getNPCLocationByTime(GetClockTime(), 1);
    mapref.placeThing(loc.x,loc.y,sam);
  }
}

mappages["naurglen2"] = {};
mappages["naurglen2"].terrain = [];
 mappages["naurglen2"].terrain[0] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["naurglen2"].terrain[1] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["naurglen2"].terrain[2] = 'sb sb sb sb sb sb rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["naurglen2"].terrain[3] = 'sb sb sb sb sb sb rf rf rf rf rf rf rf sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["naurglen2"].terrain[4] = 'sb sb sb sb sb sb rf rf rf rf rf rf rf sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["naurglen2"].terrain[5] = 'sb sb sb sb sb sb rc rc rc rc rc rc rc sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ## ## ## ## ## ## ## ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["naurglen2"].terrain[6] = 'sb sb sb sb sb sb rf rf rf rf rf rf rf sb sb sb sb sb sb sb rc rc rc rc rc rc rc rc sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ## ## ## ++ ## ## ## ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["naurglen2"].terrain[7] = 'sb sb sb sb sb sb rf rf rf rf rf rf rf sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ++ ++ ++ ++ ++ ++ ++ ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["naurglen2"].terrain[8] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb #O ++ ++ ++ ++ ++ ++ ++ #O sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["naurglen2"].terrain[9] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ++ ++ ++ ++ ++ ++ ++ ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["naurglen2"].terrain[10] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ++ ++ ++ ++ ++ ++ ++ ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["naurglen2"].terrain[11] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ## ## ## ## ## ## ## ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["naurglen2"].terrain[12] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ## ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ## ## #O ## ## ## sb ## ## ## #O ## ## ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["naurglen2"].terrain[13] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ## sb ## ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## -= -= -= -= -= ## sb ## -= -= -= -= -= ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["naurglen2"].terrain[14] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ## sb sb sb ## ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## -= -= -= -= -= ## sb ## -= -= -= -= -= ## sb sb sb sb sb sb sb sb sb ## ## ## ## #O ## ## sb sb sb sb sb';
mappages["naurglen2"].terrain[15] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## sb sb sb sb sb ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb #O -= -= -= -= -= ## sb ## -= -= -= -= -= #O sb sb sb sb sb sb sb sb sb ## -= -= -= -= -= ## sb sb sb sb sb';
mappages["naurglen2"].terrain[16] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ## sb sb sb ## ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## -= -= -= -= -= ## sb ## -= -= -= -= -= ## sb sb sb sb sb sb sb sb sb #O -= -= -= -= -= ## sb sb sb sb sb';
mappages["naurglen2"].terrain[17] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ## sb ## ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ## ## ## ## ## ## sb ## ## ## ## ## ## ## sb sb sb sb sb sb sb sb sb ## -= -= -= -= -= ## sb sb sb sb sb';
mappages["naurglen2"].terrain[18] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ## ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb #O -= -= -= -= -= ## sb sb sb sb sb';
mappages["naurglen2"].terrain[19] = 'sb sb sb sb rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## -= -= -= -= -= ## sb sb sb sb sb';
mappages["naurglen2"].terrain[20] = 'sb sb sb sb rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb sb ## ## ## ## #O ## ## sb sb sb sb sb';
mappages["naurglen2"].terrain[21] = 'sb sb sb sb rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["naurglen2"].terrain[22] = 'sb sb sb sb rc rc rc rc rc rc rc rc sb sb sb sb sb sb sb sb rc rc rc rc rc rc rc rc rc sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["naurglen2"].terrain[23] = 'sb sb sb sb rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["naurglen2"].terrain[24] = 'sb sb sb sb rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb rf rf rf rf rf rf sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["naurglen2"].terrain[25] = 'sb sb sb sb rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb rf rf rf rf rf rf sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb sb ## ## ## ## ## ## ## ## sb sb sb sb';
mappages["naurglen2"].terrain[26] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb sb ## ++ ++ ++ ++ ++ ++ ## sb sb sb sb';
mappages["naurglen2"].terrain[27] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ++ ++ ++ ++ ++ ++ ## sb sb sb sb';
mappages["naurglen2"].terrain[28] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb #O ++ ++ ++ ++ ++ ++ #O sb sb sb sb';
mappages["naurglen2"].terrain[29] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ++ ++ ++ ## ++ ## ## sb sb sb sb';
mappages["naurglen2"].terrain[30] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ++ ++ ++ ## ++ ++ ## sb sb sb sb';
mappages["naurglen2"].terrain[31] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ## ## ## ## ++ ## ## sb sb sb sb';
mappages["naurglen2"].terrain[32] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb ## ++ ++ ++ ## ++ ++ ## sb sb sb sb';
mappages["naurglen2"].terrain[33] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb #O ++ ++ ++ ++ ++ ++ ## sb sb sb sb';
mappages["naurglen2"].terrain[34] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb ## ++ ++ ++ ## ++ ++ ## sb sb sb sb';
mappages["naurglen2"].terrain[35] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb ## ## ## ## ## ++ ++ #O sb sb sb sb';
mappages["naurglen2"].terrain[36] = 'sb sb sb sb sb sb ## ## ## ## ## ## #O ## ## ## sb sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb ## ++ ++ ++ ## ++ ++ ## sb sb sb sb';
mappages["naurglen2"].terrain[37] = 'sb sb sb sb sb sb ## ++ ++ ++ ## ++ ++ ++ ## ## sb sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb rc rc rc rc rc rc rc rc rc rc rc sb sb sb sb rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc sb sb sb sb sb sb sb sb #O ++ ++ ++ ++ ++ ++ ## sb sb sb sb';
mappages["naurglen2"].terrain[38] = 'sb sb sb sb sb sb ## ++ ++ ++ ## ++ ++ ++ ## ## sb sb sb sb sb sb sb sb rc rc rc rc rc rc rc rc sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb ## ++ ++ ++ ## ++ ++ ## sb sb sb sb';
mappages["naurglen2"].terrain[39] = 'sb sb sb sb sb sb #O ++ ++ ++ ## ++ ++ ++ ## ## sb sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb ## ## ## ## ## ## ## ## sb sb sb sb';
mappages["naurglen2"].terrain[40] = 'sb sb sb sb sb sb ## ## ++ ## ## ++ ++ ++ ++ ## sb sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["naurglen2"].terrain[41] = 'sb sb sb sb sb sb ## ++ ++ ++ ## ++ ++ ++ ## ## sb sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["naurglen2"].terrain[42] = 'sb sb sb sb sb sb ## ++ ++ ++ ++ ++ ++ ++ ## ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["naurglen2"].terrain[43] = 'sb sb sb sb sb sb ## ## ## ## ## ## #O ## ## ## sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["naurglen2"].terrain[44] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["naurglen2"].terrain[45] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["naurglen2"].terrain[46] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';

mappages["naurglen2"].features = [];
mappages["naurglen2"].features[0] = {name : 'StairDown', x : 7, y : 42, entermap : 'naurglen', enterx : 7, entery : 42};
mappages["naurglen2"].features[1] = {name : 'Door', x : 8, y : 40};
mappages["naurglen2"].features[2] = {name : 'Door', x : 10, y : 42};
mappages["naurglen2"].features[3] = {name : 'BedHead', x : 7, y : 37};
mappages["naurglen2"].features[4] = {name : 'BedFoot', x : 8, y : 37};
mappages["naurglen2"].features[5] = {name : 'Dresser', x : 9, y : 37};
mappages["naurglen2"].features[6] = {name : 'UnlitBrazier', x : 9, y : 39};
mappages["naurglen2"].features[7] = {name : 'BedHead', x : 12, y : 42};
mappages["naurglen2"].features[8] = {name : 'BedFoot', x : 13, y : 42};
mappages["naurglen2"].features[9] = {name : 'Mirror', x : 11, y : 37};
mappages["naurglen2"].features[10] = {name : 'Vanity', x : 13, y : 37};
mappages["naurglen2"].features[11] = {name : 'Dresser', x : 13, y : 39};
mappages["naurglen2"].features[12] = {name : 'SmallTable', x : 12, y : 40};
mappages["naurglen2"].features[13] = {name : 'RightChair', x : 13, y : 40};
mappages["naurglen2"].features[14] = {name : 'StairDown2', x : 94, y : 30, entermap : 'naurglen', enterx : 94, entery : 30};
mappages["naurglen2"].features[15] = {name : 'GrandfatherClock', x : 89, y : 26};
mappages["naurglen2"].features[16] = {name : 'BedHead', x : 89, y : 30};
mappages["naurglen2"].features[17] = {name : 'BedFoot', x : 90, y : 30};
mappages["naurglen2"].features[18] = {name : 'LeftTable', x : 92, y : 27};
mappages["naurglen2"].features[19] = {name : 'RightTable', x : 93, y : 27};
mappages["naurglen2"].features[20] = {name : 'TopChair', x : 93, y : 26};
mappages["naurglen2"].features[21] = {name : 'TopChair', x : 94, y : 27};
mappages["naurglen2"].features[22] = {name : 'Mirror', x : 90, y : 26};
mappages["naurglen2"].features[23] = {name : 'Dresser', x : 91, y : 30};
mappages["naurglen2"].features[24] = {name : 'StairDown2', x : 93, y : 17, entermap : 'naurglen', enterx : 93, entery : 17};
mappages["naurglen2"].features[25] = {name : 'BedHead', x : 89, y : 15};
mappages["naurglen2"].features[26] = {name : 'BedHead', x : 89, y : 19};
mappages["naurglen2"].features[27] = {name : 'BedFoot', x : 90, y : 19};
mappages["naurglen2"].features[28] = {name : 'BedFoot', x : 90, y : 15};
mappages["naurglen2"].features[29] = {name : 'BookshelfLeft', x : 89, y : 17};
mappages["naurglen2"].features[30] = {name : 'BookshelfRight', x : 90, y : 17};
mappages["naurglen2"].features[31] = {name : 'Dresser', x : 93, y : 15};
mappages["naurglen2"].features[32] = {name : 'Dresser', x : 93, y : 19};
mappages["naurglen2"].features[33] = {name : 'SmallBox', x : 91, y : 19};
mappages["naurglen2"].features[34] = {name : 'Vanity', x : 91, y : 15};
mappages["naurglen2"].features[35] = {name : 'UnlitBrazier', x : 91, y : 17};
mappages["naurglen2"].features[36] = {name : 'StairDown', x : 73, y : 16, entermap : 'naurglen', enterx : 73, entery : 16};
mappages["naurglen2"].features[37] = {name : 'StairDown2', x : 69, y : 16, entermap : 'naurglen', enterx : 69, entery : 16};
mappages["naurglen2"].features[38] = {name : 'BedHead', x : 65, y : 13};
mappages["naurglen2"].features[39] = {name : 'BedHead', x : 76, y : 13};
mappages["naurglen2"].features[40] = {name : 'BedFoot', x : 77, y : 13};
mappages["naurglen2"].features[41] = {name : 'BedFoot', x : 66, y : 13};
mappages["naurglen2"].features[42] = {name : 'UnlitBrazier', x : 73, y : 13};
mappages["naurglen2"].features[43] = {name : 'UnlitBrazier', x : 69, y : 13};
mappages["naurglen2"].features[44] = {name : 'Dresser', x : 69, y : 15};
mappages["naurglen2"].features[45] = {name : 'Dresser', x : 73, y : 15};
mappages["naurglen2"].features[46] = {name : 'SmallBox', x : 65, y : 16};
mappages["naurglen2"].features[47] = {name : 'SmallBox', x : 77, y : 16};
mappages["naurglen2"].features[48] = {name : 'StairDown', x : 44, y : 7, entermap : 'null', enterx : 0, entery : 0};
mappages["naurglen2"].features[49] = {name : 'BedHead', x : 49, y : 8};
mappages["naurglen2"].features[50] = {name : 'BedHead', x : 49, y : 9};
mappages["naurglen2"].features[51] = {name : 'BedFoot', x : 50, y : 8};
mappages["naurglen2"].features[52] = {name : 'BedFoot', x : 50, y : 9};
mappages["naurglen2"].features[53] = {name : 'Dresser', x : 44, y : 9};
mappages["naurglen2"].features[54] = {name : 'Dresser', x : 44, y : 10};
mappages["naurglen2"].features[55] = {name : 'GrandfatherClock', x : 46, y : 7};
mappages["naurglen2"].features[56] = {name : 'SmallTable', x : 46, y : 10};
mappages["naurglen2"].features[57] = {name : 'TopChair', x : 46, y : 9};
mappages["naurglen2"].features[58] = {name : 'RightChair', x : 47, y : 10};
mappages["naurglen2"].features[59] = {name : 'Fireplace', x : 14, y : 40};
mappages["naurglen2"].features[60] = {name : 'Fireplace', x : 47, y : 6};
mappages["naurglen2"].features[61] = {name : 'Door', x : 93, y : 29};
mappages["naurglen2"].features[62] = {name : 'Brazier', x : 91, y : 29};
mappages["naurglen2"].features[63] = {name : 'BedHead', x : 89, y : 29};
mappages["naurglen2"].features[64] = {name : 'BedFoot', x : 90, y : 29};
mappages["naurglen2"].features[65] = {name : 'Door', x : 92, y : 33, desc : "locked door", locked : 1};
mappages["naurglen2"].features[66] = {name : 'Door', x : 92, y : 37, desc : "locked door", locked : 1};
mappages["naurglen2"].features[67] = {name : 'PottedPlant', x : 94, y : 38};
mappages["naurglen2"].features[68] = {name : 'PottedPlant', x : 94, y : 32};
mappages["naurglen2"].features[69] = {name : 'BedHead', x : 89, y : 34};
mappages["naurglen2"].features[70] = {name : 'BedHead', x : 89, y : 36};
mappages["naurglen2"].features[71] = {name : 'BedFoot', x : 90, y : 34};
mappages["naurglen2"].features[72] = {name : 'BedFoot', x : 90, y : 36};
mappages["naurglen2"].features[73] = {name : 'UnlitBrazier', x : 91, y : 32};
mappages["naurglen2"].features[74] = {name : 'UnlitBrazier', x : 91, y : 38};
mappages["naurglen2"].features[75] = {name : 'Dresser', x : 89, y : 38};
mappages["naurglen2"].features[76] = {name : 'Dresser', x : 89, y : 32};


mappages["naurglen2"].npcs = [];
mappages["naurglen2"].npcs[0] = {name : 'TownsfolkVillagerNPC', x : 7, y : 37, NPCName: 'Avery', PeaceAI: 'scheduled', Schedule: 'avery', Conversation: 'avery', ConversationFlag: 'avery', Gender: 'male', Leash: 2, Bark: '0', NPCBand: '0', OverrideGraphic: '310.gif'};
mappages["naurglen2"].npcs[1] = {name : 'RangerVillagerNPC', x : 49, y : 8, NPCName: 'Garen', PeaceAI: 'scheduled', Schedule: 'garen', Conversation: 'garen', ConversationFlag: 'garen', Gender: 'male', OverrideGraphic: 'ranger-offcolor.gif'};
mappages["naurglen2"].npcs[2] = {name : 'AdventurerVillagerNPC', x : 49, y : 9, NPCName: 'Warren', PeaceAI: 'scheduled', Schedule: 'warren', Conversation: 'warren', ConversationFlag: 'warren', Gender: 'male', OverrideGraphic: '306.gif'};
mappages["naurglen2"].npcs[3] = {name : 'TownGuardNPC', x : 65, y : 13, NPCName: 'Evelyn', PeaceAI: 'scheduled', Schedule: 'evelyn', Conversation: 'evelyn', ConversationFlag: 'evelyn', Gender: 'female', Bark: '0', NPCBand: '0'};
mappages["naurglen2"].npcs[4] = {name : 'TownsfolkVillagerNPC', x : 89, y : 15, NPCName: 'Dora', Conversation: 'dora', ConversationFlag: 'dora', Gender: 'female', Leash: 2, Bark: '0', NPCBand: '0', OverrideGraphic: '310.gif'};
mappages["naurglen2"].npcs[5] = {name : 'TownsfolkVillagerNPC', x : 89, y : 19, NPCName: 'Ingrid', Conversation: 'ingrid', ConversationFlag: 'ingrid', Gender: 'female', OverrideGraphic: '310.gif'};
mappages["naurglen2"].npcs[6] = {name : 'TownsfolkVillagerNPC', x : 89, y : 30, NPCName: 'Sand', Desc: 'innkeeper', PeaceAI: 'scheduled', Schedule: 'sand', Conversation: 'sand', Gender: 'female', Bark: '0', NPCBand: '0', OverrideGraphic: '310.gif'};

mappages["naurglen2"].desc = "Naurglen";
mappages["naurglen2"].music = 'Village';
mappages["naurglen2"].savename = 'Naurglen';
mappages["naurglen2"].exitmap = 'darkunknown';
mappages["naurglen2"].exitx = '72';
mappages["naurglen2"].exity = '75';
mappages["naurglen2"].wraps = '';
mappages["naurglen2"].enterx = '66';
mappages["naurglen2"].entery = '98';
mappages["naurglen2"].seeBelow = 'naurglen';
mappages["naurglen2"].lightLevel = 'cycle';
mappages["naurglen2"].alwaysRemember = '0';
mappages["naurglen2"].scale = '1';
mappages["naurglen2"].underground = '0';
mappages["naurglen2"].undergroundDesc = '';
mappages["naurglen2"].enterscript = '';
mappages["naurglen2"].entertestscript = '';
mappages["naurglen2"].exitscript = '';
mappages["naurglen2"].exittestscript = '';
mappages["naurglen2"].returnmap = 'darkunknown';
mappages["naurglen2"].returnx = '72';
mappages["naurglen2"].returny = '75';
mappages["naurglen2"].returninfused = '0';
mappages["naurglen2"].linkedMaps = ["naurglen","naurglen_limbo"];
mappages["naurglen2"].editorLabels = '{"div_tile66x16":"Evelyn","div_tile74x14":"Grayson","div_tile89x17":"Dora and Ingrid","div_tile92x33":"Kyvek Room","div_tile56x37":"Amaeryl","div_tile26x39":"Kylee and Sam","div_tile45x8":"Warren and Garen","div_tile23x22":"Derek","div_tile9x38":"PC Home","div_tile74x37":"Hazel","div_tile22x6":"Soldier","div_tile7x23":"Soldier"}';


mappages["naurglen_limbo"] = {};
mappages["naurglen_limbo"].terrain = [];
mappages["naurglen_limbo"].terrain[0] = 'WW WW WW WW WW';
mappages["naurglen_limbo"].terrain[1] = 'WW ## ## ## WW';
mappages["naurglen_limbo"].terrain[2] = 'WW ## ++ ## WW';
mappages["naurglen_limbo"].terrain[3] = 'WW ## ## ## WW';
mappages["naurglen_limbo"].terrain[4] = 'WW WW WW WW WW';

mappages["naurglen_limbo"].features = [];


mappages["naurglen_limbo"].npcs = [];

mappages["naurglen_limbo"].desc = "Naurglen Limbo";
mappages["naurglen_limbo"].music = 'Village';
mappages["naurglen_limbo"].savename = 'Naurglen';
mappages["naurglen_limbo"].exitmap = 'naurglen';
mappages["naurglen_limbo"].exitx = '65';
mappages["naurglen_limbo"].exity = '70';
mappages["naurglen_limbo"].wraps = '';
mappages["naurglen_limbo"].enterx = '65';
mappages["naurglen_limbo"].entery = '70';
mappages["naurglen_limbo"].seeBelow = '';
mappages["naurglen_limbo"].lightLevel = 'bright';
mappages["naurglen_limbo"].alwaysRemember = '0';
mappages["naurglen_limbo"].scale = '1';
mappages["naurglen_limbo"].underground = '0';
mappages["naurglen_limbo"].undergroundDesc = '';
mappages["naurglen_limbo"].enterscript = '';
mappages["naurglen_limbo"].entertestscript = '';
mappages["naurglen_limbo"].exitscript = '';
mappages["naurglen_limbo"].exittestscript = '';
mappages["naurglen_limbo"].returnmap = '';
mappages["naurglen_limbo"].returnx = 'NaN';
mappages["naurglen_limbo"].returny = 'NaN';
mappages["naurglen_limbo"].returninfused = '0';
mappages["naurglen_limbo"].linkedMaps = ["naurglen","naurglen2"];
mappages["naurglen_limbo"].editorLabels = '{}';


// Naurglen NPC Schedules

//DU.schedules["avery"] = new NPCSchedule();
//DU.schedules["avery"].addActivity("RouteTo", {startCondition: "Time", time: "6:00", destination: {x:8,y:41} });
//DU.schedules["avery"].addActivity("CallAI", { startCondition: "PreviousComplete", AIName: "CloseDoor", params: { x:8,y:40}});
//DU.schedules["avery"].addActivity("RouteTo", {startCondition: "PreviousComplete", destination: {x:7,y:42} });
//DU.schedules["avery"].addActivity("ChangeMap", {startCondition: "PreviousComplete", destination: { x:7, y:42, mapName: "naurglen"}});
//DU.schedules["avery"].addActivity("RouteTo", {startCondition: "PreviousComplete", destination: {x:11,y:42} });
//DU.schedules["avery"].addActivity("CallAI", { startCondition: "PreviousComplete", AIName: "PlaceItem", params: { name: "PlateWithFood", x:11,y:41}});
//DU.schedules["avery"].addActivity("CallAI", { startCondition: "Time", time: "7:00", AIName: "DeleteLastItem" } );
//DU.schedules["avery"].addActivity("RouteTo", {startCondition: "PreviousComplete", destination: {x:10,y:39}, leashLength: 3 });