"use strict";

mappages["naurglen"] = {};
mappages["naurglen"].terrain = [];
 mappages["naurglen"].terrain[0] = '.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..';
 mappages["naurglen"].terrain[1] = '.. .. ## ## ## ## ## #O ## ## ## ## ## ## ## #O ## ## ## .. ,, .. .. .. ,, .. .. .. ,; .. .. ..';
 mappages["naurglen"].terrain[2] = '.. ,, ## ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ,, .. .. ,, .. .. ,; ,, .. .. ,, .. ..';
 mappages["naurglen"].terrain[3] = '.. .. ## ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .. .. ,, ,, .. .. ,, ,, .. .. ..';
 mappages["naurglen"].terrain[4] = '.. .. ## ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. ,, .. .. .. .. .. .. .. .. .. ..';
 mappages["naurglen"].terrain[5] = ',, .. ## ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .. .. ,, .. ,, .. .. .. .. .. ..';
 mappages["naurglen"].terrain[6] = '.. .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. ,, .. .. .. .. .. .. .. ,, .. .. ..';
 mappages["naurglen"].terrain[7] = '.. .. ## ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .. ,, ,, .. ,, .. .. .. .. ,, ..';
 mappages["naurglen"].terrain[8] = '.. .. ## ## ## ## ## ## ## ## ## ## ## ## ## ## ++ ## ## ,, ,, .. .. .. .. .. ,, .. .. .. .. ..';
 mappages["naurglen"].terrain[9] = '.. ,, .. .. ,, .. .. ,, .. .. ,, .. ,, ,, ,, .. .. .. .. ,, .. .. .. .. .. .. .. .. .. .. .. ..';
mappages["naurglen"].terrain[10] = ',, .. ,, .. .. .. .. ,, ,, .. .. ,, ,, .. .. .. .. .. ,, ,, .. ## ## ## ## ## ## ## ## ## ## ,,';
mappages["naurglen"].terrain[11] = '.. .. .. ,, .. .. ,, .. .. .. .. .. .. .. ,, .. .. .. ,, .. .. ## ++ ++ ++ ++ ++ ++ ++ ++ ## ,,';
mappages["naurglen"].terrain[12] = '.. ,, ,, ,, .. ,, ,, ,, ,, ,, .. ,, .. ,, ,, .. .. .. ,, ,, ,, ## ++ ++ ++ ++ ++ ++ ++ ++ ## ..';
mappages["naurglen"].terrain[13] = '.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ## ++ ++ ++ ++ ++ ++ ++ ++ ## ..';
mappages["naurglen"].terrain[14] = '.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ,,';
mappages["naurglen"].terrain[15] = '.. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ## ++ ++ ++ ++ ++ ++ ++ ++ ## ..';
mappages["naurglen"].terrain[16] = ',, .. ,, .. ,, ,, .. ,, .. .. ,, .. .. ,, ,, .. .. .. ,, ,, ,, ## ++ ++ ++ ## ## ## ## ## ## ..';
mappages["naurglen"].terrain[17] = '.. ## ## ## ## ## ## ## ## ## ## .. .. .. ,, .. .. .. ,, ,; ,; ## ++ ++ ++ ## ++ ++ ++ ++ ## ..';
mappages["naurglen"].terrain[18] = ',, ## ## ## ## ## ++ ## ## ## ## ,, ,, .. .. .. .. .. .. ,; .. ## ++ ++ ++ ## ++ ++ ++ ++ #O ,,';
mappages["naurglen"].terrain[19] = '.. ## ++ ++ ++ ++ ++ ++ ++ ++ ## ,, .. .. ,, .. .. .. ,, .. ,; ## ++ ++ ++ ## ++ ++ ++ ++ ## ..';
mappages["naurglen"].terrain[20] = '.. #O ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. ,, ,, .. .. .. .. ,, .. ## ++ ++ ++ ++ ++ ++ ++ ++ ## ..';
mappages["naurglen"].terrain[21] = '.. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ .. .. .. ,, .. .. .. ,, .. .. ## ++ ++ ++ ## ## ## ## ## ## ..';
mappages["naurglen"].terrain[22] = '.. ## ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. ,, ,, .. .. .. ,, ,, .. ## ++ ++ ++ ## ++ ++ ++ ++ ## ,,';
mappages["naurglen"].terrain[23] = ',, ## ++ ++ ++ ++ ++ ++ ## ++ ## .. ,, .. ,, .. .. .. .. .. .. ## ++ ++ ++ ## ++ ++ ++ ++ #O ..';
mappages["naurglen"].terrain[24] = '.. ## ++ ++ ++ ++ ++ ++ ## ++ ## .. .. .. .. .. .. .. ,, .. .. ## ++ ++ ++ ## ++ ++ ++ ++ ## ,,';
mappages["naurglen"].terrain[25] = '.. ## ++ ++ ++ ++ ++ ++ ## ++ ## .. .. ,, ,, .. .. .. ,, ,, .. ## ++ ++ ++ ++ ++ ++ ++ ++ ## ..';
mappages["naurglen"].terrain[26] = '.. ## ## ## #O ## ## ## ## ## ## .. .. ,, .. .. .. .. ,; ,, .. ## ## ## ## ## ## ## ## ## ## ..';
mappages["naurglen"].terrain[27] = '.. .. .. ,, ,, .. .. ,, .. .. .. ,; .. .. ,, .. .. .. ,, .. .. ,, .. ,, ,, .. .. .. .. .. .. ..';
mappages["naurglen"].terrain[28] = '.. ,, ,, ,, .. .. ,, .. ,; .. ,, .. ,, .. ,, .. .. .. ,, ,, .. .. .. .. .. .. ,, .. ,, .. .. ..';
mappages["naurglen"].terrain[29] = ',, .. ,, .. ,, ,, .. ,; ,; .. ,, ,, .. .. ,, .. .. .. .. .. ,, .. .. ,, ,, .. .. ,, .. .. .. ,,';
mappages["naurglen"].terrain[30] = '.. .. ,, .. .. .. ,, .. ,, ,, .. ,, .. ,, ,, .. .. .. ,, .. ,; ,, ,, .. .. ,, .. .. .. ,, .. ..';
mappages["naurglen"].terrain[31] = '.. .. .. ,, .. .. .. .. ,, ,, .. .. .. .. ,, .. .. .. ,, ,, .. ,, .. ,; .. .. .. .. .. .. .. ..';

mappages["naurglen"].features = [];
mappages["naurglen"].features[0] = {name : 'DoorWindow', x : 10, y : 21};
mappages["naurglen"].features[1] = {name : 'DoorWindow', x : 21, y : 14};
mappages["naurglen"].features[2] = {name : 'Door', x : 25, y : 25};
mappages["naurglen"].features[3] = {name : 'Door', x : 25, y : 20};
mappages["naurglen"].features[4] = {name : 'DoorWindow', x : 16, y : 8};
mappages["naurglen"].features[5] = {name : 'Well', x : 26, y : 4};
mappages["naurglen"].features[6] = {name : 'SingleSignpost', x : 19, y : 16};
mappages["naurglen"].features[7] = {name : 'InnSign', x : 19, y : 15, prefix : "a", desc : "sign: Ye Olde Inn", prefix : ""};
mappages["naurglen"].features[8] = {name : 'SignpostLeft', x : 13, y : 10};
mappages["naurglen"].features[9] = {name : 'SignpostRight', x : 15, y : 10};
mappages["naurglen"].features[10] = {name : 'TavernSign', x : 14, y : 10, prefix : "a", desc : "sign: The Red Hen Tavern", prefix : ""};
mappages["naurglen"].features[11] = {name : 'LeftTable', x : 4, y : 3};
mappages["naurglen"].features[12] = {name : 'MiddleTable', x : 5, y : 3};
mappages["naurglen"].features[13] = {name : 'MiddleTable', x : 6, y : 3};
mappages["naurglen"].features[14] = {name : 'RightTable', x : 7, y : 3};
mappages["naurglen"].features[15] = {name : 'Fireplace', x : 3, y : 6};
mappages["naurglen"].features[16] = {name : 'LeftTable', x : 7, y : 6};
mappages["naurglen"].features[17] = {name : 'RightTable', x : 8, y : 6};
mappages["naurglen"].features[18] = {name : 'LeftTable', x : 12, y : 3};
mappages["naurglen"].features[19] = {name : 'RightTable', x : 13, y : 3};
mappages["naurglen"].features[20] = {name : 'LeftTable', x : 15, y : 5};
mappages["naurglen"].features[21] = {name : 'RightTable', x : 16, y : 5};
mappages["naurglen"].features[22] = {name : 'LeftChair', x : 6, y : 6};
mappages["naurglen"].features[23] = {name : 'TopChair', x : 13, y : 2};
mappages["naurglen"].features[24] = {name : 'TopChair', x : 16, y : 4};
mappages["naurglen"].features[25] = {name : 'RightChair', x : 17, y : 5};
mappages["naurglen"].features[26] = {name : 'LeftTable', x : 27, y : 13};
mappages["naurglen"].features[27] = {name : 'MiddleTable', x : 28, y : 13};
mappages["naurglen"].features[28] = {name : 'RightTable', x : 29, y : 13};
mappages["naurglen"].features[29] = {name : 'BedHead', x : 28, y : 17};
mappages["naurglen"].features[30] = {name : 'BedHead', x : 28, y : 22};
mappages["naurglen"].features[31] = {name : 'BedFoot', x : 29, y : 17};
mappages["naurglen"].features[32] = {name : 'BedFoot', x : 29, y : 22};
mappages["naurglen"].features[33] = {name : 'Mirror', x : 26, y : 17};
mappages["naurglen"].features[34] = {name : 'Mirror', x : 26, y : 22};
mappages["naurglen"].features[35] = {name : 'UnlitBrazier', x : 29, y : 19};
mappages["naurglen"].features[36] = {name : 'UnlitBrazier', x : 29, y : 24};
mappages["naurglen"].features[37] = {name : 'Brazier', x : 23, y : 11};
mappages["naurglen"].features[38] = {name : 'Fireplace', x : 6, y : 18};
mappages["naurglen"].features[39] = {name : 'BedHead', x : 2, y : 22};
mappages["naurglen"].features[40] = {name : 'BedHead', x : 2, y : 24};
mappages["naurglen"].features[41] = {name : 'BedHead', x : 5, y : 22};
mappages["naurglen"].features[42] = {name : 'BedHead', x : 5, y : 24};
mappages["naurglen"].features[43] = {name : 'BedFoot', x : 6, y : 22};
mappages["naurglen"].features[44] = {name : 'BedFoot', x : 6, y : 24};
mappages["naurglen"].features[45] = {name : 'BedFoot', x : 3, y : 24};
mappages["naurglen"].features[46] = {name : 'BedFoot', x : 3, y : 22};
mappages["naurglen"].features[47] = {name : 'BookshelfLeft', x : 8, y : 19};
mappages["naurglen"].features[48] = {name : 'BookshelfRight', x : 9, y : 19};
mappages["naurglen"].features[49] = {name : 'LeftTable', x : 4, y : 20};
mappages["naurglen"].features[50] = {name : 'RightTable', x : 5, y : 20};
mappages["naurglen"].features[51] = {name : 'Door', x : 9, y : 23, desc : "locked door", locked : 1};
mappages["naurglen"].features[52] = {name : 'SingleSignpost', x : 11, y : 24};
mappages["naurglen"].features[53] = {name : 'HealerSign', x : 11, y : 23, prefix : "a", desc : "sign: Healer Hazel"};


mappages["naurglen"].npcs = [];
mappages["naurglen"].npcs[0] = {name : 'ShepherdVillagerNPC', x : 28, y : 4, NPCName: 'Samuel', Desc: 'blind shepherd', Conversation: 'samuel', Gender: 'male', Bark: '0', NPCBand: '0', OverrideGraphic: '301.gif'};
mappages["naurglen"].npcs[1] = {name : 'TownsfolkVillagerNPC', x : 28, y : 12, NPCName: 'Daniel', Conversation: 'daniel', Gender: 'male', Bark: '0', NPCBand: '0', OverrideGraphic: '310.gif'};
mappages["naurglen"].npcs[2] = {name : 'TinkerVillagerNPC', x : 23, y : 24, NPCName: 'Kyvek', Conversation: 'kyvek', ConversationFlag: 'debt_paid', Gender: 'male', Bark: '0', NPCBand: '0', OverrideGraphic: '304.2.gif'};
mappages["naurglen"].npcs[3] = {name : 'DruidVillagerNPC', x : 3, y : 20, NPCName: 'Hazel', Desc: 'healer', Conversation: 'hazel', ConversationFlag: 'given_hood', Gender: 'female', Leash: 2, Bark: '0', NPCBand: '0', OverrideGraphic: 'druid-offcolor.1.gif'};
mappages["naurglen"].npcs[4] = {name : 'RangerVillagerNPC', x : 11, y : 3, NPCName: 'Garen', Conversation: 'garen', Gender: 'male', Bark: '0', NPCBand: '0', OverrideGraphic: 'ranger-offcolor.gif'};
mappages["naurglen"].npcs[5] = {name : 'AdventurerVillagerNPC', x : 13, y : 4, NPCName: 'Warren', Conversation: 'warren', Gender: 'male', Bark: '0', NPCBand: '0', OverrideGraphic: '306.gif'};
mappages["naurglen"].npcs[6] = {name : 'PaladinVillagerNPC', x : 9, y : 6, NPCName: 'Amaeryl', Conversation: 'amaeryl', Gender: 'female', Bark: '0', NPCBand: '0', OverrideGraphic: '307.2.gif'};
mappages["naurglen"].npcs[7] = {name : 'TownGuardNPC', x : 8, y : 13, NPCName: 'Guard', Alignment: 'good', Conversation: 'naurglen_guard', Gender: 'male'};
mappages["naurglen"].npcs[8] = {name : 'TownsfolkVillagerNPC', x : 25, y : 3, NPCName: 'Kylee', Desc: 'farmer', Conversation: 'kylee', ConversationFlag: 'rescued_sam', Gender: 'female', Bark: '0', NPCBand: '0', OverrideGraphic: '310.2.gif'};
mappages["naurglen"].npcs[9] = {name : 'TownsfolkVillagerNPC', x : 5, y : 2, NPCName: 'Ingrid', Conversation: 'ingrid', Gender: 'female', Bark: '0', NPCBand: '0', OverrideGraphic: '310.gif'};

mappages["naurglen"].desc = "the Village of Naurglen";
mappages["naurglen"].music = 'Village';
mappages["naurglen"].exitmap = 'darkunknown';
mappages["naurglen"].exitx = '72';
mappages["naurglen"].exity = '75';
mappages["naurglen"].wraps = 'None';
mappages["naurglen"].enterx = '16';
mappages["naurglen"].entery = '30';
mappages["naurglen"].seeBelow = '';
mappages["naurglen"].lightLevel = 'bright';
mappages["naurglen"].alwaysRemember = '0';
mappages["naurglen"].scale = '1';
mappages["naurglen"].enterscript = '';
mappages["naurglen"].entertestscript = '';
mappages["naurglen"].exitscript = '';
mappages["naurglen"].exittestscript = '';
mappages["naurglen"].returnmap = 'darkunknown';
mappages["naurglen"].returnx = '69';
mappages["naurglen"].returny = '74';
mappages["naurglen"].returninfused = '0';
mappages["naurglen"].linkedMaps = [""];

mappages["naurglen"].onload = function(mapref) {
  
  if (DU.gameflags["rescued_sam"]) {
    var sam = localFactory.createTile("ChildVillagerNPC");
    sam.setNPCName("Samantha");
    sam.setConversation("samantha2");
    sam.setGender("female");
    sam.setDesc("excited girl");
    sam.setPrefix("an");
    sam.setBark("sam");
    sam.setLeash(3);
    mapref.placeThing(23,4,sam);
  }
}