mappages["onyx"] = {};
mappages["onyx"].terrain = [];
 mappages["onyx"].terrain[0] = '.. uu uu .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..';
 mappages["onyx"].terrain[1] = '.. uu uu .. ## ## ## ## ## ## ## ## #O ## ## .. .. .. .. .. .. ## ## ## ## ## ## ## ## ## ## .. .. .. .. .. .. .. .. .. .. .. .. ..';
 mappages["onyx"].terrain[2] = '.. uu uu .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ## ## #O ## ## ## ## ;; ;; ;; ;; ;; ;; ;; ;; ## .. .. .. .. .. .. .. .. .. .. .. .. ..';
 mappages["onyx"].terrain[3] = '.. uu uu .. ## [: :: :: :: :] ++ ++ ++ ++ ## ++ ++ ++ ## .. .. ;; ;; ## ## ## ## ## ++ ## ## .. .. .. ## ## ## ## ## ## ## ## ## ..';
 mappages["onyx"].terrain[4] = '.. uu uu .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ## .. .. .. ;; ## ++ ++ ++ ++ ++ ++ ## .. .. .. ## ++ ++ ++ ++ ++ ++ ++ ## ..';
 mappages["onyx"].terrain[5] = '.. uu uu .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ## .. .. .. .. ## ++ ++ ++ ++ ++ ++ ## .. .. .. ## ++ ++ ++ ++ ++ ++ ++ ## ..';
 mappages["onyx"].terrain[6] = '.. uu uu .. #O ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ## ## ## ## .. .. ,, .. ## ## ## ## ## ## ## ## ## ## ## ## ++ ++ ++ ++ ++ ++ ++ ## ..';
 mappages["onyx"].terrain[7] = '.. uu uu .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ## .. .. .. .. ## ++ ++ ++ ++ ++ ++ ## ;; ;; ;; ## ++ ++ ++ ++ ++ ++ ++ ## ..';
 mappages["onyx"].terrain[8] = '.. uu uu .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ## .. .. ,, ,, ## ++ ++ ++ ++ ++ ++ ## ;; ;; ;; ## ++ ++ ++ ++ ++ ++ ++ ## ..';
 mappages["onyx"].terrain[9] = '.. uu uu .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ## ,, .. .. ,, ## ++ ++ ++ ++ ++ ++ ## ;; ;; ;; ## ++ ++ ++ ++ ++ ++ ++ ## ..';
mappages["onyx"].terrain[10] = '.. uu uu .. ## ## ## #O ## ++ ## ## ## ## ## ## ## #O ## ,, ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ;; ;; ,, ## ++ ++ ++ ++ ++ ++ ++ ## ..';
mappages["onyx"].terrain[11] = '.. uu uu .. .. ## ,; .. ,, .. .. .. .. .. .. .. .. .. .. .. ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ## ;; ;; .. ## ++ ++ ++ ++ ++ ++ ++ ## ..';
mappages["onyx"].terrain[12] = '.. uu uu .. .. ## .. ,, .. .. .. .. .. .. .. .. .. .. .. ,, ++ ++ .. ## ++ ++ ++ ++ ++ ++ ## ,, .. .. ## ++ ++ ++ ++ ++ ++ ++ ## ..';
mappages["onyx"].terrain[13] = '.. uu uu ## ## ## ,, .. ,, ,, .. .. .. .. .. .. .. .. ,, ,, ++ ++ ,, ## ## ## ## ## ## ## ## ,, .. .. ## ++ ++ ++ ++ ++ ++ ++ ## ..';
mappages["onyx"].terrain[14] = '.. -= -= -= ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ .. .. .. .. ,, ,, .. .. .. .. .. .. ## ++ ++ ++ ++ ++ ++ ++ ## ..';
mappages["onyx"].terrain[15] = '.. -= -= -= ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ .. .. .. .. .. .. .. ,, .. .. .. ,, ## ++ ++ ++ ++ ++ ++ ++ ## ..';
mappages["onyx"].terrain[16] = '.. -= -= -= ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ .. .. .. ,, .. .. .. .. .. .. .. .. ## ## ## ## ++ ## ## ## ## ..';
mappages["onyx"].terrain[17] = '.. uu uu ## ## ## .. .. .. .. .. .. .. .. .. .. ,, ,, ,, ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ uu uu ## ..';
mappages["onyx"].terrain[18] = '.. uu uu .. .. ## ,; .. .. .. .. .. .. .. .. .. .. .. ,, ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ uu uu ## ..';
mappages["onyx"].terrain[19] = '.. uu uu .. .. ## ,; ,; .. .. .. .. .. .. .. .. .. .. .. ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ uu uu ## ..';
mappages["onyx"].terrain[20] = '.. uu uu .. ## ## ## ## ## ++ ## ## ## ## ## .. .. .. .. .. .. .. .. .. .. .. .. .. __ __ .. ,, ,, ,, ## ## ## ## ++ ## ## ## ## ..';
mappages["onyx"].terrain[21] = '.. uu uu .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .. .. .. .. .. ,, .. .. .. .. ./ uu uu `. .. ,, ,, ## ++ ++ ++ ++ ++ ++ ++ ## ..';
mappages["onyx"].terrain[22] = '.. uu uu .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .. .. .. .. .. ,, ,, .. .. .. .` uu uu /. .. .. ,, ## ++ ++ ++ ++ ++ ++ ++ ## ..';
mappages["onyx"].terrain[23] = '.. uu uu .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .. .. ,, .. ,, .. .. .. .. .. .. -- -- ,, ,, .. .. ## ++ ++ ++ ++ ++ ++ ++ ## ..';
mappages["onyx"].terrain[24] = '.. uu uu .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ## ## ## ## ## ## ## ## .. .. .. .. .. .. .. ,, .. .. ,; ## ++ ++ ++ ++ ++ ++ ++ ## ..';
mappages["onyx"].terrain[25] = '.. uu uu .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ## ,, .. .. .. .. .. .. .. ,; ,; ,; ## ++ ++ ++ ++ ++ ++ ++ ## ..';
mappages["onyx"].terrain[26] = '.. uu uu .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .. .. .. .. ., ## ## ## ## ## ++ ++ ++ ++ ++ ++ ++ ## ..';
mappages["onyx"].terrain[27] = '.. uu uu .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ## .. .. .. .. ., ., ., ## .. .. .. ## ++ ++ ++ ++ ++ ++ ++ ## ..';
mappages["onyx"].terrain[28] = '.. uu uu .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ++ .. .. ., ., ., ., ., ## .. .. .. ## ## ## ## ## ## ## ## ## ..';
mappages["onyx"].terrain[29] = '.. uu uu .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ## ## ## ## ## ## ## ## .. ., ., ., ., ., ., ## .. .. .. .. .. .. .. .. .. .. .. .. ..';
mappages["onyx"].terrain[30] = '.. uu uu .. ## ## ## ## ## ## ## ## ## ## ## .. .. .. .. .. .. .. ## ## ## ## ## ## ## ## ## .. .. .. .. .. .. .. .. .. .. .. .. ..';
mappages["onyx"].terrain[31] = '.. uu uu .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..';

mappages["onyx"].features = [];
mappages["onyx"].features[0] = {name : 'Doorway', x : 28, y : 3};
mappages["onyx"].features[1] = {name : 'Door', x : 28, y : 3};
mappages["onyx"].features[2] = {name : 'DoorWindow', x : 9, y : 10};
mappages["onyx"].features[3] = {name : 'Door', x : 14, y : 5, desc : "locked door", locked : 1};
mappages["onyx"].features[4] = {name : 'Door', x : 14, y : 7, desc : "locked door", locked : 1};
mappages["onyx"].features[5] = {name : 'Well', x : 27, y : 28};
mappages["onyx"].features[6] = {name : 'Doorway', x : 14, y : 26};
mappages["onyx"].features[7] = {name : 'DoorWindow', x : 9, y : 20};
mappages["onyx"].features[8] = {name : 'Door', x : 22, y : 28, desc : "locked door", locked : 1};
mappages["onyx"].features[9] = {name : 'Door', x : 38, y : 20, desc : "locked door", locked : 1};
mappages["onyx"].features[10] = {name : 'Door', x : 38, y : 16, desc : "locked door", locked : 1};
mappages["onyx"].features[11] = {name : 'DoorWindow', x : 23, y : 10};


mappages["onyx"].npcs = [];

mappages["onyx"].desc = 'the Towne of Onyx';
mappages["onyx"].music = 'Dark Towne';
mappages["onyx"].exitmap = 'darkunknown';
mappages["onyx"].exitx = '64';
mappages["onyx"].exity = '119';
mappages["onyx"].wraps = 'None';
mappages["onyx"].enterx = '1';
mappages["onyx"].entery = '15';
mappages["onyx"].seeBelow = '';
mappages["onyx"].lightLevel = 'bright';
mappages["onyx"].alwaysRemember = '0';
mappages["onyx"].scale = '1';
mappages["onyx"].enterscript = '';
mappages["onyx"].entertestscript = '';
mappages["onyx"].exitscript = '';
mappages["onyx"].exittestscript = '';
mappages["onyx"].returnmap = 'darkunknown';
mappages["onyx"].returnx = '29';
mappages["onyx"].returny = '43';
mappages["onyx"].returninfused = '0';
mappages["onyx"].linkedMaps = [""];
