mappages["Onyx"] = {};
mappages["Onyx"].terrain = [];
 mappages["Onyx"].terrain[0] = '.. uu uu .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..';
 mappages["Onyx"].terrain[1] = '.. uu uu .. ## ## ## ## ## ## ## ## #O ## ## .. .. .. .. .. .. ## ## ## ## ## ## ## ## ## ## .. .. .. .. .. .. .. .. .. .. .. .. ..';
 mappages["Onyx"].terrain[2] = '.. uu uu .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ## ## #O ## ## ## ## ;; ;; ;; ;; ;; ;; ;; ;; ## .. .. .. .. .. .. .. .. .. .. .. .. ..';
 mappages["Onyx"].terrain[3] = '.. uu uu .. ## [: :: :: :: :] ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ## ;; ;; ## ## ## ## ## ++ ## ## .. .. .. ## ## ## ## ## ## ## ## ## ..';
 mappages["Onyx"].terrain[4] = '.. uu uu .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ## .. ;; ## ++ ++ ++ ++ ++ ++ ## .. .. .. ## .. .. .. .. .. .. .. ## ..';
 mappages["Onyx"].terrain[5] = '.. uu uu .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ## .. .. ## ++ ++ ++ ++ ++ ++ ## .. .. .. ## .. .. .. .. .. .. .. ## ..';
 mappages["Onyx"].terrain[6] = '.. uu uu .. #O ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ## ## ## ## ## ## .. .. ## ## ## ## ## ## ## ## ## ## ## ## .. .. .. .. .. .. .. ## ..';
 mappages["Onyx"].terrain[7] = '.. uu uu .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ## .. .. ## ++ ++ ++ ++ ++ ++ ## .. .. .. ## .. .. .. .. .. .. .. ## ..';
 mappages["Onyx"].terrain[8] = '.. uu uu .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ## .. .. ## ++ ++ ++ ++ ++ ++ ## .. .. .. ## .. .. .. .. .. .. .. ## ..';
 mappages["Onyx"].terrain[9] = '.. uu uu .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ## .. .. ## ++ ++ ++ ++ ++ ++ ## .. .. .. ## .. .. .. .. .. .. .. ## ..';
mappages["Onyx"].terrain[10] = '.. uu uu .. ## ## ## #O ## ++ ## ## ## ## ## ## ## #O ## ## ## .. .. ## ++ ++ ++ ++ ++ ++ ## .. .. .. ## .. .. .. .. .. .. .. ## ..';
mappages["Onyx"].terrain[11] = '.. uu uu .. .. ## .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ## ++ ++ ++ ++ ++ ++ ## .. .. .. ## .. .. .. .. .. .. .. ## ..';
mappages["Onyx"].terrain[12] = '.. uu uu .. .. ## .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ## ++ ++ ++ ++ ++ ++ ## .. .. .. .. .. .. .. .. .. .. .. ## ..';
mappages["Onyx"].terrain[13] = '.. uu uu ## ## ## .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ## ## ++ ## ## ## ## ## .. .. .. .. .. .. .. .. .. .. .. ## ..';
mappages["Onyx"].terrain[14] = '.. -= -= -= .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ## ..';
mappages["Onyx"].terrain[15] = '.. -= -= -= .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ## ..';
mappages["Onyx"].terrain[16] = '.. -= -= -= .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ## ..';
mappages["Onyx"].terrain[17] = '.. uu uu ## ## ## .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ## ..';
mappages["Onyx"].terrain[18] = '.. uu uu .. .. ## .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ## ..';
mappages["Onyx"].terrain[19] = '.. uu uu .. .. ## .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ## ..';
mappages["Onyx"].terrain[20] = '.. uu uu .. ## ## ## ## ## ++ ## ## ## ## ## .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ## ..';
mappages["Onyx"].terrain[21] = '.. uu uu .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ## ..';
mappages["Onyx"].terrain[22] = '.. uu uu .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ## ..';
mappages["Onyx"].terrain[23] = '.. uu uu .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ## ..';
mappages["Onyx"].terrain[24] = '.. uu uu .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ## ## ## ## ## ## ## ## .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ## ..';
mappages["Onyx"].terrain[25] = '.. uu uu .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ## .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ## ..';
mappages["Onyx"].terrain[26] = '.. uu uu .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## .. .. .. .. .. .. .. ## ## ## ## ## .. .. .. .. .. .. .. ## ..';
mappages["Onyx"].terrain[27] = '.. uu uu .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ## .. .. .. .. .. .. .. ## .. .. .. ## .. .. .. .. .. .. .. ## ..';
mappages["Onyx"].terrain[28] = '.. uu uu .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ## .. .. .. .. .. .. .. ## .. .. .. ## ## ## ## ## ## ## ## ## ..';
mappages["Onyx"].terrain[29] = '.. uu uu .. ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ## ## ## ## ## ## ## ## .. .. .. .. .. .. .. ## .. .. .. .. .. .. .. .. .. .. .. .. ..';
mappages["Onyx"].terrain[30] = '.. uu uu .. ## ## ## ## ## ## ## ## ## ## ## .. .. .. .. .. .. .. ## ## ## ## ## ## ## ## ## .. .. .. .. .. .. .. .. .. .. .. .. ..';
mappages["Onyx"].terrain[31] = '.. uu uu .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..';

mappages["Onyx"].features = [];
mappages["Onyx"].features[0] = {name : 'Doorway', x : 28, y : 3};
mappages["Onyx"].features[1] = {name : 'Door', x : 28, y : 3};
mappages["Onyx"].features[2] = {name : 'Doorway', x : 25, y : 13};
mappages["Onyx"].features[3] = {name : 'DoorWindow', x : 25, y : 13};
mappages["Onyx"].features[4] = {name : 'DoorWindow', x : 9, y : 10};
mappages["Onyx"].features[5] = {name : 'Door', x : 14, y : 5, desc : "locked door", locked : 1};
mappages["Onyx"].features[6] = {name : 'Door', x : 14, y : 7, desc : "locked door", locked : 1};
mappages["Onyx"].features[7] = {name : 'Well', x : 27, y : 28};
mappages["Onyx"].features[8] = {name : 'Doorway', x : 14, y : 26};
mappages["Onyx"].features[9] = {name : 'DoorWindow', x : 9, y : 20};


mappages["Onyx"].npcs = [];

mappages["Onyx"].desc = 'the Towne of Onyx';
mappages["Onyx"].music = 'Dark Towne';
mappages["Onyx"].exitmap = 'darkunknown';
mappages["Onyx"].exitx = '64';
mappages["Onyx"].exity = '119';
mappages["Onyx"].wraps = 'None';
mappages["Onyx"].enterx = '1';
mappages["Onyx"].entery = '15';
mappages["Onyx"].seeBelow = '';
mappages["Onyx"].lightLevel = 'bright';
mappages["Onyx"].alwaysRemember = '0';
mappages["Onyx"].scale = '1';
mappages["Onyx"].enterscript = '';
mappages["Onyx"].entertestscript = '';
mappages["Onyx"].exitscript = '';
mappages["Onyx"].exittestscript = '';
mappages["Onyx"].linkedMaps = [""];
