mappages["pitdespair1"] = {};
mappages["pitdespair1"].terrain = [];
 mappages["pitdespair1"].terrain[0] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["pitdespair1"].terrain[1] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["pitdespair1"].terrain[2] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["pitdespair1"].terrain[3] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["pitdespair1"].terrain[4] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["pitdespair1"].terrain[5] = 'BK BK BK BK BK BK BK ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## BK BK BK BK BK BK BK BK';
 mappages["pitdespair1"].terrain[6] = 'BK BK BK BK BK BK BK ## BK BK BK ## !! !! !! -= -= -= -= -= -= -= -= -= -= -= -= -= -= ## BK BK BK ## BK BK BK BK BK BK BK BK';
 mappages["pitdespair1"].terrain[7] = 'BK BK BK BK BK BK BK ## BK BK BK ## !! !! !! -= -= -= -= -= -= -= -= -= -= -= -= -= -= ## BK BK BK ## BK BK BK BK BK BK BK BK';
 mappages["pitdespair1"].terrain[8] = 'BK BK BK BK BK BK BK ## BK BK BK ## !! !! !! -= -= -= -= -= -= -= -= -= -= -= -= -= -= ## BK BK BK ## BK BK BK BK BK BK BK BK';
 mappages["pitdespair1"].terrain[9] = 'BK BK BK BK BK BK BK ## BK BK BK ## !! !! !! ## ## ## ## ## -= ## ## ## ## ## !! !! !! ## BK BK BK ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[10] = 'BK BK BK BK BK BK BK ## BK BK BK ## !! !! !! ## -= -= -= -= -= -= -= -= -= ## !! !! !! ## BK BK BK ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[11] = 'BK BK BK BK BK BK BK ## BK BK BK ## !! !! !! ## -= -= -= -= -= -= -= -= -= ## !! !! !! ## BK BK BK ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[12] = 'BK BK BK BK BK BK BK ## BK BK BK ## !! !! !! ## -= -= -= -= -= -= -= -= -= ## !! !! !! ## BK BK BK ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[13] = 'BK BK BK BK BK BK BK ## BK BK BK ## !! !! !! ## -= -= -= -= -= -= -= -= -= ## !! !! !! ## BK BK BK ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[14] = 'BK BK BK BK BK BK BK ## BK BK BK ## !! !! !! ## -= -= -= -= -= -= -= -= -= ## !! !! !! ## BK BK BK ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[15] = 'BK BK BK BK BK BK BK ## BK BK BK ## !! !! !! ## -= -= -= -= -= -= -= -= -= ## !! !! !! ## BK BK BK ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[16] = 'BK BK BK BK BK BK BK ## BK BK BK ## !! !! !! ## -= -= -= -= -= -= -= -= -= ## !! !! !! ## BK BK BK ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[17] = 'BK BK BK BK BK BK BK ## BK BK BK ## !! !! !! ## -= -= -= -= -= -= -= -= -= ## !! !! !! ## BK BK BK ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[18] = 'BK BK BK BK BK BK BK ## ## ## ## ## !! !! !! ## ## ## ## ## ## ## ## ## ## ## !! !! !! ## BK BK BK ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[19] = 'BK BK BK BK BK BK BK ## -= -= -= ## !! !! !! ## -= -= -= ## -= -= -= -= -= ## !! !! !! ## BK BK BK ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[20] = 'BK BK BK BK BK BK BK ## -= -= -= -= !! !! !! -= -= -= -= ## -= -= -= -= -= -= !! !! !! ## BK BK BK ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[21] = 'BK BK BK BK BK BK BK ## -= -= -= ## !! !! !! ## -= -= -= ## -= -= -= -= -= ## !! !! !! ## BK BK BK ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[22] = 'BK BK BK BK BK BK BK ## ## ## ## ## !! !! !! ## ## ## ## ## ## ## ## ## ## ## !! !! !! ## BK BK BK ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[23] = 'BK BK BK BK BK BK BK ## -= -= -= ## !! !! !! ## -= -= -= ## -= -= -= -= -= ## !! !! !! ## BK BK BK ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[24] = 'BK BK BK BK BK BK BK ## -= -= -= -= !! !! !! -= -= -= -= ## -= -= -= -= -= -= !! !! !! ## BK BK BK ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[25] = 'BK BK BK BK BK BK BK ## -= -= -= ## !! !! !! ## -= -= -= ## -= -= -= -= -= ## !! !! !! ## BK BK BK ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[26] = 'BK BK BK BK BK BK BK ## -= -= -= ## !! !! !! ## ## ## ## ## ## ## ## ## ## ## !! !! !! ## BK BK BK ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[27] = 'BK BK BK BK BK BK BK ## ## ## ## ## !! !! !! ## -= -= -= ## -= -= -= -= -= ## !! !! !! ## BK BK BK ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[28] = 'BK BK BK BK BK BK BK ## -= -= -= ## !! !! !! -= -= -= -= ## -= -= -= -= -= ## !! !! !! ## BK BK BK ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[29] = 'BK BK BK BK BK BK BK ## -= -= -= ## !! !! !! ## -= -= -= ## -= -= -= -= -= -= !! !! !! ## BK BK BK ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[30] = 'BK BK BK BK BK BK BK ## -= -= -= ## !! !! !! ## -= -= -= ## -= -= -= -= -= ## !! !! !! ## BK BK BK ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[31] = 'BK BK BK BK BK BK BK ## -= -= -= -= !! !! !! ## ## ## ## ## ## ## ## ## ## ## !! !! !! ## BK BK BK ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[32] = 'BK BK BK BK BK BK BK ## -= -= -= ## -= -= -= -= -= -= -= -= -= -= -= -= -= -= !! !! !! ## BK BK BK ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[33] = 'BK BK BK BK BK BK BK ## -= -= -= ## -= -= -= -= -= -= -= -= -= -= -= -= -= -= !! !! !! ## BK BK BK ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[34] = 'BK BK BK BK BK BK BK ## -= -= -= ## -= -= -= -= -= -= -= -= -= -= -= -= -= -= !! !! !! ## BK BK BK ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[35] = 'BK BK BK BK BK BK BK ## ## ## ## ## -= -= -= -= -= -= -= -= -= -= -= -= -= -= !! !! !! ## BK BK BK ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[36] = 'BK BK BK BK BK BK BK ## -= -= -= ## ## ## -= ## ## ## ## ## ## -= ## ## ## ## ## -= ## ## ## ## ## ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[37] = 'BK BK BK BK BK BK BK ## -= -= -= ## -= -= -= -= -= ## -= -= -= -= -= -= -= ## -= -= -= -= -= -= -= ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[38] = 'BK BK BK BK BK BK BK ## -= -= -= ## -= -= -= -= -= ## -= -= -= -= -= -= -= ## -= -= -= -= -= -= -= ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[39] = 'BK BK BK BK BK BK BK ## -= -= -= -= -= -= -= -= -= ## -= -= -= -= -= -= -= ## -= -= -= -= -= -= -= ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[40] = 'BK BK BK BK BK BK BK ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[41] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[42] = '## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[43] = '## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[44] = '## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[45] = '## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["pitdespair1"].terrain[46] = '## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';

mappages["pitdespair1"].features = [];
mappages["pitdespair1"].features[0] = {name : 'LadderUp', x : 8, y : 19, entermap : 'null', enterx : 0, entery : 0};
mappages["pitdespair1"].features[1] = {name : 'Door', x : 11, y : 20, desc : "locked door", locked : 1};
mappages["pitdespair1"].features[2] = {name : 'LadderDown', x : 16, y : 21, entermap : 'null', enterx : 0, entery : 0};
mappages["pitdespair1"].features[3] = {name : 'Door', x : 15, y : 20, desc : "locked door", locked : 1};
mappages["pitdespair1"].features[4] = {name : 'Door', x : 20, y : 9};


mappages["pitdespair1"].npcs = [];

mappages["pitdespair1"].desc = "Pit of Despair 1";
mappages["pitdespair1"].music = 'Dungeon';
mappages["pitdespair1"].exitmap = 'darkunknown';
mappages["pitdespair1"].exitx = '65';
mappages["pitdespair1"].exity = '70';
mappages["pitdespair1"].wraps = 'None';
mappages["pitdespair1"].enterx = '65';
mappages["pitdespair1"].entery = '70';
mappages["pitdespair1"].seeBelow = '';
mappages["pitdespair1"].lightLevel = 'dark';
mappages["pitdespair1"].alwaysRemember = '0';
mappages["pitdespair1"].scale = '0';
mappages["pitdespair1"].enterscript = '';
mappages["pitdespair1"].entertestscript = '';
mappages["pitdespair1"].exitscript = '';
mappages["pitdespair1"].exittestscript = '';
mappages["pitdespair1"].linkedMaps = [""];
