"use strict";

mappages["shadow1"] = {};
mappages["shadow1"].terrain = [];
 mappages["shadow1"].terrain[0] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["shadow1"].terrain[1] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["shadow1"].terrain[2] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["shadow1"].terrain[3] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["shadow1"].terrain[4] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["shadow1"].terrain[5] = 'BK BK BK BK BK cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["shadow1"].terrain[6] = 'BK BK BK BK BK cw cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw BK BK BK BK BK BK BK BK BK';
 mappages["shadow1"].terrain[7] = 'BK BK BK BK BK cw cf cf cw cw BK BK BK BK BK BK BK BK BK cw cw cw cw cf cf cf cw cw cw BK BK BK BK BK BK BK';
 mappages["shadow1"].terrain[8] = 'BK BK BK BK cw cw cf cf cf cw BK BK BK BK BK BK BK cw cw cw cf cf cf cf cf cf cf cf cw BK BK BK BK BK BK BK';
 mappages["shadow1"].terrain[9] = 'BK BK BK BK cw cf cf cf cf cw BK BK BK BK BK cw cw cw cf cf cf cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK';
mappages["shadow1"].terrain[10] = 'BK BK BK BK cw cf cf cf cf cw BK BK BK BK BK cw cf cf cf cf cf cf cf cf cf cw cf cf cf cw BK BK BK BK BK BK';
mappages["shadow1"].terrain[11] = 'BK BK BK BK cw cw cf cf cf cw BK BK BK BK BK cw cf cf cf cf cf cf cf cf cf cf cf cf cf cw BK BK BK BK BK BK';
mappages["shadow1"].terrain[12] = 'BK BK BK BK cw cw cf cf cf cw BK BK BK BK cw cw cf cf cf cf cf cf cf cf cf cf cf cf cf cw BK BK BK BK BK BK';
mappages["shadow1"].terrain[13] = 'BK BK BK BK cw cf cf cf cf cw BK BK cw cw cw cf cf cf cw cf cf cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK';
mappages["shadow1"].terrain[14] = 'BK BK BK BK cw cf cf cf cw cw BK cw cw cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cw BK BK BK BK BK BK BK';
mappages["shadow1"].terrain[15] = 'BK BK BK BK cw cf cf cf cf cw cw cw cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cw BK BK BK BK BK BK BK';
mappages["shadow1"].terrain[16] = 'BK BK BK BK cw cw cf cf cf cf cf cf cf cf cw cw cw cf cf cf cf cf cf cf cw cf cf cf cw BK BK BK BK BK BK BK';
mappages["shadow1"].terrain[17] = 'BK BK BK BK BK cw cw cf cf cf cf cf cf cw cw BK cw cw cw cf cf cf cf cw cw cw cf cf cw BK BK BK BK BK BK BK';
mappages["shadow1"].terrain[18] = 'BK BK BK BK BK BK cw cw cf cf cf cf cw cw BK BK BK BK cw cw cw cw cw cw BK cw cf cf cw cw BK BK BK BK BK BK';
mappages["shadow1"].terrain[19] = 'BK BK BK BK BK BK BK cw cw cw cw cw cw BK BK cw cw cw cw BK BK BK BK BK BK cw cf cf cf cw BK BK BK BK BK BK';
mappages["shadow1"].terrain[20] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cw cw BK BK BK BK BK cw cf cf cf cw BK BK BK BK BK BK';
mappages["shadow1"].terrain[21] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw BK BK BK BK cw cw cf cf cf cw BK BK BK BK BK BK';
mappages["shadow1"].terrain[22] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cw cw cw BK cw cw cw cf cf cf cw cw BK BK BK BK BK BK';
mappages["shadow1"].terrain[23] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cw cw cw cf cf cf cf cf cw BK BK BK BK BK BK BK';
mappages["shadow1"].terrain[24] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK';
mappages["shadow1"].terrain[25] = 'BK BK BK BK BK BK BK BK cw cw cw cw BK BK BK cw cw cf cf cf cf cf cf cf cf cf cf cf cf cw BK BK BK BK BK BK';
mappages["shadow1"].terrain[26] = 'BK BK BK BK BK BK cw cw cw cf cf cw cw cw cw cw cw cw cf cf cf cf cf cf cw cw cf cf cf cw BK BK BK BK BK BK';
mappages["shadow1"].terrain[27] = 'BK BK BK BK BK BK cw cf cf cf cf cf cw cw cf cf cf cf cf cf cf cf cf cw cw cw cf cf cf cw BK BK BK BK BK BK';
mappages["shadow1"].terrain[28] = 'BK BK BK BK BK cw cw cf cf cf cf cf cf cf cf cf cf cf cf cf cf cw cw cw cw cw cf cf cf cw BK BK BK BK BK BK';
mappages["shadow1"].terrain[29] = 'BK BK BK BK BK cw cf cf cf cf cf cf cf cf cf cf cf cw cw cw cw cw BK BK cw cf cf cf cf cw cw BK BK BK BK BK';
mappages["shadow1"].terrain[30] = 'BK BK BK BK BK cw cf cf cf cf cf cf cf cf cw cw cw cw BK BK BK BK BK BK cw cf cf cf cf cf cw BK BK BK BK BK';
mappages["shadow1"].terrain[31] = 'BK BK BK BK BK cw cw cf cf cf cf cw cw cw cw BK BK BK BK BK BK BK BK BK cw cw cf cf cf cw cw BK BK BK BK BK';
mappages["shadow1"].terrain[32] = 'BK BK BK BK BK BK cw cw cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw BK BK BK BK BK BK';
mappages["shadow1"].terrain[33] = 'BK BK BK BK BK BK BK cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow1"].terrain[34] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow1"].terrain[35] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';

mappages["shadow1"].features = [];
mappages["shadow1"].features[0] = {name : 'LadderUp', x : 7, y : 9, entermap : 'darkunknown', enterx : 96, entery : 31};
mappages["shadow1"].features[1] = {name : 'LadderDown', x : 7, y : 30, entermap : 'shadow2', enterx : 7, entery : 30};
mappages["shadow1"].features[2] = {name : 'OrbStrength', x : 29, y : 30};


mappages["shadow1"].npcs = [];
mappages["shadow1"].npcs[0] = {name : 'GiantRatNPC', x : 20, y : 10, Gender: 'monster', Bark: '0', NPCBand: '1'};
mappages["shadow1"].npcs[1] = {name : 'GiantRatNPC', x : 23, y : 14, Gender: 'monster', Bark: '0', NPCBand: '1'};
mappages["shadow1"].npcs[2] = {name : 'PythonNPC', x : 26, y : 9, NPCBand: '1'};
mappages["shadow1"].npcs[3] = {name : 'GiantRatNPC', x : 18, y : 15, NPCBand: '1'};
mappages["shadow1"].npcs[4] = {name : 'GiantRatNPC', x : 26, y : 13, NPCBand: '1'};
mappages["shadow1"].npcs[5] = {name : 'SlimeNPC', x : 27, y : 26, NPCBand: '3'};
mappages["shadow1"].npcs[6] = {name : 'SlimeNPC', x : 28, y : 27, NPCBand: '3'};
mappages["shadow1"].npcs[7] = {name : 'SlimeNPC', x : 26, y : 29, NPCBand: '3'};
mappages["shadow1"].npcs[8] = {name : 'ChildVillagerNPC', x : 18, y : 21, NPCName: 'Samantha', Attitude: 'neutral', Conversation: 'samantha', ConversationFlag: 'samantha', Gender: 'female', NPCBand: '0', skintone: '1'};
mappages["shadow1"].npcs[9] = {name : 'HeadlessNPC', x : 9, y : 26};

mappages["shadow1"].desc = "Dungeon Shadow (L1)";
mappages["shadow1"].music = 'Dungeon';
mappages["shadow1"].savename = 'Shadow';
mappages["shadow1"].exitmap = 'darkunknown';
mappages["shadow1"].exitx = '96';
mappages["shadow1"].exity = '31';
mappages["shadow1"].wraps = 'None';
mappages["shadow1"].enterx = '7';
mappages["shadow1"].entery = '9';
mappages["shadow1"].seeBelow = '';
mappages["shadow1"].lightLevel = 'dark';
mappages["shadow1"].alwaysRemember = '0';
mappages["shadow1"].scale = '1';
mappages["shadow1"].underground = '1';
mappages["shadow1"].undergroundDesc = 'Level 1';
mappages["shadow1"].enterscript = '';
mappages["shadow1"].entertestscript = '';
mappages["shadow1"].exitscript = '';
mappages["shadow1"].exittestscript = '';
mappages["shadow1"].returnmap = 'darkunknown';
mappages["shadow1"].returnx = '96';
mappages["shadow1"].returny = '31';
mappages["shadow1"].returninfused = '0';
mappages["shadow1"].linkedMaps = ["shadow2","shadow3"];

mappages["shadow1"].onload = function(mapref) {
  if (gamestate.getMode() !== "loadgame") {
    if (DU.gameflags["rescued_sam"]) {
      let sam = mapref.getTile(18,21).getTopNPC();
      mapref.deleteThing(sam);
      DUTime.removeEntityFrom(sam);
    }
    delete DU.gameflags["shadow_safe"];
  }
}

mappages["shadow2"] = {};
mappages["shadow2"].terrain = [];
 mappages["shadow2"].terrain[0] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["shadow2"].terrain[1] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["shadow2"].terrain[2] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw BK BK BK BK BK BK BK BK';
 mappages["shadow2"].terrain[3] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cw cw BK BK BK BK BK BK BK';
 mappages["shadow2"].terrain[4] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cw BK BK BK BK BK BK BK';
 mappages["shadow2"].terrain[5] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cw cw BK BK BK BK BK BK';
 mappages["shadow2"].terrain[6] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw cw cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw BK BK BK BK BK BK cw cw cw cf cf cf cf cf cf cw BK BK BK BK BK BK';
 mappages["shadow2"].terrain[7] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cf cf cf cf cf cf cf cf cw cw cw cw cw cw cw cw BK BK cw cw cw cw cw cf cf cw cw BK BK BK BK BK cw cf cf cf cf cf cf cf cf cw BK BK BK BK BK BK';
 mappages["shadow2"].terrain[8] = 'BK BK BK BK BK BK BK BK BK BK BK cw cw cw cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cw cw cw cw cf cf cf cf cf cf cf cw cw BK BK BK BK cw cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK';
 mappages["shadow2"].terrain[9] = 'BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cw cw cw cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cw cw cw cw cw cf cf cf cf cf cf cf cf cw BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[10] = 'BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cf cw cw cw cw cw cw cw cw cw cw cf cf cf cf cf cf cf cf cf cw cw cf cf cf cf cf cw cf cf cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[11] = 'BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK cw cw cf cf cf cw cw cw cw cw cw cw cw cf cf cf cf cf cf cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[12] = 'BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cf cf cf cf cf cf cw BK BK BK BK BK BK BK cw cw cw cw cw BK BK BK BK BK BK cw cw cw cf cf cf cf cf cw cf cw cf cw cw cw BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[13] = 'BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cw cw cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[14] = 'BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[15] = 'BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cf cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[16] = 'BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cf cf cf cw cw cw cw cw cw cw cw cw cw cw cw BK BK BK BK BK BK BK BK cw cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[17] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cw cw cw BK BK BK BK BK BK cw cw cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[18] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cw BK BK BK BK BK BK BK cw cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[19] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cf cf cw cw cf cf cf cw cf cf cf cf cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK cw cw cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[20] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw cw cw cw cw cw cw cw cw cw cw cw cw cw cf cf cf cw BK BK BK BK BK BK BK cw cw cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[21] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cw BK BK BK BK BK BK BK cw cw cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[22] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cw BK BK BK BK BK BK cw cw cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[23] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cw cw BK BK BK BK BK BK cw cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[24] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cw BK BK BK BK BK cw cw cw cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[25] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cw cw BK BK BK cw cw cw cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[26] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cw BK BK BK BK cw cf cf cf cf cf cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[27] = 'BK BK BK BK BK BK cw cw cw cw cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cw cw BK BK BK cw cw cf cf cf cf cf cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[28] = 'BK BK BK BK BK cw cw cf cf cw cw cf cf cw cw cw BK BK BK BK cw cw cw cw cw cw cw cw cw BK cw cf cf cf cw cw BK BK BK BK cw cf cf cf cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[29] = 'BK BK BK BK BK cw cf cf cf cf cf cf cf cf cf cw cw cw cw cw cw cf cf cf cw cw cf cf cw cw cw cf cf cf cw BK BK BK BK BK cw cf cf cf cf cf cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[30] = 'BK BK BK BK BK cw cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cw cw BK BK BK BK BK cw cf cf cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[31] = 'BK BK BK BK BK cw cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK cw cw cf cf cf cf cf cf cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[32] = 'BK BK BK BK BK cw cw cf cf cf cf cf cf cf cf cw cw cf cf cw cw cw cf cf cf cf cw cf cf cf cf cf cw BK BK BK BK BK BK BK BK cw cw cw cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[33] = 'BK BK BK BK BK BK cw cw cf cf cf cf cf cf cw cw cw cw cw cw BK cw cw cw cw cw cw cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[34] = 'BK BK BK BK BK BK BK cw cw cw cw cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[35] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cw cw BK BK BK BK BK BK BK cw cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[36] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cw BK BK BK BK BK BK BK cw cw cf cf cf cw BK BK BK cw cw cw cw cw cw cw BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[37] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cw cw BK BK BK BK BK BK cw cw cf cf cf cf cw cw BK cw cw cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[38] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cw cw BK BK BK BK BK cw cw cf cf cf cf cf cf cw cw cw cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[39] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw BK BK BK BK BK cw cf cf cf cf cf cf cf cf cf cf cf cf cw cw cf cf cf cf cw BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[40] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cw cw BK BK BK BK cw cw cf cf cf cf cf cf cf cf cf cf cf cw cw cf cf cf cf cf cw BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[41] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cw BK BK BK BK BK cw cf cf cf cf cf cf cf cf cf cf cw cw cw cw cf cf cf cf cf cw BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[42] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cw BK BK BK BK BK cw cf cf cf cf cf cf cf cf cf cw cw BK cw cf cf cf cf cf cf cw BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[43] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cw cw cw BK BK BK BK BK cw cf cf cf cf cf cf cf cf cf cw BK BK cw cf cf cf cf cf cf cw BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[44] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw cf cf cf cw cw cw BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cw cw BK BK cw cf cf cf cf cf cw cw BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[45] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cf cw cw BK BK BK cw cw cf cf cf cw cw BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[46] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cw cw cw BK BK BK BK BK BK BK BK BK BK BK cw cw cw cf cf cf cw cw BK BK BK BK BK cw cf cf cw cw BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[47] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cw cw BK BK BK BK BK BK cw cw cw cw BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[48] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw cw cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[49] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cf cf cw cw cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[50] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cw cw BK BK BK BK BK BK BK BK BK cw cw cw cf cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[51] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cw cw cw cw cw cw cw cw cw cw cw cf cf cf cf cf cf cf cf cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[52] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[53] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cf cf cf cf cf cf cf cw cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[54] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cw cw cf cf cf cf cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[55] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw cw cw cw cw cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[56] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[57] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[58] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["shadow2"].terrain[59] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';

mappages["shadow2"].features = [];
mappages["shadow2"].features[0] = {name : 'LadderUp', x : 7, y : 30, entermap : 'shadow1', enterx : 7, entery : 30};
mappages["shadow2"].features[1] = {name : 'LadderDown', x : 43, y : 30, entermap : 'shadow3', enterx : 43, entery : 30};
mappages["shadow2"].features[2] = {name : 'SiriCloak', x : 40, y : 49};
mappages["shadow2"].features[3] = {name : 'SkeletonDecoration', x : 39, y : 49};
mappages["shadow2"].features[4] = {name : 'Chest', x : 11, y : 11, locked : 0, lootgroup : 'headlesscave', lootedid : 'shadow2_1'};
mappages["shadow2"].features[5] = {name : 'Chest', x : 11, y : 12, locked : 0, lootgroup : 'headlesscave', lootedid : 'shadow2_2'};
mappages["shadow2"].features[6] = {name : 'Campfire', x : 15, y : 12};
mappages["shadow2"].features[7] = {name : 'Chest', x : 53, y : 4, locked : 0, lootgroup : 'Shadow2', lootedid : 'Shadow2_3'};
mappages["shadow2"].features[8] = {name : 'Chest', x : 55, y : 4, locked : 0, lootgroup : 'Shadow2', lootedid : 'Shadow2_4'};
mappages["shadow2"].features[9] = {name : 'Chest', x : 51, y : 26, locked : 0, lootgroup : 'Shadow2', lootedid : 'Shadow2_5'};
mappages["shadow2"].features[10] = {name : 'Chest', x : 51, y : 27, locked : 0, lootgroup : 'Shadow2', lootedid : 'Shadow2_6'};


mappages["shadow2"].npcs = [];
mappages["shadow2"].npcs[0] = {name : 'HeadlessNPC', x : 51, y : 43, skintone: '1'};
mappages["shadow2"].npcs[1] = {name : 'HeadlessNPC', x : 54, y : 41, skintone: '1'};
mappages["shadow2"].npcs[2] = {name : 'HeadlessNPC', x : 53, y : 38, skintone: '1'};
mappages["shadow2"].npcs[3] = {name : 'HeadlessNPC', x : 41, y : 39, skintone: '1'};
mappages["shadow2"].npcs[4] = {name : 'HeadlessNPC', x : 40, y : 41, skintone: '1'};
mappages["shadow2"].npcs[5] = {name : 'HeadlessNPC', x : 43, y : 41, skintone: '1'};
mappages["shadow2"].npcs[6] = {name : 'HeadlessNPC', x : 41, y : 45, skintone: '1'};
mappages["shadow2"].npcs[7] = {name : 'HeadlessNPC', x : 33, y : 51, skintone: '1'};
mappages["shadow2"].npcs[8] = {name : 'HeadlessNPC', x : 26, y : 53, skintone: '1'};
mappages["shadow2"].npcs[9] = {name : 'GiantBatNPC', x : 29, y : 33, skintone: '1'};
mappages["shadow2"].npcs[10] = {name : 'GiantBatNPC', x : 28, y : 40, skintone: '1'};
mappages["shadow2"].npcs[11] = {name : 'GiantBatNPC', x : 22, y : 45, skintone: '1'};
mappages["shadow2"].npcs[12] = {name : 'GiantBatNPC', x : 16, y : 50, skintone: '1'};
mappages["shadow2"].npcs[13] = {name : 'GiantBatNPC', x : 17, y : 50, skintone: '1'};
mappages["shadow2"].npcs[14] = {name : 'SlimeNPC', x : 11, y : 29, skintone: '1'};
mappages["shadow2"].npcs[15] = {name : 'SlimeNPC', x : 13, y : 31, skintone: '1'};
mappages["shadow2"].npcs[16] = {name : 'SlimeNPC', x : 10, y : 33, skintone: '1'};
mappages["shadow2"].npcs[17] = {name : 'OrcNPC', x : 13, y : 10, skintone: '1'};
mappages["shadow2"].npcs[18] = {name : 'OrcNPC', x : 16, y : 9, skintone: '1'};
mappages["shadow2"].npcs[19] = {name : 'OrcNPC', x : 18, y : 12, skintone: '1'};
mappages["shadow2"].npcs[20] = {name : 'OrcNPC', x : 15, y : 14, skintone: '1'};
mappages["shadow2"].npcs[21] = {name : 'OrcNPC', x : 18, y : 16, skintone: '1'};
mappages["shadow2"].npcs[22] = {name : 'TrollNPC', x : 53, y : 5, skintone: '1'};
mappages["shadow2"].npcs[23] = {name : 'TrollNPC', x : 55, y : 8, skintone: '1'};
mappages["shadow2"].npcs[24] = {name : 'TremendousSpiderNPC', x : 39, y : 7, skintone: '1'};
mappages["shadow2"].npcs[25] = {name : 'OrcNPC', x : 51, y : 8, skintone: '1'};
mappages["shadow2"].npcs[26] = {name : 'OrcNPC', x : 49, y : 9, skintone: '1'};
mappages["shadow2"].npcs[27] = {name : 'OrcNPC', x : 52, y : 10, skintone: '1'};
mappages["shadow2"].npcs[28] = {name : 'MimicNPC', x : 54, y : 3, skintone: '1'};
mappages["shadow2"].npcs[29] = {name : 'TrollNPC', x : 49, y : 26, skintone: '1'};
mappages["shadow2"].npcs[30] = {name : 'TrollNPC', x : 46, y : 26, skintone: '1'};

mappages["shadow2"].desc = "Dungeon Shadow (L2)";
mappages["shadow2"].longdesc = '';
mappages["shadow2"].music = 'Dungeon';
mappages["shadow2"].savename = 'Shadow';
mappages["shadow2"].exitmap = '';
mappages["shadow2"].exitx = '65';
mappages["shadow2"].exity = '70';
mappages["shadow2"].wraps = '';
mappages["shadow2"].enterx = '7';
mappages["shadow2"].entery = '30';
mappages["shadow2"].seeBelow = '';
mappages["shadow2"].lightLevel = 'dark';
mappages["shadow2"].alwaysRemember = '0';
mappages["shadow2"].scale = '1';
mappages["shadow2"].underground = '1';
mappages["shadow2"].undergroundDesc = 'Level 2';
mappages["shadow2"].enterscript = '';
mappages["shadow2"].entertestscript = '';
mappages["shadow2"].exitscript = '';
mappages["shadow2"].exittestscript = '';
mappages["shadow2"].returnmap = 'darkunknown';
mappages["shadow2"].returnx = '96';
mappages["shadow2"].returny = '31';
mappages["shadow2"].returninfused = '0';
mappages["shadow2"].linkedMaps = ["shadow1","shadow3"];
mappages["shadow2"].editorLabels = '{}';

mappages["shadow2"].onload = function(mapref) {
  if (gamestate.getMode() !== "loadgame") {
    if ((DU.gameflags.getFlag("returned_cloak")) || (PC.checkInventory("SiriCloak"))) {
      let cloak = mapref.getTile(40,49).getTopFeature();
      if (cloak) {
        mapref.deleteThing(cloak);
      }
    }
  }
}

mappages["shadow3"] = {};
mappages["shadow3"].terrain = [];
 mappages["shadow3"].terrain[0] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["shadow3"].terrain[1] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["shadow3"].terrain[2] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["shadow3"].terrain[3] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["shadow3"].terrain[4] = 'BK BK BK BK BK %% %% %% %% BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["shadow3"].terrain[5] = 'BK BK BK BK BK %% df df %% BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw BK BK BK BK BK BK BK cw cw cw cw BK BK BK BK';
 mappages["shadow3"].terrain[6] = 'BK BK BK BK BK %% df df %% BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cw cw BK BK BK BK BK cw cw cw cf cf cw BK BK BK BK';
 mappages["shadow3"].terrain[7] = 'BK BK BK BK BK %% df %% %% BK BK BK BK BK BK BK BK BK BK BK cw cw cw cf cf cf cf cw BK BK BK BK BK BK cw cf cf cf cf cw BK BK BK BK';
 mappages["shadow3"].terrain[8] = 'BK BK BK BK BK %% df df %% BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cw cw BK BK BK BK BK BK cw cf cf cf cf cw BK BK BK BK';
 mappages["shadow3"].terrain[9] = 'BK BK BK BK BK %% %% df %% BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw cw BK BK BK BK BK BK BK cw cf cf cf cf cw BK BK BK BK';
mappages["shadow3"].terrain[10] = 'BK BK BK BK BK BK %% df %% BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw BK BK BK BK BK BK BK BK cw cw cf cf cw cw BK BK BK BK';
mappages["shadow3"].terrain[11] = 'BK BK BK BK BK BK %% df %% %% BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cw BK BK BK BK BK BK BK BK BK cw cf cf cw cw BK BK BK BK';
mappages["shadow3"].terrain[12] = 'BK BK BK BK %% %% %% df df %% %% %% %% %% BK BK BK BK BK BK BK cw cw cf cf cw cw BK BK BK BK BK BK BK BK cw cf cf cf cw BK BK BK BK';
mappages["shadow3"].terrain[13] = 'BK BK BK %% %% df df df df %% df df df %% %% BK BK BK BK BK BK BK cw cf cf cf cw cw BK BK BK BK BK BK cw cw cf cf cf cw BK BK BK BK';
mappages["shadow3"].terrain[14] = 'BK BK BK %% df df df df df %% df df df df %% cw cw cw cw cw cw cw cw cf cf cf cf cw cw BK BK BK BK BK cw cf cf cf cw cw BK BK BK BK';
mappages["shadow3"].terrain[15] = 'BK BK BK %% %% %% df %% %% %% df df df df %% cf cf cw cw cf cf cf cf cf cf cf cf cf cw BK BK BK BK BK cw cf cf cf cw BK BK BK BK BK';
mappages["shadow3"].terrain[16] = 'BK BK %% %% df df df df df %% df df df df %% cf cf cf cf cf cf cf cf cf cf cf cf cf cw BK BK BK BK BK cw cw cf cf cw BK BK BK BK BK';
mappages["shadow3"].terrain[17] = 'BK BK %% df df df df df df df df df df df %% cf cf cf cf cf cf cf cw cw cw cf cf cf cw BK BK BK BK BK cw cw cf cf cw BK BK BK BK BK';
mappages["shadow3"].terrain[18] = 'BK BK %% %% df df df df df %% df df df %% %% cw cf cf cw cw cw cw cw BK cw cw cf cf cw BK BK BK BK BK cw cf cf cf cw cw BK BK BK BK';
mappages["shadow3"].terrain[19] = 'BK BK BK %% %% df df df df %% df df %% %% BK cw cw cw cw BK BK BK BK BK BK cw cf cf cw cw BK BK BK BK cw cf cf cf cf cw BK BK BK BK';
mappages["shadow3"].terrain[20] = 'BK BK BK BK %% %% %% df df %% %% %% %% BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cw BK BK BK BK cw cw cf cf cf cw cw BK BK BK';
mappages["shadow3"].terrain[21] = 'BK BK BK BK BK BK %% %% %% %% %% BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cw BK BK BK BK cw cw cf cf cf cf cw BK BK BK';
mappages["shadow3"].terrain[22] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cw BK BK BK BK cw cf cf cf cf cf cw BK BK BK';
mappages["shadow3"].terrain[23] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw BK BK BK BK cw cf cf cf cf cw cw BK BK BK';
mappages["shadow3"].terrain[24] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw cw cw cw cw cw cf cf cf cf cw BK BK BK BK';
mappages["shadow3"].terrain[25] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw cw cf cf cw cw cf cf cf cw cw BK BK BK BK';
mappages["shadow3"].terrain[26] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cf cf cf cf cf cf cf cw cw BK BK BK BK BK';
mappages["shadow3"].terrain[27] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cf cf cf cf cw BK BK BK BK BK BK';
mappages["shadow3"].terrain[28] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK';
mappages["shadow3"].terrain[29] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw cf cf cw cw cw cw BK BK BK BK BK BK BK';
mappages["shadow3"].terrain[30] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw BK BK BK BK BK BK BK BK BK BK';
mappages["shadow3"].terrain[31] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';

mappages["shadow3"].features = [];
mappages["shadow3"].features[0] = {name : 'LadderUp', x : 7, y : 5, entermap : 'null', enterx : 0, entery : 0};
mappages["shadow3"].features[1] = {name : 'Altar', x : 6, y : 13};
mappages["shadow3"].features[2] = {name : 'UnlitBrazier', x : 8, y : 12};
mappages["shadow3"].features[3] = {name : 'BookshelfLeft', x : 4, y : 16};
mappages["shadow3"].features[4] = {name : 'BookshelfLeft', x : 7, y : 16};
mappages["shadow3"].features[5] = {name : 'BookshelfRight', x : 8, y : 16};
mappages["shadow3"].features[6] = {name : 'BookshelfRight', x : 5, y : 16};
mappages["shadow3"].features[7] = {name : 'SmallBox', x : 3, y : 17};
mappages["shadow3"].features[8] = {name : 'LeftTable', x : 7, y : 20};
mappages["shadow3"].features[9] = {name : 'RightTable', x : 8, y : 20};
mappages["shadow3"].features[10] = {name : 'UnlitBrazier', x : 5, y : 19};
mappages["shadow3"].features[11] = {name : 'UnlitBrazier', x : 13, y : 14};
mappages["shadow3"].features[12] = {name : 'UnlitBrazier', x : 13, y : 17};
mappages["shadow3"].features[13] = {name : 'BookshelfLeft', x : 10, y : 13};
mappages["shadow3"].features[14] = {name : 'BookshelfRight', x : 11, y : 13};
mappages["shadow3"].features[15] = {name : 'SmallBox', x : 12, y : 13};
mappages["shadow3"].features[16] = {name : 'SmallBox', x : 11, y : 19};
mappages["shadow3"].features[17] = {name : 'SmallBox', x : 10, y : 19};
mappages["shadow3"].features[18] = {name : 'LadderUp', x : 37, y : 8, entermap : 'null', enterx : 0, entery : 0};


mappages["shadow3"].npcs = [];

mappages["shadow3"].desc = "Dungeon Shadow";
mappages["shadow3"].longdesc = ``;
mappages["shadow3"].music = 'Dungeon';
mappages["shadow3"].savename = `Shadow`;
mappages["shadow3"].exitmap = '';
mappages["shadow3"].exitx = '65';
mappages["shadow3"].exity = '70';
mappages["shadow3"].wraps = '';
mappages["shadow3"].enterx = '65';
mappages["shadow3"].entery = '70';
mappages["shadow3"].seeBelow = '';
mappages["shadow3"].lightLevel = 'dark';
mappages["shadow3"].alwaysRemember = '0';
mappages["shadow3"].scale = '1';
mappages["shadow3"].underground = '1';
mappages["shadow3"].undergroundDesc = 'Level 3';
mappages["shadow3"].enterscript = '';
mappages["shadow3"].entertestscript = '';
mappages["shadow3"].exitscript = '';
mappages["shadow3"].exittestscript = '';
mappages["shadow3"].returnmap = 'darkunknown';
mappages["shadow3"].returnx = '96';
mappages["shadow3"].returny = '31';
mappages["shadow3"].returninfused = '0';
mappages["shadow3"].linkedMaps = ["shadow1","shadow2"];
mappages["shadow3"].editorLabels = '{}';
