"use strict";

mappages["toshin1"] = {};
mappages["toshin1"].terrain = [];
 mappages["toshin1"].terrain[0] = '^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn ^^ ^^ ^^ ^^';
 mappages["toshin1"].terrain[1] = '^^ ^^ ^^ ^^ nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn ^^ ^^';
 mappages["toshin1"].terrain[2] = '^^ ^^ nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn ^^';
 mappages["toshin1"].terrain[3] = '^^ nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn';
 mappages["toshin1"].terrain[4] = 'nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn';
 mappages["toshin1"].terrain[5] = 'nn nn nn nn nn nn nn ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## nn nn nn nn nn nn';
 mappages["toshin1"].terrain[6] = 'nn nn nn nn nn nn nn ## ++ ++ ++ ++ ++ ++ ++ ++ ## ## ++ ## ## ## ## ## ## ## nn nn nn nn nn nn';
 mappages["toshin1"].terrain[7] = 'nn nn nn nn nn nn nn ## ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ## ++ ++ ++ ++ ++ ## ., nn nn nn nn nn';
 mappages["toshin1"].terrain[8] = 'nn nn nn nn nn nn nn ## ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ## ++ ++ ++ ++ ++ ## ., ., nn nn nn nn';
 mappages["toshin1"].terrain[9] = 'nn nn nn nn nn nn nn ## ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ## ++ ++ ++ ++ ++ ## ., nn nn nn nn nn';
mappages["toshin1"].terrain[10] = 'nn nn nn nn nn nn ., ## ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ## ++ ++ ++ ++ ++ ## nn nn nn nn nn nn';
mappages["toshin1"].terrain[11] = 'nn nn nn nn nn ., ., ## ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ## ## ## ## ++ ## ## nn nn nn nn nn nn';
mappages["toshin1"].terrain[12] = 'nn nn nn nn nn ., ., ## ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ++ ## ., ., ., ., nn .,';
mappages["toshin1"].terrain[13] = 'nn nn nn nn nn ., ., ## ## ## ## ++ ## ## ## ## ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ., nn ., ., ., .,';
mappages["toshin1"].terrain[14] = 'nn nn nn nn nn nn ., ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ., ., ., ., ., .,';
mappages["toshin1"].terrain[15] = 'nn nn nn nn nn nn nn ## ## ## ## ++ ## ## ## ## ## ++ ++ ## ## ## ## ## ## ## nn nn nn nn nn nn';
mappages["toshin1"].terrain[16] = 'nn nn nn nn nn nn nn ## ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ## ++ ++ ++ ++ ++ ## nn nn nn nn nn nn';
mappages["toshin1"].terrain[17] = 'nn nn nn nn nn nn nn ## ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ## ++ ++ ++ ++ ++ ## nn nn nn nn nn nn';
mappages["toshin1"].terrain[18] = 'nn nn nn nn nn nn nn ## ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ## ++ ++ ++ ++ ++ ## nn nn nn nn nn nn';
mappages["toshin1"].terrain[19] = 'nn nn nn nn nn nn nn #+ ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ## ++ ++ ++ ++ ++ #+ nn nn nn nn ., nn';
mappages["toshin1"].terrain[20] = 'nn nn nn nn nn nn nn ## ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ++ ## nn nn nn ., ., nn';
mappages["toshin1"].terrain[21] = 'nn nn nn nn nn nn nn ## ++ ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ## ++ ++ ++ ++ ++ ## nn nn nn nn ., .,';
mappages["toshin1"].terrain[22] = 'nn nn nn nn nn nn nn ## ## ## ## #+ ## ## ## ## ## ## ## ## ## ## #+ ## ## ## nn nn nn nn ., .,';
mappages["toshin1"].terrain[23] = 'nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn';
mappages["toshin1"].terrain[24] = 'nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn';
mappages["toshin1"].terrain[25] = 'nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn';
mappages["toshin1"].terrain[26] = 'nn nn nn nn nn nn nn nn nn nn nn ;; ;; nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn';
mappages["toshin1"].terrain[27] = 'nn nn nn nn nn nn nn nn nn nn ;; ;; ;; nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn';
mappages["toshin1"].terrain[28] = 'nn nn nn nn nn nn nn nn nn ;; ;; ;; ;; ;; nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn ^^';
mappages["toshin1"].terrain[29] = '^^ nn nn nn nn nn nn nn nn nn ;; ;; ;; nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn ^^ ^^';
mappages["toshin1"].terrain[30] = '^^ ^^ nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^';
mappages["toshin1"].terrain[31] = '^^ ^^ ^^ ^^ nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^';

mappages["toshin1"].features = [];
mappages["toshin1"].features[0] = {name : 'DoorWindow', x : 25, y : 13, locked : 0, keyname : "ToshinKey", lootedid : 'toshintree'};
mappages["toshin1"].features[1] = {name : 'Door', x : 23, y : 11};
mappages["toshin1"].features[2] = {name : 'Door', x : 19, y : 20};
mappages["toshin1"].features[3] = {name : 'StairUp', x : 17, y : 7, entermap : 'toshin2', enterx : 17, entery : 7};
mappages["toshin1"].features[4] = {name : 'BookshelfLeft', x : 8, y : 6};
mappages["toshin1"].features[5] = {name : 'BookshelfRight', x : 9, y : 6};
mappages["toshin1"].features[6] = {name : 'BookshelfLeft', x : 10, y : 6};
mappages["toshin1"].features[7] = {name : 'BookshelfRight', x : 11, y : 6};
mappages["toshin1"].features[8] = {name : 'BookshelfLeft', x : 14, y : 6};
mappages["toshin1"].features[9] = {name : 'BookshelfRight', x : 15, y : 6};
mappages["toshin1"].features[10] = {name : 'BookshelfRight', x : 13, y : 6};
mappages["toshin1"].features[11] = {name : 'BookshelfLeft', x : 12, y : 6};
mappages["toshin1"].features[12] = {name : 'RightChair', x : 15, y : 11};
mappages["toshin1"].features[13] = {name : 'BottomChair', x : 14, y : 12};
mappages["toshin1"].features[14] = {name : 'BookshelfLeft', x : 8, y : 9};
mappages["toshin1"].features[15] = {name : 'BookshelfRight', x : 9, y : 9};
mappages["toshin1"].features[16] = {name : 'BookshelfRight', x : 15, y : 9};
mappages["toshin1"].features[17] = {name : 'BookshelfLeft', x : 14, y : 9};
mappages["toshin1"].features[18] = {name : 'BookshelfLeft', x : 11, y : 10};
mappages["toshin1"].features[19] = {name : 'BookshelfRight', x : 12, y : 10};
mappages["toshin1"].features[20] = {name : 'LeftChair', x : 11, y : 8};
mappages["toshin1"].features[21] = {name : 'DeadTree', x : 6, y : 12, lootedid : 'toshintree', searchyield : 'ScrollShockwave'};
mappages["toshin1"].features[22] = {name : 'Fountain', x : 18, y : 13};
mappages["toshin1"].features[23] = {name : 'Evergreen', x : 26, y : 7};
mappages["toshin1"].features[24] = {name : 'Evergreen', x : 26, y : 8};
mappages["toshin1"].features[25] = {name : 'Evergreen', x : 27, y : 8};
mappages["toshin1"].features[26] = {name : 'Evergreen', x : 26, y : 9};
mappages["toshin1"].features[27] = {name : 'Evergreen', x : 30, y : 19};
mappages["toshin1"].features[28] = {name : 'Evergreen', x : 30, y : 20};
mappages["toshin1"].features[29] = {name : 'Evergreen', x : 29, y : 20};
mappages["toshin1"].features[30] = {name : 'Evergreen', x : 30, y : 21};
mappages["toshin1"].features[31] = {name : 'Evergreen', x : 31, y : 21};
mappages["toshin1"].features[32] = {name : 'Evergreen', x : 31, y : 22};
mappages["toshin1"].features[33] = {name : 'Evergreen', x : 5, y : 11};
mappages["toshin1"].features[34] = {name : 'Evergreen', x : 5, y : 12};
mappages["toshin1"].features[35] = {name : 'Evergreen', x : 5, y : 13};
mappages["toshin1"].features[36] = {name : 'Evergreen', x : 6, y : 14};
mappages["toshin1"].features[37] = {name : 'DoorWindow', x : 11, y : 13};
mappages["toshin1"].features[38] = {name : 'DoorWindow', x : 11, y : 15};
mappages["toshin1"].features[39] = {name : 'BookshelfLeft', x : 14, y : 16};
mappages["toshin1"].features[40] = {name : 'BookshelfRight', x : 15, y : 16, lootedid : 'ToshinJournal', searchyield : 'ToshinJournal'};
mappages["toshin1"].features[41] = {name : 'BookshelfLeft', x : 14, y : 18};
mappages["toshin1"].features[42] = {name : 'BookshelfLeft', x : 14, y : 19};
mappages["toshin1"].features[43] = {name : 'BookshelfLeft', x : 14, y : 21};
mappages["toshin1"].features[44] = {name : 'BookshelfRight', x : 15, y : 18};
mappages["toshin1"].features[45] = {name : 'BookshelfRight', x : 15, y : 19};
mappages["toshin1"].features[46] = {name : 'BookshelfRight', x : 15, y : 21};
mappages["toshin1"].features[47] = {name : 'AlchemyLab', x : 9, y : 19};
mappages["toshin1"].features[48] = {name : 'AlchemyLab2', x : 10, y : 19};
mappages["toshin1"].features[49] = {name : 'AlchemyLabTop2', x : 10, y : 18};
mappages["toshin1"].features[50] = {name : 'AlchemyLabTop', x : 9, y : 18};
mappages["toshin1"].features[51] = {name : 'LeftTable', x : 8, y : 19};
mappages["toshin1"].features[52] = {name : 'RightTable', x : 11, y : 19};
mappages["toshin1"].features[53] = {name : 'BottomChair', x : 9, y : 20};
mappages["toshin1"].features[54] = {name : 'Evergreen', x : 27, y : 18};
mappages["toshin1"].features[55] = {name : 'Evergreen', x : 22, y : 24};
mappages["toshin1"].features[56] = {name : 'Evergreen', x : 4, y : 21};
mappages["toshin1"].features[57] = {name : 'Evergreen', x : 2, y : 17};
mappages["toshin1"].features[58] = {name : 'Evergreen', x : 4, y : 6};
mappages["toshin1"].features[59] = {name : 'Evergreen', x : 11, y : 2};
mappages["toshin1"].features[60] = {name : 'Evergreen', x : 19, y : 3};
mappages["toshin1"].features[61] = {name : 'Evergreen', x : 25, y : 1};
mappages["toshin1"].features[62] = {name : 'Evergreen', x : 29, y : 6};
mappages["toshin1"].features[63] = {name : 'LeftTable', x : 22, y : 18};
mappages["toshin1"].features[64] = {name : 'MiddleTable', x : 23, y : 18};
mappages["toshin1"].features[65] = {name : 'RightTable', x : 24, y : 18};
mappages["toshin1"].features[66] = {name : 'TopChair', x : 24, y : 17};
mappages["toshin1"].features[67] = {name : 'TopChair', x : 23, y : 17};
mappages["toshin1"].features[68] = {name : 'BottomChair', x : 22, y : 19};
mappages["toshin1"].features[69] = {name : 'BottomChair', x : 23, y : 19};
mappages["toshin1"].features[70] = {name : 'GrandfatherClock', x : 21, y : 16};
mappages["toshin1"].features[71] = {name : 'Barrel', x : 21, y : 7};
mappages["toshin1"].features[72] = {name : 'Barrel', x : 20, y : 7};
mappages["toshin1"].features[73] = {name : 'Barrel', x : 20, y : 8};
mappages["toshin1"].features[74] = {name : 'Barrel', x : 22, y : 10};
mappages["toshin1"].features[75] = {name : 'Barrel', x : 21, y : 10};
mappages["toshin1"].features[76] = {name : 'Barrel', x : 23, y : 7};
mappages["toshin1"].features[77] = {name : 'Barrel', x : 24, y : 7};
mappages["toshin1"].features[78] = {name : 'Barrel', x : 24, y : 8};
mappages["toshin1"].features[79] = {name : 'Barrel', x : 24, y : 9};
mappages["toshin1"].features[80] = {name : 'ToshinKey', x : 8, y : 14};
mappages["toshin1"].features[81] = {name : 'ToshinWalkOn', x : 11, y : 12};
mappages["toshin1"].features[82] = {name : 'Fireplace', x : 18, y : 6};
mappages["toshin1"].features[83] = {name : 'UnlitBrazier', x : 13, y : 16};
mappages["toshin1"].features[84] = {name : 'UnlitBrazier', x : 9, y : 16};
mappages["toshin1"].features[85] = {name : 'UnlitBrazier', x : 8, y : 21};
mappages["toshin1"].features[86] = {name : 'UnlitBrazier', x : 20, y : 16};
mappages["toshin1"].features[87] = {name : 'UnlitBrazier', x : 24, y : 21};
mappages["toshin1"].features[88] = {name : 'Fireplace', x : 9, y : 14};
mappages["toshin1"].features[89] = {name : 'Brazier', x : 13, y : 12};
mappages["toshin1"].features[90] = {name : 'Brazier', x : 9, y : 12};

mappages["toshin1"].npcs = [];
mappages["toshin1"].npcs[0] = {name : 'MageVillagerNPC', x : 14, y : 10, NPCName: 'Arlan', PeaceAI: 'scheduled', Schedule: 'arlan', Conversation: 'arlan', Gender: 'male', NPCBand: '1', OverrideGraphic: 'mage-offcolor.gif', skintone: '1'};
mappages["toshin1"].npcs[1] = {name : 'RangerVillagerNPC', x : 12, y : 9, NPCName: 'Elora', PeaceAI: 'scheduled', Schedule: 'elora', Conversation: 'elora', Gender: 'female', NPCBand: '0', OverrideGraphic: '305.gif', skintone: '1'};

mappages["toshin1"].desc = "Toshin's Tower";
mappages["toshin1"].longdesc = 'Before you, rising perhaps 50 feet in the air, is a square stone tower. Outwardly utilitarian, it once housed one of the greatest wizards in recent memory. She disappeared decades ago, but her tower still stands.';
mappages["toshin1"].music = 'Magic';
mappages["toshin1"].savename = `Toshin's Tower`;
mappages["toshin1"].exitmap = 'darkunknown';
mappages["toshin1"].exitx = '102';
mappages["toshin1"].exity = '126';
mappages["toshin1"].wraps = 'None';
mappages["toshin1"].enterx = '31';
mappages["toshin1"].entery = '16';
mappages["toshin1"].seeBelow = '';
mappages["toshin1"].lightLevel = 'cycle';
mappages["toshin1"].alwaysRemember = '0';
mappages["toshin1"].scale = '1';
mappages["toshin1"].underground = '0';
mappages["toshin1"].undergroundDesc = '';
mappages["toshin1"].enterscript = '';
mappages["toshin1"].entertestscript = '';
mappages["toshin1"].exitscript = 'toshin_exit';
mappages["toshin1"].exittestscript = '';
mappages["toshin1"].returnmap = 'darkunknown';
mappages["toshin1"].returnx = '102';
mappages["toshin1"].returny = '126';
mappages["toshin1"].returninfused = '0';
mappages["toshin1"].linkedMaps = ["toshin2","toshin3","toshin4"];
mappages["toshin1"].editorLabels = '{}';

mappages["toshin1"].toshin_exit = function(mapref) {
  mapref.Exit = function(who,tomap,oldx,oldy,destx,desty) {
    if ((tomap.getName() === "darkunknown") || (tomap.getName() === "landsbeyond")) {
      let key=PC.checkInventory("ToshinKey");
      PC.removeFromInventory(key);
    }
  }
  return 1;
}

mappages["toshin1"].onload = function(mapref) {
  if ((gamestate.getMode() !== "loadgame") && (!DU.gameflags.getFlag("editor"))) {
    let npcs = mapref.npcs.getAll();
    let arlan, elora;
    for (let i=0;i<npcs.length;i++) {
      if (npcs[i].getNPCName() === "Arlan") { arlan = npcs[i]; }
      if (npcs[i].getNPCName() === "Elora") { elora = npcs[i]; } 
    }
    if ((arlan.getCurrentScheduleIndex() >= 14) && (arlan.getCurrentScheduleIndex() <= 15)) {
      arlan.setGraphicArray(["master_spritesheet.png","","-64","-800"]);
    }
    if ((elora.getCurrentScheduleIndex() >= 3) && (elora.getCurrentScheduleIndex() <= 4)) {
      elora.setGraphicArray(["master_spritesheet.png","","-64","-800"]);
    }
  }
}

mappages["toshin2"] = {};
mappages["toshin2"].terrain = [];
 mappages["toshin2"].terrain[0] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["toshin2"].terrain[1] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["toshin2"].terrain[2] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["toshin2"].terrain[3] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["toshin2"].terrain[4] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["toshin2"].terrain[5] = 'sb sb sb sb sb sb sb ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## sb sb sb sb sb sb';
 mappages["toshin2"].terrain[6] = 'sb sb sb sb sb sb sb ## ++ ++ ++ ++ ++ ## ## ## ## ## ## ## +* ## ## ## ## ## sb sb sb sb sb sb';
 mappages["toshin2"].terrain[7] = 'sb sb sb sb sb sb sb ## ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ## +* +* +* +* +* ## sb sb sb sb sb sb';
 mappages["toshin2"].terrain[8] = 'sb sb sb sb sb sb sb #O ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ## +* +* +* +* +* ## sb sb sb sb sb sb';
 mappages["toshin2"].terrain[9] = 'sb sb sb sb sb sb sb ## ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ## +* +* +* +* +* ## sb sb sb sb sb sb';
mappages["toshin2"].terrain[10] = 'sb sb sb sb sb sb sb ## ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ++ ## +* +* +* +* +* ## sb sb sb sb sb sb';
mappages["toshin2"].terrain[11] = 'sb sb sb sb sb sb sb ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ +* +* +* +* +* ## sb sb sb sb sb sb';
mappages["toshin2"].terrain[12] = 'sb sb sb sb sb sb sb ## ++ ++ ++ ++ ++ ## ## ## ++ ## ## ## ## ## ## ## ## ## sb sb sb sb sb sb';
mappages["toshin2"].terrain[13] = 'sb sb sb sb sb sb sb ## ++ ++ ++ ++ ++ ## ## ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ## sb sb sb sb sb sb';
mappages["toshin2"].terrain[14] = 'sb sb sb sb sb sb sb ## ++ ++ ++ ++ ++ ## ## ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ## sb sb sb sb sb sb';
mappages["toshin2"].terrain[15] = 'sb sb sb sb sb sb sb ## ++ ++ ++ ++ ++ ## ## ++ ++ ++ ++ ++ ## ++ ++ ++ ++ ## sb sb sb sb sb sb';
mappages["toshin2"].terrain[16] = 'sb sb sb sb sb sb sb ## ++ ++ ++ ++ ++ ## ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## sb sb sb sb sb sb';
mappages["toshin2"].terrain[17] = 'sb sb sb sb sb sb sb ## ++ ++ ++ ++ ++ ## ## ## ## ++ ## ## ## ## ## ## ## ## sb sb sb sb sb sb';
mappages["toshin2"].terrain[18] = 'sb sb sb sb sb sb sb ## ++ ++ ++ ++ ++ ## ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## sb sb sb sb sb sb';
mappages["toshin2"].terrain[19] = 'sb sb sb sb sb sb sb #O ++ ++ ++ ++ ++ ## ## ++ ++ ++ b1 b2 b2 b2 b2 b2 b3 #O sb sb sb sb sb sb';
mappages["toshin2"].terrain[20] = 'sb sb sb sb sb sb sb ## ++ ++ ++ ++ ++ ## ## ++ ++ ++ b8 b0 b0 b0 b0 b0 b4 ## sb sb sb sb sb sb';
mappages["toshin2"].terrain[21] = 'sb sb sb sb sb sb sb ## ++ ++ ++ ++ ++ ## ## ++ ++ ++ b7 b6 b6 b6 b6 b6 b5 ## sb sb sb sb sb sb';
mappages["toshin2"].terrain[22] = 'sb sb sb sb sb sb sb ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## #O ## ## ## sb sb sb sb sb sb';
mappages["toshin2"].terrain[23] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["toshin2"].terrain[24] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["toshin2"].terrain[25] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["toshin2"].terrain[26] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["toshin2"].terrain[27] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["toshin2"].terrain[28] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["toshin2"].terrain[29] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["toshin2"].terrain[30] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["toshin2"].terrain[31] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';

mappages["toshin2"].features = [];
mappages["toshin2"].features[0] = {name : 'StairDown', x : 17, y : 7, entermap : 'toshin1', enterx : 17, entery : 7};
mappages["toshin2"].features[1] = {name : 'Door', x : 19, y : 11, desc : "magically locked door", locked : 2, keyname : "ToshinKey"};
mappages["toshin2"].features[2] = {name : 'Door', x : 13, y : 11};
mappages["toshin2"].features[3] = {name : 'PentagramNW', x : 21, y : 8};
mappages["toshin2"].features[4] = {name : 'PentagramN', x : 22, y : 8};
mappages["toshin2"].features[5] = {name : 'PentagramNE', x : 23, y : 8};
mappages["toshin2"].features[6] = {name : 'PentagramE', x : 23, y : 9};
mappages["toshin2"].features[7] = {name : 'PentagramC', x : 22, y : 9};
mappages["toshin2"].features[8] = {name : 'PentagramW', x : 21, y : 9};
mappages["toshin2"].features[9] = {name : 'PentagramSW', x : 21, y : 10};
mappages["toshin2"].features[10] = {name : 'PentagramS', x : 22, y : 10};
mappages["toshin2"].features[11] = {name : 'PentagramSE', x : 23, y : 10};
mappages["toshin2"].features[12] = {name : 'Door', x : 16, y : 12, desc : "locked door", locked : 1, keyname : "ToshinKey"};
mappages["toshin2"].features[13] = {name : 'LadderUp', x : 20, y : 6, entermap : 'toshin3', enterx : 20, entery : 6};
mappages["toshin2"].features[14] = {name : 'Door', x : 20, y : 16};
mappages["toshin2"].features[15] = {name : 'Door', x : 17, y : 17};
mappages["toshin2"].features[16] = {name : 'Harpsichord', x : 10, y : 17};
mappages["toshin2"].features[17] = {name : 'TopChair', x : 10, y : 16};
mappages["toshin2"].features[18] = {name : 'RightChair', x : 10, y : 8};
mappages["toshin2"].features[19] = {name : 'SmallTable', x : 9, y : 8};
mappages["toshin2"].features[20] = {name : 'GrandfatherClock', x : 8, y : 13};
mappages["toshin2"].features[21] = {name : 'Altar', x : 10, y : 6};
mappages["toshin2"].features[22] = {name : 'DoubleBedTopHead', x : 23, y : 20};
mappages["toshin2"].features[23] = {name : 'DoubleBedBottomHead', x : 23, y : 21};
mappages["toshin2"].features[24] = {name : 'DoubleBedTopFoot', x : 24, y : 20};
mappages["toshin2"].features[25] = {name : 'DoubleBedBottomFoot', x : 24, y : 21};
mappages["toshin2"].features[26] = {name : 'Mirror', x : 15, y : 18};
mappages["toshin2"].features[27] = {name : 'Dresser', x : 21, y : 18};
mappages["toshin2"].features[28] = {name : 'BookshelfLeft', x : 23, y : 18};
mappages["toshin2"].features[29] = {name : 'BookshelfRight', x : 24, y : 18};
mappages["toshin2"].features[30] = {name : 'SmallBox', x : 22, y : 18, locked : 0, lootedid : 'toshin2box', searchyield : 'YellowPotion'};
mappages["toshin2"].features[31] = {name : 'LeftTable', x : 18, y : 14};
mappages["toshin2"].features[32] = {name : 'RightTable', x : 19, y : 14};
mappages["toshin2"].features[33] = {name : 'TopChair', x : 19, y : 13};
mappages["toshin2"].features[34] = {name : 'BookshelfOne', x : 15, y : 13, lootedid : 'targrion', searchyield : 'FallOfTargrion'};
mappages["toshin2"].features[35] = {name : 'StatueBase', x : 15, y : 10};
mappages["toshin2"].features[36] = {name : 'StatueBase', x : 17, y : 10};
mappages["toshin2"].features[37] = {name : 'StatueTop', x : 15, y : 9};
mappages["toshin2"].features[38] = {name : 'StatueTop', x : 17, y : 9};
mappages["toshin2"].features[39] = {name : 'Fireplace', x : 14, y : 20};
mappages["toshin2"].features[40] = {name : 'UnlitBrazier', x : 24, y : 11};
mappages["toshin2"].features[41] = {name : 'UnlitBrazier', x : 24, y : 7};
mappages["toshin2"].features[42] = {name : 'UnlitBrazier', x : 14, y : 7};
mappages["toshin2"].features[43] = {name : 'UnlitBrazier', x : 12, y : 6};
mappages["toshin2"].features[44] = {name : 'UnlitBrazier', x : 8, y : 6};
mappages["toshin2"].features[45] = {name : 'UnlitBrazier', x : 12, y : 21};
mappages["toshin2"].features[46] = {name : 'UnlitBrazier', x : 8, y : 21};
mappages["toshin2"].features[47] = {name : 'UnlitBrazier', x : 12, y : 13};
mappages["toshin2"].features[48] = {name : 'EnergyField', x : 21, y : 13};
mappages["toshin2"].features[49] = {name : 'EnergyField', x : 24, y : 13};
mappages["toshin2"].features[50] = {name : 'EnergyField', x : 24, y : 16};
mappages["toshin2"].features[51] = {name : 'EnergyField', x : 22, y : 16};
mappages["toshin2"].features[52] = {name : 'SleepField', x : 21, y : 14};
mappages["toshin2"].features[53] = {name : 'SleepField', x : 23, y : 15};
mappages["toshin2"].features[54] = {name : 'FireField', x : 24, y : 14};
mappages["toshin2"].features[55] = {name : 'FireField', x : 23, y : 13};
mappages["toshin2"].features[56] = {name : 'FireField', x : 22, y : 15};
mappages["toshin2"].features[57] = {name : 'FireField', x : 23, y : 16};
mappages["toshin2"].features[58] = {name : 'PoisonField', x : 24, y : 15};
mappages["toshin2"].features[59] = {name : 'PoisonField', x : 23, y : 14};
mappages["toshin2"].features[60] = {name : 'PoisonField', x : 22, y : 14};
mappages["toshin2"].features[61] = {name : 'PoisonField', x : 21, y : 15};
mappages["toshin2"].features[62] = {name : 'SleepField', x : 22, y : 13};
mappages["toshin2"].features[63] = {name : 'SleepField', x : 21, y : 16};
mappages["toshin2"].features[64] = {name : 'UnlitBrazier', x : 15, y : 16};


mappages["toshin2"].npcs = [];

mappages["toshin2"].desc = "Toshin's Tower";
mappages["toshin2"].longdesc = '';
mappages["toshin2"].music = 'Magic';
mappages["toshin2"].savename = `Toshin's Tower`;
mappages["toshin2"].exitmap = 'darkunknown';
mappages["toshin2"].exitx = '65';
mappages["toshin2"].exity = '70';
mappages["toshin2"].wraps = 'None';
mappages["toshin2"].enterx = '31';
mappages["toshin2"].entery = '16';
mappages["toshin2"].seeBelow = 'toshin1';
mappages["toshin2"].lightLevel = 'cycle';
mappages["toshin2"].alwaysRemember = '0';
mappages["toshin2"].scale = '1';
mappages["toshin2"].underground = '0';
mappages["toshin2"].undergroundDesc = '';
mappages["toshin2"].enterscript = '';
mappages["toshin2"].entertestscript = '';
mappages["toshin2"].exitscript = '';
mappages["toshin2"].exittestscript = '';
mappages["toshin2"].returnmap = 'darkunknown';
mappages["toshin2"].returnx = '69';
mappages["toshin2"].returny = '74';
mappages["toshin2"].returninfused = '0';
mappages["toshin2"].linkedMaps = ["toshin1","toshin3","toshin4"];
mappages["toshin2"].editorLabels = '{}';

mappages["toshin3"] = {};
mappages["toshin3"].terrain = [];
 mappages["toshin3"].terrain[0] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["toshin3"].terrain[1] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["toshin3"].terrain[2] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["toshin3"].terrain[3] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["toshin3"].terrain[4] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["toshin3"].terrain[5] = 'sb sb sb sb sb sb sb ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## sb sb sb sb sb sb';
 mappages["toshin3"].terrain[6] = 'sb sb sb sb sb sb sb ## +* ## ## ## ## ## ## ## ## ## ## ## +* +* +* +* +* ## sb sb sb sb sb sb';
 mappages["toshin3"].terrain[7] = 'sb sb sb sb sb sb sb ## +* +* +* +* +* +* +* +* +* +* +* ## ## ## ## ## +* ## sb sb sb sb sb sb';
 mappages["toshin3"].terrain[8] = 'sb sb sb sb sb sb sb ## ## ## +* +* +* +* +* +* +* +* +* +* +* +* +* ## ## ## sb sb sb sb sb sb';
 mappages["toshin3"].terrain[9] = 'sb sb sb sb sb sb sb ## ## ## +* +* +* +* +* +* +* +* +* +* +* +* +* ## ## ## sb sb sb sb sb sb';
mappages["toshin3"].terrain[10] = 'sb sb sb sb sb sb sb ## ## ## +* +* +* +* +* +* +* +* +* +* +* +* +* ## ## ## sb sb sb sb sb sb';
mappages["toshin3"].terrain[11] = 'sb sb sb sb sb sb sb ## ## ## +* +* +* +* +* +* +* +* +* +* +* +* +* ## ## ## sb sb sb sb sb sb';
mappages["toshin3"].terrain[12] = 'sb sb sb sb sb sb sb ## ## ## +* +* +* +* +* +* +* +* +* +* +* +* +* ## ## ## sb sb sb sb sb sb';
mappages["toshin3"].terrain[13] = 'sb sb sb sb sb sb sb ## ## ## +* +* +* +* +* +* +* +* +* +* +* +* +* ## ## ## sb sb sb sb sb sb';
mappages["toshin3"].terrain[14] = 'sb sb sb sb sb sb sb ## ## ## +* +* +* +* +* +* +* +* +* +* +* +* +* ## ## ## sb sb sb sb sb sb';
mappages["toshin3"].terrain[15] = 'sb sb sb sb sb sb sb ## +* +* +* +* +* +* +* +* +* +* +* +* +* +* +* ## ## ## sb sb sb sb sb sb';
mappages["toshin3"].terrain[16] = 'sb sb sb sb sb sb sb ## +* ## +* +* +* +* +* +* +* +* +* +* +* +* +* ## ## ## sb sb sb sb sb sb';
mappages["toshin3"].terrain[17] = 'sb sb sb sb sb sb sb ## +* ## +* +* +* +* +* +* +* +* +* +* +* +* +* ## ## ## sb sb sb sb sb sb';
mappages["toshin3"].terrain[18] = 'sb sb sb sb sb sb sb ## ## ## +* +* +* +* +* +* +* +* +* +* +* +* +* ## ## ## sb sb sb sb sb sb';
mappages["toshin3"].terrain[19] = 'sb sb sb sb sb sb sb ## ## ## +* +* +* +* +* +* +* +* +* +* +* +* +* +* +* ## sb sb sb sb sb sb';
mappages["toshin3"].terrain[20] = 'sb sb sb sb sb sb sb ## +* ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## +* ## sb sb sb sb sb sb';
mappages["toshin3"].terrain[21] = 'sb sb sb sb sb sb sb ## +* +* +* +* +* ## ## ## ## ## +* +* +* +* +* +* +* ## sb sb sb sb sb sb';
mappages["toshin3"].terrain[22] = 'sb sb sb sb sb sb sb ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## sb sb sb sb sb sb';
mappages["toshin3"].terrain[23] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["toshin3"].terrain[24] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["toshin3"].terrain[25] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["toshin3"].terrain[26] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["toshin3"].terrain[27] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["toshin3"].terrain[28] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["toshin3"].terrain[29] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["toshin3"].terrain[30] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["toshin3"].terrain[31] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';

mappages["toshin3"].features = [];
mappages["toshin3"].features[0] = {name : 'LadderDown', x : 20, y : 6, entermap : 'toshin2', enterx : 20, entery : 6};
mappages["toshin3"].features[1] = {name : 'LadderUp', x : 12, y : 21, entermap : 'toshin4', enterx : 12, entery : 21};
mappages["toshin3"].features[2] = {name : 'Chest', x : 8, y : 6, lootgroup : 'Level4', lootedid : 'toshin3-1'};
mappages["toshin3"].features[3] = {name : 'TeleporterPlatform', x : 15, y : 13};
mappages["toshin3"].features[4] = {name : 'TeleporterPlatform', x : 24, y : 7};
mappages["toshin3"].features[5] = {name : 'TeleporterPlatform', x : 8, y : 20};
mappages["toshin3"].features[6] = {name : 'ToshinPanel', x : 17, y : 13};
mappages["toshin3"].features[7] = {name : 'Chest', x : 8, y : 17, lootgroup : 'Level4', lootedid : 'toshin3-2'};
mappages["toshin3"].features[8] = {name : 'TeleporterPlatform', x : 18, y : 21};
mappages["toshin3"].features[9] = {name : 'EnergyField', x : 15, y : 12};
mappages["toshin3"].features[10] = {name : 'EnergyField', x : 17, y : 12};
mappages["toshin3"].features[11] = {name : 'EnergyField', x : 18, y : 12};
mappages["toshin3"].features[12] = {name : 'EnergyField', x : 18, y : 14};
mappages["toshin3"].features[13] = {name : 'EnergyField', x : 17, y : 14};
mappages["toshin3"].features[14] = {name : 'EnergyField', x : 16, y : 14};
mappages["toshin3"].features[15] = {name : 'EnergyField', x : 15, y : 14};
mappages["toshin3"].features[16] = {name : 'EnergyField', x : 14, y : 14};
mappages["toshin3"].features[17] = {name : 'EnergyField', x : 14, y : 13};
mappages["toshin3"].features[18] = {name : 'EnergyField', x : 14, y : 12};
mappages["toshin3"].features[19] = {name : 'EnergyField', x : 18, y : 13};
mappages["toshin3"].features[20] = {name : 'EnergyField', x : 17, y : 11};
mappages["toshin3"].features[21] = {name : 'EnergyField', x : 17, y : 10};
mappages["toshin3"].features[22] = {name : 'EnergyField', x : 16, y : 10};
mappages["toshin3"].features[23] = {name : 'EnergyField', x : 15, y : 10};
mappages["toshin3"].features[24] = {name : 'EnergyField', x : 19, y : 8};
mappages["toshin3"].features[25] = {name : 'EnergyField', x : 17, y : 8};
mappages["toshin3"].features[26] = {name : 'EnergyField', x : 18, y : 8};
mappages["toshin3"].features[27] = {name : 'EnergyField', x : 16, y : 8};
mappages["toshin3"].features[28] = {name : 'EnergyField', x : 15, y : 8};
mappages["toshin3"].features[29] = {name : 'EnergyField', x : 17, y : 9};
mappages["toshin3"].features[30] = {name : 'EnergyField', x : 11, y : 8};
mappages["toshin3"].features[31] = {name : 'EnergyField', x : 12, y : 8};
mappages["toshin3"].features[32] = {name : 'EnergyField', x : 13, y : 8};
mappages["toshin3"].features[33] = {name : 'EnergyField', x : 10, y : 10};
mappages["toshin3"].features[34] = {name : 'EnergyField', x : 19, y : 10};
mappages["toshin3"].features[35] = {name : 'EnergyField', x : 19, y : 9};
mappages["toshin3"].features[36] = {name : 'EnergyField', x : 12, y : 14};
mappages["toshin3"].features[37] = {name : 'EnergyField', x : 14, y : 15};
mappages["toshin3"].features[38] = {name : 'EnergyField', x : 14, y : 16};
mappages["toshin3"].features[39] = {name : 'EnergyField', x : 13, y : 16};
mappages["toshin3"].features[40] = {name : 'EnergyField', x : 12, y : 16};
mappages["toshin3"].features[41] = {name : 'EnergyField', x : 11, y : 16};
mappages["toshin3"].features[42] = {name : 'EnergyField', x : 11, y : 14};
mappages["toshin3"].features[43] = {name : 'FireField', x : 12, y : 15};
mappages["toshin3"].features[44] = {name : 'EnergyField', x : 19, y : 12};
mappages["toshin3"].features[45] = {name : 'EnergyField', x : 20, y : 12};
mappages["toshin3"].features[46] = {name : 'EnergyField', x : 21, y : 12};
mappages["toshin3"].features[47] = {name : 'EnergyField', x : 21, y : 11};
mappages["toshin3"].features[48] = {name : 'EnergyField', x : 21, y : 10};
mappages["toshin3"].features[49] = {name : 'EnergyField', x : 21, y : 9};
mappages["toshin3"].features[50] = {name : 'EnergyField', x : 19, y : 14};
mappages["toshin3"].features[51] = {name : 'EnergyField', x : 20, y : 14};
mappages["toshin3"].features[52] = {name : 'EnergyField', x : 21, y : 14};
mappages["toshin3"].features[53] = {name : 'EnergyField', x : 22, y : 16};
mappages["toshin3"].features[54] = {name : 'EnergyField', x : 21, y : 16};
mappages["toshin3"].features[55] = {name : 'EnergyField', x : 20, y : 16};
mappages["toshin3"].features[56] = {name : 'EnergyField', x : 20, y : 18};
mappages["toshin3"].features[57] = {name : 'EnergyField', x : 21, y : 18};
mappages["toshin3"].features[58] = {name : 'EnergyField', x : 22, y : 18};
mappages["toshin3"].features[59] = {name : 'EnergyField', x : 20, y : 17};
mappages["toshin3"].features[60] = {name : 'EnergyField', x : 18, y : 15};
mappages["toshin3"].features[61] = {name : 'EnergyField', x : 18, y : 16};
mappages["toshin3"].features[62] = {name : 'EnergyField', x : 16, y : 16};
mappages["toshin3"].features[63] = {name : 'EnergyField', x : 16, y : 17};
mappages["toshin3"].features[64] = {name : 'EnergyField', x : 16, y : 18};
mappages["toshin3"].features[65] = {name : 'EnergyField', x : 17, y : 18};
mappages["toshin3"].features[66] = {name : 'EnergyField', x : 18, y : 18};
mappages["toshin3"].features[67] = {name : 'EnergyField', x : 19, y : 18};
mappages["toshin3"].features[68] = {name : 'EnergyField', x : 12, y : 18};
mappages["toshin3"].features[69] = {name : 'EnergyField', x : 14, y : 18};
mappages["toshin3"].features[70] = {name : 'EnergyField', x : 15, y : 18};
mappages["toshin3"].features[71] = {name : 'FireField', x : 12, y : 19};
mappages["toshin3"].features[72] = {name : 'FireField', x : 12, y : 17};
mappages["toshin3"].features[73] = {name : 'EnergyField', x : 13, y : 18};
mappages["toshin3"].features[74] = {name : 'EnergyField', x : 14, y : 8};
mappages["toshin3"].features[75] = {name : 'FireField', x : 21, y : 13};
mappages["toshin3"].features[76] = {name : 'EnergyField', x : 13, y : 10};
mappages["toshin3"].features[77] = {name : 'EnergyField', x : 13, y : 11};
mappages["toshin3"].features[78] = {name : 'EnergyField', x : 13, y : 12};
mappages["toshin3"].features[79] = {name : 'FireField', x : 12, y : 11};
mappages["toshin3"].features[80] = {name : 'EnergyField', x : 11, y : 9};
mappages["toshin3"].features[81] = {name : 'EnergyField', x : 11, y : 10};
mappages["toshin3"].features[82] = {name : 'EnergyField', x : 11, y : 10};
mappages["toshin3"].features[83] = {name : 'EnergyField', x : 11, y : 11};
mappages["toshin3"].features[84] = {name : 'EnergyField', x : 11, y : 12};
mappages["toshin3"].features[85] = {name : 'EnergyField', x : 11, y : 12};
mappages["toshin3"].features[86] = {name : 'EnergyField', x : 11, y : 13};
mappages["toshin3"].features[87] = {name : 'EnergyField', x : 11, y : 13};
mappages["toshin3"].features[88] = {name : 'EnergyField', x : 11, y : 18};
mappages["toshin3"].features[89] = {name : 'FireField', x : 11, y : 7};


mappages["toshin3"].npcs = [];
mappages["toshin3"].npcs[0] = {name : 'ToshinSentinelNPC', x : 15, y : 17, skintone: '1'};
mappages["toshin3"].npcs[1] = {name : 'ToshinSentinelNPC', x : 16, y : 9, skintone: '1'};
mappages["toshin3"].npcs[2] = {name : 'ToshinSentinelNPC', x : 22, y : 9, skintone: '1'};
mappages["toshin3"].npcs[3] = {name : 'ToshinSentinelNPC', x : 10, y : 12, skintone: '1'};

mappages["toshin3"].desc = "Toshin's Tower";
mappages["toshin3"].longdesc = '';
mappages["toshin3"].music = 'Magic';
mappages["toshin3"].savename = `Toshin's Tower`;
mappages["toshin3"].exitmap = 'darkunknown';
mappages["toshin3"].exitx = '65';
mappages["toshin3"].exity = '70';
mappages["toshin3"].wraps = 'None';
mappages["toshin3"].enterx = '31';
mappages["toshin3"].entery = '16';
mappages["toshin3"].seeBelow = 'toshin2';
mappages["toshin3"].lightLevel = 'cycle';
mappages["toshin3"].alwaysRemember = '0';
mappages["toshin3"].scale = '1';
mappages["toshin3"].underground = '0';
mappages["toshin3"].undergroundDesc = '';
mappages["toshin3"].enterscript = '';
mappages["toshin3"].entertestscript = '';
mappages["toshin3"].exitscript = '';
mappages["toshin3"].exittestscript = '';
mappages["toshin3"].returnmap = 'darkunknown';
mappages["toshin3"].returnx = '69';
mappages["toshin3"].returny = '74';
mappages["toshin3"].returninfused = '0';
mappages["toshin3"].linkedMaps = ["toshin1","toshin2","toshin4"];
mappages["toshin3"].editorLabels = '{}';

mappages["toshin3"].onload = function(mapref) {
  if (gamestate.getMode() !== "loadgame") {
    let tile = mapref.getTile(24,7);
    let tp = tile.getTopFeature();
    if (tp.getName() === "TeleporterPlatform") {
      let destobj = {};
      destobj.map = mapref.getName();
      destobj.x = 15;
      destobj.y = 13;
      tp.setDestination(destobj);
    }
    tile = mapref.getTile(15,13);
    tp = tile.getTopFeature();
    if (tp.getName() === "TeleporterPlatform") {
      let destobj = {};
      destobj.map = mapref.getName();
      destobj.x = 24;
      destobj.y = 7;
      tp.setDestination(destobj);
    }
    tile = mapref.getTile(8,20);
    tp = tile.getTopFeature();
    if (tp.getName() === "TeleporterPlatform") {
      let destobj = {};
      destobj.map = mapref.getName();
      destobj.x = 18;
      destobj.y = 21;
      tp.setDestination(destobj);
    }
    tile = mapref.getTile(18,21);
    tp = tile.getTopFeature();
    if (tp.getName() === "TeleporterPlatform") {
      let destobj = {};
      destobj.map = mapref.getName();
      destobj.x = 8;
      destobj.y = 20;
      tp.setDestination(destobj);
    }
    
    tile = mapref.getTile(16,9);
    let sentinel = tile.getTopNPC();
    sentinel.patrol = 0;
    sentinel.step = 0;
    sentinel.direction = 1;
    sentinel.setMaxHP(10000);
    tile = mapref.getTile(22,9);
    sentinel = tile.getTopNPC();
    sentinel.patrol = 1;
    sentinel.step = 12;
    sentinel.direction = -1;
    sentinel.setMaxHP(10000);
    tile = mapref.getTile(10,12);
    sentinel = tile.getTopNPC();
    sentinel.patrol = 2;
    sentinel.step = 6;
    sentinel.direction = -1;
    sentinel.setMaxHP(10000);
    tile = mapref.getTile(15,17);
    sentinel = tile.getTopNPC();
    sentinel.patrol = 3;
    sentinel.step = 5;
    sentinel.direction = -1;
    sentinel.setMaxHP(10000);
  }
}


mappages["toshin4"] = {};
mappages["toshin4"].terrain = [];
 mappages["toshin4"].terrain[0] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["toshin4"].terrain[1] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["toshin4"].terrain[2] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["toshin4"].terrain[3] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["toshin4"].terrain[4] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
 mappages["toshin4"].terrain[5] = 'sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb';
 mappages["toshin4"].terrain[6] = 'sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb';
 mappages["toshin4"].terrain[7] = 'sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb';
 mappages["toshin4"].terrain[8] = 'sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb';
 mappages["toshin4"].terrain[9] = 'sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb';
mappages["toshin4"].terrain[10] = 'sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb';
mappages["toshin4"].terrain[11] = 'sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb';
mappages["toshin4"].terrain[12] = 'sb sb sb sb sb sb sb rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc rc sb sb sb sb sb sb';
mappages["toshin4"].terrain[13] = 'sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb';
mappages["toshin4"].terrain[14] = 'sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb';
mappages["toshin4"].terrain[15] = 'sb sb sb sb sb sb sb rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb';
mappages["toshin4"].terrain[16] = 'sb sb sb sb sb sb sb ## ## ## ## ## ## ## rf rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb';
mappages["toshin4"].terrain[17] = 'sb sb sb sb sb sb sb ## ++ ++ ++ ++ ++ ## rf rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb';
mappages["toshin4"].terrain[18] = 'sb sb sb sb sb sb sb ## ++ ++ ++ ++ ++ ## rf rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb';
mappages["toshin4"].terrain[19] = 'sb sb sb sb sb sb sb ## ++ ++ ++ ++ ++ ## rf rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb';
mappages["toshin4"].terrain[20] = 'sb sb sb sb sb sb sb ## ++ ++ ++ ++ ++ ## rf rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb';
mappages["toshin4"].terrain[21] = 'sb sb sb sb sb sb sb ## ++ ++ ++ ++ ++ ## rf rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb';
mappages["toshin4"].terrain[22] = 'sb sb sb sb sb sb sb ## ## ## ## ## ## ## rf rf rf rf rf rf rf rf rf rf rf rf sb sb sb sb sb sb';
mappages["toshin4"].terrain[23] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["toshin4"].terrain[24] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["toshin4"].terrain[25] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["toshin4"].terrain[26] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["toshin4"].terrain[27] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["toshin4"].terrain[28] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["toshin4"].terrain[29] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["toshin4"].terrain[30] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';
mappages["toshin4"].terrain[31] = 'sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb sb';

mappages["toshin4"].features = [];
mappages["toshin4"].features[0] = {name : 'LadderDown', x : 12, y : 21, entermap : 'toshin3', enterx : 12, entery : 21};
mappages["toshin4"].features[1] = {name : 'Chest', x : 12, y : 19, locked : 0, lootgroup : 'Toshin', lootedid : 'toshin4-15'};
mappages["toshin4"].features[2] = {name : 'Chest', x : 12, y : 18, locked : 0, lootgroup : 'Toshin', lootedid : 'toshin4-14'};
mappages["toshin4"].features[3] = {name : 'Chest', x : 12, y : 17, locked : 0, lootgroup : 'Toshin', lootedid : 'toshin4-13'};
mappages["toshin4"].features[4] = {name : 'Chest', x : 11, y : 17, locked : 0, lootgroup : 'Toshin', lootedid : 'toshin4-12'};
mappages["toshin4"].features[5] = {name : 'Chest', x : 10, y : 17, locked : 0, lootgroup : 'Toshin', lootedid : 'toshin4-11'};
mappages["toshin4"].features[6] = {name : 'Chest', x : 11, y : 21, locked : 0, lootgroup : 'Toshin', lootedid : 'toshin4-2'};
mappages["toshin4"].features[7] = {name : 'Chest', x : 10, y : 21, locked : 0, lootgroup : 'Toshin', lootedid : 'toshin4-3'};
mappages["toshin4"].features[8] = {name : 'Chest', x : 10, y : 20, locked : 0, lootgroup : 'Toshin', lootedid : 'toshin4-1'};
mappages["toshin4"].features[9] = {name : 'Chest', x : 10, y : 19, locked : 0, lootedid : 'toshin4-ring', searchyield : 'RingOfFireResist'};
mappages["toshin4"].features[10] = {name : 'Chest', x : 9, y : 17, locked : 0, lootgroup : 'Toshin', lootedid : 'toshin4-10'};
mappages["toshin4"].features[11] = {name : 'Chest', x : 8, y : 17, locked : 0, lootgroup : 'Toshin', lootedid : 'toshin4-9'};
mappages["toshin4"].features[12] = {name : 'Chest', x : 8, y : 18, locked : 0, lootgroup : 'Toshin', lootedid : 'toshin4-8'};
mappages["toshin4"].features[13] = {name : 'Chest', x : 8, y : 19, locked : 0, lootgroup : 'Toshin', lootedid : 'toshin4-7'};
mappages["toshin4"].features[14] = {name : 'Chest', x : 8, y : 20, locked : 0, lootgroup : 'Toshin', lootedid : 'toshin4-6'};
mappages["toshin4"].features[15] = {name : 'Chest', x : 8, y : 21, locked : 0, lootgroup : 'Toshin', lootedid : 'toshin4-5'};
mappages["toshin4"].features[16] = {name : 'Chest', x : 9, y : 21, locked : 0, lootgroup : 'Toshin', lootedid : 'toshin4-4'};


mappages["toshin4"].npcs = [];

mappages["toshin4"].desc = "Toshin's Tower";
mappages["toshin4"].longdesc = '';
mappages["toshin4"].music = 'Magic';
mappages["toshin4"].savename = `Toshin's Tower`;
mappages["toshin4"].exitmap = 'darkunknown';
mappages["toshin4"].exitx = '65';
mappages["toshin4"].exity = '70';
mappages["toshin4"].wraps = 'None';
mappages["toshin4"].enterx = '31';
mappages["toshin4"].entery = '16';
mappages["toshin4"].seeBelow = 'toshin3';
mappages["toshin4"].lightLevel = 'cycle';
mappages["toshin4"].alwaysRemember = '0';
mappages["toshin4"].scale = '1';
mappages["toshin4"].underground = '0';
mappages["toshin4"].undergroundDesc = '';
mappages["toshin4"].enterscript = '';
mappages["toshin4"].entertestscript = '';
mappages["toshin4"].exitscript = '';
mappages["toshin4"].exittestscript = '';
mappages["toshin4"].returnmap = 'darkunknown';
mappages["toshin4"].returnx = '69';
mappages["toshin4"].returny = '74';
mappages["toshin4"].returninfused = '0';
mappages["toshin4"].linkedMaps = ["toshin1","toshin2","toshin3"];
mappages["toshin4"].editorLabels = '{}';
