"use strict";

// MAP BEGINS HERE
mappages["volcano"] = {};
mappages["volcano"].terrain = [];
 mappages["volcano"].terrain[0] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["volcano"].terrain[1] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["volcano"].terrain[2] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["volcano"].terrain[3] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["volcano"].terrain[4] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["volcano"].terrain[5] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["volcano"].terrain[6] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["volcano"].terrain[7] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["volcano"].terrain[8] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
 mappages["volcano"].terrain[9] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["volcano"].terrain[10] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["volcano"].terrain[11] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["volcano"].terrain[12] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["volcano"].terrain[13] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ^^ ^^ ^^ ^^ ^^ ^^ ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["volcano"].terrain[14] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ^^ ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW';
mappages["volcano"].terrain[15] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn ^^ ^^ ^^ ww ww ww ww ww WW WW WW WW WW WW WW WW WW';
mappages["volcano"].terrain[16] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ^^ ^^ ^^ nn nn nn nn nn nn nn nn ^^ ^^ ^^ ^^ ww ww ww ww WW WW WW WW WW WW WW WW';
mappages["volcano"].terrain[17] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ^^ ^^ ^^ ^^ nn nn nn nn nn nn nn nn nn ^^ ^^ ^^ ^^ ww ww ww WW WW WW WW WW WW WW WW';
mappages["volcano"].terrain[18] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ^^ ^^ ^^ nn nn nn nn nn nn nn nn nn nn nn nn ^^ ^^ ^^ ww ww WW WW WW WW WW WW WW WW';
mappages["volcano"].terrain[19] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ^^ ^^ ^^ nn nn nn nn nn nn nn nn nn nn nn nn nn nn ^^ ^^ ww ww WW WW WW WW WW WW WW WW';
mappages["volcano"].terrain[20] = 'WW WW WW WW WW WW WW WW WW WW uu uu ww ww ww ww ww ^^ ^^ ^^ nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn ^^ ^^ ww ww ww WW WW WW WW WW WW';
mappages["volcano"].terrain[21] = 'WW WW WW WW WW WW WW WW WW WW uu ww ww ww ww ww ^^ ^^ ^^ ^^ nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn ^^ ^^ ww ww ww WW WW WW WW WW WW';
mappages["volcano"].terrain[22] = 'WW WW WW WW WW WW WW WW WW WW uu ww ww ww ww ww ^^ ^^ ^^ nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn ^^ ^^ ^^ ww ww ww WW WW WW WW WW';
mappages["volcano"].terrain[23] = 'WW WW WW WW WW WW WW WW WW WW uu uu ww ww ww ww ^^ ^^ ^^ ^^ nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn ^^ ^^ ^^ ww ww ww WW WW WW WW WW';
mappages["volcano"].terrain[24] = 'WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ^^ ^^ ^^ nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn ^^ ^^ ^^ ww ww ww WW WW WW WW WW';
mappages["volcano"].terrain[25] = 'WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ^^ ^^ ^^ nn nn nn nn nn nn nn nn nn nn nn nn nn nn nn ^^ ^^ ww ww ww ww WW WW WW WW WW';
mappages["volcano"].terrain[26] = 'WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ^^ ^^ ^^ ^^ ^^ nn nn nn nn nn nn nn nn nn nn nn nn nn nn ^^ ^^ ww ww ww ww WW WW WW WW WW WW';
mappages["volcano"].terrain[27] = 'WW WW WW WW WW WW WW WW WW WW ww ww ww ww ^^ ^^ ^^ ^^ ^^ ^^ ^^ nn nn nn nn nn nn nn nn nn nn nn nn ^^ ^^ ^^ ww ww ww ww WW WW WW WW WW WW';
mappages["volcano"].terrain[28] = 'WW WW WW WW WW WW WW WW WW ww ww ww ww ww ^^ ^^ ^_ ^^ Rb ^^ ^^ ^^ ^^ nn nn nn nn nn nn nn ^^ ^^ ^^ ^^ ^^ ww ww ww ww WW WW WW WW WW WW WW';
mappages["volcano"].terrain[29] = 'WW WW WW WW WW WW WW WW WW ww ww ww ww ^^ ^^ nn nn ^^ Rn ^^ ^^ ^^ ^^ nn nn nn nn nn ^^ ^^ ^^ ^^ ^^ ww ww ww ww ww WW WW WW WW WW WW WW WW';
mappages["volcano"].terrain[30] = 'WW WW WW WW WW WW WW WW ww ww ww /. -- nn nn nn nn nn RR nn ^^ ^^ nn nn ^^ nn ^^ ^^ ^^ ^^ ^^ ^^ ww ww ww ww ww WW WW WW WW WW WW WW WW WW';
mappages["volcano"].terrain[31] = 'WW WW WW WW WW WW WW ww ww ww ww |. .. nn nn nn nn nn Rn nn nn ^^ nn ^^ ^^ ^^ ^^ ^^ ^^ ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW';
mappages["volcano"].terrain[32] = 'WW WW WW WW WW WW ww ww ww ww /. .. .. .. nn nn nn Rw RH nn nn nn nn ^^ ^^ ^^ ^^ ww ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW';
mappages["volcano"].terrain[33] = 'WW WW WW WW WW WW ww ww ww /. .. .. .. .. .. nn nn RR nn nn nn nn nn ^^ ^^ ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["volcano"].terrain[34] = 'WW WW WW WW WW WW ww ww ww |. .. .. .. .. .. .. nn Rm nn nn nn .. nn nn ^^ ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["volcano"].terrain[35] = 'WW WW WW WW WW WW WW ww ww |. .. .. .. .. .. Rv Rp RG .. .. .. .. .. nn ^^ ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["volcano"].terrain[36] = 'WW WW WW WW WW WW WW ww ww `. __ .. .. Rv Rp R* .. .. .. .. .. .. .. ./ ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["volcano"].terrain[37] = 'WW WW WW WW WW WW WW ww ww ww ww `. .. Rm .. RD Ry .. .. .. .. .. ./ ww ww uu uu WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["volcano"].terrain[38] = 'WW WW WW WW WW WW WW WW ww ww ww ww |. Rm .. .. Rm .. .. .. .. ./ ww ww ww uu WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["volcano"].terrain[39] = 'WW WW WW WW WW WW WW WW WW ww ww ww `. RM .. .. Rm .. .. __ ./ ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["volcano"].terrain[40] = 'WW WW WW WW WW WW WW WW WW WW ww ww ww ww `. __ RM __ ./ ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["volcano"].terrain[41] = 'WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["volcano"].terrain[42] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW ww ww ww ww ww ww ww WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["volcano"].terrain[43] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["volcano"].terrain[44] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["volcano"].terrain[45] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["volcano"].terrain[46] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["volcano"].terrain[47] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["volcano"].terrain[48] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';
mappages["volcano"].terrain[49] = 'WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW WW';

mappages["volcano"].features = [];
mappages["volcano"].features[0] = {name : 'Ruins', x : 14, y : 37, entermap : 'null', enterx : 0, entery : 0};
mappages["volcano"].features[1] = {name : 'Cave', x : 16, y : 28, entermap : 'null', enterx : 0, entery : 0};
mappages["volcano"].features[2] = {name : 'BrokenShrine', x : 11, y : 34};
mappages["volcano"].features[3] = {name : 'BridgeEW', x : 13, y : 38};
mappages["volcano"].features[4] = {name : 'BridgeEW', x : 16, y : 38};
mappages["volcano"].features[5] = {name : 'Waterfall', x : 18, y : 30};
mappages["volcano"].features[6] = {name : 'Waterfall', x : 17, y : 33};
mappages["volcano"].features[7] = {name : 'Lava', x : 19, y : 22};
mappages["volcano"].features[8] = {name : 'Lava', x : 20, y : 19};
mappages["volcano"].features[9] = {name : 'Lava', x : 20, y : 22};
mappages["volcano"].features[10] = {name : 'Lava', x : 20, y : 23};
mappages["volcano"].features[11] = {name : 'Lava', x : 20, y : 24};
mappages["volcano"].features[12] = {name : 'Lava', x : 21, y : 18};
mappages["volcano"].features[13] = {name : 'Lava', x : 21, y : 19};
mappages["volcano"].features[14] = {name : 'Lava', x : 21, y : 22};
mappages["volcano"].features[15] = {name : 'Lava', x : 21, y : 23};
mappages["volcano"].features[16] = {name : 'Lava', x : 22, y : 16};
mappages["volcano"].features[17] = {name : 'Lava', x : 22, y : 22};
mappages["volcano"].features[18] = {name : 'Lava', x : 22, y : 26};
mappages["volcano"].features[19] = {name : 'Lava', x : 23, y : 16};
mappages["volcano"].features[20] = {name : 'Lava', x : 23, y : 17};
mappages["volcano"].features[21] = {name : 'Lava', x : 23, y : 22};
mappages["volcano"].features[22] = {name : 'Lava', x : 23, y : 25};
mappages["volcano"].features[23] = {name : 'Lava', x : 23, y : 26};
mappages["volcano"].features[24] = {name : 'Lava', x : 24, y : 17};
mappages["volcano"].features[25] = {name : 'Lava', x : 24, y : 21};
mappages["volcano"].features[26] = {name : 'Lava', x : 24, y : 22};
mappages["volcano"].features[27] = {name : 'Lava', x : 25, y : 17};
mappages["volcano"].features[28] = {name : 'Lava', x : 25, y : 18};
mappages["volcano"].features[29] = {name : 'Lava', x : 25, y : 21};
mappages["volcano"].features[30] = {name : 'Lava', x : 26, y : 18};
mappages["volcano"].features[31] = {name : 'Lava', x : 26, y : 20};
mappages["volcano"].features[32] = {name : 'Lava', x : 26, y : 21};
mappages["volcano"].features[33] = {name : 'Lava', x : 26, y : 22};
mappages["volcano"].features[34] = {name : 'Lava', x : 27, y : 15};
mappages["volcano"].features[35] = {name : 'Lava', x : 27, y : 18};
mappages["volcano"].features[36] = {name : 'Lava', x : 27, y : 19};
mappages["volcano"].features[37] = {name : 'Lava', x : 27, y : 20};
mappages["volcano"].features[38] = {name : 'Lava', x : 27, y : 21};
mappages["volcano"].features[39] = {name : 'Lava', x : 27, y : 22};
mappages["volcano"].features[40] = {name : 'Lava', x : 27, y : 23};
mappages["volcano"].features[41] = {name : 'Lava', x : 27, y : 24};
mappages["volcano"].features[42] = {name : 'Lava', x : 27, y : 25};
mappages["volcano"].features[43] = {name : 'Lava', x : 27, y : 26};
mappages["volcano"].features[44] = {name : 'Lava', x : 27, y : 28};
mappages["volcano"].features[45] = {name : 'Lava', x : 27, y : 29};
mappages["volcano"].features[46] = {name : 'Lava', x : 28, y : 15};
mappages["volcano"].features[47] = {name : 'Lava', x : 28, y : 16};
mappages["volcano"].features[48] = {name : 'Lava', x : 28, y : 17};
mappages["volcano"].features[49] = {name : 'Lava', x : 28, y : 18};
mappages["volcano"].features[50] = {name : 'Lava', x : 28, y : 21};
mappages["volcano"].features[51] = {name : 'Lava', x : 28, y : 22};
mappages["volcano"].features[52] = {name : 'Lava', x : 28, y : 26};
mappages["volcano"].features[53] = {name : 'Lava', x : 28, y : 27};
mappages["volcano"].features[54] = {name : 'Lava', x : 28, y : 28};
mappages["volcano"].features[55] = {name : 'Lava', x : 29, y : 20};
mappages["volcano"].features[56] = {name : 'Lava', x : 29, y : 21};
mappages["volcano"].features[57] = {name : 'Lava', x : 29, y : 22};
mappages["volcano"].features[58] = {name : 'Lava', x : 29, y : 28};
mappages["volcano"].features[59] = {name : 'Lava', x : 30, y : 20};
mappages["volcano"].features[60] = {name : 'Lava', x : 30, y : 22};
mappages["volcano"].features[61] = {name : 'Lava', x : 30, y : 23};
mappages["volcano"].features[62] = {name : 'Lava', x : 30, y : 24};
mappages["volcano"].features[63] = {name : 'Lava', x : 31, y : 19};
mappages["volcano"].features[64] = {name : 'Lava', x : 31, y : 20};
mappages["volcano"].features[65] = {name : 'Lava', x : 31, y : 24};
mappages["volcano"].features[66] = {name : 'Lava', x : 32, y : 18};
mappages["volcano"].features[67] = {name : 'Lava', x : 32, y : 19};
mappages["volcano"].features[68] = {name : 'Lava', x : 32, y : 24};
mappages["volcano"].features[69] = {name : 'Lava', x : 32, y : 25};
mappages["volcano"].features[70] = {name : 'Lava', x : 33, y : 19};
mappages["volcano"].features[71] = {name : 'Lava', x : 33, y : 25};
mappages["volcano"].features[72] = {name : 'Lava', x : 33, y : 26};
mappages["volcano"].features[73] = {name : 'Lava', x : 34, y : 22};
mappages["volcano"].features[74] = {name : 'Lava', x : 34, y : 25};



mappages["volcano"].npcs = [];
mappages["volcano"].npcs[0] = {name : 'FireLizardGroup', x : 28, y : 19, skintone: '1'};

mappages["volcano"].desc = "Volcanic Island";
mappages["volcano"].longdesc = `This island is dominated by rugged mountains and active volcanoes, visible even from here. In this corner, a flat crescent of land was once settled, but now looks to be empty.`;
mappages["volcano"].music = 'Island';
mappages["volcano"].savename = `Volcanic Isle`;
mappages["volcano"].exitmap = '';
mappages["volcano"].exitx = '65';
mappages["volcano"].exity = '70';
mappages["volcano"].wraps = '';
mappages["volcano"].enterx = '14';
mappages["volcano"].entery = '76';
mappages["volcano"].seeBelow = '';
mappages["volcano"].lightLevel = 'cycle';
mappages["volcano"].alwaysRemember = '1';
mappages["volcano"].scale = '0';
mappages["volcano"].underground = '0';
mappages["volcano"].undergroundDesc = '';
mappages["volcano"].enterscript = '';
mappages["volcano"].entertestscript = '';
mappages["volcano"].exitscript = '';
mappages["volcano"].exittestscript = '';
mappages["volcano"].returnmap = 'darkunknown';
mappages["volcano"].returnx = '69';
mappages["volcano"].returny = '74';
mappages["volcano"].returninfused = '1';
mappages["volcano"].linkedMaps = [""];
mappages["volcano"].editorLabels = '{}';
// MAP ENDS HERE

mappages["volcano"].onload = function(mapref) {
  
  if (gamestate.getMode() !== "loadgame") {
    let shrinetile = mapref.getTile(11,34);
    let shrine = shrinetile.getTopFeature();
    shrine.gotomap = "island";
    shrine.gotox = 60;
    shrine.gotoy = 63;
  }
  
  CreateBeaches(mapref);
}

mappages["lavatubes"] = {};
mappages["lavatubes"].terrain = [];
 mappages["lavatubes"].terrain[0] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
 mappages["lavatubes"].terrain[1] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
 mappages["lavatubes"].terrain[2] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
 mappages["lavatubes"].terrain[3] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
 mappages["lavatubes"].terrain[4] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
 mappages["lavatubes"].terrain[5] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
 mappages["lavatubes"].terrain[6] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
 mappages["lavatubes"].terrain[7] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
 mappages["lavatubes"].terrain[8] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt lt lt lt lt lt lt F^ F^ F^ F^ lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
 mappages["lavatubes"].terrain[9] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt lt lt lt lt lt F^ F^ F^ F^ lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^';
mappages["lavatubes"].terrain[10] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^';
mappages["lavatubes"].terrain[11] = 'F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^';
mappages["lavatubes"].terrain[12] = 'F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^';
mappages["lavatubes"].terrain[13] = 'F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt lt lt lt F^ lt lt lt lt F^ F^ F^ F^ F^ F^';
mappages["lavatubes"].terrain[14] = 'F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt F^ F^ F^ F^ lt lt lt lt lt lt lt lt lt lt lt F^ F^ F^ lt lt lt lt lt F^ F^ F^ F^ F^';
mappages["lavatubes"].terrain[15] = 'F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt F^ F^ lt lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt F^ F^ F^ F^ F^';
mappages["lavatubes"].terrain[16] = 'F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt F^ F^ lt lt lt lt lt lt lt lt F^ F^ lt F^ F^ F^ F^ F^ F^ lt lt lt lt F^ F^ F^ F^ F^';
mappages["lavatubes"].terrain[17] = 'F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt F^ lt lt lt lt lt lt lt lt F^ F^ lt lt lt F^ F^ F^ F^ F^ lt lt lt lt F^ F^ F^ F^ F^';
mappages["lavatubes"].terrain[18] = 'F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt lt lt lt lt lt lt F^ F^ lt lt lt lt lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^';
mappages["lavatubes"].terrain[19] = 'F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt lt lt lt lt lt lt F^ F^ lt lt lt lt lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^';
mappages["lavatubes"].terrain[20] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt lt lt lt lt F^ F^ F^ F^ lt lt lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^';
mappages["lavatubes"].terrain[21] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^';
mappages["lavatubes"].terrain[22] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
mappages["lavatubes"].terrain[23] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
mappages["lavatubes"].terrain[24] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
mappages["lavatubes"].terrain[25] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
mappages["lavatubes"].terrain[26] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
mappages["lavatubes"].terrain[27] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
mappages["lavatubes"].terrain[28] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
mappages["lavatubes"].terrain[29] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';

mappages["lavatubes"].features = [];
mappages["lavatubes"].features[0] = {name : 'LadderUp', x : 27, y : 18, entermap : 'volcano', enterx : 27, entery : 21};
mappages["lavatubes"].features[1] = {name : 'LadderDown', x : 21, y : 8, entermap : 'deeplava', enterx : 21, entery : 8};


mappages["lavatubes"].npcs = [];
mappages["lavatubes"].npcs[0] = {name : 'FireLizardNPC', x : 35, y : 14, skintone: '1'};
mappages["lavatubes"].npcs[1] = {name : 'FireLizardNPC', x : 31, y : 11, skintone: '1'};
mappages["lavatubes"].npcs[2] = {name : 'FireSnakeNPC', x : 20, y : 15, skintone: '1'};
mappages["lavatubes"].npcs[3] = {name : 'FireSnakeNPC', x : 11, y : 19, skintone: '1'};
mappages["lavatubes"].npcs[4] = {name : 'FireElementalNPC', x : 14, y : 8, skintone: '1'};

mappages["lavatubes"].desc = "Lava Tubes";
mappages["lavatubes"].longdesc = 'As you descend into the lava tubes, the heat is intense. Surely this volcano is extinct...';
mappages["lavatubes"].music = 'Cave';
mappages["lavatubes"].savename = `Lava Tubes`;
mappages["lavatubes"].exitmap = 'volcano';
mappages["lavatubes"].exitx = '27';
mappages["lavatubes"].exity = '21';
mappages["lavatubes"].wraps = '';
mappages["lavatubes"].enterx = '27';
mappages["lavatubes"].entery = '18';
mappages["lavatubes"].seeBelow = '';
mappages["lavatubes"].lightLevel = 'dark';
mappages["lavatubes"].alwaysRemember = '0';
mappages["lavatubes"].scale = '1';
mappages["lavatubes"].underground = '1';
mappages["lavatubes"].undergroundDesc = 'Lava Tubes';
mappages["lavatubes"].enterscript = '';
mappages["lavatubes"].entertestscript = '';
mappages["lavatubes"].exitscript = '';
mappages["lavatubes"].exittestscript = '';
mappages["lavatubes"].returnmap = 'volcano';
mappages["lavatubes"].returnx = '27';
mappages["lavatubes"].returny = '21';
mappages["lavatubes"].returninfused = '0';
mappages["lavatubes"].linkedMaps = ["deeplavatubes"];
mappages["lavatubes"].editorLabels = '{}';

mappages["lavatubes"].onload = function(mapref) {
  if ((gamestate.getMode() !== "loadgame") && (!DU.gameflags.getFlag("editor"))) { 
    let spawn = localFactory.createTile("Spawner");
    let spawngroup = ["FireLizardNPC"];

    spawn.setSpawngroup(spawngroup);
    spawn.setMaxSpawns(3);
    spawn.setSpawnRadius(3);

    let freq = 90 + Dice.roll("1d20");
    spawn.setSpawnFreq(freq);
  
    mapref.placeThing(32,11,spawn);


    spawn = localFactory.createTile("Spawner");
    spawngroup = ["FireLizardNPC"];

    spawn.setSpawngroup(spawngroup);
    spawn.setMaxSpawns(3);
    spawn.setSpawnRadius(3);

    freq = 90 + Dice.roll("1d20");
    spawn.setSpawnFreq(freq);
  
    mapref.placeThing(11,11,spawn);
  }
}

// MAP BEGINS HERE
mappages["deeplavatubes"] = {};
mappages["deeplavatubes"].terrain = [];
 mappages["deeplavatubes"].terrain[0] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
 mappages["deeplavatubes"].terrain[1] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
 mappages["deeplavatubes"].terrain[2] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
 mappages["deeplavatubes"].terrain[3] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
 mappages["deeplavatubes"].terrain[4] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt F^ F^ F^ F^ lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
 mappages["deeplavatubes"].terrain[5] = 'F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^';
 mappages["deeplavatubes"].terrain[6] = 'F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt lt lt lt lt lt lt lt lt lt lt lt lt lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^';
 mappages["deeplavatubes"].terrain[7] = 'F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^';
 mappages["deeplavatubes"].terrain[8] = 'F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ lt lt F^ lt lt lt lt F^ F^ F^ F^ F^ F^';
 mappages["deeplavatubes"].terrain[9] = 'F^ F^ F^ F^ lt lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[10] = 'F^ F^ F^ F^ lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[11] = 'F^ F^ F^ F^ F^ lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt F^ F^ F^ F^ F^ lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[12] = 'F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[13] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt lt F^ F^ F^ F^ lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[14] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt lt lt lt F^ F^ lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[15] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt F^ F^ lt lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[16] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt F^ F^ F^ F^ F^ lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[17] = 'F^ F^ F^ F^ F^ lt lt F^ F^ F^ F^ F^ F^ F^ lt lt lt lt F^ F^ F^ F^ F^ F^ F^ lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[18] = 'F^ F^ F^ F^ F^ lt lt lt F^ F^ F^ F^ lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[19] = 'F^ F^ F^ F^ F^ lt lt lt lt lt F^ lt lt lt lt F^ F^ F^ F^ F^ F^ lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[20] = 'F^ F^ F^ F^ lt lt lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[21] = 'F^ F^ F^ lt lt lt lt lt lt lt lt lt lt lt F^ F^ F^ F^ lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[22] = 'F^ F^ F^ lt lt lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[23] = 'F^ F^ F^ lt lt lt lt lt F^ lt lt F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt F^ F^ F^ F^ F^ lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[24] = 'F^ F^ F^ lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt F^ F^ F^ F^ F^ lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[25] = 'F^ F^ F^ lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt F^ F^ F^ F^ lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[26] = 'F^ F^ F^ F^ lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt F^ F^ lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[27] = 'F^ F^ F^ F^ F^ lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[28] = 'F^ F^ F^ F^ F^ lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[29] = 'F^ F^ F^ F^ F^ lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[30] = 'F^ F^ F^ F^ F^ lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[31] = 'F^ F^ F^ F^ F^ F^ F^ lt lt lt lt F^ F^ F^ lt lt lt lt lt lt lt lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[32] = 'F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt lt lt lt lt lt lt lt lt F^ F^ lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[33] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ lt lt lt F^ F^ lt lt F^ F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[34] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[35] = 'F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[36] = 'F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ lt lt F^ lt lt F^ F^ F^ lt lt lt lt lt lt lt F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[37] = 'F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt F^ F^ F^ lt lt lt lt lt lt F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[38] = 'F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt F^ F^ F^ F^ F^ lt lt lt lt lt lt F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[39] = 'F^ F^ F^ F^ F^ lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt F^ F^ F^ lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[40] = 'F^ F^ F^ F^ F^ lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[41] = 'F^ F^ F^ F^ F^ F^ F^ lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ lt lt lt lt lt lt lt lt lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[42] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ lt F^ F^ F^ lt lt lt F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[43] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';
mappages["deeplavatubes"].terrain[44] = 'F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^ F^';

mappages["deeplavatubes"].features = [];
mappages["deeplavatubes"].features[0] = {name : 'LadderUp', x : 26, y : 16, entermap : 'lavatubes', enterx : 21, entery : 8};
mappages["deeplavatubes"].features[1] = {name : 'WallOfFlames', x : 20, y : 22};
mappages["deeplavatubes"].features[2] = {name : 'SulfurousAsh', x : 7, y : 7};
mappages["deeplavatubes"].features[3] = {name : 'SulfurousAsh', x : 8, y : 10};
mappages["deeplavatubes"].features[4] = {name : 'SulfurousAsh', x : 6, y : 19};
mappages["deeplavatubes"].features[5] = {name : 'SulfurousAsh', x : 5, y : 24};
mappages["deeplavatubes"].features[6] = {name : 'SulfurousAsh', x : 10, y : 33};
mappages["deeplavatubes"].features[7] = {name : 'SulfurousAsh', x : 8, y : 38};
mappages["deeplavatubes"].features[8] = {name : 'SulfurousAsh', x : 8, y : 41};
mappages["deeplavatubes"].features[9] = {name : 'SulfurousAsh', x : 23, y : 38};
mappages["deeplavatubes"].features[10] = {name : 'SulfurousAsh', x : 21, y : 40};
mappages["deeplavatubes"].features[11] = {name : 'SulfurousAsh', x : 23, y : 24};
mappages["deeplavatubes"].features[12] = {name : 'Lava', x : 11, y : 11};
mappages["deeplavatubes"].features[13] = {name : 'Lava', x : 11, y : 12};
mappages["deeplavatubes"].features[14] = {name : 'Lava', x : 10, y : 12};
mappages["deeplavatubes"].features[15] = {name : 'Lava', x : 9, y : 12};
mappages["deeplavatubes"].features[16] = {name : 'Lava', x : 8, y : 12};
mappages["deeplavatubes"].features[17] = {name : 'Lava', x : 7, y : 12};
mappages["deeplavatubes"].features[18] = {name : 'Lava', x : 6, y : 12};
mappages["deeplavatubes"].features[19] = {name : 'Lava', x : 6, y : 11};
mappages["deeplavatubes"].features[20] = {name : 'Lava', x : 5, y : 11};
mappages["deeplavatubes"].features[21] = {name : 'Lava', x : 7, y : 11};
mappages["deeplavatubes"].features[22] = {name : 'Lava', x : 8, y : 11};
mappages["deeplavatubes"].features[23] = {name : 'Lava', x : 9, y : 11};
mappages["deeplavatubes"].features[24] = {name : 'Lava', x : 10, y : 11};
mappages["deeplavatubes"].features[25] = {name : 'Lava', x : 4, y : 10};
mappages["deeplavatubes"].features[26] = {name : 'Lava', x : 5, y : 10};
mappages["deeplavatubes"].features[27] = {name : 'Lava', x : 6, y : 10};
mappages["deeplavatubes"].features[28] = {name : 'Lava', x : 7, y : 10};
mappages["deeplavatubes"].features[29] = {name : 'Lava', x : 4, y : 9};
mappages["deeplavatubes"].features[30] = {name : 'Lava', x : 5, y : 9};
mappages["deeplavatubes"].features[31] = {name : 'Lava', x : 5, y : 8};
mappages["deeplavatubes"].features[32] = {name : 'Lava', x : 5, y : 7};
mappages["deeplavatubes"].features[33] = {name : 'Lava', x : 6, y : 7};
mappages["deeplavatubes"].features[34] = {name : 'Lava', x : 6, y : 6};
mappages["deeplavatubes"].features[35] = {name : 'Lava', x : 7, y : 6};
mappages["deeplavatubes"].features[36] = {name : 'Lava', x : 8, y : 6};
mappages["deeplavatubes"].features[37] = {name : 'Lava', x : 8, y : 5};
mappages["deeplavatubes"].features[38] = {name : 'Lava', x : 9, y : 5};
mappages["deeplavatubes"].features[39] = {name : 'Lava', x : 7, y : 5};
mappages["deeplavatubes"].features[40] = {name : 'Lava', x : 6, y : 18};
mappages["deeplavatubes"].features[41] = {name : 'Lava', x : 6, y : 17};
mappages["deeplavatubes"].features[42] = {name : 'Lava', x : 5, y : 17};
mappages["deeplavatubes"].features[43] = {name : 'Lava', x : 5, y : 18};
mappages["deeplavatubes"].features[44] = {name : 'Lava', x : 5, y : 19};
mappages["deeplavatubes"].features[45] = {name : 'Lava', x : 5, y : 20};
mappages["deeplavatubes"].features[46] = {name : 'Lava', x : 4, y : 20};
mappages["deeplavatubes"].features[47] = {name : 'Lava', x : 4, y : 21};
mappages["deeplavatubes"].features[48] = {name : 'Lava', x : 4, y : 22};
mappages["deeplavatubes"].features[49] = {name : 'Lava', x : 3, y : 22};
mappages["deeplavatubes"].features[50] = {name : 'Lava', x : 3, y : 21};
mappages["deeplavatubes"].features[51] = {name : 'Lava', x : 5, y : 22};
mappages["deeplavatubes"].features[52] = {name : 'Lava', x : 5, y : 21};
mappages["deeplavatubes"].features[53] = {name : 'Lava', x : 4, y : 23};
mappages["deeplavatubes"].features[54] = {name : 'Lava', x : 5, y : 12};
mappages["deeplavatubes"].features[55] = {name : 'Lava', x : 6, y : 13};
mappages["deeplavatubes"].features[56] = {name : 'Lava', x : 7, y : 13};
mappages["deeplavatubes"].features[57] = {name : 'Lava', x : 8, y : 13};
mappages["deeplavatubes"].features[58] = {name : 'Lava', x : 7, y : 14};
mappages["deeplavatubes"].features[59] = {name : 'Lava', x : 6, y : 14};
mappages["deeplavatubes"].features[60] = {name : 'Lava', x : 6, y : 15};
mappages["deeplavatubes"].features[61] = {name : 'Lava', x : 6, y : 16};
mappages["deeplavatubes"].features[62] = {name : 'Lava', x : 7, y : 16};
mappages["deeplavatubes"].features[63] = {name : 'Lava', x : 8, y : 16};
mappages["deeplavatubes"].features[64] = {name : 'Lava', x : 8, y : 15};
mappages["deeplavatubes"].features[65] = {name : 'Lava', x : 7, y : 15};
mappages["deeplavatubes"].features[66] = {name : 'Lava', x : 5, y : 16};
mappages["deeplavatubes"].features[67] = {name : 'Lava', x : 7, y : 17};
mappages["deeplavatubes"].features[68] = {name : 'Lava', x : 4, y : 24};
mappages["deeplavatubes"].features[69] = {name : 'Lava', x : 4, y : 25};
mappages["deeplavatubes"].features[70] = {name : 'Lava', x : 5, y : 25};
mappages["deeplavatubes"].features[71] = {name : 'Lava', x : 5, y : 26};
mappages["deeplavatubes"].features[72] = {name : 'Lava', x : 5, y : 27};
mappages["deeplavatubes"].features[73] = {name : 'Lava', x : 6, y : 27};
mappages["deeplavatubes"].features[74] = {name : 'Lava', x : 6, y : 28};
mappages["deeplavatubes"].features[75] = {name : 'Lava', x : 7, y : 28};
mappages["deeplavatubes"].features[76] = {name : 'Lava', x : 6, y : 29};
mappages["deeplavatubes"].features[77] = {name : 'Lava', x : 5, y : 29};
mappages["deeplavatubes"].features[78] = {name : 'Lava', x : 5, y : 30};
mappages["deeplavatubes"].features[79] = {name : 'Lava', x : 6, y : 30};
mappages["deeplavatubes"].features[80] = {name : 'Lava', x : 7, y : 30};
mappages["deeplavatubes"].features[81] = {name : 'Lava', x : 8, y : 30};
mappages["deeplavatubes"].features[82] = {name : 'Lava', x : 8, y : 29};
mappages["deeplavatubes"].features[83] = {name : 'Lava', x : 9, y : 30};
mappages["deeplavatubes"].features[84] = {name : 'Lava', x : 7, y : 29};
mappages["deeplavatubes"].features[85] = {name : 'Lava', x : 3, y : 23};
mappages["deeplavatubes"].features[86] = {name : 'Lava', x : 3, y : 24};
mappages["deeplavatubes"].features[87] = {name : 'Lava', x : 3, y : 25};
mappages["deeplavatubes"].features[88] = {name : 'Lava', x : 4, y : 26};
mappages["deeplavatubes"].features[89] = {name : 'Lava', x : 5, y : 28};
mappages["deeplavatubes"].features[90] = {name : 'Lava', x : 8, y : 31};
mappages["deeplavatubes"].features[91] = {name : 'Lava', x : 8, y : 32};
mappages["deeplavatubes"].features[92] = {name : 'Lava', x : 9, y : 32};
mappages["deeplavatubes"].features[93] = {name : 'Lava', x : 9, y : 31};
mappages["deeplavatubes"].features[94] = {name : 'Lava', x : 10, y : 31};
mappages["deeplavatubes"].features[95] = {name : 'Lava', x : 10, y : 32};
mappages["deeplavatubes"].features[96] = {name : 'Lava', x : 9, y : 33};
mappages["deeplavatubes"].features[97] = {name : 'Lava', x : 9, y : 34};
mappages["deeplavatubes"].features[98] = {name : 'Lava', x : 9, y : 35};
mappages["deeplavatubes"].features[99] = {name : 'Lava', x : 8, y : 35};
mappages["deeplavatubes"].features[100] = {name : 'Lava', x : 8, y : 36};
mappages["deeplavatubes"].features[101] = {name : 'Lava', x : 7, y : 36};
mappages["deeplavatubes"].features[102] = {name : 'Lava', x : 7, y : 37};
mappages["deeplavatubes"].features[103] = {name : 'Lava', x : 6, y : 37};
mappages["deeplavatubes"].features[104] = {name : 'Lava', x : 6, y : 36};
mappages["deeplavatubes"].features[105] = {name : 'Lava', x : 6, y : 38};
mappages["deeplavatubes"].features[106] = {name : 'Lava', x : 7, y : 38};
mappages["deeplavatubes"].features[107] = {name : 'Lava', x : 7, y : 39};
mappages["deeplavatubes"].features[108] = {name : 'Lava', x : 6, y : 39};
mappages["deeplavatubes"].features[109] = {name : 'Lava', x : 6, y : 40};
mappages["deeplavatubes"].features[110] = {name : 'Lava', x : 7, y : 40};
mappages["deeplavatubes"].features[111] = {name : 'Lava', x : 5, y : 38};
mappages["deeplavatubes"].features[112] = {name : 'Lava', x : 5, y : 39};
mappages["deeplavatubes"].features[113] = {name : 'Lava', x : 5, y : 40};
mappages["deeplavatubes"].features[114] = {name : 'Lava', x : 7, y : 41};
mappages["deeplavatubes"].features[115] = {name : 'Lava', x : 26, y : 36};
mappages["deeplavatubes"].features[116] = {name : 'Lava', x : 25, y : 36};
mappages["deeplavatubes"].features[117] = {name : 'Lava', x : 25, y : 37};
mappages["deeplavatubes"].features[118] = {name : 'Lava', x : 26, y : 37};
mappages["deeplavatubes"].features[119] = {name : 'Lava', x : 24, y : 37};
mappages["deeplavatubes"].features[120] = {name : 'Lava', x : 23, y : 37};
mappages["deeplavatubes"].features[121] = {name : 'Lava', x : 23, y : 36};
mappages["deeplavatubes"].features[122] = {name : 'Lava', x : 22, y : 36};
mappages["deeplavatubes"].features[123] = {name : 'Lava', x : 22, y : 37};
mappages["deeplavatubes"].features[124] = {name : 'Lava', x : 21, y : 37};
mappages["deeplavatubes"].features[125] = {name : 'Lava', x : 21, y : 38};
mappages["deeplavatubes"].features[126] = {name : 'Lava', x : 21, y : 39};
mappages["deeplavatubes"].features[127] = {name : 'Lava', x : 20, y : 39};
mappages["deeplavatubes"].features[128] = {name : 'Lava', x : 19, y : 39};
mappages["deeplavatubes"].features[129] = {name : 'Lava', x : 19, y : 40};
mappages["deeplavatubes"].features[130] = {name : 'Lava', x : 18, y : 40};
mappages["deeplavatubes"].features[131] = {name : 'Lava', x : 19, y : 38};
mappages["deeplavatubes"].features[132] = {name : 'Lava', x : 20, y : 38};
mappages["deeplavatubes"].features[133] = {name : 'Lava', x : 20, y : 40};
mappages["deeplavatubes"].features[134] = {name : 'Lava', x : 22, y : 38};
mappages["deeplavatubes"].features[135] = {name : 'Lava', x : 23, y : 22};
mappages["deeplavatubes"].features[136] = {name : 'Lava', x : 22, y : 22};
mappages["deeplavatubes"].features[137] = {name : 'Lava', x : 22, y : 21};
mappages["deeplavatubes"].features[138] = {name : 'Lava', x : 22, y : 20};
mappages["deeplavatubes"].features[139] = {name : 'Lava', x : 22, y : 19};
mappages["deeplavatubes"].features[140] = {name : 'Lava', x : 21, y : 19};
mappages["deeplavatubes"].features[141] = {name : 'Lava', x : 21, y : 20};
mappages["deeplavatubes"].features[142] = {name : 'Lava', x : 20, y : 20};
mappages["deeplavatubes"].features[143] = {name : 'Lava', x : 19, y : 21};
mappages["deeplavatubes"].features[144] = {name : 'Lava', x : 18, y : 21};
mappages["deeplavatubes"].features[145] = {name : 'Lava', x : 18, y : 22};
mappages["deeplavatubes"].features[146] = {name : 'Lava', x : 18, y : 23};
mappages["deeplavatubes"].features[147] = {name : 'Lava', x : 18, y : 24};
mappages["deeplavatubes"].features[148] = {name : 'Lava', x : 17, y : 24};
mappages["deeplavatubes"].features[149] = {name : 'Lava', x : 19, y : 20};
mappages["deeplavatubes"].features[150] = {name : 'Lava', x : 19, y : 22};
mappages["deeplavatubes"].features[151] = {name : 'Lava', x : 19, y : 23};
mappages["deeplavatubes"].features[152] = {name : 'Lava', x : 19, y : 24};
mappages["deeplavatubes"].features[153] = {name : 'Lava', x : 19, y : 25};
mappages["deeplavatubes"].features[154] = {name : 'Lava', x : 20, y : 21};
mappages["deeplavatubes"].features[155] = {name : 'Lava', x : 21, y : 21};
mappages["deeplavatubes"].features[156] = {name : 'Lava', x : 21, y : 22};
mappages["deeplavatubes"].features[157] = {name : 'Lava', x : 22, y : 23};
mappages["deeplavatubes"].features[158] = {name : 'Lava', x : 23, y : 23};
mappages["deeplavatubes"].features[159] = {name : 'Lava', x : 7, y : 31};


mappages["deeplavatubes"].npcs = [];
mappages["deeplavatubes"].npcs[0] = {name : 'MagmaSpawnNPC', x : 7, y : 21, skintone: '1'};
mappages["deeplavatubes"].npcs[1] = {name : 'MagmaSpawnNPC', x : 8, y : 8, skintone: '1'};
mappages["deeplavatubes"].npcs[2] = {name : 'MagmaSpawnNPC', x : 22, y : 27, skintone: '1'};
mappages["deeplavatubes"].npcs[3] = {name : 'MagmaSpawnNPC', x : 24, y : 40, skintone: '1'};
mappages["deeplavatubes"].npcs[4] = {name : 'DrakeNPC', x : 9, y : 39, skintone: '1'};
mappages["deeplavatubes"].npcs[5] = {name : 'DrakeNPC', x : 10, y : 35, skintone: '1'};
mappages["deeplavatubes"].npcs[6] = {name : 'DrakeNPC', x : 30, y : 5, skintone: '1'};

mappages["deeplavatubes"].desc = "Deep Lava Tubes";
mappages["deeplavatubes"].longdesc = ``;
mappages["deeplavatubes"].music = 'Cave';
mappages["deeplavatubes"].savename = `Lava Tubes`;
mappages["deeplavatubes"].exitmap = '';
mappages["deeplavatubes"].exitx = '65';
mappages["deeplavatubes"].exity = '70';
mappages["deeplavatubes"].wraps = '';
mappages["deeplavatubes"].enterx = '21';
mappages["deeplavatubes"].entery = '8';
mappages["deeplavatubes"].seeBelow = '';
mappages["deeplavatubes"].lightLevel = 'dark';
mappages["deeplavatubes"].alwaysRemember = '0';
mappages["deeplavatubes"].scale = '1';
mappages["deeplavatubes"].underground = '1';
mappages["deeplavatubes"].undergroundDesc = 'Deep Lava Tubes';
mappages["deeplavatubes"].enterscript = '';
mappages["deeplavatubes"].entertestscript = '';
mappages["deeplavatubes"].exitscript = '';
mappages["deeplavatubes"].exittestscript = '';
mappages["deeplavatubes"].returnmap = 'volcano';
mappages["deeplavatubes"].returnx = '27';
mappages["deeplavatubes"].returny = '21';
mappages["deeplavatubes"].returninfused = '0';
mappages["deeplavatubes"].linkedMaps = ["lavatubes"];
mappages["deeplavatubes"].editorLabels = '{}';
// MAP ENDS HERE

mappages["deeplavatubes"].onload = function(mapref) {
  if ((gamestate.getMode() !== "loadgame") && (!DU.gameflags.getFlag("editor"))) { 
    let spawn = localFactory.createTile("Spawner");
    let spawngroup = ["FireLizardNPC", "DrakeNPC"];

    spawn.setSpawngroup(spawngroup);
    spawn.setMaxSpawns(3);
    spawn.setSpawnRadius(3);

    let freq = 90 + Dice.roll("1d20");
    spawn.setSpawnFreq(freq);
  
    mapref.placeThing(21,5,spawn);

    spawn = localFactory.createTile("Spawner");
    spawngroup = ["FireLizardNPC", "DrakeNPC"];

    spawn.setSpawngroup(spawngroup);
    spawn.setMaxSpawns(3);
    spawn.setSpawnRadius(3);

    freq = 90 + Dice.roll("1d20");
    spawn.setSpawnFreq(freq);
  
    mapref.placeThing(33,36,spawn);

  }
}