"use strict";

mappages["worldsending1"] = {};
mappages["worldsending1"].terrain = [];
 mappages["worldsending1"].terrain[0] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["worldsending1"].terrain[1] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["worldsending1"].terrain[2] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["worldsending1"].terrain[3] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["worldsending1"].terrain[4] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["worldsending1"].terrain[5] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["worldsending1"].terrain[6] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["worldsending1"].terrain[7] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["worldsending1"].terrain[8] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["worldsending1"].terrain[9] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[10] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[11] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[12] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[13] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[14] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[15] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[16] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[17] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ## ## ## ## ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[18] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ## ## ++ ## ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[19] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ## ## ## ## ## ## ## ## ## ++ ++ ++ ## ## ## ## ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[20] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[21] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ## ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ## ++ ++ ++ ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[22] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ## ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ## ++ ++ ++ ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[23] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ## ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ## ## ## ## ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[24] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ## ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[25] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ## ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[26] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ## ## ## ## ## ## ## ## ## #O ++ #O ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[27] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ## p* p* p* ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[28] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ## p* p* p* ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[29] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ## p* p* p* ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[30] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ## p* p* p* ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[31] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ## p* p* p* ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[32] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ## p* p* p* ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[33] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ## ## p* ## ## ## p* ## ## ## p* ## ## ## p* ## ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[34] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ## p* p* p* ## p* p* p* ## p* p* p* ## p* p* p* ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[35] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ## p* p* p* ## p* p* p* ## p* p* p* ## p* p* p* ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[36] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ## p* p* p* ## p* p* p* ## p* p* p* ## p* p* p* ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[37] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ## p* p* p* ## p* p* p* ## p* p* p* ## p* p* p* ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[38] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ## p* p* p* ## p* p* p* ## p* p* p* ## p* p* p* ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[39] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ## p* p* p* ## p* p* p* ## p* p* p* ## p* p* p* ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[40] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw ## p* p* p* ## p* p* p* ## p* p* p* ## p* p* p* ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cf cf cf cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[41] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw ## p* p* p* ## p* p* p* ## p* p* p* ## p* p* p* ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[42] = 'BK BK BK BK BK BK !# !# !# !# !# !# !# BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cf ## p* p* p* ## p* p* p* ## p* p* p* ## p* p* p* ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[43] = 'BK BK BK BK BK BK !# p* p* p* p* p* !# BK BK cw cw cw cw BK BK BK BK cw cw cf cw cf p* ## ## p* ## ## ## p* ## ## ## p* ## ## ## p* ## ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cf cw cw cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[44] = 'BK BK BK BK BK BK !# p* p* p* p* p* !# cw cw cw cf cf cw cw cw cw cw cw cf p* cf cf p* ## p* p* p* p* p* p* p* p* p* p* p* ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cw cw cf cf cf cf cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[45] = 'BK BK BK BK BK BK !# p* p* p* p* p* i# cf cf cf cf cf cf cf cf cf cf cf cf cf cf p* cf p* p* p* p* p* p* p* p* p* p* p* p* ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cf cf cf cw cw cw cw cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[46] = 'BK BK BK BK BK BK !# p* p* p* p* p* !# cw cw cw cf cf cf cf cf cf cf cf p* cf cf cf cf ## p* p* p* p* p* p* p* p* p* p* p* ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cw BK BK cw cw cf cf cf cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[47] = 'BK BK BK BK BK BK !# p* p* p* p* p* !# BK BK cw cw cf cf cf cf cw cw cf cf cf p* p* p* ## ## p* ## ## ## p* ## ## ## p* ## ## ## p* ## ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cw cw BK BK BK cw cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[48] = 'BK BK BK BK BK BK !# !# !# !# !# !# !# BK BK BK cw cw cw cw cw cw cw cw cw cf cf cf p* ## p* p* p* ## p* p* p* ## p* p* p* ## p* p* p* ## BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[49] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw ## p* p* p* ## p* p* p* ## p* p* p* ## p* p* p* ## BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[50] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw ## p* p* p* ## p* p* p* ## p* p* p* ## p* p* p* ## BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[51] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ## p* p* p* ## p* p* p* ## p* p* p* ## p* p* p* ## BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[52] = 'BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK ## p* p* p* ## p* p* p* ## p* p* p* ## p* p* p* ## BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[53] = 'BK BK BK BK BK BK BK BK BK BK BK cw cw cf cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK ## p* p* p* ## p* p* p* ## p* p* p* ## p* p* p* ## BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[54] = 'BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK ## p* p* p* ## p* p* p* ## p* p* p* ## p* p* p* ## BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cf cf cf cf cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[55] = 'BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK ## p* p* p* ## p* p* p* ## p* p* p* ## p* p* p* ## BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cf cf cf cf cf cf cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[56] = 'BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK ## p* p* p* ## p* p* p* ## p* p* p* ## p* p* p* ## BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw cw cf cf cf cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[57] = 'BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK ## ## p* ## ## ## p* ## ## ## p* ## ## ## p* ## ## BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cw cw cw cw cf cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[58] = 'BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ## p* p* p* ## BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw cw BK BK cw cw cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[59] = 'BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ## p* p* p* ## BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cw cw BK BK BK BK cw cw cw cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[60] = 'BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ## p* p* p* ## BK BK BK BK BK BK BK BK cw cw cw cf cf cf cf cw BK BK BK BK BK BK BK cw cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[61] = 'BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ## p* p* p* ## BK BK BK BK BK BK BK cw cw cf cf cf cf cf cw cw BK BK BK BK BK BK cw cw cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[62] = 'BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ## p* p* p* ## BK BK BK BK BK BK BK cw cf cf cf cf cf cf cw BK BK BK BK BK BK BK cw cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[63] = 'BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf p* cf cw cw BK BK BK BK BK BK cw cf cf cf cf cf cw cw BK BK BK BK BK BK cw cw cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[64] = 'BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cf cf cw cw cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw p* cf cf cf cw cw BK BK BK BK BK cw cf cf cf cf cf cw BK BK BK BK BK BK BK cw cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[65] = 'BK BK BK BK BK BK BK cw cw cw cw cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cw cw cw cw BK BK BK BK BK BK BK BK BK cw cw cf cf cf p* cf cf cw BK BK BK BK BK cw cw cf cf cw cw cw BK BK BK BK BK BK cw cw cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[66] = 'BK BK BK BK cw cw cw cw cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK cw cf cf p* cf cf cf cf cw cw BK BK BK BK BK cw cw cw cw BK BK BK BK BK BK BK BK cw cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[67] = 'BK BK BK BK cw cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK cw p* cf cf cf cf p* cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[68] = 'BK BK BK BK cw cw cf cf cf cf cf cf cw cw cw cf cw cw cw cf cf cw cf cf cw cw cf cf cf cf cw cw BK BK BK BK BK BK BK cw cw cf cf cf cf cf cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[69] = 'BK BK BK BK BK cw cw cw cf cf cf cf cw BK cw cw cw BK cw cw cw cw cw cw cw cw cw cf cf cf cf cw BK BK BK BK BK BK BK BK cw cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[70] = 'BK BK BK BK BK BK BK cw cw cf cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cw BK BK BK BK BK BK BK BK cw cw cw cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[71] = 'BK BK BK BK BK BK BK BK cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cw BK BK BK BK BK cw cw cw cw cw cw BK BK BK BK cw cw cw cf cf cf cf cf cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[72] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cw BK BK BK cw cw cw cw cw BK cw cw cf cf cf cf cw cw cw cw BK BK cw cw cf cf cf cf cw BK BK BK cw cw cf cf cf cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[73] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cw cw cw cw cw cf cf cf cw cw cw cf cf cf cf cf cf cf cf cw cw cw cw cf cf cf cf cf cw cw cw cw cw cf cf cf cf cf cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[74] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cw cw cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cw cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[75] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[76] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cf cf cf cf cf cf cf cf cf cw cw cw cw cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cw cw cf cf cf cf cw cw cw cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[77] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cf cf cf cf cf cf cw cw BK BK cw cw cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cw cw cw cw cw cw cw cw BK cw cw cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[78] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw cw cw cf cf cf cf cf cf cf cf cf cf cf cw cw cw cw BK BK BK BK cw cw cf cf cf cf cf cf cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK cw cw cw cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[79] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cw cf cf cf cf cf cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK cw cw cw cf cf cf cf cf cf cf cf cf cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[80] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[81] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[82] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cf cf cf cf cw cw cw cw cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[83] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cf cf cf cf cf cf cw cw BK BK cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cw cw cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[84] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[85] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cf cf cf cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[86] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[87] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[88] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cf cf cf cf cf cf cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[89] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cf cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[90] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cf cf cf cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[91] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK cw cw cw cw cw BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[92] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[93] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[94] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[95] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[96] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[97] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[98] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["worldsending1"].terrain[99] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';

mappages["worldsending1"].features = [];
mappages["worldsending1"].features[0] = {name : 'LadderUp', x : 9, y : 45, entermap : 'darkunknown', enterx : 27, entery : 44};
mappages["worldsending1"].features[1] = {name : 'DoorWindow', x : 29, y : 45};
mappages["worldsending1"].features[2] = {name : 'UnlitWEBrazier', x : 7, y : 43};
mappages["worldsending1"].features[3] = {name : 'UnlitWEBrazier', x : 7, y : 47};
mappages["worldsending1"].features[4] = {name : 'UnlitWEBrazier', x : 11, y : 47};
mappages["worldsending1"].features[5] = {name : 'UnlitWEBrazier', x : 11, y : 43};
mappages["worldsending1"].features[6] = {name : 'Door', x : 39, y : 33};
mappages["worldsending1"].features[7] = {name : 'Door', x : 35, y : 33};
mappages["worldsending1"].features[8] = {name : 'Door', x : 31, y : 33};
mappages["worldsending1"].features[9] = {name : 'Door', x : 31, y : 57};
mappages["worldsending1"].features[10] = {name : 'Door', x : 35, y : 57};
mappages["worldsending1"].features[11] = {name : 'Door', x : 39, y : 57};
mappages["worldsending1"].features[12] = {name : 'Door', x : 43, y : 33};
mappages["worldsending1"].features[13] = {name : 'Door', x : 43, y : 57};
mappages["worldsending1"].features[14] = {name : 'Door', x : 101, y : 99};
mappages["worldsending1"].features[15] = {name : 'IllusionaryEnergyField', x : 12, y : 45};
mappages["worldsending1"].features[16] = {name : 'Door', x : 43, y : 26};
mappages["worldsending1"].features[17] = {name : 'Door', x : 45, y : 20};
mappages["worldsending1"].features[18] = {name : 'Door', x : 41, y : 20};
mappages["worldsending1"].features[19] = {name : 'DustyFireplace', x : 43, y : 18};
mappages["worldsending1"].features[20] = {name : 'BookshelfLeft', x : 34, y : 20, lootedid : 'spirescrap', searchyield : 'SpireScrap'};
mappages["worldsending1"].features[21] = {name : 'BookshelfRight', x : 35, y : 20};
mappages["worldsending1"].features[22] = {name : 'LeftTable', x : 35, y : 22};
mappages["worldsending1"].features[23] = {name : 'MiddleTable', x : 36, y : 22};
mappages["worldsending1"].features[24] = {name : 'MiddleTable', x : 37, y : 22};
mappages["worldsending1"].features[25] = {name : 'RightTable', x : 38, y : 22};
mappages["worldsending1"].features[26] = {name : 'SmallTable', x : 40, y : 25};
mappages["worldsending1"].features[27] = {name : 'TopChair', x : 40, y : 24};
mappages["worldsending1"].features[28] = {name : 'LeftChair', x : 39, y : 25};
mappages["worldsending1"].features[29] = {name : 'BottomChair', x : 36, y : 23};
mappages["worldsending1"].features[30] = {name : 'StairUp2', x : 48, y : 22, entermap : 'spire2', enterx : 18, entery : 18};
mappages["worldsending1"].features[31] = {name : 'Door', x : 43, y : 43};
mappages["worldsending1"].features[32] = {name : 'Door', x : 43, y : 47};
mappages["worldsending1"].features[33] = {name : 'Door', x : 39, y : 47};
mappages["worldsending1"].features[34] = {name : 'Door', x : 39, y : 43};
mappages["worldsending1"].features[35] = {name : 'Door', x : 35, y : 43};
mappages["worldsending1"].features[36] = {name : 'Door', x : 35, y : 47};
mappages["worldsending1"].features[37] = {name : 'Door', x : 31, y : 47};
mappages["worldsending1"].features[38] = {name : 'Door', x : 31, y : 43};
mappages["worldsending1"].features[39] = {name : 'UnlitBrazier', x : 34, y : 22};


mappages["worldsending1"].npcs = [];

mappages["worldsending1"].desc = "World's Ending (L1)";
mappages["worldsending1"].longdesc = ``;
mappages["worldsending1"].music = 'Dungeon';
mappages["worldsending1"].savename = `World's Ending`;
mappages["worldsending1"].exitmap = '';
mappages["worldsending1"].exitx = '65';
mappages["worldsending1"].exity = '70';
mappages["worldsending1"].wraps = '';
mappages["worldsending1"].enterx = '65';
mappages["worldsending1"].entery = '70';
mappages["worldsending1"].seeBelow = '';
mappages["worldsending1"].lightLevel = 'dark';
mappages["worldsending1"].alwaysRemember = '0';
mappages["worldsending1"].scale = '1';
mappages["worldsending1"].underground = '1';
mappages["worldsending1"].undergroundDesc = 'Level 1';
mappages["worldsending1"].enterscript = '';
mappages["worldsending1"].entertestscript = '';
mappages["worldsending1"].exitscript = '';
mappages["worldsending1"].exittestscript = '';
mappages["worldsending1"].returnmap = 'darkunknown';
mappages["worldsending1"].returnx = '27';
mappages["worldsending1"].returny = '44';
mappages["worldsending1"].returninfused = '0';
mappages["worldsending1"].linkedMaps = ["spire2","spire3"];
mappages["worldsending1"].editorLabels = '{}';

mappages["worldsending1"].onload = function(mapref) {
  if ((gamestate.getMode() !== "loadgame") && (!DU.gameflags.getFlag("editor"))) {
    WE_PlaceWalkon(mapref,31,34);
    WE_PlaceWalkon(mapref,35,34);
    WE_PlaceWalkon(mapref,39,34);
    WE_PlaceWalkon(mapref,31,56);
    WE_PlaceWalkon(mapref,35,56);
    WE_PlaceWalkon(mapref,39,56);
    WE_PlaceWalkon(mapref,43,48);
    WE_PlaceWalkon(mapref,43,42);
  }
}

function WE_PlaceWalkon(mapref, walkonx, walkony) {
  let walkontile = localFactory.createTile("WorldsEndingWalkOn");
  mapref.placeThing(walkonx, walkony, walkontile);
  let desty = 0;
  let destx = [31,35,39];
  if ((walkony === 34) || (walkony === 48)) { desty = 48; }
  if ((walkony === 56) || (walkony === 42)) { desty = 42; }
  walkontile.destx = destx;
  walkontile.desty = desty;
  
}

function CloseWEDoors(mapref) {
  let doorslist = [];
  doorslist[0] = mapref.getTile(31,33).getTopFeature();
  doorslist[1] = mapref.getTile(35,33).getTopFeature();
  doorslist[2] = mapref.getTile(39,33).getTopFeature();
  doorslist[3] = mapref.getTile(43,33).getTopFeature();
  doorslist[4] = mapref.getTile(31,43).getTopFeature();
  doorslist[5] = mapref.getTile(35,43).getTopFeature();
  doorslist[6] = mapref.getTile(39,43).getTopFeature();
  doorslist[7] = mapref.getTile(43,43).getTopFeature();
  doorslist[8] = mapref.getTile(31,47).getTopFeature();
  doorslist[9] = mapref.getTile(35,47).getTopFeature();
  doorslist[10] = mapref.getTile(39,47).getTopFeature();
  doorslist[11] = mapref.getTile(43,47).getTopFeature();
  doorslist[12] = mapref.getTile(31,57).getTopFeature();
  doorslist[13] = mapref.getTile(35,57).getTopFeature();
  doorslist[14] = mapref.getTile(39,57).getTopFeature();
  doorslist[15] = mapref.getTile(43,57).getTopFeature();
  
  for (let i=0; i<=15; i++) {
    if (doorslist[i].open) {
      doorslist[i].use(PC, "silent");
    }
  }
}

mappages["spire2"] = {};
mappages["spire2"].terrain = [];
 mappages["spire2"].terrain[0] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["spire2"].terrain[1] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["spire2"].terrain[2] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["spire2"].terrain[3] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["spire2"].terrain[4] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["spire2"].terrain[5] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK ## ## ## BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
 mappages["spire2"].terrain[6] = 'BK BK BK BK BK BK BK BK BK BK BK ## ## ## ## ## ## ++ ## ## ## ## ## ## BK BK BK BK BK BK BK BK BK BK BK';
 mappages["spire2"].terrain[7] = 'BK BK BK BK BK BK BK BK BK BK BK ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## BK BK BK BK BK BK BK BK BK BK BK';
 mappages["spire2"].terrain[8] = 'BK BK BK BK BK BK BK BK BK BK BK ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## BK BK BK BK BK BK BK BK BK BK BK';
 mappages["spire2"].terrain[9] = 'BK BK BK BK BK BK BK BK BK BK BK ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## BK BK BK BK BK BK BK BK BK BK BK';
mappages["spire2"].terrain[10] = 'BK BK BK BK BK BK BK BK BK BK BK ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## BK BK BK BK BK BK BK BK BK BK BK';
mappages["spire2"].terrain[11] = 'BK BK BK BK BK BK BK BK BK BK BK ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## BK BK BK BK BK BK BK BK BK BK BK';
mappages["spire2"].terrain[12] = 'BK BK BK BK BK BK BK ## ## ## ## ## ## ## ## ## ## ++ ## ## ## ## ## ## ## ## ## ## ## BK BK BK BK BK BK';
mappages["spire2"].terrain[13] = 'BK BK BK BK BK BK BK ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ## ## BK BK BK BK BK';
mappages["spire2"].terrain[14] = 'BK BK BK BK BK BK ## ## ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ## BK BK BK BK BK';
mappages["spire2"].terrain[15] = 'BK BK BK BK BK BK ## ++ ++ ++ ++ ++ ++ ++ ++ ## ## ## ## ## ++ ++ ++ ++ ++ ++ ++ ++ ## ## BK BK BK BK BK';
mappages["spire2"].terrain[16] = 'BK BK BK BK BK BK ## ## ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ## ++ ++ ++ ++ ++ +* +* +* ## BK BK BK BK BK BK';
mappages["spire2"].terrain[17] = 'BK BK BK BK BK BK BK ## ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ +* +* +* ## BK BK BK BK BK BK';
mappages["spire2"].terrain[18] = 'BK BK BK BK BK BK BK ## ++ ++ ++ ++ ++ ++ ++ ## ++ ++ ++ ## ++ ++ ++ ++ ++ +* +* +* ## BK BK BK BK BK BK';
mappages["spire2"].terrain[19] = 'BK BK BK BK BK BK BK ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## ## BK BK BK BK BK BK';
mappages["spire2"].terrain[20] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["spire2"].terrain[21] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["spire2"].terrain[22] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["spire2"].terrain[23] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["spire2"].terrain[24] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["spire2"].terrain[25] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["spire2"].terrain[26] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["spire2"].terrain[27] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["spire2"].terrain[28] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';
mappages["spire2"].terrain[29] = 'BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK BK';

mappages["spire2"].features = [];
mappages["spire2"].features[0] = {name : 'StairDown2', x : 18, y : 18, entermap : 'worldsending1', enterx : 48, entery : 22};
mappages["spire2"].features[1] = {name : 'StairUp', x : 16, y : 16, entermap : 'spire3', enterx : 13, entery : 12};
mappages["spire2"].features[2] = {name : 'Door', x : 19, y : 17};
mappages["spire2"].features[3] = {name : 'Door', x : 15, y : 17};
mappages["spire2"].features[4] = {name : 'Doorway', x : 19, y : 13};
mappages["spire2"].features[5] = {name : 'Doorway', x : 15, y : 13};
mappages["spire2"].features[6] = {name : 'Door', x : 17, y : 12};
mappages["spire2"].features[7] = {name : 'DustyFireplace', x : 17, y : 6};
mappages["spire2"].features[8] = {name : 'BedHead', x : 12, y : 9};
mappages["spire2"].features[9] = {name : 'BedFoot', x : 13, y : 9};
mappages["spire2"].features[10] = {name : 'Mirror', x : 19, y : 7};
mappages["spire2"].features[11] = {name : 'SmallBox', x : 22, y : 7};
mappages["spire2"].features[12] = {name : 'SmallBox', x : 22, y : 7, lootgroup : 'potslow', lootedid : 'spire6'};
mappages["spire2"].features[13] = {name : 'SmallBox', x : 22, y : 8, lootgroup : 'potslow', lootedid : 'spire5'};
mappages["spire2"].features[14] = {name : 'LeftTable', x : 10, y : 15};
mappages["spire2"].features[15] = {name : 'Harpsichord', x : 21, y : 11};
mappages["spire2"].features[16] = {name : 'RightTable', x : 13, y : 15};
mappages["spire2"].features[17] = {name : 'Mirror', x : 8, y : 13};
mappages["spire2"].features[18] = {name : 'DustyFireplace', x : 7, y : 15};
mappages["spire2"].features[19] = {name : 'Barrel', x : 14, y : 18};
mappages["spire2"].features[20] = {name : 'Chest', x : 13, y : 18, lootgroup : 'spireloot', lootedid : 'spire3'};
mappages["spire2"].features[21] = {name : 'Chest', x : 12, y : 18, lootgroup : 'spireloot', lootedid : 'spire2'};
mappages["spire2"].features[22] = {name : 'Chest', x : 11, y : 18, lootgroup : 'spireloot', lootedid : 'spire1'};
mappages["spire2"].features[23] = {name : 'BookshelfLeft', x : 10, y : 13, lootedid : 'windchange', searchyield : 'AudachtaNemesosWindChange'};
mappages["spire2"].features[24] = {name : 'BookshelfLeft', x : 12, y : 13, lootedid : 'spireshelf3', searchyield : 'ScrollPeer'};
mappages["spire2"].features[25] = {name : 'BookshelfRight', x : 13, y : 13, lootedid : 'opengate', searchyield : 'AudachtaNemesosOpenGate'};
mappages["spire2"].features[26] = {name : 'BookshelfRight', x : 11, y : 13, lootedid : 'spireshelf2', searchyield : 'ScrollLifeDrain'};
mappages["spire2"].features[27] = {name : 'BottomChair', x : 11, y : 16};
mappages["spire2"].features[28] = {name : 'PentagramNW', x : 25, y : 16};
mappages["spire2"].features[29] = {name : 'PentagramN', x : 26, y : 16};
mappages["spire2"].features[30] = {name : 'PentagramNE', x : 27, y : 16};
mappages["spire2"].features[31] = {name : 'PentagramW', x : 25, y : 17};
mappages["spire2"].features[32] = {name : 'PentagramC', x : 26, y : 17};
mappages["spire2"].features[33] = {name : 'PentagramE', x : 27, y : 17};
mappages["spire2"].features[34] = {name : 'PentagramSE', x : 27, y : 18};
mappages["spire2"].features[35] = {name : 'PentagramS', x : 26, y : 18};
mappages["spire2"].features[36] = {name : 'PentagramSW', x : 25, y : 18};
mappages["spire2"].features[37] = {name : 'DustyFireplace', x : 28, y : 14};
mappages["spire2"].features[38] = {name : 'SmallBox', x : 27, y : 13, lootgroup : 'potslow', lootedid : 'spire7'};
mappages["spire2"].features[39] = {name : 'BookshelfRight', x : 26, y : 13, lootedid : 'spireshelf4', searchyield : 'ScrollHeal'};
mappages["spire2"].features[40] = {name : 'BookshelfLeft', x : 25, y : 13, lootedid : 'natassaresearch', searchyield : 'NatassaResearch,NatassaResearch2'};
mappages["spire2"].features[41] = {name : 'Vanity', x : 12, y : 7};
mappages["spire2"].features[42] = {name : 'BookshelfOne', x : 13, y : 7, lootedid : 'spireshelf1', searchyield : 'NatassaJournal'};
mappages["spire2"].features[43] = {name : 'Chest', x : 20, y : 15, lootgroup : 'spireloot', lootedid : 'spire4'};
mappages["spire2"].features[44] = {name : 'Mirror', x : 22, y : 13};
mappages["spire2"].features[45] = {name : 'RightChair', x : 22, y : 10};
mappages["spire2"].features[46] = {name : 'AlchemyLab', x : 11, y : 15};
mappages["spire2"].features[47] = {name : 'AlchemyLab2', x : 12, y : 15};
mappages["spire2"].features[48] = {name : 'AlchemyLabTop', x : 11, y : 14};
mappages["spire2"].features[49] = {name : 'AlchemyLabTop2', x : 12, y : 14};
mappages["spire2"].features[50] = {name : 'UnlitBrazier', x : 12, y : 11};
mappages["spire2"].features[51] = {name : 'UnlitBrazier', x : 22, y : 11};
mappages["spire2"].features[52] = {name : 'UnlitBrazier', x : 8, y : 18};
mappages["spire2"].features[53] = {name : 'UnlitBrazier', x : 24, y : 15};
mappages["spire2"].features[54] = {name : 'EnergyField', x : 24, y : 18};
mappages["spire2"].features[55] = {name : 'EnergyField', x : 27, y : 15};
mappages["spire2"].features[56] = {name : 'PurpleCarpetNW', x : 14, y : 8};
mappages["spire2"].features[57] = {name : 'PurpleCarpetN', x : 15, y : 8};
mappages["spire2"].features[58] = {name : 'PurpleCarpetN', x : 16, y : 8};
mappages["spire2"].features[59] = {name : 'PurpleCarpetN', x : 17, y : 8};
mappages["spire2"].features[60] = {name : 'PurpleCarpetN', x : 18, y : 8};
mappages["spire2"].features[61] = {name : 'PurpleCarpetN', x : 19, y : 8};
mappages["spire2"].features[62] = {name : 'PurpleCarpetNE', x : 20, y : 8};
mappages["spire2"].features[63] = {name : 'PurpleCarpetE', x : 20, y : 9};
mappages["spire2"].features[64] = {name : 'PurpleCarpetC', x : 19, y : 9};
mappages["spire2"].features[65] = {name : 'PurpleCarpetC', x : 18, y : 9};
mappages["spire2"].features[66] = {name : 'PurpleCarpetC', x : 17, y : 9};
mappages["spire2"].features[67] = {name : 'PurpleCarpetC', x : 16, y : 9};
mappages["spire2"].features[68] = {name : 'PurpleCarpetC', x : 15, y : 9};
mappages["spire2"].features[69] = {name : 'PurpleCarpetW', x : 14, y : 9};
mappages["spire2"].features[70] = {name : 'PurpleCarpetSW', x : 14, y : 10};
mappages["spire2"].features[71] = {name : 'PurpleCarpetS', x : 15, y : 10};
mappages["spire2"].features[72] = {name : 'PurpleCarpetS', x : 16, y : 10};
mappages["spire2"].features[73] = {name : 'PurpleCarpetS', x : 17, y : 10};
mappages["spire2"].features[74] = {name : 'PurpleCarpetS', x : 18, y : 10};
mappages["spire2"].features[75] = {name : 'PurpleCarpetS', x : 19, y : 10};
mappages["spire2"].features[76] = {name : 'PurpleCarpetSE', x : 20, y : 10};


mappages["spire2"].npcs = [];

mappages["spire2"].desc = "The Spire";
mappages["spire2"].longdesc = ``;
mappages["spire2"].music = 'Magic';
mappages["spire2"].savename = `The Spire`;
mappages["spire2"].exitmap = '';
mappages["spire2"].exitx = '65';
mappages["spire2"].exity = '70';
mappages["spire2"].wraps = '';
mappages["spire2"].enterx = '65';
mappages["spire2"].entery = '70';
mappages["spire2"].seeBelow = '';
mappages["spire2"].lightLevel = 'dark';
mappages["spire2"].alwaysRemember = '0';
mappages["spire2"].scale = '1';
mappages["spire2"].underground = '0';
mappages["spire2"].undergroundDesc = '';
mappages["spire2"].enterscript = '';
mappages["spire2"].entertestscript = '';
mappages["spire2"].exitscript = '';
mappages["spire2"].exittestscript = '';
mappages["spire2"].returnmap = 'darkunknown';
mappages["spire2"].returnx = '27';
mappages["spire2"].returny = '44';
mappages["spire2"].returninfused = '0';
mappages["spire2"].linkedMaps = ["spire3","worldsending1"];
mappages["spire2"].editorLabels = '{}';

mappages["spire2"].onload = function(mapref) {
  if ((gamestate.getMode() !== "loadgame") && (!DU.gameflags.getFlag("editor"))) {
    if (PC.checkInventory("NatassaResearch") && PC.checkInventory("NatassaResearch2")) { 
      let tile = mapref.getTile(25,13);
      let shelf = tile.getTopFeature();
      shelf.searchyield = '';
    } else if (PC.checkInventory("NatassaResearch")) {
      let tile = mapref.getTile(25,13);
      let shelf = tile.getTopFeature();
      shelf.searchyield = 'NatassaResearch2';
    } else if (PC.checkInventory("NatassaResearch2")) {
      let tile = mapref.getTile(25,13);
      let shelf = tile.getTopFeature();
      shelf.searchyield = 'NatassaResearch';
    } 
  }
}


mappages["spire3"] = {};
mappages["spire3"].terrain = [];
 mappages["spire3"].terrain[0] = '_^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';
 mappages["spire3"].terrain[1] = '_^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';
 mappages["spire3"].terrain[2] = '_^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';
 mappages["spire3"].terrain[3] = '_^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';
 mappages["spire3"].terrain[4] = '_^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';
 mappages["spire3"].terrain[5] = '_^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';
 mappages["spire3"].terrain[6] = '_^ _^ _^ _^ _^ _^ _^ _^ _^ #O #O #O #O #O #O #O #O #O #O #O _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';
 mappages["spire3"].terrain[7] = '_^ _^ _^ _^ _^ _^ _^ _^ _^ #O ++ ++ ++ ++ ++ ++ ++ ++ ++ #O _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';
 mappages["spire3"].terrain[8] = '_^ _^ _^ _^ _^ _^ _^ #O #O #O ++ ++ ++ ++ ++ ++ ++ ++ ++ #O #O #O _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';
 mappages["spire3"].terrain[9] = '_^ _^ _^ _^ _^ _^ _^ #O ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ #O _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';
mappages["spire3"].terrain[10] = '_^ _^ _^ _^ _^ _^ _^ #O ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ #O _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';
mappages["spire3"].terrain[11] = '_^ _^ _^ _^ _^ _^ _^ #O ++ ++ ++ ++ ## ## ## ## ## ++ ++ ++ ++ #O _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';
mappages["spire3"].terrain[12] = '_^ _^ _^ _^ _^ _^ _^ #O ++ ++ ++ ++ ## ++ ++ ++ ## ++ ++ ++ ++ #O _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';
mappages["spire3"].terrain[13] = '_^ _^ _^ _^ _^ _^ _^ #O ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ #O _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';
mappages["spire3"].terrain[14] = '_^ _^ _^ _^ _^ _^ _^ #O ++ ++ ++ ++ ## ++ ++ ++ ## ++ ++ ++ ++ #O _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';
mappages["spire3"].terrain[15] = '_^ _^ _^ _^ _^ _^ _^ #O ++ ++ ++ ++ ## ## ## ## ## ++ ++ ++ ++ #O _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';
mappages["spire3"].terrain[16] = '_^ _^ _^ _^ _^ _^ _^ #O ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ #O _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';
mappages["spire3"].terrain[17] = '_^ _^ _^ _^ _^ _^ _^ #O ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ ++ #O _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';
mappages["spire3"].terrain[18] = '_^ _^ _^ _^ _^ _^ _^ #O #O #O ++ ++ ++ ++ ++ ++ ++ ++ ++ #O #O #O _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';
mappages["spire3"].terrain[19] = '_^ _^ _^ _^ _^ _^ _^ _^ _^ #O ++ ++ ++ ++ ++ ++ ++ ++ ++ #O _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';
mappages["spire3"].terrain[20] = '_^ _^ _^ _^ _^ _^ _^ _^ _^ #O #O #O #O #O #O #O #O #O #O #O _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';
mappages["spire3"].terrain[21] = '_^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';
mappages["spire3"].terrain[22] = '_^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';
mappages["spire3"].terrain[23] = '_^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';
mappages["spire3"].terrain[24] = '_^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';
mappages["spire3"].terrain[25] = '_^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';
mappages["spire3"].terrain[26] = '_^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';
mappages["spire3"].terrain[27] = '_^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';
mappages["spire3"].terrain[28] = '_^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';
mappages["spire3"].terrain[29] = '_^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';
mappages["spire3"].terrain[30] = '_^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';
mappages["spire3"].terrain[31] = '_^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^ _^';

mappages["spire3"].features = [];
mappages["spire3"].features[0] = {name : 'Door', x : 16, y : 13};
mappages["spire3"].features[1] = {name : 'Door', x : 12, y : 13};
mappages["spire3"].features[2] = {name : 'StairDown', x : 13, y : 12, entermap : 'spire2', enterx : 16, entery : 16};


mappages["spire3"].npcs = [];

mappages["spire3"].desc = "The Spire";
mappages["spire3"].music = 'Magic';
mappages["spire3"].savename = "The Spire";
mappages["spire3"].exitmap = '';
mappages["spire3"].exitx = '65';
mappages["spire3"].exity = '70';
mappages["spire3"].wraps = '';
mappages["spire3"].enterx = '65';
mappages["spire3"].entery = '70';
mappages["spire3"].seeBelow = '';
mappages["spire3"].lightLevel = 'dark';
mappages["spire3"].alwaysRemember = '0';
mappages["spire3"].scale = '1';
mappages["spire3"].underground = '0';
mappages["spire3"].enterscript = '';
mappages["spire3"].entertestscript = '';
mappages["spire3"].exitscript = '';
mappages["spire3"].exittestscript = '';
mappages["spire3"].returnmap = 'darkunknown';
mappages["spire3"].returnx = '27';
mappages["spire3"].returny = '44';
mappages["spire3"].returninfused = '0';
mappages["spire3"].linkedMaps = ["spire2","worldsending1"];
